### ISSUE TITLE
Help and Cookie impl inlined into every page render: CMU-309

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1018]
**Describe the bug**
The help form and cookie consent implementation are currently both inlined to all pages that render them. This adds unnecessary page bloat. Also, the JavaScript present is less maintainable than the equivalent TypeScript. 

**To Fix**
Pull out both implementations and isolate as much as possible into a separate script include.  Consider reworking, if necessary, the modal popups as tiny React applications (or just dynamically fetching their content from a server template, or rendering directly via innerHTML, etc)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1853
