### ISSUE TITLE
[FEATURE REQUEST] Formative questions should not re-shuffle after each submission

### ISSUE THREAD

**Issue by LEDThereBeLight** [Simon-Initiative/oli-torus#1023]
**Is your feature request related to a problem? Please describe.**
Submitting an answer to a formative question and resetting it causes the answer choices to re-shuffle. This causes problems when people expect the answer choices to be in the same order and want to test other answer choices (e.g. to see feedback, or to try it again if they got it wrong the first time).

**Describe the solution you'd like**
An activity content transformation should only be run once per activity, and resetting should not re-transform them.

**Comment by gjbunyea** [comment]
+1
