### ISSUE TITLE
Apply style differences to MCQ and Check-All questions

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1024]
**Is your feature request related to a problem? Please describe.**
From a student perspective, MCQ and Check-All questions look very similar. The only difference at first glance is a "submit" button in the bottom left for a check-all, but it's easily missed and can lead to a confusing question answering experience.

I also feel it's odd that the choice buttons are numbered. That numbering won't be meaningful for questions with shuffled answers, and could be confusing if the answers themselves are numbers. 

There are potential pedagogic implications to this as well, imagine a student who thinks a question is a Check-All but is actually an MCQ. Or a student who thinks something is an MCQ but is actually a Check-All - they may only be selecting and submitting one option at a time. 

**Describe the solution you'd like**
Using circular buttons on MCQs, and squares for Check-All would bring a clearer feed-forward that uses known interactivity patterns (radio buttons and checkboxes). Also, dropping the numbers from the option choices would avoid potential confusing they bring. 

**Additional context**
Below are two questions, one MCQ, the other Check-All. It is challenging to tell which is which until something is clicked on. 

![image](https://user-images.githubusercontent.com/18299544/117183502-9ec74280-ada5-11eb-8b5e-cbb79093fca2.png)

**Comment by LEDThereBeLight** [comment]
Closing as done.
