### ISSUE TITLE
Broken image link from within confirmation email: CMU-308

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1032]
The email that a new author receives when signing up via identity flow to confirm their email references an image that is now 404ing. 

                                                                   Look here

                                                                                 \
                                                                                   \
                                                                                     \
   
![Screen Shot 2021-05-06 at 11 01 01 AM](https://user-images.githubusercontent.com/7431756/117324608-f1fccc00-ae5d-11eb-96b6-49db4985cdfe.png)

**Comment by eliknebel** [comment]
The fix here I think is to configure email templates to use the configured branding assets, instead of always assuming OLI logo

**Comment by LEDThereBeLight** [comment]
Fixed
