### ISSUE TITLE
Action tracking/logging/recording for later auditing

### ISSUE THREAD

**Issue by rgachuhi** [Simon-Initiative/oli-torus#1039]
Taking the opportunity to consider places where Audit tracking support (recoding who did what, when) would make sense is something we should incorporate in torus development. The ability to answer questions about who was responsible for certain actions or simply the ability to provide audit reporting if needed is a request we often receive. 

Some of the places where audit recording may be relevant are:
- Who issued deleted the course package
- Trace of who published course package changes when
- Who created the course section
- History of merging content from multiple sources into a single course at delivery
- Who modified syllabus scheduling
- Who modified high stakes activities or added exceptions

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1852
