### ISSUE TITLE
Codeblock does not allow new lines

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1041]
**Describe the bug**
Using the 'enter' key to create newlines in a codeblock formatted text creates new codeblocks instead of creating new lines in the same code block

**To Reproduce**
1. Write some text
2. Format it as code
3. Click in middle of text, hit 'Enter' to create new line
4. NOTICE: New codeblock created

**Expected behavior**
Hitting 'Enter' within a codeblock should create a new line within that codeblock.

**Screenshots**
![codeblock_formating](https://user-images.githubusercontent.com/18299544/117724684-1afcc400-b1b2-11eb-998d-f2b2e3034364.gif)

**Comment by darrensiegel** [comment]
This was fixed in digest creation and manually repaired for the affected codeblocks.
