### ISSUE TITLE
Allow multi-column cells in tables

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1042]
**Is your feature request related to a problem? Please describe.**
Tables need to allow cells to span multiple columns

**Describe the solution you'd like**
A merge-cell features seems like a logical solution, using known patterns

**Additional context**
Content in Column 4, Row 4 should span across all columns.
![image](https://user-images.githubusercontent.com/18299544/117725077-a5452800-b1b2-11eb-9079-7785411b550d.png)

**Comment by darrensiegel** [comment]
done
