### ISSUE TITLE
Closing page does not release page lock: CMU-451

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1050]
**Describe the bug**
When 2 users are looking at the same page, one gets the page lock. Closing that page will not release the page lock for the other user. 

**To Reproduce**
1. You (user1) open a page in a course to gain edit access
2. Have another user (user2) open the same page
3. NOTICE: user1 has the page lock, user2 sees "Read Only. user1 is currently editing this page."
4. user1 closes their page tab
5. user2 refreshes their page
6. NOTICE: user2 continues to see page lock message and is **unable** to edit.
7. user1 reopens their page tab
8. user1 navigates to a different page.
9. user2 no longer sees page lock and is now able to edit

**Expected behavior**
1. You (user1) open a page in a course to gain edit access
2. Have another user (user2) open the same page
3. NOTICE: user1 has the page lock, user2 sees "Read Only. user1 is currently editing this page."
4. user1 closes their page tab
5. user2 refreshes their page
6. NOTICE: user2 **no longer** sees page lock message and **is now able** to edit.

**Comment by LEDThereBeLight** [comment]
I think this is still an issue as of 3/1/22. Something is wrong with the lock/save mechanism when exiting a page.

**Comment by eliknebel** [comment]
Closing as stale
