### ISSUE TITLE
Ingestion created false Review warnings for Image-Coding activity: CMU-449

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1059]
**Describe the bug**
Review warnings for "No Attached Objective" appear for many image-coding activities in KTH CS101, despite all image-coding activities being tagged in the course. These review warnings also have no link and do not go away when linking or unlinking an objective to an image-coding activity

**Expected behavior**

**Screenshots**
Notice the "Image coding activity" text is not blue like a link
![image](https://user-images.githubusercontent.com/18299544/118167980-52a77e00-b3f5-11eb-88a3-0646c84454b9.png)

**Additional context**
https://proton.oli.cmu.edu/project/kth_swedish_cs101/review?filters=accessibility%2Ccontent%2Cpedagogy&selected=3797

**Comment by eliknebel** [comment]
Closing as stale
