### ISSUE TITLE
ReleaseTasks migrate_and_seed does not have config available

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1068]
**Describe the bug**
When running the task `./oli/bin/oli eval "Oli.ReleaseTasks.migrate_and_seed"` on a new torus production instance, the seed task will fail because the lti_1p3 config is not loaded. A workaround is to start torus then run the task as a remote call using the `./oli/bin/oli remote` shell. Seed should be adjusted so that calls do not rely on the configs.

**Comment by LEDThereBeLight** [comment]
I think this is fixed.
