### ISSUE TITLE
Missing functionality when removing learning objectives: CMU-448

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1085]
**Describe the bug**
When removing LOs, this dialoge shows up:
![image](https://user-images.githubusercontent.com/53688217/119525086-82a03b00-bd7e-11eb-954d-24d82c6b7afe.png)
However, the Delete-button has no effect (besides closing the dialoge).

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/project/kth_swedish_cs101/objectives
2. Click on any objective
3. Click on Delete

**Expected behavior**
I expect the learning objective to disappear from the list (and all attached activities)

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 11.3.1
 - Browser Chrome
 - Version Version 90.0.4430.212 

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by LEDThereBeLight** [comment]
Still an issue as of 3/1/22.

**Comment by eliknebel** [comment]
Resolved by https://github.com/Simon-Initiative/oli-torus/pull/3049
