### ISSUE TITLE
Internal server error when following link from Learning Objectives

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1086]
**Describe the bug**

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/project/kth_swedish_cs101/objectives
2. Click on 'Använda funktioner för att visa information'
3. Click on Remove
4. Click on Delete

**Expected behavior**
Expect the sub-objective to disappear (and be removed from the activity)

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 11.3.1
 - Browser Chrome
 - Version Version 90.0.4430.212 

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by LEDThereBeLight** [comment]
Closing as done / dup.
