### ISSUE TITLE
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1087]
**Describe the bug**
This error message appears when I try to run Image code activity

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/bildmanipulation
2. Go to LBD "Skriv kod som minskar värdet för röd till 25% av ursprungsvärdet. "
3. Press Run

**Expected behavior**
Image of banana would show up

**Screenshots**
![image](https://user-images.githubusercontent.com/53688217/119542734-27774400-bd90-11eb-802d-66ab3d149af0.png)

**Environment (please complete the following information):**
 - OS: macOS 11.3.1
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by joecoolle** [comment]
Sam problem with the first activity on the net page:
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/bildpussel

**Comment by andersweinstein** [comment]
This indicates a problem handling Cross-Origin Resource Sharing (CORS) requirements properly.  It is tricky to configure Amazon S3 + Cloudfront properly for a mix of CORS-enabled and non-CORS-enabled requests for the same resource. Briefly,  the activity script requires cross-origin access to the image, but in some circumstances a cached result of an earlier non-CORS-enabled response can get served in response to CORS-enabled request, and then access to the image winds up blocked. 

I believe we have corrected the Amazon S3 and Cloudfront configurations to prevent this issue.

**Comment by joecoolle** [comment]
Seems you are correct!
