### ISSUE TITLE
Open&Free Section Creation Fails for KTH Swedish CS101 Package

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1089]
**Describe the bug**
On Proton, using the Open&Free section creation for this package https://proton.oli.cmu.edu/project/kth_swedish_cs101 results in no section created. There is no feedback provided if something is going wrong. Possible this is due to it being an ingested course.

**To Reproduce**
1. Be Admin
2. Go to Open and Free creation page
3. Click "New Open and Free" button
4. Choose **KTH Swedish CS101** package (KTH Swedish CS101 v1.0.0 (kth_swedish_cs101))
5. Change title to "**Sommarprogrammering**"
6. Set Start Date to **Today**; End Date to **Oct 31 2021**
7. Set Time Zone to **(GMT +01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna**
8. Keep Registration Available as **Open**
9. Click "Create"
10. NOTICE: Open and Free creation dialog resets all fields to blank
11. NOTICE: Not taken to the Open and Free Details page 
12. Click 'Back', Refresh page
13. NOTICE: No newly created section
14. NOTICE: No change to Open and Free list

**Expected behavior**
Should see the Open and Free Details page for the newly created course
Should see the course available when navigating back to the Open and Free page

**Screenshots**
![image](https://user-images.githubusercontent.com/18299544/119556617-3f899c00-bd6d-11eb-9c86-802d4b035710.png)
![openandfreeKTHCS101](https://user-images.githubusercontent.com/18299544/119557625-698f8e00-bd6e-11eb-8a51-8a116f79ee89.gif)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser : Brave: 1.24.86, Chrome: 90.0.4430.212
 - 
**Additional context**
I was able to create an Open and Free section of a different package suggesting the overall process is not broken, just this particular package. Possible due to this package having been ingested (as opposed to created natively like the section I was able to build)

**Comment by darrensiegel** [comment]
The issue here is that only "Published" packages can have sections created.  The KTH course had never ben published. 

I just published it, so try again to create this section.

**Comment by gjbunyea** [comment]
Open & Free creation worked now. Can we get this feedback displayed at O&F creation failure? Something like "Unable to create O&F Section: Course has not been published".
