### ISSUE TITLE
Add possibility to use regexp for grading short text and numeric answers

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1094]
**Is your feature request related to a problem? Please describe.**
Students do not always answer in the way we teachers imagine. Regular expressions could increase the number of answers we would accept.

**Describe the solution you'd like**
Add possibility to use regexp for grading short text and numeric answers

**Additional context**
![image](https://user-images.githubusercontent.com/53688217/119836697-38e05d80-bf02-11eb-9d08-58df0a509d14.png)
![image](https://user-images.githubusercontent.com/53688217/119836804-501f4b00-bf02-11eb-97c4-f2b22e391869.png)

**Comment by LEDThereBeLight** [comment]
Closing as done.
