### ISSUE TITLE
Hints do not work in production

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1095]
**Describe the bug**
Hints do not work in production

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/sections/sommarprogrammering/page/utveckla_frmgor_fr_sjlvstndigt
2. Click on any of the Hint buttons

**Expected behavior**
First hint shows up

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by darrensiegel** [comment]
This has been resolved.
