### ISSUE TITLE
regexp grading does not work on text output activities

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1096]
**Describe the bug**
regexp grading does not work

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/sections/sommarprogrammering/page/kodskrivande
2. Goto "Fixa syntaxfelet i koden och kör den så att den skriver ut rätt"
3. Change 
print("hej", "du);
to 
print("hej", "du");
3. Press Run
4. Press Submit

**Expected behavior**
Green light for the answer.

**Screenshots**
![image](https://user-images.githubusercontent.com/53688217/119850587-fa50a000-bf0d-11eb-9bdb-3fa552458a14.png)

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by joecoolle** [comment]
However, it works in this activity:
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/tabelldata/activity/image_coding_activity_fw1y0

**Comment by andersweinstein** [comment]
Would help to include the regex. It is specfied in the dialog box as `1\s2\shej\sdu` This becomes the value of pat which in effect gets  used in `correct = new Regexp(pat).test(output)` 

It looks like there is some problem matching the line break with `\s`. Experimenting with different patterns shows the output matches `1\s2\s` but not `1\s2\shej`

**Comment by joecoolle** [comment]
Apologies for not adding the regexp.
Thank you for identifying the problem. I do not deem this as important for the moment. I can revise the other regexp ativities now that I know.

**Comment by andersweinstein** [comment]
I think we should get rid of the extra space in the output beause it is unexpected and the change is easy to make. But if you use \s+ for now, the regexp will work either way.

**Comment by joecoolle** [comment]
Your call!

**Comment by joecoolle** [comment]
I have fixed the other regexp patterns, but these two got me stomped:
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/att_rkna/activity/image_coding_activity_gxizq
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/att_rkna/activity/image_coding_activity_yycsj

The first have a possible solution code:
tabell = new SimpleTable("baby-2016.csv");
antal = 0;
for (rad: tabell) {
  if (rad.getField("Namn").startsWith("O")) {
      antal += 1
    print(antal);
  }
}
print("Antal:", antal);

With the original regexp:
ntal:?\s6\n$

The other one maintain its original regexp and has a possible solution code:
tabell = new SimpleTable("baby-2016.csv");
antal = 0;
for (rad: tabell) {
  if (rad.getField("Namn").endsWith("k")) {
    print(rad);
        antal = antal + 1; 
  }
}

print("antal", antal);

**Comment by joecoolle** [comment]
And the same goes for this:
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/tabeller_quiz/activity/image_coding_activity_e8p2c

**Comment by andersweinstein** [comment]
I looked at the first one, it comes from the same issue: the print function adds a space after every element it prints, so there is an extra space at the end of the line which must be matched. The following regexp therefore works:

`ntal:?\s6\s\n$`

I have left that in after my experimenting. 

I definitely want to take out that extra space to eliminate this confusion. But it could be a little while before we can get this change deployed. For an expression which will work without change both before and after we remove the extra space when printing, I think you could use `ntal:?\s6\s?\n$` or`ntal:?\s6\s+$`

**Comment by joecoolle** [comment]
Thank you! As you already have guessed, regexp is not my strong side and when I could not get it to work on Proton, although  I could get matches with the same output on https://regex101.com/ 
I did not know what to do. I have now added \s? to these three, and that solves the current problems.
