### ISSUE TITLE
Internal server error when following links from delete Objective

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1100]
**Describe the bug**
Internal server error when following links from Delete Objective

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/project/kth_swedish_cs101/objectives
2. Click on Remove button for "Använda funktioner för att visa information"
3. Click on the link "oli_multiple_choice"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53688217/119960421-3aaf2d00-bfa5-11eb-99c8-032707e5b689.png)
Clicking on the link "oli_multiple_choice" leads to
https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/oli_multiple_choice_12aee
but the page only states
Internal Server Error

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by joecoolle** [comment]
And pressing Delete directly in that dialoge seems to have no effect at all.

**Comment by LEDThereBeLight** [comment]
Closing as done.

**Comment by LEDThereBeLight** [comment]
Reopening - only original issue is fixed. Followup issue is not fixed - objectives cannot be deleted when attached.

**Comment by LEDThereBeLight** [comment]
Re-closing - duplicate.
