### ISSUE TITLE
Login in dark mode is difficult to read

### ISSUE THREAD

**Issue by hturnercmu** [Simon-Initiative/oli-torus#1120]
The OLI Torus logo and the account fields are impossible to read. Using latest Chrome version (Version 91.0.4472.77 (Official Build) (x86_64)) in updated MacOS (11.3.1 (20E241)). MacOS is set to dark mode.

<img width="1552" alt="Screen Shot 2021-06-04 at 4 44 15 PM" src="https://user-images.githubusercontent.com/82517606/120860720-21cdeb00-c554-11eb-9192-4d8efcac8538.png">

**Comment by eliknebel** [comment]
I'm able to reproduce the logo issue, it's a compile time config issue and I'm working on a fix. I'm having trouble reproducing the inputs though. I've also tried in Safari and it appears to work fine.
<img width="1184" alt="Screen Shot 2021-06-04 at 5 38 40 PM" src="https://user-images.githubusercontent.com/6248894/120865270-b5ef8080-c55b-11eb-8250-05e81fff4d60.png">

Do you have any other details I can work with? Do you have any chrome themes or extensions installed that could be a factor? Have you tried any other browsers or machines?
