### ISSUE TITLE
Content missing/out of order in Author view, but Page Preview is correct.

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1132]
**Describe the bug**
This page: https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/bildmanipulation has a different amount of content blocks, and some are in a different order than what shows up in Preview. Oddly, it's the Preview that shows the correct order/content. 

Reverting the page to a prior, known correct version has not resolved the issue. The Published version of the page is correct.

**Steps to Reproduce**
1. Open this page: https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/bildmanipulation
2. Scroll down slightly, notice image-coding activity with "_Ursprungsbilden är en gul vallmo"_ in the prompt below 1st content block
3. Launch Preview
4. Scroll to very bottom of page
5. Notice the "_Ursprungsbilden är en gul vallmo"_ activity is at the bottom of page (This is the correct location).
6. Scroll to middle of Preview
7. Notice image-coding with prompt _"Koden nedan minskar värdet_
8. Go back to Author view, search for "Koden nedan minskar värdet" 
9. Notice, this activity is not present (but it should be)

In Author view, this activity shows below the **"Uttryck"** heading. This activity should be at the bottom of the page.
![image](https://user-images.githubusercontent.com/18299544/121260008-ca46bc80-c87e-11eb-917e-3278ad0486d3.png)

In the page preview, it is not there. 
![image](https://user-images.githubusercontent.com/18299544/121259943-b307cf00-c87e-11eb-84e7-6380a33c4391.png)

In page preview, this activity appears below the banana picture (as it should)
![image](https://user-images.githubusercontent.com/18299544/121260217-08dc7700-c87f-11eb-997b-1c3c4c3adbd8.png)

In author view, this activity is nowhere to be found, and it definitely not below the banana picture. 
![image](https://user-images.githubusercontent.com/18299544/121260298-23165500-c87f-11eb-8b4d-0bccb1a78977.png)

**Comment by darrensiegel** [comment]
This was a problem identified and fixed by: https://github.com/Simon-Initiative/oli-torus/pull/1071

It appears that fix has not yet made its way to production.

**Comment by gjbunyea** [comment]
Latest torus update has allowed the Revision History to restore the proper version.
