### ISSUE TITLE
docker-compose run app mix octo.create requires Elixir ~> 1.12

### ISSUE THREAD

**Issue by mydevbox** [Simon-Initiative/oli-torus#1137]
**Describe the bug**

Attempting to run the project for the first time following the quick start steps.  

**To Reproduce**

Follow the quick start guide on a clean system.

**Expected behavior**

Expected that octo.create would complete successfully, not with an error.

**Screenshots**

► $ docker-compose run app mix octo.create
Creating oli-torus_app_run ... done
** (Mix) You're trying to run :oli on Elixir v1.11.4 but it has declared in its mix.exs file it supports only Elixir ~> 1.12
ERROR: 1

**Environment (please complete the following information):**
 - OS: macos Catalina

**Additional context**

**Comment by darrensiegel** [comment]
This docker-based quick start option is out of date, and unfortunately has become a burden to maintain.  We do not believe that it is necessary however, and thus are going to be removing it. 

I would suggest following the instructions for setting up a native development environment: https://github.com/Simon-Initiative/oli-torus/wiki/Setup-Dev-Environment
