### ISSUE TITLE
Image captions unreadable in dark theme: CMU-462

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1160]
**Describe the bug**
Image captions are unreadable in dark theme

**Screenshots**
<img width="1146" alt="Screen Shot 2021-06-15 at 10 41 40 AM" src="https://user-images.githubusercontent.com/6248894/122073493-754aff00-cdc6-11eb-965c-6b73dbacc480.png">

**Comment by LEDThereBeLight** [comment]
Still an issue.
