### ISSUE TITLE
Student Account sign-in dialog for O&F cut off on small screens: CMU-461

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1163]
**Describe the bug**
The dialog that opens to encourage O&F section students to create an account does not properly resize on small screens.

**To Reproduce**
1. On cell-phone web browser, go to https://proton.oli.cmu.edu/sections/sommarprogrammering
2. NOTICE: Student Account dialog is cut-off

**Expected behavior**
Dialog should resize to fit the screen size

**Screenshots**
![image](https://user-images.githubusercontent.com/18299544/122115837-df799900-cdf2-11eb-80b5-9cf5adb47d22.png)

**Environment (please complete the following information):**
- Windows 10:
- - Chrome (via devtools)
- - Firefox (via devtools)  
- Android:
- - Chrome

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by LEDThereBeLight** [comment]
Still an issue.

**Comment by eliknebel** [comment]
We need to have this responsive and fit in the window
