### ISSUE TITLE
Creating an activity and immediately clicking edit fails to add activity to page in Safari: CMU-460

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1175]
**Describe the bug**
Creating an activity and immediately clicking edit fails to add the new activity to the page

**To Reproduce**
1. Go to a page in authoring
2. Click on "Add Content or Activity" and add an activity
3. Quickly click the "Edit ..." button on the new activity
4. Return to the previous page using back (from the activity editor) and see that the activity is not on the page.

**Expected behavior**
Activity should be added to a page now matter how fast the Edit button is clicked

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari 14.1.1

**Additional context**
This appeared in Safari but I couldn't recreate in Chrome

**Comment by LEDThereBeLight** [comment]
Have not confirmed this is still an issue.
