### ISSUE TITLE
Revise MCQ Shuffling Options

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1178]
**Is your feature request related to a problem? Please describe.**
Shuffling MCQ Choices is generally a good practice, though there are cases where you would want the choices in a set order. Currently, turning Shuffle Off results in the 1st choice always being the correct choice. If the course had no shuffled questions, it would not take long for students to determine this pattern. 

Also, question choices should not reshuffle on every reset. Maybe once on page load. #1023 addresses this issue. 

**Describe the solution you'd like**
If choosing to turn Shuffle off, the Correct answer should be able to be placed in any position. 
If choosing to turn Shuffle on, the choices should be shuffled on page-load, not each activity reset. 

**Additional context**

![image](https://user-images.githubusercontent.com/18299544/122599282-15f62480-d03c-11eb-8ee2-6883fdf7ce59.png)

**Comment by LEDThereBeLight** [comment]
**Describe the solution you'd like**
If choosing to turn Shuffle off, the Correct answer should be able to be placed in any position.
- **Resolved**
If choosing to turn Shuffle on, the choices should be shuffled on page-load, not each activity reset.
- **Needs a change in how activities are delivered in general. Not supported yet.**

**Comment by darrensiegel** [comment]
done
