### ISSUE TITLE
Dark Mode Is Enabled When OS "Prefers" Dark Mode: CMU-458

### ISSUE THREAD

**Issue by ThinkThoughtThunk** [Simon-Initiative/oli-torus#1216]
**Describe the bug**
We removed the ability to toggle between light and dark mode in authoring, but OS dark-mode preferences set the UI to dark mode and there's no way to force light mode.

**Expected behavior**
We need to either fix dark mode everywhere or disable whatever setting allows the browser/os to select the theme based on dark/light mode preferences.

**Comment by eliknebel** [comment]
Either way, dark mode should work everywhere for accessibility reasons. It seems like a good first step here would be to fix dark mode wherever it is broken and followup with a feature to allow toggling independent of OS theme if necessary.
