### ISSUE TITLE
Add possibilities to use conditionals to formulate more advanced feedback 

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1219]
**Is your feature request related to a problem? Please describe.**
When formulating numeric feedback, it is tiresome to e.g. cover all alternatives that are too big (to give the feedback "to big")

**Describe the solution you'd like**
I would like to be able to use e.g. >, <,  &&  to do the selection for which feedback to give.

**Describe alternatives you've considered**

**Additional context**

**Comment by joecoolle** [comment]
I am referring to Short questions of Numerical type.

**Comment by eliknebel** [comment]
Torus provides catch all feedback. Closing as stale, we can reopen if this is still an issue
