### ISSUE TITLE
Interface improvement: move button for "Add feedback" in Short answers up one line

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1220]
**Is your feature request related to a problem? Please describe.**
It took me quite a while to understand I could add more answer alternatives (and feedback) to short_answers as the button to do this comes after the "Feedback for any other Incorrect Answer" which to me seems like the end of the question.

**Describe the solution you'd like**
Please move the button "Add Feedback"  up before "Feedback for any other Incorrect Answer" to make it more logical and also will place the button closer to where the feedback actually will be added. Possible change the text to "Add answer alternative and feedback" to describe the behaviour more precise.

**Describe alternatives you've considered**

**Additional context**

**Comment by eliknebel** [comment]
We need a UX designer to take a pass at this interface and a larger wholistic view
