### ISSUE TITLE
Issues with deployment

### ISSUE THREAD

**Issue by fkohrt** [Simon-Initiative/oli-torus#1305]
**Describe the bug**

Not having any prior experience with the Elixir stack or OLI Torus itself, I went through the current instructions for [Building Releases and Production Deployments](https://github.com/Simon-Initiative/oli-torus/wiki/Building-Releases-and-Production-Deployments) and tried to get `v0.12.3` up and running, but experienced some issues:

1. Missing prerequisites. I took them (Elixir, Phoenix) from the page [Setup Dev Environment](https://github.com/Simon-Initiative/oli-torus/wiki/Setup-Dev-Environment), Docker shouldn't be required, is it?
2. Running `npm install --prefix ./assets` failed due to a dependency conflict.

<details>
<summary>Log</summary>

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: oli@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-rc || ^15.0.0 || ^16.0.0" from react-select2-wrapper@1.0.4-beta6
npm ERR! node_modules/react-select2-wrapper
npm ERR!   react-select2-wrapper@"^1.0.4-beta6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/primus/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/primus/.npm/_logs/2021-07-26T20_38_44_651Z-debug.log
```

</details>

I continued with `--force`.

3. Running `mix phx.digest` failed due to missing dev dependencies:

<details>
<summary>Log</summary>

```
Unchecked dependencies for environment dev:
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_live_reload (Hex package)
  the dependency is not available, run "mix deps.get"
* dialyxir (Hex package)
  the dependency is not available, run "mix deps.get"
* credo (Hex package)
  the dependency is not available, run "mix deps.get"
* mix_test_watch (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

</details>

Running `MIX_ENV=prod mix phx.digest` worked fine instead, so this should probably be documented.

4. Unclear PostgreSQL setup.
   - What's the minimal required version?
   - What's the required configuration?
   - I believe it should be documented at which point the DB should be set up.
5. Running `./oli/bin/oli start` failed due to permission errors.

<details>
<summary>Log</summary>

```
20:53:17.092 [info]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
20:53:17.095 [info]     :alarm_handler: {:set, {:process_memory_high_watermark, #PID<0.5932.0>}}
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:phoenix, :endpoint, :stop, :duration]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:phoenix, :router_dispatch, :stop, :duration]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :plug, :stop, :duration]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :resolvers, :authoring, :duration]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :resolvers, :delivery, :duration]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :repo, :query, :total_time]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :repo, :query, :decode_time]
20:53:17.096 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :repo, :query, :query_time]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :repo, :query, :queue_time]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:oli, :repo, :query, :idle_time]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:vm, :memory, :total]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:vm, :total_run_queue_lengths, :total]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:vm, :total_run_queue_lengths, :cpu]
20:53:17.097 [warn] Metric type summary is unsupported. Dropping measure. metric_name:=[:vm, :total_run_queue_lengths, :io]
20:53:17.099 [error] Failed to start Ranch listener OliWeb.Endpoint.HTTP in :ranch_tcp:listen([{:cacerts, :...}, {:key, :...}, {:cert, :...}, :inet6, {:port, 80}]) for reason :eacces (permission denied)

20:53:17.101 [info] Application oli exited: Oli.Application.start(:normal, []) returned an error: shutdown: failed to start child: OliWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, OliWeb.Endpoint.HTTP}
        ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
            ** (EXIT) {:listen_error, OliWeb.Endpoint.HTTP, :eacces}
[os_mon] memory supervisor port (memsup): Erlang has closed
20:53:17.108 [info]     :alarm_handler: {:clear, :system_memory_high_watermark}
20:53:17.108 [info]     :alarm_handler: {:clear, :process_memory_high_watermark}
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,oli,{{shutdown,{failed_to_start_child,'Elixir.OliWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.OliWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.OliWeb.Endpoint.HTTP',eacces}}}}}}},{'Elixir.Oli.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,oli,{{shutdown,{failed_to_start_child,'Elixir.OliWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.O

Crash dump is being written to: erl_crash.dump...done
```

</details>

Becoming privileged user and running from there helped, but that should not be the case, right?

```sh
sudo -s
set -a; source ./oli.env
./oli/bin/oli start
```

6. I couldn't get the database connection working, although PostgreSQL was up and running with the data configured in `DATABASE_URL`. Neither `DB_HOST=localhost` nor `DB_HOST=postgres` worked. Any ideas?

<details>
<summary>Log</summary>

```
(snip)
22:18:50.745 [error] Postgrex.Protocol (#PID<0.6308.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
22:18:50.745 [error] Postgrex.Protocol (#PID<0.6303.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
22:18:50.746 [error] Postgrex.Protocol (#PID<0.6298.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
22:18:50.746 [error] Postgrex.Protocol (#PID<0.6302.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
22:18:50.749 [error] Postgrex.Protocol (#PID<0.6297.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
22:18:50.750 [error] Postgrex.Protocol (#PID<0.6305.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres
(snip)
```

</details>

Maybe the deployment should better live in the repo itself, instead of the wiki? And are there helpful details from your `deploy.sh` that could be shared?

https://github.com/Simon-Initiative/oli-torus/blob/31d9e58300aff2f13471cb1aed94d83878e4eb98/.github/workflows/deploy.yml#L24-L33

**Environment:**

 - Ubuntu 20.04.2 LTS
 - Node v16.5.0
 - PostgreSQL 12.7

**Comment by eliknebel** [comment]
Hi, thanks for letting us know the wiki was out of date. I have updated the instructions so that they should work with the latest release now.

I see there are a mix of dev setup and prod instructions you followed here. We have a complete guide on setting up and running a development environment, which you mentioned [Setup Dev Environment](https://github.com/Simon-Initiative/oli-torus/wiki/Setup-Dev-Environment).

The [Building Releases and Production Deployments](https://github.com/Simon-Initiative/oli-torus/wiki/Building-Releases-and-Production-Deployments) guide you mention was intended to be more informational guide to understanding how a release is created and can be run. The official Elixir Releases page is a more in depth guide for learning how to use releases. Since production environments can vary depending on multiple factors, we do not have an explicit guide on how to setup a specific system or database. However, I have updated the guide to be a bit more opinionated on how to setup a production environment so there is less confusion.

It is not recommended to run as root. It is much better to have a user created on the system intended specifically to run torus. For example, `useradd -m torus` then `sudo -u torus -s`. Please make sure the user has full permissions and ownership of the directory where the release is. If the permissions issue is related to opening a port under 1024 (torus defaults to 80) then it is recommended to set a specific port above this range using env variable `HTTP_PORT=8080` and using a reverse proxy.

It's hard to say without an explicit error report, but try the updated [Building Releases and Production Deployments](https://github.com/Simon-Initiative/oli-torus/wiki/Building-Releases-and-Production-Deployments) instructions. Please make sure the database user has the necessary permissions and is accessible from torus. Then run `set -a; source ./oli.env && ./oli/bin/oli start_iex` and then in the iex shell: `Oli.ReleaseTasks.setup()`

The deploy.sh script is simply a set of commands we run from our CI/CD to download a release, unpack it, migrate and seed the database and restart the server. These commands will likely differ depending on the specific system and CI/CD process.

**Comment by LEDThereBeLight** [comment]
Closing as stale.

**Comment by fkohrt** [comment]
@eliknebel Sorry for not coming back to you. I finally came around testing again with all the new instructions and it worked just fine – thanks a lot!

In case others are interested:

Minio blob storage can be implemented by adding the following ExAws configuration to `config/config.exs` ([source](https://github.com/ex-aws/ex_aws_s3/blob/main/README.md#configuration)):

```exs
config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 9000
```

And if you are using an Nginx reverse proxy, one needs to take care of WebSocket support, e.g.:

```
server {
        # (snip)

        location / {
                proxy_pass          "http://127.0.0.1:8080";
                proxy_http_version  1.1;
                proxy_set_header    Upgrade $http_upgrade;
                proxy_set_header    Connection "Upgrade";
                proxy_set_header    Host $host;
        }

        # (snip)
}
```
