### ISSUE TITLE
Alt text editor doesn't always display the image for the author

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#1314]
When adding alt text to an image, the author is shown the image so it can be described. It doesn't always appear. See example attached.
![Screen Shot 2021-07-28 at 10 39 12 AM](https://user-images.githubusercontent.com/24977416/127342703-e8ebb2e4-e818-495d-ab0c-a256c91bd414.png)

Image sits on this page: https://proton.oli.cmu.edu/authoring/project/introduction_to_statistics/resource/sample_space_and_events

Steps to recreate:

1. click image
2. click alt text button
3. Image doesn't appear in dialog box

**Comment by LEDThereBeLight** [comment]
I think this is actually fixed now with the page editor rework.
