### ISSUE TITLE
Add appropriate icons to Review categories

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#1317]
**Is your feature request related to a problem? Please describe.**
The summary at the top of the Publish > Review page outlines three categories: Accessibility, Equity, and Pedagogy. The actual list of reviewable items aren't named, they're labeled with icons. But the icons aren't visually associated with the topics in the summary area. 

**Describe the solution you'd like**
Add the topical icons to the summary, so it's clear what category each list item falls into.

**Describe alternatives you've considered**
Adding headers to the list, visually separating each category of items by more than their icons.

![Screen Shot 2021-07-28 at 10 38 26 AM](https://user-images.githubusercontent.com/24977416/127366394-36c7cd41-3b24-4369-a4a4-9d5a8d72b504.png)

**Comment by eliknebel** [comment]
Kristine will identify a suitable set of icons
