### ISSUE TITLE
Requested hints should remain visible after answer is submitted

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1320]
**Describe the bug**
Requested hints should remain visible after answer is submitted so that a user can return and see the full context of what got them to the answer.

**To Reproduce**
1. Go to an ungraded question with hints in delivery
2. Request hints
3. Answer the question and click submit
4. See requested hints disappear

**Screenshots**
<img width="821" alt="Screen Shot 2021-07-29 at 9 34 13 AM" src="https://user-images.githubusercontent.com/6248894/127501595-3853de31-1bed-4651-bcfd-8fcf26cababb.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1

**Comment by darrensiegel** [comment]
fixed
