### ISSUE TITLE
Place Submit button and Reset button in different locations to avoid accidental resets: CMU-456

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#1321]
**Is your feature request related to a problem? Please describe.**
When a student submits an answer with the SUBMIT button, the RESET button appears immediately in the same location. Any inadvertent double-click or double-tap would reset the activity.

**Describe the solution you'd like**
* A grayed-out reset button at the far-right boundary, inline with the Submit button, that becomes active after a submission. OR
* After submission, the Reset button appears in a different location

**Describe alternatives you've considered**
N/A

Eli's video related to data collection for insights shows the current button alignment.

https://user-images.githubusercontent.com/24977416/127521440-1fc5af5f-8030-41cb-8707-456f2ffc2181.mov

**Comment by eliknebel** [comment]
I agree, this could lead to inadvertent resets and it also makes it harder to identify which activities have been completed and which have not

**Comment by eliknebel** [comment]
Hal: We should keep the original submit button, but disable it and show the reset button next to it.
