### ISSUE TITLE
Red X's and Green checkmarks are confusing when reviewing attempt

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1328]
**Describe the bug**
When reviewing an attempt, either red X's are displayed or green checkmarks depending on if the question was answered correctly. However, these appear to indicate *which* were answered incorrectly, when in fact they are always all red or green depending on if the response was correct or not. This may be confusing to students because they may think they got all checkboxes incorrect, even though some may have been correct. We should simply not show these markings when reviewing an attempt.

**To Reproduce**
1. Go to check all that apply in delivery graded page
2. Complete the assessment and then review attempt
3. See that even though one of the checks was correct, it has a red X on it

**Expected behavior**
We should not give the student any indication as to which checks were correct or not. We should simply not show these markings.

**Screenshots**
<img width="544" alt="Screen Shot 2021-07-29 at 11 12 36 AM" src="https://user-images.githubusercontent.com/6248894/127562963-c591743a-cfae-427d-a482-b51a8ad4902e.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Safari
 - Version 14.1.1

**Comment by LEDThereBeLight** [comment]
Closing as done.
