### ISSUE TITLE
Safari doesn't give up page locks when leaving or closing a page: CMU-455

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1329]
**Describe the bug**
When leaving a page in Safari, either by navigating out or closing the tab, the lock on the resource remains until it times out.

**To Reproduce**
1. In Safari, go to a page
2. Leave the page and view the lock icon still belongs to you

**Expected behavior**
Locks should be release when leaving or closing a page

**Screenshots**
<img width="823" alt="Screen Shot 2021-07-29 at 5 25 27 PM" src="https://user-images.githubusercontent.com/6248894/127567924-f91d4ebd-adf9-4dd3-8aad-6c80ccbe066f.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Additional context**
This appears to only be a Safari issue

**Comment by LEDThereBeLight** [comment]
Cross-browser issue as of 3/1/22.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1796
