### ISSUE TITLE
Insights contain an activity that doesn't appear to exist: CMU-306

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1330]
**Describe the bug**
Insights contain an activity that doesn't appear to exist in the course. There is no link, no attempts, and it cannot be identified in the course. This issue has appeared in several other courses as well.

**To Reproduce**
1. Go to insights for a production course that has some attempts
2. See there is a non-navigable activity with no attempts

**Expected behavior**
Insights should only show activities that exist in the course at the time the insights page is loaded.

**Screenshots**
<img width="1186" alt="Screen Shot 2021-07-29 at 5 31 36 PM" src="https://user-images.githubusercontent.com/6248894/127568787-6730df1c-e8da-4116-90bf-78b83dbcd5f3.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by LEDThereBeLight** [comment]
duplicate
