### ISSUE TITLE
Multiple choice bubbles of different sizes: CMU-304

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#1336]
**Describe the bug**
A multiple choice question has differently sized selection bubbles.
https://proton.oli.cmu.edu/sections/goal_setting_course/page/attainable_relevant_and_timeba

![Screen Shot 2021-07-29 at 9 20 37 PM](https://user-images.githubusercontent.com/24977416/127586647-55424e7a-64ee-4cc5-9c8c-d6474c0be087.png)

**Comment by LEDThereBeLight** [comment]
resolved
