### ISSUE TITLE
Institution with similar URL did not merge as expected: CMU-301

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1343]
**Describe the bug**
An old institution URL was updated to match an incoming request so that the existing institution would be used. The UI showed correctly that an existing institution would be used but after approving, a new institution was created. Also, there is no facility to delete the now defunct institution.

**Expected behavior**
The existing institution with a similar URL (same domain) should be used as the UI indicates. There should also be the ability to delete institutions 

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by LEDThereBeLight** [comment]
Several issues with institutions, including not being able to delete them, identifying institutions through a URL. Maybe expanding institutions infra. Needs larger convo.

**Comment by dkantergithub** [comment]
Test last night didn't work:
On the ArgosProd instance of Torus updated to Version 0.17.0 (1E46D00) 12/14/2021 I have an existing ASU Canvas deployment on ArgosProd (asu.edu) and also a new one from an ASU Canvas Dev instance that is a pending registration (https://asu-dev.instructure.com).  When I try to approve as is, it tells me “Pending registration with issuer ‘https://canvas.instructure.com’, client_id ‘127470000000000212’ and deployment_id ‘’ does not exist”. If I change by hand the URL for the new one to asu.edu, I get the same error.  So ultimately unable to register a second instance from the same institution.  Deployment ID is not filled in in the request for the new registration.  This request likely was started before the updated build.  Should I ask the customer to simply try again?

**Comment by eliknebel** [comment]
This issue is now being tracked by https://github.com/Simon-Initiative/oli-torus/issues/1998
