### ISSUE TITLE
Table editor is broken: CMU-300

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1346]
**Describe the bug**
This ticket is a catch all for a couple different issues in the table editor:

1. When trying to select a table size, the popup run away from the cursor
<img width="532" alt="Screen Shot 2021-08-02 at 4 39 04 PM" src="https://user-images.githubusercontent.com/6248894/127921179-abb5fc96-80ae-43d6-9a51-bfc421a7343e.png">

2. The table cell options caret is only shown in the top right of the table
3. Table cell selection is finicky, sometimes it sticks but other times it will revert back to the previous selection when cursor moves or a few seconds pass.

**To Reproduce**
1. Go to a page in the editor
2. Try to create and use the table editor

**Expected behavior**
Table creation and editing should be easier. Issues outlined above should be resolved.

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by LEDThereBeLight** [comment]
Resolved
