### ISSUE TITLE
Referencable Activity/Content Blocks 

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1359]
**Is your feature request related to a problem? Please describe.**
Cases exist where it would be great to have a pointer directly to an activity or content block, for example in the Insights or Review page. 

**Describe the solution you'd like**
Giving Content blocks and activities referencable urls (such as how Google docs does with Headings) would provide an easier way to direct someone to a block.

Then a user could do the following
1. Go to Insights
2. Find an activity they want to improve
3. Click on it's link
4. Be brought to the page the activity is on, and page is scrolled directly to the activity.

There are several cases where this would be useful, another being Review page feedback.

**Describe alternatives you've considered**
Currently, the closest approximation we have for this is by changing the Titles of activities, but thus far many don't realize this is possible and think the Titles are just the names of the type of activity (MCQ, etc..). Perhaps improving this mechanism could help solve the problem. 

**Additional context**
Add any other context or screenshots about the feature request here.  If you know of other platforms that offer this suggested functionality, please list them.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1759
