### ISSUE TITLE
Fix minor but noticeable delay when editing text Draft editor components

### ISSUE THREAD

**Issue by LEDThereBeLight** [Simon-Initiative/oli-torus#136]

**Comment by darrensiegel** [comment]
Can you elaborate on what the problem is here?  The `ActivityEditor` component does have in place a deferred persistence strategy that is currently set to a half a second.  Is this perhaps the delay that you are referring to?

**Comment by darrensiegel** [comment]
This was fixed as part of the MCQ editor work
