### ISSUE TITLE
Tooltip Descriptions on Insights Tab: CMU-299

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1360]
**Is your feature request related to a problem? Please describe.**
Some of the columns in the Insights tabs aren't super intuitive. Attempts in particular could reasonably mean "# of students who tried this" (incorrect) or "# of tries by anyone" (correct)

**Describe the solution you'd like**
Provide short tooltip descriptions for the headings in Insights
![image](https://user-images.githubusercontent.com/18299544/128084392-cd52e0fd-e4b9-4135-985d-b6cc713138a0.png)

**Comment by LEDThereBeLight** [comment]
Agreed
