### ISSUE TITLE
Deleted Activities still show in Review and Insights tabs: CMU-298

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1362]
**Describe the bug**
Deleting activities causes some odd behavior in the Insights and Review tabs.
Some activities will be deleted 
others will stay on the Insights tab but not be clickable (Dark)
others still will look as if they're still in the course, but clicking will lead to an Internal Server Error (Ghosts)

It seems to be related to whether or not I delete the Page with activities, or the activity itself. In any case, the Insights and Reivew are out of sync with the course content.

Related to #1330 

**To Reproduce**
I'm unable to successfully reproduce a Dark 

Ghosts seem to be random, but the procedure goes as follows:

1. Create activity on a page
2. Notice it appears on the Insights tab
3. Delete the activity, or delete the whole page
4. Notice the activity is a Ghost on the Insight tab

**Expected behavior**
Deleted activities/pages/etc are reflected properly in the Review and Insights tabs.

**Screenshots**
This course has only 2 Single response activities (and a youtube video). Nothing else, yet

![image](https://user-images.githubusercontent.com/18299544/128088057-080d7678-1480-429d-a75d-280bf47e6f36.png)

And...

![image](https://user-images.githubusercontent.com/18299544/128088012-d70b8d8a-7281-45a0-8916-fc7c54217f2e.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
You can use this course as an example: https://proton.oli.cmu.edu/authoring/project/gregs_test/
The history of it should reveal what I deleted when

**Comment by LEDThereBeLight** [comment]
Need to change queries to not show deleted. For analytics: do we want to add a toggle to show deleted activities? Maybe consider as a feature, but disable from view currently.
