### ISSUE TITLE
Restore undo/redo buttons

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1369]
**Describe the bug**
In Safari, Ctrl+Z is a browser level command to reopen last closed tab, therefore we cannot rely solely on these hotkeys for undo/redo in the page editor.

**To Reproduce**
1. Go to a page using Safari
2. Make some changes, try to undo them

**Expected behavior**
Users should be able to undo/redo changes regardless of browser.

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by darrensiegel** [comment]
We cannot consider restoring undo/redo buttons to address this, as that approach would require showing undo/redo buttons *for every slate editor present on the page*.  Text-level undo/redo is now Slate editor centric, as opposed to how it was previously when it was Resource level centric. 

Perhaps a solution here is to manually add another hot key sequence that triggers Undo within the current active Slate editor.

**Comment by LEDThereBeLight** [comment]
Find a way to handle undo/redo in safari (Verify keystroke used -- can we support multiple? another sequence? A button?)

**Comment by LEDThereBeLight** [comment]
discoverability of hotkey a concern
