### ISSUE TITLE
Pasting Newlines breaks Codeblock: CMU-297

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1372]
**Describe the bug**
Pasting content with newlines into a code block with no content present fails (need to add text first).

**To Reproduce**
1. write code in a Notepad that has newlines
2. Create codeblock
3. Copy code and try to paste into the codeblock
4. Notice codeblock disappears

**Expected behavior**
1. write code in a Notepad that has newlines
2. Create codeblock
3. Copy code and try to paste into the codeblock
4. Notice code is pasted into codeblock with proper line breaks

**Screenshots**
https://slack-files.com/T0C5GFUPJ-F029HU9BM7C-59b5bc6e21

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: FF

**Comment by LEDThereBeLight** [comment]
Resolved
