### ISSUE TITLE
Move Block to another page

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1373]
**Is your feature request related to a problem? Please describe.**
While its trivial to copy and paste a big block of text onto a new page, activities and other rich content have to be rebuilt from scratch if they need to be put on another page. 

One key use-case is in making an improvement to a course - we find that a page is really challenging, want to break it up into separate pages but are unable to move content between them. 

**Describe the solution you'd like**
Using the same design pattern as the "Move Page/Module/Unit" in the Curriculum View, provide a little options area on each content block that includes "Move To -->"
Clicking would bring up the same dialog, but instead of choosing a container, you choose a page. That content could then be popped into the bottom of the page. Authors could then rearrange the content on that page by clicking and dragging

1. System has Options button on each Content/Activity block
2. Author clicks Options, sees "Move To"
3. Author clicks "Move To", see sPage selection dialog
4. Author navigates to desired Page in dialog, selects and confirms. 
5. System confirms Block has moved, informs that it has moved to bottom of desired page
6. Author navigates to that page in Curriculum editor, sees Block at bottom of page, drags Block into desired position

**Describe alternatives you've considered**
Echo got around this issue via the "Insert Activity" which could work here, though there's no way to view a solitary activity (and therefore confirm it's the correct one) so it makes less sense here.

**Comment by gjbunyea** [comment]
#1359 This has a relationship with desire to reference Blocks via direct links. If a Block gets moved, what happens to prior links? Do moved Blocks get new URLs? Does the system just _know_ where each block is?

**Comment by LEDThereBeLight** [comment]
Move activity to other pages
Split pages
Copy/Change activity type
Example templates copyable / importable

**Comment by eliknebel** [comment]
Fall under a larger bucket of "authoring improvements"
