### ISSUE TITLE
Reintegrate Course into LMS (no Open in New Window)

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1374]
**Is your feature request related to a problem? Please describe.**
Institutions may want all courses to appear to be housed under the same domain. The Open in New Window LMS launch brings them out of the LMS into Torus. 

It also looks a lot better when its fully integrated into the LMS 

**Describe the solution you'd like**
When choosing the OLI Torus option in your LMS, the course should be present in the current page. 

**Describe alternatives you've considered**
Offering the option to be brought into a new window could alleviate any technical issues that may come with the integrated solution. Though it should be as a back-up option, not the primary mechanism

**Comment by eliknebel** [comment]
fixed
