### ISSUE TITLE
Delivery login failure due to unconfirmed email redirects to enroll page: CMU-296

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1378]
**Describe the bug**
When trying to login to delivery as a user after creating an account, if the user's email is not confirmed the page correctly shows an error message but it redirects to the enroll page which will create a Guest user instead of the newly created account.

**To Reproduce**
1. Go to an enrollment url, enroll as open and free and see pop-up requesting to create account
2. Click create account in the pop up and enter details, then click create
3. Attempt to log in without confirming email
4. See error message but notice you are on the enrollment page
5. If you continue to enroll, you won't be logged in as the created account but you will be logged in as a new guest

**Expected behavior**
The unconfirmed message should be shown and the user should remain on the login page.

**Screenshots**
<img width="996" alt="Screen Shot 2021-08-05 at 10 44 05 AM" src="https://user-images.githubusercontent.com/6248894/128369965-cf3f4ca9-9e69-4bac-b47f-b3f88c7ec8b7.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by LEDThereBeLight** [comment]
Configure default pow redirect routes for delivery.
