### ISSUE TITLE
Need stronger relationship between revision and project

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#141]
Now that a project and resource has a many-to-many relationship in place, we likely do not have a strong enough relationship between a revision and the project that it pertains to. 

The only way we can track which project a revision belongs to through a `PublishedResource` record - which ties a resource and revision to a particular publication (which is tied to a project). Even leveraging this is a challenge, since not every revision is published. This means that to find a project that a revisions pertains to one likely will need to traverse backwards (or forwards) thru revision history until you find one that has a `PublishedResource` record. 

To solve this we could add a project_id reference from a revision which would reference the project directly. This might pose a challenge for modeling a resource that is created wholly within an instructor customization.  The revisions pertaining to a resource that an instructor creates anew do not necessarily exist in the project - but rather in this instructor's publication. So we could put a reference to the publication on the revision. This could be more flexible in allowing a revision (and resource) to be tied to a project or more narrowly to a section.

**Comment by bitbldr** [comment]
What if we add a Project-Resource-Revision mapping (similar to ResourceMapping to publication) to map a revision to a project when it is created.

**Comment by bitbldr** [comment]
It's important to tackle this before we add a Clone Course feature

**Comment by darrensiegel** [comment]
It turns out, we did not need this stronger relationship
