### ISSUE TITLE
Warning for multiple windows/tabs open on the same page

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1412]
**Is your feature request related to a problem? Please describe.**
A colleague of mine accidently erased his work repeatedly by having two windows open on the same page in Echo. He was unaware of the 2nd window. As I perceive Torus working in a similar way, perhaps this is something to take into account.

**Describe the solution you'd like**
When the same user opens more than one window/tab open on the same page, add a warning to those windows/tabs, similar to the warning we get today with the lock that prevents two different users from editing the same page.

**Describe alternatives you've considered**
I can see the use for having two editable windows on the same page, so locking either window would reduce functionality, also you might be unable to close an open window (say that you are working from home and have your office computer open on a page). 
Synchronized updating similar to Google documents would of course be even better, but would probably require more resources.

**Additional context**

**Comment by eliknebel** [comment]
Torus currently does lock editing on a page for a per user session basis, this should not be an issue. But if there is any specific issue in torus we identify we can reopen
