### ISSUE TITLE
Github accounts do not provide separate First and Last name fields: CMU-295

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1418]
**Describe the bug**
Github accounts do not have separate first and last name data, the name data is stored entirely in the "name" field. Because of this, certain parts of the UI do not show properly because they use the separate first and last name fields. To fix this, we should either generate these values in the database from the name information or any UI that needs the name should simply use the "name" field, which is the user's full name (part of the OIDC standard fields)

**To Reproduce**
1. Create an account/Log in using Github
2. See missing generated avatar letters in top right account icon
<img width="211" alt="Screen Shot 2021-08-17 at 8 45 50 AM" src="https://user-images.githubusercontent.com/6248894/129728702-8c1132f7-e132-4e5b-b419-4e8f9960ee0a.png">

3. Log in as admin, got to Admin > Accounts > Users and see that there is no name information associated with the github account(s)
<img width="1104" alt="Screen Shot 2021-08-17 at 8 47 19 AM" src="https://user-images.githubusercontent.com/6248894/129728811-8dce34a1-b990-4fb9-822f-a68dac70f749.png">

**Expected behavior**
User interface elements which reply on user name should not be blank.

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Chrome
 - Version: 92

**Comment by LEDThereBeLight** [comment]
Resolved
