### ISSUE TITLE
User account menu items appear twice: CMU-294

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1419]
**Describe the bug**
User account menu items appear twice. This could be an issue with the HTML template

**To Reproduce**
1. Login as admin and Go to Admin > Accounts
2. Click on Manage (specific on an account with an unverified email, to see the email options)
4. See that some menu items are duplicated

**Expected behavior**
Menu items should only appear once.

**Screenshots**
<img width="465" alt="Screen Shot 2021-08-17 at 8 43 42 AM" src="https://user-images.githubusercontent.com/6248894/129729411-5081a498-3cda-4dde-b501-ec7b7ba87fa1.png">

Additionally, menu items appear off-screen. These items should be right-aligned.
<img width="261" alt="Screen Shot 2021-08-17 at 8 44 45 AM" src="https://user-images.githubusercontent.com/6248894/129729407-10ae7edd-c538-49eb-a9cf-011d376219dd.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Chrome
 - Version: 92

**Comment by LEDThereBeLight** [comment]
Changed, resolved.
