### ISSUE TITLE
Page slugs seem to be changing when they shouldn't

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#142]
In using the Revision History tool, it became apparent that page slugs are changing on ever new revision - even when the title of the page hasn't changed.

**Comment by LEDThereBeLight** [comment]
I have a question about the logic here - will it generate a new slug whenever the model is first created? ie if I make a new revision with a title and a slug `page_title`, will it generate a new, unique slug to replace what is given?
```
def update_on_change(changeset, table) do
    case changeset.valid? do
      true ->
        case Ecto.Changeset.get_change(changeset, :title) do
          nil -> changeset
          title -> Ecto.Changeset.put_change(changeset, :slug, generate(table, title))
        end

      _ -> changeset
    end
  end
```

**Comment by darrensiegel** [comment]
Yeah it will - which I would argue is probably the correct thing to do - we really should never be specifiying the slug on a change request and instead should be letting the Slug logic take care of generating it.
