### ISSUE TITLE
Guidance for/enforcement of naming conventions

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1447]
Naming conventions present a problem when reviewing course data. It is problematic when IDs and names for anything, but particularly activities/questions are not human-readable.

**Describe the solution you'd like**
Need a way to enforce human-readable names, not only for the folks creating courses, but for the data repositories that could potentially be used by others.

Not sure what the solution should be.

**Comment by LEDThereBeLight** [comment]
Activity titles - what is the use?
Do we need them?
Do we force people to set them when creating?
Change insights to use question stem?
