### ISSUE TITLE
 Cannot promote author to admin in QA or Tokamak: CMU-237

### ISSUE THREAD

**Issue by dsonaty** [Simon-Initiative/oli-torus#1453]
Scenario:

1. A user created an Author account in Torus QA.
2. Logged into QA or Tokamak as an admin.
3. Click on the Admin link on the left side of the screen and select Accounts.
4. Locate the account, click the Manage dropdown menu and select Grant Admin.

Expected behavior: A confirmation modal open and when I click on the Grant button, the account is promoted to admin.
Actual behavior: The confirmation modal is open for a second. Even if I am able to click the Grant button, the account is NOT promoted to admin.

I first thought this was because the email address has two accounts associated to it, one as a student and one as an author, and the student association is preventing me from granting admin access to the author account. However, I am seeing this issue with any Author account I try to promote.

**Comment by LEDThereBeLight** [comment]
Likely fixed by a modal change.
