### ISSUE TITLE
Empty assessments can never be updated after student begins: CMU-236

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1474]
**Describe the bug**
If a student begins an assessment with no activities, the assessment will never be able to be completed and therefore will be stuck in this state forever.

**To Reproduce**
1. Go to an empty assessment as a student and begin the assessment.
2. As an author, add an activity to the assessment and publish the new assessment.
3. Apply the update either through open and free or LMS instructor view.
4. Return to assessment and see that it is still empty and cannot be submitted.

**Expected behavior**
Empty assessments should either have a submit button to clear this state when necessary or the system should be robust against this and always move attempts forward if there are no activities for an assessment.

**Screenshots**
<img width="991" alt="Screen Shot 2021-09-02 at 4 49 26 PM" src="https://user-images.githubusercontent.com/6248894/131915009-e3b3c26e-aa00-47b9-a246-cf4bd99237a3.png">

**Comment by LEDThereBeLight** [comment]
Because of this, course updates will not propagate to empty assessment pages because students have an "in progress" assessment on that page.

**Comment by LEDThereBeLight** [comment]
Doesn't seem like any reasonable use-case for allowing empty assessments, so we should fix this.

**Comment by LEDThereBeLight** [comment]
Talk about in a future UX meeting

**Comment by eliknebel** [comment]
We should always show a submit button regardless if there is any content in the assessment. This would prevent a user from starting an assessment.

@czerwinskie @halturner: We need some more discussion around this to decide if we should even allow empty assessments to be published

**Comment by eliknebel** [comment]
This is still an issue as of v24

**Comment by eliknebel** [comment]
We have to make sure we handle this correctly related to LMS grade pass back, we should ensure the system doesn't unintentionally divide by 0, possibly handle this special case and send a score of 1? 0?

This covers the use case where an ungraded page with no activities is flipped to graded, or the unintended case where a blank assessment is published and the student begins an attempt.

We should also consider adding another QA review check for this case to help instructors identify if they forget to add activities (or any content) to an assessment.
