### ISSUE TITLE
Course overview bottom border styles are missing for page followed by container: CMU-235

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1495]
**Describe the bug**
The borders on pages are messed up when followed by a container

**Screenshots**
<img width="977" alt="Screen Shot 2021-09-07 at 4 38 03 PM" src="https://user-images.githubusercontent.com/6248894/132409283-d3c5aac8-5e00-4263-a0f0-83b7a5597e65.png">

**Environment (please complete the following information):**
 - OS: macOS 11.5
 - Browser: Chrome 92

**Comment by LEDThereBeLight** [comment]
Closing as fixed
