### ISSUE TITLE
Show student progress in basic and adaptive pages within Course Overview: CMU-184

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1535]
For all pages displayed in the course overview, a progress as a percentage complete is to be displayed. 

For both basic and adaptive pages, this percentage complete will be calculated using the following rules:
1. If there is at least one "evaluated" resource attempt, the percentage complete is "100%".
2. Otherwise, the percentage complete is the proportion of activities that have at least one "evaluated" attempt out of the total number of activities present in the page.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1719
