### ISSUE TITLE
Allow content layout variations and instructor selection for Course Overview: CMU-185

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1536]
The system should support a number of preconfigued, prebuilt "content layouts" that an instructor can choose from in determining how the Course Overview page for their section should "summarize" the course content. 

There is work to be done here to define the needed layout variations and what degree of control an instructor needs.  

The attributes of display that can vary include:
-Depth of course hierarchy to display (e.g. only top-level Units, only-top two levels, all levels)
-The layout style of presentation of the content.  One variation here could be to layout the top-level items horizontally like a tab strip and allow the student to click on one to make it active and reveal next level details.  Another option is to display vertically.

**Comment by eliknebel** [comment]
Certain presentation options may need to be configurable by an instructor

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1718
