### ISSUE TITLE
Next page buttons should be easier to use

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1585]
I do not want to have to scroll to the bottom of the page to get to the next page button...either put it also at the top, or in the middle of the page like it is in legacy with the new theme.

**Comment by gjbunyea** [comment]
Chaperone on a mobile device swaps between the full-length arrows on either side of the content, for a bottom-of-page navigation bar.

![image](https://user-images.githubusercontent.com/18299544/178999462-004705d7-1273-4d2e-a260-e55dd3fbfae4.png)

**Comment by eliknebel** [comment]
- There should always be navigation present on the screen no matter where you are scrolled
- The navigation should be quickly accessible, ideally 1 click
- Take inspiration from the current legacy chaperone theme
