### ISSUE TITLE
Enforce unique and informative names for new projects and their copies 

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1649]
**Is your feature request related to a problem? Please describe.**
It will be difficult to find, administer, and support course projects without enforcing some naming conventions for those projects and products. 

**Describe the solution you'd like**
enforcement of unique and informative naming for projects and products.

Currently already have 4 instances of "test"...need to get this under control before more folks are in the system.

**Comment by LEDThereBeLight** [comment]
slug is unique, but title should probably be allowed to be anything (individual authors can make titles independently of the rest of the authors)

**Comment by LEDThereBeLight** [comment]
Primarily an admin search/find functionality request (keeping track of courses, hierarchies, etc).

**Comment by LEDThereBeLight** [comment]
Help requests - functionality/infra around making it easier for users to give link/slug when requesting help (don't just give course "title")
