### ISSUE TITLE
Filtering and sorting the project list by a number of things

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1650]
**Is your feature request related to a problem? Please describe.**
It is difficult to manage/administer and find projects and troubleshoot/support without some sort of filtering/sorting of projects.  

Even for folks who are collaborators on more than one project, it is difficult to find exactly what is needed. It would be nice to be able to determine what my course list shows as default.

Ideas for filtering/sorting options: Institution, author, status, collaborator names, dates, "lineage/source" (all projects copied from existing), keyword in title and descriptions.

[possibly need an exercise where we show the tech team where/how things exist now to get ideas for all the admin tools needed]

**Comment by LEDThereBeLight** [comment]
"courses I'm in" - some way to see your courses vs your "side" (Added to) courses?

**Comment by LEDThereBeLight** [comment]
Possible UX discussion topic
