### ISSUE TITLE
No undo redo for activity bank selections or activities: CMU-225

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1696]
Users might expect to be able to undo/redo page level changes like changing or removing activities and activity bank selections.

**Describe the solution you'd like**
Add undo redo stack for non-text page level edits, like adding/removing activities and bank selections as well as non-content related modifications to them. Overall, the undo/redo strategy might be confusing and may lead to undesirable user experience.

**Describe alternatives you've considered**
Reintroducing page level undo redos which cover higher level edits outside of slate edits. Or somehow plugging into the slate undo/redo strategy so that a page level undo/redo action can trigger the lower level slate undo/redos.

**Comment by LEDThereBeLight** [comment]
Undo/redo is inconsistent and can lead to lost work through toasts disappearing.
Undo/redo in text editors is impossible in safari because the hotkey is claimed by the browser.

**Comment by LEDThereBeLight** [comment]
Should undo/redo stay part of the block - add to toolbar (inserted at top of content/activity block)? Not have undo/redo across entire page for text editing?

**Comment by LEDThereBeLight** [comment]
Page-level undoable changes - keep list of them somewhere visible so they can be accessed?? Not sure.

**Comment by eliknebel** [comment]
We expect that adding ability for an author to see history and revert to previous versions combined with current undo/redo impl will be sufficient
