### ISSUE TITLE
Sorting by some columns does not work correctly: CMU-224

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1697]
Sorting server tables by some columns does not work as expected. For instance, in the "Authors" view, sorting by Role does not work correctly.  Also, sorting by All Sections by Type does not seem to work

**Comment by eliknebel** [comment]
As of Dec 10, 2021 this is still and issue in the authors view `/admin/authors`, click the roles column and sorting doesn't work as expected. This is most likely a table column name config issue. Other tables in the admin views should be verified as well.
