### ISSUE TITLE
Cancelling Remix during Custom LMS section creation still creates section: CMU-232

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1717]
I had launched from Canvas into Torus and selected "Custom Course Creation".  I entered Remix, and selected a base project.  Then, from the UI where I can customize the content, I clicked "Cancel", thinking it would back me out to the main page where I could choose "Basic Course Creation".  Instead, it created the course section and took me to the section overview page.

**Comment by LEDThereBeLight** [comment]
Maybe change button -> cancel section creation vs cancel remix?
Section is already created before opening remix tool

**Comment by LEDThereBeLight** [comment]
Priority? argos?
