### ISSUE TITLE
Content editing has some issues: CMU-231

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1725]
**Describe the bug**
While trying to edit content there are a few issues I noticed:

1. Cursor placement and selection doesn't always stick the first time. This may be due to slate slow to update and resetting cursor position or the state being updated when a page save completes
![2021-10-20 11-05-38 2021-10-20 11_06_45](https://user-images.githubusercontent.com/6248894/138119920-65130e52-8cfa-49eb-ba5c-67770a0435ac.gif)

2. When trying to select text, hovering over the selection toolbar causes weird jittery behavior
![2021-10-20 11-02-27 2021-10-20 11_04_33](https://user-images.githubusercontent.com/6248894/138119574-2c8bd363-8370-4600-8371-04f53a2ae149.gif)

3. Placement of the insert toolbar is incorrect. It should appear next to the plus button that was clicked. It seems to be relative to the editor container, and not the button
![2021-10-20 11-07-47 2021-10-20 11_08_41](https://user-images.githubusercontent.com/6248894/138120479-9f84ba07-ccc1-40aa-b446-b0f10bfa84b8.gif)

4. Add content scrolls to incorrect location, and the popup stays open. The scroll position probably shouldn't change at all and the popup should automatically close
![2021-10-20 11-11-13 2021-10-20 11_12_54](https://user-images.githubusercontent.com/6248894/138120915-8d1954db-e042-48d2-bbaa-ddd809e66487.gif)

**To Reproduce**
1. Go to authoring page editor and see screen captures above

**Environment (please complete the following information):**
 - OS: macOS 11.6
 - Browser: Chrome 94

**Comment by LEDThereBeLight** [comment]
Sometimes adding a content block and clicking into the text editor to start editing text does not select/focus and allow text editing.

**Comment by LEDThereBeLight** [comment]
Firefox on windows: ^ issue above with selection after adding content block

**Comment by LEDThereBeLight** [comment]
3 & 4 captured in other tickets

**Comment by LEDThereBeLight** [comment]
number 2 has technical difficulties, might need another solution instead of the hovering toolbar

**Comment by eliknebel** [comment]
1 and 3 are fixed. 3 is being tracked by https://github.com/Simon-Initiative/oli-torus/issues/1502

This issue will remain open to track issue 2
