### ISSUE TITLE
Users who register as Author account using Google Sign In cannot confirm their email address: CMU-230

### ISSUE THREAD

**Issue by dsonaty** [Simon-Initiative/oli-torus#1728]
Scenario:

1. Go to https://tokamak.oli.cmu.edu/
2. Click on the 'Authoring Sign In' button.
3. Click on the 'Create an Account' link.
4. Click on the 'Sign In With Google' button.

The user is authenticated but has not registered in Torus and does not received an email confirmation. 

1. When I login as an admin
2. Click the Admin icon on the left side of the screen
3. Click the Manage Authoring Accounts link
4. I see the author's email address but their name does not appear. 

Issue: The user in the scenario can log into Tokamak as an author, but I am unable to grant them admin access. 

Here is the Slack conversation I had with an individual at ASU:

Earlier I had registered with gmail so it showed google authentication so had no password set.
I first sent myself forgot password email. Then reset to a new password
Then removed google authentication because it needed password to remove authentication from Google
Then I created a new account with same email address using create account and a password
So I believe issue comes with accounts which are made with google authentication

**Comment by eliknebel** [comment]
Cannot reproduce
