### ISSUE TITLE
Adding Learning Objectives and Sub-objectives continues to be problematic

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1733]
Please change the way that objectives and sub-objectives are added.

For starting a new project, the "break-down" continues to be very confusing to explain and use. 

Add the ability to JUST add objectives and sub-objectives - very rarely are objectives needing to be children of a larger objective. More frequently, authors just want to be able to add objectives and sub-objectives in a straightforward way.

**Comment by LEDThereBeLight** [comment]
Need another design discussion. What exactly should this look like? Technical complexity and problems with migrating from oli legacy.

**Comment by LEDThereBeLight** [comment]
Is supporting Datashop our first priority or should it be more intuitive?

**Comment by LEDThereBeLight** [comment]
https://docs.google.com/document/d/1krTyKPOASXZ27S019h43KG6iUpUH3U80UMuFidFCOfo/edit#heading=h.d1q7zsogcxlk

**Comment by LEDThereBeLight** [comment]
Add second button for create child objective in addition to break down?

**Comment by eliknebel** [comment]
https://github.com/Simon-Initiative/oli-torus/pull/3049
