### ISSUE TITLE
Image resizing functionality with Custom Dimensions, Aspect Ratio, Alignment, and Accessibility options. 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#1740]
Currently, image resizing occurs when the user resizes it using the mouse intuitively but cannot enter custom image dimensions. There might be custom dimensions that a user might want to enter instead of resizing it intuitively. 

It would be great to enter the custom dimensions height and width of the image along with intuitive resizing. 

Along with this, "Maintain Aspect Ratio" and "Alignment" of the image would also be good to have in the settings. (referring to Echo toolbar). Another attribute that will be good to add would be a checkbox to indicate whether the image is a Decorative Image. If the image is a decorative image then it is usually not read by screenreaders (Canvas does this currently).

**Comment by LEDThereBeLight** [comment]
UX agenda item - what options/settings do we need for each content item?
