### ISSUE TITLE
Ability to change to custom font size and style

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#1741]
Currently, we can only resize the text in 3 standard sizes (small, medium, large). It would be great for users to set custom font size and font style for the text. 

In the bar that pops up when we select a text, we can also change the text style and size. 

Additional features like left/right/center justification of text, indentation, subscript, and superscript support are helpful while editing content. These are currently available in Echo authoring, Canvas authoring, and many other platforms.

**Comment by LEDThereBeLight** [comment]
UX meeting topic. Need to understand what exactly we need and why.
