### ISSUE TITLE
Summative Image-Coding does not show Feedback: CMU-222

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1778]
**Is your feature request related to a problem? Please describe.**
When using an Image-Coding activity in a summative quiz, there is no feedback on which questions that are correct, nor wrong the you do the review.
You can only see the summary (5.0 out of 5.0) but not how you did on the individual questions. This defeats the possibility to learn from your mistakes. 

**Describe the solution you'd like**
When reviewing a summative Image-Coding activity, feedback should be shown like all other question types. 

**Additional context**
![image](https://user-images.githubusercontent.com/18299544/139305110-1259e867-21a0-47c1-9cd9-2e3f65640dda.png)

![image](https://user-images.githubusercontent.com/18299544/139305064-5285782d-348a-4c8b-a78f-e8a58627b025.png)

**Comment by LEDThereBeLight** [comment]
In review mode: image coding does not show feedback, other activities do
