### ISSUE TITLE
Characters not rendering properly (',<,>)

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1780]
**Describe the bug**
Several characters do not render properly. Particularly `'` `<` `>`
This is likely due to use of Swedish keyboards - I'm unable to duplicate the issue myself.

**Screenshots**
![image](https://user-images.githubusercontent.com/18299544/139312901-f3d31622-3a5d-4dba-a864-86da9add06b4.png)
https://proton.oli.cmu.edu/sections/img_python_course_test/page/python_functions_introduction

![image](https://user-images.githubusercontent.com/18299544/139313098-a38f0411-335c-4fb4-a5c1-157e0146643c.png)
https://proton.oli.cmu.edu/sections/mechanics_forces_and_equilibri/page/new_page_wfnce

**Additional context**
It seems that even previewing the page results in the errors. This page contains all 3 known character issues - two in the choices for Q1, the other in the text of Q3
https://proton.oli.cmu.edu/authoring/project/introduktion_till_krafter/resource/new_page_wfnce

Any attempt I've made to copy the char to my own course and try yields a proper render, but we have a growing body of users in Sweden to which this would be an issue

**Comment by eliknebel** [comment]
Fixed in #1826
