### ISSUE TITLE
Create Content Dialog and Insert Multimedia Floats off screen: CMU-221

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1786]
**Describe the bug**
The Create Content or Activity dialog floats sometimes in unpredicatble locations. On smaller screen sizes this will result in lack of access to menu options, or in some cases, the menu being completely off screen. This is particularly the case when the dialog is at the bottom of the screen

The MultiMedia insert dialog can sometimes appear all the way up a page from where you want to insert it. This may be related to page length.

**To Reproduce**
1. Scroll to bottom of screen
2. Click Add Content
3. NOTICE: Dialog gets cut off by bottom of screen OR Dialog appears awkwardly to the side

1. Create long page with many elements
2. In Content Block, click to add multi-media
3. NOTICE: Dialog does not appear where clicked
4. Scroll up page
5. NOTICE: dialog appears floating far above where clicked

**Expected behavior**
Dialogs should always appear adjacent to where they were clicked. If there is no room for the dialog to appear below the click point, it should appear directly above (click-point becomes the coordinate for the bottom of the dialog)

**Screenshots**
https://proton.oli.cmu.edu/authoring/project/gregs_test/resource/dimensions_of_loneliness#
![image](https://user-images.githubusercontent.com/18299544/139459477-bf3c4b0c-67dc-4fd8-ad39-cdd0bcbe706a.png)
![image](https://user-images.githubusercontent.com/18299544/139460376-1759a164-2fb4-4084-9904-d39596172f99.png)

![floating dialog](https://user-images.githubusercontent.com/18299544/139460729-da86f207-eead-4157-87d5-90c70db474dc.gif)

**Environment (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome, Firefox

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by LEDThereBeLight** [comment]
Also tooltips not disappearing when inserting link/popup etc.

**Comment by gjbunyea** [comment]
Looks like this happens with the "Shuffle Order" dialog as well
I have a report of it floating up past the view screen.
![image](https://user-images.githubusercontent.com/18299544/141160226-e7988a20-1511-44dc-b564-78f71e5834f4.png)

**Comment by gjbunyea** [comment]
Still an issue as of Feb 15, 2022
