### ISSUE TITLE
Improve media library experience

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#179]
There are other enhancements we should probably consider tackling in ER2 such as:

- [x] Finally adding other Media type filters to the left sidebar under "All Media" or removing it
- [x] Restyling to fix inconsistencies and swap Insert and Cancel buttons for consistency
- [ ] Show upload progress bar(s)
- [ ] Maintain sort by preference when media window is closed/reopened
- [ ] Allow multiple selection of media items
- [ ] Consider consolidating media insertion to single button that encompasses images, videos, audio instead of having separate buttons

**Comment by gjbunyea** [comment]
Suggestion: Ability to remove media from the library. 
If someone uploads the wrong image (for example), there's no way to remove that from the project.

**Comment by czerwinskie** [comment]
Revisited on 8-7.
First step is to access the media library regardless of actions needed (just be able to browse).
project-based media library at the moment; access the project-wide media library and being able to manage media there.

**Comment by tanvidomadia** [comment]
From slack thread: good to have alt text for an image that lives in the media library but that can be overridden in a particular page.
