### ISSUE TITLE
Editing links to external pages disabled: CMU-437

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1847]
**Describe the bug**
When I try to edit the link to an external page, I cannot select, edit, delete, nor change the default link text.

**To Reproduce**
1. Go to https://proton.oli.cmu.edu/authoring/project/questionbased_learning/resource/questionbased_learning_from_a_
2. Click on Answer Key
3. Klick on the link in the answer key
4. Try to edit the link

**Expected behavior**
Link text should be editable

**Screenshots**
![image](https://user-images.githubusercontent.com/53688217/141330693-c58a3b3b-3a3d-42ad-9966-9813c38a629f.png)

**Environment (please complete the following information):**
 - OS: macOS 11.6
 - Browser: chrome
 - Version: Version 95.0.4638.69 (Officiell version) (x86_64)

**Comment by chrislawson** [comment]
Same is true on a practice page in Authoring mode in both Chrome and Safari.  Firefox does not even let you select text to make a link.

**Comment by LEDThereBeLight** [comment]
Closing as resolved.
