### ISSUE TITLE
Simplify and improve objective creation and tagging: CMU-404

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1859]
This current UI for attaching learning objectives to activities is allowing top-level, non leaf node objectives to be attached.

**Comment by LEDThereBeLight** [comment]
Is this an original requirement or did something new come up? What is the reason for an explicit difference between LOs / skills or parent objectives / children objectives? Does this have to do with datashop? Is there a way to automatically attach all children objectives when exporting to datashop when a parent is tagged? Some confusion around why we're changing this now.

**Comment by gjbunyea** [comment]
Need for LearnLab

**Comment by gjbunyea** [comment]
A related matter is to manipulate the LO tree more fluidly. Desired LO features include:
- Create Sub-LO on the fly (no 'Breakdown')
- Move LOs around in structure
- Identify which LOs have no Activities (Echo-style Design Audit)

Most important of these is creating sub-LOs on the fly

**Comment by gitnauk** [comment]
Tested 6/27/22

- Sub-LOs can be created on the fly ✔️ 
- LOs can't be moved around in structure ❌
- It's not evident which LOs have no Activities ❌
