### ISSUE TITLE
After applying updates to a section there is no way to get back: CMU-436

### ISSUE THREAD

**Issue by bsparks** [Simon-Initiative/oli-torus#1871]
Coming from the section detail (open & free) and then going to "Manage Updates", view the update and apply. There is no way (other than the browser back button) to get somewhere relevant.

![image](https://user-images.githubusercontent.com/384189/142072678-3e952ad7-43ed-4071-b19d-db6d1c348c3d.png)

**Comment by LEDThereBeLight** [comment]
Part of a larger discussion - we need to think through how delivery routing / navigation should look, workflows. Many other pages have a similar problem.
