### ISSUE TITLE
Slow query during OliWeb.Api.AttemptController#submit_activity: CMU-407

### ISSUE THREAD

**Issue by ehilfer** [Simon-Initiative/oli-torus#1903]
About 7 user testing courses in Argos qa

During OliWeb.Api.AttemptController#submit_activity

The following query was averaging about 10 seconds to complete:

SELECT a0."id", a0."attempt_guid", a0."attempt_number", a0."date_evaluated", a0."scoreable", a0."score", a0."out_of", a0."transformed_model", a0."resource_id", a0."revision_id", a0."resource_attempt_id", a0."inserted_at", a0."updated_at", r1."id", r1."title", r1."slug", r1."deleted", r1."author_id", r1."resource_id", r1."previous_revision_id", r1."resource_type_id", r1."content", r1."children", r1."tags", r1."objectives", r1."graded", r1."max_attempts", r1."recommended_attempts", r1."time_limit", r1."scope", r1."scoring_strategy_id", r1."activity_type_id", r1."primary_resource_id", r1."inserted_at", r1."updated_at", p3."id", p3."attempt_guid", p3."attempt_number", p3."date_evaluated", p3."score", p3."out_of", p3."response", p3."feedback", p3."hints", p3."part_id", p3."activity_attempt_id", p3."inserted_at", p3."updated_at" FROM "activity_attempts" AS a0 INNER JOIN "revisions" AS r1 ON r1."id" = a0."revision_id" LEFT OUTER JOIN "activity_attempts" AS a2 ON ((a0."resource_id" = a2."resource_id") AND (a0."id" < a2."id")) AND (a0."resource_attempt_id" = a2."resource_attempt_id") INNER JOIN "part_attempts" AS p3 ON a0."id" = p3."activity_attempt_id" LEFT OUTER JOIN "part_attempts" AS p4 ON (((a0."id" = p4."activity_attempt_id") AND (p3."part_id" = p4."part_id")) AND (p3."id" < p4."id")) AND (p3."activity_attempt_id" = p4."activity_attempt_id") WHERE (((a0."resource_attempt_id" = $1) AND (a2."id" IS NULL)) AND (p4."id" IS NULL))

**Comment by ehilfer** [comment]
More context info here: https://appsignal.com/argos-education/sites/6195a9ad7ccda61059f95916/performance/in[…]ge=2021-11-23T19%3A40%3A00.000Z%2C2021-11-23T19%3A41%3A00.000Z

**Comment by darrensiegel** [comment]
This has been addressed.
