### ISSUE TITLE
Send actual total points for line item instead of hardcoded 1: CMU-413

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#1962]

**Comment by dkantergithub** [comment]
@darrensiegel @eliknebel Tested this with "course like no other" adaptive page which should be worth 3 points.  Saw the attached behavior where the line item came in at 116 points and upon successful completion, all 116 points were awarded to the student.  Seems like we're on the right track but somehow calculation of total points for a given lesson is wrong.  I'll pull in a bigger product and see what we're looking at
<img width="1924" alt="Screen Shot 2021-12-14 at 8 06 18 PM" src="https://user-images.githubusercontent.com/89100627/146104329-08815a44-9235-40ba-9bea-dc0a00348539.png">
<img width="1924" alt="Screen Shot 2021-12-14 at 8 05 54 PM" src="https://user-images.githubusercontent.com/89100627/146104330-257a5e3e-d6d6-4f10-a60d-2fbbb9b4cf8b.png">
<img width="1924" alt="Screen Shot 2021-12-14 at 8 04 28 PM" src="https://user-images.githubusercontent.com/89100627/146104331-0829d13c-3788-4bec-b8ae-8784c3e52c76.png">
.

**Comment by dkantergithub** [comment]
When I look at the BioBeyond course, Unit 1, I see the following point values:
Course Like No Other = 3 max points
Scientific Reasoning = 243 max points
Scientific Tools = 275 max points
Graphing Skills = 106 max points
Scientific Skills = 125 max points

When I use the current Torus build and manage the section as an instructor and pre-populate the line items I get the following:
Course Like No Other = 116 max points
Scientific Reasoning = 730 max points
Scientific Tools = 469 max points
Graphing Skills = 135 max points
Scientific Skills = 275 max points
<img width="1924" alt="Screen Shot 2021-12-14 at 8 19 42 PM" src="https://user-images.githubusercontent.com/89100627/146105175-05bb483b-f648-4dba-b1e8-bc651da17c31.png">

So something seems off with the totalling of the max score.  Can we dig into the "BioBeyond" product that's on Argos Prod to understand what it's including in the calculation and figure out how to tweak?

**Comment by dkantergithub** [comment]
Hi, Darren.  Yes, those are what a user sees when taking BioBeyond on SmartSparrow and what Lucien keeps referring me to as the expected max points for each lesson.  It’s quite possible that the error is in the specification in the migration about which screens are to be scored and which are not and this needs to be attended to by their editorial team.  But I’m eager to figure out why there’s a difference.
