### ISSUE TITLE
System-maintenance landing page pointed to wrong support email, and didn't work

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2148]
The **Contact us** link on the system-down notification page was non-functional. Hovering on the link revealed a mailto:oli-help@lists.andrew.cmu.edu. The correct email is oli-help@cmu.edu

![Screen Shot 2022-01-25 at 10 06 45 AM](https://user-images.githubusercontent.com/24977416/151006024-7a5692b7-155c-4a65-9d72-6274aa6545ae.png)

**Comment by eliknebel** [comment]
Production maintenance page update to correctly point to oli-help@cmu.edu
