### ISSUE TITLE
Add guidance to failure notifications for grade passback: CMU-470

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2155]
In all places an instructor would be notified of an LTI grade passback failure, add guidance for actions to take.

- LTI test failure
This failure should recommend the instructor consult the LMS admin about revisiting the configuration. If there are URLs the LMS admin should refer to, such as a knowledgebase article or an internal, institution-specific LMS config document, we should provide that in the language

- grade passback failure
If the instructor should attempt manual passbacks, they need instructions on doing so. The instructions should include basic information about what OLI has already tried as well as reasons failure may have happened. Then, what are the steps for manual updates? Can they be done in bulk if there are multiple?

**Comment by LEDThereBeLight** [comment]
Add guidance around bulk passback updating (e.g. for lost connection across many students). The feature exists, but no explanation right now.

**Comment by LEDThereBeLight** [comment]
LMS admin needs to know how to handle failures. LTI Test tool should help with this - allows an admin to know the course was setup correctly.

**Comment by LEDThereBeLight** [comment]
Need to do this at some point. Taking off triage list.

**Comment by LEDThereBeLight** [comment]
There is a feature to test the grade passback mechanism. You can see if this fails. Also, in the Torus gradebook, instructors can see where students had failed grade passback. We can put language advising on how to address failures in both of these places.

Need specific wording. Do we want a help article or just a UI change?
