### ISSUE TITLE
Provide Legacy Alternatives/Alternative compatibility

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2190]
Legacy OLI provides the `alternatives` and `alternative` elements, which allow an author to provide two or more different representations of a piece of content, one of which is displayed at run-time based on a a course section / organization setting. This feature is used to allow a Statistics course, for example, to support multiple statistical software packages in their worked examples.  For every worked example in the course, an alternative would exist implemented in Excel, one in Minitab, and one in R.  Then, at a org level, a preference is set to determine which alternative to use across then entire course.

Torus needs to provide the same capability, but needs to do so at a more general level so that eventually the same infrastructure can power A/B testing and perhaps other features.

**Comment by eliknebel** [comment]
#3093
