### ISSUE TITLE
Editor UX Consistency and Improvements: CMU-468

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2195]
There are some general UI inconsistencies in the editor that should be addressed, for example:

1. In general, border styles and overall feel is inconsistent with the rest of the UI. We should add some styling to the toolbar and its menus to make it feel more consistent, like its part of the overall system. The floating toolbar can also get in the way of editing, for example seeing/editing the previous line. I think this is a usability regression of the "always show" toolbar approach from the existing "only show when selected" approach.
<img width="358" alt="Screen Shot 2022-02-07 at 3 02 07 PM" src="https://user-images.githubusercontent.com/6248894/152863026-05c661cd-7799-4ac6-9573-6bbca9e0fc18.png">
<img width="308" alt="Screen Shot 2022-02-07 at 3 02 13 PM" src="https://user-images.githubusercontent.com/6248894/152863029-5185d6f4-4244-4a60-82b3-b24e5b4cfa03.png">
2. There is no action to button for links to "Apply" to hide to popup and give a user the indication that their url will be saved
<img width="501" alt="Screen Shot 2022-02-07 at 2 50 05 PM" src="https://user-images.githubusercontent.com/6248894/152861988-815850bb-f6fd-46da-82f8-46ce2751abce.png">
3. Modals should use bootstrap styling so that they are consistent with the rest of the system (see Add Webpage or Media Manager for example)
<img width="1025" alt="Screen Shot 2022-02-07 at 2 49 51 PM" src="https://user-images.githubusercontent.com/6248894/152862138-26224992-b39d-4347-8ef7-9c73352a05df.png">
4. Insert from URL shows a browser popup, which is inconsistent with the other modals
<img width="1192" alt="Screen Shot 2022-02-07 at 2 59 44 PM" src="https://user-images.githubusercontent.com/6248894/152862497-a53ffd29-2b93-4363-901d-91cd17f5b6cc.png">

If not addressed here, then a followup issue should probably be created to track these.

_Originally posted by @eliknebel in https://github.com/Simon-Initiative/oli-torus/issues/2159#issuecomment-1031864511_

**Comment by LEDThereBeLight** [comment]
Figure out how to handle content editing / adding items in general + toolbar. Need better design.

**Comment by eliknebel** [comment]
Closing in favor of more granular issues and some of the issue here have already been resolved.

https://github.com/Simon-Initiative/oli-torus/issues/2612
