### ISSUE TITLE
Ordering options can appear In Order at the outset: CMU-467

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2205]
**Describe the bug**
Ordering activities can have their options appear in order when the activity is loaded. It seems random, but this case should be controlled for.

**To Reproduce**
1. Create Ordering activity with several options (the more options, the more difficult to reproduce this issue)
2. Preview page
3. NOTICE: Question options appear already in order

**Expected behavior**
Ordering options should be randomized, but never show the correct order at first. Students should always have to move something to create the correct order.

**Screenshots**
![image](https://user-images.githubusercontent.com/18299544/153426663-9ff55fd7-d6c2-47cd-93ab-d17668a80372.png)

**Environment (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome

**Comment by joecoolle** [comment]
On this question:
https://proton.oli.cmu.edu/sections/questionbased_learning/page/value_of_textbooks
It happened 3 out of 12 attempts, which is higher than completely random (1/6)! Of course, that could just be bad luck, but it is suspicious. The proposal above would solve the issue.
<img width="846" alt="image" src="https://user-images.githubusercontent.com/53688217/153569127-07eed26a-ba51-4651-ab15-7b202d78b089.png">
macOS 12.1
Chrome Version 98.0.4758.80 (Officiell version) (x86_64)
