### ISSUE TITLE
Allow instructors to alter resource settings

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2211]
Currently settings on resources within a course can only be changed by an author.  This capability needs to be exposed to instructors.  The most important resource settings to allow modification of are:

1. Whether or not a page is graded or practice
2. When graded, how many attempts a student should have
3. When graded, what scoring strategy to use

This of course has to be done in a way that instructor changes are scoped locally to the course section and do not affect the underlying project. 

The solution should facilitate receipt of ongoing updates that change settings in resources that do not conflict with any instructor changes.  For example, if an instructor mades no customizations of their own, as they continually migrate to new course updates their course section should receive any settings changes.   If an instructor has updated the settings for a particular page, that fact should block the automatic application of new settings form an update.

**Comment by LEDThereBeLight** [comment]
We need support for global overrides and individual page overrides. For example, activity attempts should be able to be changed at the section/course level.

**Comment by eliknebel** [comment]
Part of this work has been started #3101
