### ISSUE TITLE
Torus should notify via email if someone tries to create an account with existing email address: CMU-464

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2234]
Torus should send an email to the existing account holder if they/someone tries to create a new account with that email. Currently torus will simply display a message saying the email must be confirmed, but if the account already exists no email will be sent. This may cause a user, who already has an account but is trying to create one with the same email, to think that the confirmation email simply failed to send when in fact, they already have an existing account.

A email that explains "Someone tried to create a new account with this email" giving the user the option to sign in, or simply ignore the email would at least let the user know that they already have an account and can access it by signing in.

**Comment by LEDThereBeLight** [comment]
What should the language be? Requesting an LE's help: please add some example wording to this ticket.
