### ISSUE TITLE
Course Ingestion: pcard: CMU-484

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2272]
This is a course ingestion task for the "CMU Finance Fundamentals" course. 

SVN location: https://svn.oli.cmu.edu/svn/content/financial_systems/finance_fundamentals/branches/v_1_1-echo

Ingestion of this course is blocked by:

- [x] https://github.com/Simon-Initiative/oli-torus/issues/2274

**Comment by gitnauk** [comment]
DTD version upgrades were made in version 1.2. 
This is the SVN location of the version that should get ingested into Torus:
https://svn.oli.cmu.edu/svn/content/financial_systems/finance_fundamentals/branches/v_1_2-echo
