### ISSUE TITLE
New Units added "above" existing content get published to the bottom of the order: CMU-479

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2299]
**Describe the bug**
If you add, for example, a new "Welcome" unit to your course at the top of the curriculum, and then publish, that unit will appear in the publish as the last unit. 

**To Reproduce**
1. Create a course with a Unit (Unit A)
2. publish it
3. Add a Unit (Unit B) above the original unit
4. Publish again
5. Note that Unit B appears below Unit A in the publish. 

**Expected behavior**
When publishing course structure changes, published content should be made to match the structure of the Curriculum. 

Alternately, if Curriculum is meant to be more of a "pool of resources" require creating a Product before publishing and enforce that only Products can be Published. Then tie publication structure to Product structure. 

**Screenshots**
In the Curriculum View, the order is as follows:
![image](https://user-images.githubusercontent.com/18299544/157265880-5aca45df-043a-46ef-9577-d8457d96e2ad.png)
But when I go to update the publish of the course, the order has changed. 
![image](https://user-images.githubusercontent.com/18299544/157265812-58631c5b-09fd-43d0-b1ba-3f5fa5e56d89.png)

Using the curriculum builder to add contents from a different course, the structure appears to match the structure of the Curriculum. (Though the Unit numbers are odd here...)
![image](https://user-images.githubusercontent.com/18299544/157263582-d1b4304c-7ea6-4859-81f2-707c3c36c232.png)

Once the contents have been added via course builder, the Welcome unit jumps to the back.
![image](https://user-images.githubusercontent.com/18299544/157263615-e8285b32-996d-499f-93a2-906d02105b88.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
This problem is exacerbated by the fact that reordering Units makes the Unit Numbers out of order. See:  #2298

**Comment by eliknebel** [comment]
We need to verify with a unit test, that when items in a container remain unchanged (not reordered), that torus updates with the correct ordering specified in the project/product (replacing the ordering in the updated product/section)

**Comment by darrensiegel** [comment]
Closed, no longer an issue due to rework of update algorithm
