### ISSUE TITLE
Container titles don't save if you choose dropdown in Option: CMU-491

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2327]
**Describe the bug**
In Tokamak authoring, after creating a container like a Unit or Module, the container titles doesn't save if you go to Options and then choose a title from the dropdown menu. The screen also greys out and freezes, then needs to be refreshed.

**To Reproduce**
1. Go to Curriculum
2. Click on a container type, like Unit
3. Click on the dropdown on the very right and select Options
4. Click in the Title text box and select a title from the dropdown menu that shows up
5. Click Save

**Expected behavior**
The title should save and you should return to a working view of the curriculum

**Screenshots**
This is the view when selecting a title from the dropdown menu
![image](https://user-images.githubusercontent.com/41222927/158417235-69cf0c2a-fd64-4e8d-9c96-df640481317f.png)

And this is the view once the screen freezes and greys out
![image](https://user-images.githubusercontent.com/41222927/158417354-2a7e63cf-791d-41cb-b740-8a5bd693b637.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 99

**Comment by LEDThereBeLight** [comment]
Environment-specific issue? Need to track down.
