### ISSUE TITLE
Account social login details don't render properly: CMU-490

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2341]
**Describe the bug**
On the account page, the social login provider details do not render properly. See screenshot below.

<img width="1262" alt="Screen Shot 2022-03-16 at 4 00 36 PM" src="https://user-images.githubusercontent.com/6248894/158680110-dacc69ed-0ff3-4a6b-b5da-e96ecf8f1fd9.png">

**Comment by LEDThereBeLight** [comment]
Yeah we should fix the styling.
