### ISSUE TITLE
Table dropdown menu inaccessible: CMU-489

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2345]
**Describe the bug**
Table dropdown menu inaccessible because it overflows inside the table. See screenshot below.

**Screenshots**
<img width="642" alt="Screen Shot 2022-03-17 at 12 04 56 PM" src="https://user-images.githubusercontent.com/6248894/158843013-064b9f6f-e07f-421d-9b83-896ae248ad29.png">

**Comment by LEDThereBeLight** [comment]
We need to look at the menus for content editors and make sure they all show. Probably a z-index issue? Overflow: none?
