### ISSUE TITLE
Modules show up in the prev/next navigation in the author: CMU-488

### ISSUE THREAD

**Issue by bsparks** [Simon-Initiative/oli-torus#2359]
![image](https://user-images.githubusercontent.com/384189/160027172-e856e022-97c2-417f-8409-81e0e547f32e.png)
the item circled is a Module, if you click on it in the authoring view then it opens as if it were a page that you can edit.
![image](https://user-images.githubusercontent.com/384189/160027465-c01bc0a8-37d9-42fa-ab1e-6a8c9e80b2cc.png)
since I believe Modules are just another kind of container that should not be editable, this doesn't make sense and we should probably skip them like units in the nav

**Comment by LEDThereBeLight** [comment]
Opening a link to a container in the page editor will open the page editor for that container resource, but that page should not be editable. We need to handle container page editing routes -> should not be able to directly navigate to the page editor view for a container. Also, should remove the containers as links from the hierarchy in authoring mode (page editor - not preview).

Preview should still route to containers.

**Comment by LEDThereBeLight** [comment]
Could detect at the page editor level and just conditionally render a message "containers are not editable" instead of showing the page editor components.
