### ISSUE TITLE
Swap out "graded" for "scored"

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2374]
Change language from graded or grading to scored or scoring.

Instructor input indicates that students are concerned with anything that refers to grades, because OLI is often used purely for practice and never bears on their grades (formally). Therefore, the common request is to call activities "scored" and the act of assigning them a score to be called "scoring" rather than "grading."

Every number a student earns during the class is a score, and only the final record for their class is a grade, granted by their teacher and the school, not by OLI. OLI work only contributes to the student's grade (or doesn't contribute at all).

**Comment by LEDThereBeLight** [comment]
Not all courses use OLI scores to account for student grades. We should change instances of the word "grade(d?)" to "score(d?)".

**Comment by darrensiegel** [comment]
We want to move away from using any terms related to "Graded", but only in a student facing context. It's fine to keep language "Gradebook" and "View Grades" for instructor oriented views. 

The last remaining student facing place s that we need to update, I believe, is the "Submit Assessment" button that a student uses to submit a graded page. Maybe this can just be renamted to "Submit"

**Comment by darrensiegel** [comment]
Closed, done.
