### ISSUE TITLE
Display time stamps in user's time zone, not UTC: CMU-486

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2376]
Time stamps in the gradebook/attempt lists are presented in UTC instead of the user's (viewer's) time zone. All time stamps and other time-related displays should be localized to the viewer, and not in UTC.

**Comment by LEDThereBeLight** [comment]
We need to audit the usages of timestamps in the codebase and ensure the timezone is taken into account. All delivery-related (section) views should use the course section's selected timezone, regardless of the user's actual local timezone.

Should we add an option to allow user-overridden timezones?

**Comment by LEDThereBeLight** [comment]
Need more discussion first with Argos etc on how exactly to handle it.
