### ISSUE TITLE
Non-Admin managed O&F / LMS-Lite sections

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2379]
**Is your feature request related to a problem? Please describe.**
Currently, only Admins are able to make use of the O&F or LMS-Lite style published courses. This effectively keeps admins in the middle of course updates, enrollment changes, and other management needs. 

**Describe the solution you'd like**
Being able to specify instructors for section management, or permitting non-admins to build LMS-Lite sections would get Torus LMS-Lite closer bridging the gap between push-button-publishing, without an LMS

**Comment by eliknebel** [comment]
Resolved
