### ISSUE TITLE
Project Export unable to be re-imported: CMU-493

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2410]
**Describe the bug**
When trying to import an exported project, the import fails, stating several resources are missing. It appears these resources are not produced by the export. 

**To Reproduce**
1. Go to this course: https://proton.oli.cmu.edu/authoring/project/kth_swedish_cs101
2. Export the course 
3. Go to Admin > Ingest Course Project
4. Choose the digest you exported, hit 'Upload'
5. **Notice** Upload fails, produces error saying invalid activity references

**Expected behavior**
This course should be able to be imported successfully. All features are native. 

**Screenshots**
The error for the specific course in question
![image](https://user-images.githubusercontent.com/18299544/162215139-d17423c3-a72f-4279-a8a6-c2f92e7d9d98.png)

In the digest, the error activity references do not appear (3305 for an example)
![image](https://user-images.githubusercontent.com/18299544/162215708-5b5a6861-29d9-44c7-b59f-a416eff794e2.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome Latest

**Additional context**
This is important for our ability to move content between servers (Argos, KTH, etc...)

**Comment by gjbunyea** [comment]
The KTH instance of Torus is Version 0.18.4 (66CCD43) 03/04/2022

**Comment by LEDThereBeLight** [comment]
Issue is likely on course-digest creation, but db admin difficulties across servers make this tough to work through.

Need to find a way to reproduce locally.

**Comment by LEDThereBeLight** [comment]
Workaround to manually remove the affected files, re-export/import, then copy the content back into the imported course. Not ideal but could unblock.

KTH has a need for this by the summer schedule.

**Comment by gjbunyea** [comment]
Note that all 3 missing references were located in 1 file: `3483.json`

**Comment by gjbunyea** [comment]
After removing these 5 invalid references, I was able to successfully import the course. ✅

In summary, a total of 8 invalid activities showed over 2 export json files. They are as follows

`3483.json` : missing 3305, 3273, 3421
`3447.json` : missing 3297, 3250, 3347, 3328, 3291
