### ISSUE TITLE
Youtube titles are captions in Torus: CMU-494

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2426]
**Is your feature request related to a problem? Please describe.**
If an author adds a title to a youtube video in Echo, it shows up in the Legacy course as a header. 
However, if that course is ingested into Torus, the authored title shows up as a caption

**Describe the solution you'd like**
Support authored titles in Torus

Links to Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/b15ae083c7464a9082fb4c44bf5b1146?organization=test-3ygubwm6-1.0_default
and Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/key_takeaways_from_the_quiz_snrz0

This is how it looks in the student view in Legacy:
![image](https://user-images.githubusercontent.com/41222927/163021925-e93436ec-6135-440d-b036-2dd57b38a649.png)

And student view in Torus:
![image](https://user-images.githubusercontent.com/41222927/163022018-af0db6b6-033a-4ae8-805e-6cf1b1322c2a.png)

**Comment by LEDThereBeLight** [comment]
Examples of differences between legacy courses and torus courses.

**Comment by LEDThereBeLight** [comment]
We should remove these "titles" from the youtube elements themselves and add actual title-elements to the content above the youtube video.

**Comment by LEDThereBeLight** [comment]
Consider a way of keeping the title tagged with the video for identification purposes. Possible data analytics feature.
