### ISSUE TITLE
Allow Torus authors to view current Youtube link and change it: CMU-495

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2427]
**Is your feature request related to a problem? Please describe.**
In Echo, an author can add a youtube video, and there's a field where they can view and change the link.
In Torus, entering a youtube link renders a static image on the page. There doesn't seem to be a way to view what the current link is, or click on it to change the link. An author would have to just delete the current video and copy/paste a new link in the content container.

**Describe the solution you'd like**
For authors to be able to change the link of a youtube video in Torus authoring

Legacy:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/f4657d9c07ca4711af394bbe3d181655?organization=test-3ygubwm6-1.0_default
Torus:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/including_all_students_xflqc

How it looks in Echo:
![image](https://user-images.githubusercontent.com/41222927/163023089-dbd3272a-0755-4986-97b7-e26b37c65a64.png)

How it looks in Torus:
![image](https://user-images.githubusercontent.com/41222927/163023177-460b9db2-3fe7-4c80-8e01-cf1499c3d578.png)

**Comment by LEDThereBeLight** [comment]
We need to add the options menu back into the youtube editor. Also for iframe/website embeds.

Need to decide what options we actually want.
