### ISSUE TITLE
Render Learn by Doing activities in Torus as a group

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2428]
**Is your feature request related to a problem? Please describe.**
 When a course is ingested from Legacy into Torus, the Learn by Doing formative assessment is rendered as multiple individual Learn by Doing Activities, rather than one large group as the author intended.

Supporting Content from formative assessments in Echo gets put into Content containers in Torus (there doesn't seem to be any other option), but then this makes it appear as not part of the whole Learn by Doing activity. (rather than activity containers)

**Describe the solution you'd like**
Keep the Supporting Content and Questions/Activities in Echo's Learn by Doing grouped when a course is ingested into Torus.

Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/f3143010165b4628975396b41f2e009f?organization=test-3ygubwm6-1.0_default
Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/including_all_students_xflqc

Legacy, student view:
https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=dce7b9c27f000001498a6df9d81bafa7
Torus, student view:
https://tokamak.oli.cmu.edu/sections/gusio_1ox7s/page/including_all_students_xflqc

How it looks in Legacy course to students:
![image](https://user-images.githubusercontent.com/41222927/163024950-b937b257-99de-42ab-8a5f-ee6778a85a57.png)

How it looks in Torus course to students:
![image](https://user-images.githubusercontent.com/41222927/163025036-0fc2f01c-9670-40f4-a337-63d5cabfa4a3.png)

**Comment by LEDThereBeLight** [comment]
Containment issues in general around activities because of the layout decisions we've made in torus to move away from activities having their own supporting content, introduction, and conclusion content. 

In torus, those could be groups ("LBD" etc). the group wraps the content related to the activities, and we can make legacy introduction/conclusion/supporting content to these groups.

**Comment by eliknebel** [comment]
Resolved by https://github.com/Simon-Initiative/oli-torus/pull/2442 and https://github.com/Simon-Initiative/course-digest/pull/39
