### ISSUE TITLE
Images in Supporting Content are not transferring in ingested course: CMU-506

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2446]
**Describe the bug**
In an ingested course, if there is an image in Supporting Content in an inline formative assessment in Echo, it is not showing up in Torus. Instead they appear as a little icon.

The images show up as an icon in all other tested views in Torus (authoring preview, instructor view of a course section, student view of a course section).

**To Reproduce**
Legacy - Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/newaf1a1b51bcf54126ad495928f002ca21?organization=test-3ygubwm6-1.0_default&nodeGuid=fc80e6a429174ffeb302cef530d583b7

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/worked_examples_jmuu4

**Expected behavior**
Images should transfer as images

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164300080-64db620b-bdeb-4d25-bf2f-01276431f63f.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164300226-256b4dae-cc16-4e4a-b65c-b69416604fd8.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by eliknebel** [comment]
Fixes have landed, we need to retest this to verify it is working now

**Comment by gitnauk** [comment]
In the recent ingestion 6/9/22, the images in Supporting Content in a formative assessment were not transferring over in the Torus authoring view, authoring preview, instructor view, or student view.

This is the link to the [formative assessment in Echo authoring](https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/newaf1a1b51bcf54126ad495928f002ca21?organization=test-3ygubwm6-1.0_default)

This is the link to the [formative assessment in Torus authoring](https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_hyhwj/resource/worked_examples_o1hzt)

This is how it looks in Torus authoring:

![image](https://user-images.githubusercontent.com/41222927/172940035-65aaafc0-45a8-47ee-8d4d-da6a062894e2.png)
