### ISSUE TITLE
Image caption formatting is not rendering in ingested course

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2447]
**Describe the bug**
Text formatting in image captions in Echo are not showing up in Torus. 
For instance, bold, subscript, and line breaks are not rendering in any of the tested views in Torus (authoring environment, authoring preview, instructor view of a course section, student view of a course section). 

**To Reproduce**
Legacy - Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/newaf1a1b51bcf54126ad495928f002ca21?organization=test-3ygubwm6-1.0_default&nodeGuid=adf7689fdf8a4fd5b31ec2ba099818ae

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/worked_examples_jmuu4

**Expected behavior**
Text formatting should render properly in the ingested course

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164302575-af71a6a5-0fc7-41ed-bf2b-96c154d9a60f.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164302891-bef53c61-96a8-4112-b789-d498024deab3.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by darrensiegel** [comment]
We need to add the ability to include rich text (including, and probably most importantly hyperlinks) to captions in Torus. 

This needs to be done carefully, in a way that will be backwards compatible with all of the existing "string" based captions.  We do not want to have to create a migration to upgrade all captions of all images in all revisions of all resources.
