### ISSUE TITLE
Code blocks are rendering as normal text in ingested course

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2448]
**Describe the bug**
"Code blocks in Supporting Content in an inline formative assessment are showing up as normal text in an ingested Torus course in all of the tested views (authoring environment, authoring preview, instructor view of a course section, student view of a course section).

**To Reproduce**
Legacy - Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/newaf1a1b51bcf54126ad495928f002ca21?organization=test-3ygubwm6-1.0_default&nodeGuid=fca05696f88d4faabc673df0e348a299

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/worked_examples_jmuu4

**Expected behavior**
Code blocks should render as code blocks

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164304118-5abfd43f-8e76-4ef4-9809-ccd45dd8750b.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164304267-6a290c4a-2197-4927-b069-ab636c698f29.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by darrensiegel** [comment]
Closing.  In the original XML file the content in this example is not a codeblock element, rather a sequences of paragraphs with inline code elements. 

```
<p id="f11e538444504f68a68689dc35e44c0e">
				<em>
					Computer Science Worked Example
				</em>
			</p>
			<p id="dc3c7fc362cd41feb17ea6cf558af415">
				<em>
					Problem
				</em>
				: Consider the following implementation of selection sort:
			</p>
			<p id="f96f389e0fc940799764a7061a561ee5">
				<code>
					<![CDATA[void selection_sort(int[] A, int lo, int hi) ]]>
				</code>
			</p>
```
