### ISSUE TITLE
Tables are not rendering properly in ingested course

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2449]
**Describe the bug**
Some aspects of tables are not rendering properly in the ingested Torus course.

For instance, apostrophes in table titles are being converted to "&apos". The titles are also appearing below the table like captions.
In some tables, new lines aren't rendering properly

**To Reproduce**
Legacy - Echo authoring, title rendering
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/f39e0cdf84c14d72a97b4f42b12290d3?organization=test-3ygubwm6-1.0_default

Torus authoring, title rendering:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/step_1_define_your_learning_ob_0wj2h

Legacy - Echo authoring, new line rendering
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/f7de97f6f9e14e76902f2f96bd5452f7?organization=test-3ygubwm6-1.0_default

Torus authoring, new line rendering:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/step_3__write_your_discussion__fu9ss
**Expected behavior**

**Screenshots**

This is how apostrophes in titles look in **Echo**:
![image](https://user-images.githubusercontent.com/41222927/164305943-cf88537c-046f-4538-9193-8672c7c56580.png)
and how line rendering looks in Echo:
![image](https://user-images.githubusercontent.com/41222927/164306190-831ffbcd-758e-46e7-8515-b5be8a34cf4e.png)

Versus how apostrophes in titles look in **Torus**:
![image](https://user-images.githubusercontent.com/41222927/164306380-2b6e31dc-d684-44ea-981f-74b40c189977.png)
and how line rendering looks in **Torus**:
![image](https://user-images.githubusercontent.com/41222927/164306494-c388c0c7-70a4-4fda-b269-853e8259f764.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by darrensiegel** [comment]
"titles" as first class elements of tables, images, and other media elements will not be supported.  But, any migrated table or media element with a title present will have the contents of that title migrated over as an "h6" header element, positioned just above the table or image.

**Comment by darrensiegel** [comment]
Fixed the rendering of titles.  There is no issue with table rendering. The example above is a table that is inside of a list item, which Torus does not support.  It gave a best effort.
