### ISSUE TITLE
Images and text are rendering inline in unordered list (in ingested course)

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2450]
**Describe the bug**
Images and text within an unordered list are rendering on the same line in the _authoring preview_, _instructor view_, and _student view_, even though they appear on different lines in the Torus _authoring environment_ (which is how they should appear, according to the Legacy course)

**To Reproduce**
Legacy - Echo author preview:
https://echo.oli.cmu.edu/content-service/api/a41a25715a2445aa80ac6cd04daa0fb3/resources/quick_preview/325698c142b34a91a7353150a5f1c3ed

Torus author preview:
https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals/preview/welcome_to_cmu_finance_fundame

**Expected behavior**
Images and text should appear on different lines.

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164308264-c0cc9eeb-7546-406b-80f8-eb2016efe760.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164308346-7b5d0b0b-7fa8-44cb-b02b-2fa5e91fb711.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by eliknebel** [comment]
We first need to investigate how difficult this to accomplish in the editor
