### ISSUE TITLE
Images in text blocks are not transferring in ingested course: CMU-505

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2451]
**Describe the bug**
In a practice page, images that were in an Image Block in Legacy are transferring properly, but images that were in Text Blocks are not transferring to the ingested course in Torus or showing up in any of the Torus views (authoring environment, authoring preview, instructor view of a course section, student view of a course section).

**To Reproduce**
Legacy - Echo authoring:
https://echo.oli.cmu.edu/#finance_fundamentals-1.2/system_overview2?organization=finance_fundamentals-1.2_default

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals/resource/system_overview_2_of_2

**Expected behavior**
All images should transfer in the ingested course, whether they're in an image block or text block in Legacy.

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164309210-6ebd9bf8-9582-4d48-8130-35d8e4a70dba.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164309097-4349fced-fd30-4947-82c1-7ab3bd15b220.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by darrensiegel** [comment]
The approach for handling inline images will be:
1. Update Torus authoring and delivery to support *existing* inline images.  
2. Do not allow (for the moment) new inline images to be created.

**Comment by LEDThereBeLight** [comment]
Note: need to not only support inline images, but also change the course ingestion code to handle block images that are children of other elements (e.g. a block image in an echo text block on its own line). Can map them directly to block images in torus and continue to render subsequent block-items. Images might also be direct children of list items, need to double check the DTD to see where images are allowed.
