### ISSUE TITLE
"My Response" Survey is not showing up in the ingested course

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2456]
**Describe the bug**
The whole "My Response" Survey is missing.
The last line from the previous Content container is also missing.

**To Reproduce**
Legacy - Echo authoring:
https://echo.oli.cmu.edu/#finance_fundamentals-1.2/certification?organization=finance_fundamentals-1.2_default

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals/resource/certification_assessment

**Expected behavior**
The Survey and the last line of content should show up

**Screenshots**

This is how it looks in Echo authoring:
![image](https://user-images.githubusercontent.com/41222927/164340864-ea8681f7-2fe3-4bfc-9f0b-6bc70ca3ee7c.png)

And this is how it looks in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/164340919-ade6e44c-8237-4b15-9e5a-ca97e37d6db4.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by darrensiegel** [comment]
This is expected, as Torus does not yet support Surveys.
