### ISSUE TITLE
Insights page doesn't show links to activities in the Activity Bank

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2457]
**Describe the bug**
The analytics in the Insights page in Torus looks unusual. Some questions have scores but can't be clicked on.

**To Reproduce**
Torus authoring view of Insights page:
https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals/insights

**Expected behavior**
All the questions should be clickable

**Screenshots**

And this is how the Insights page looks in Torus:
![image](https://user-images.githubusercontent.com/41222927/164341189-07ffa67d-9fcb-41f0-85a8-e672a585cead.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.18.4

**Comment by eliknebel** [comment]
We need some more investigation here on how to solve the identification problem of activities in the analytics

**Comment by eliknebel** [comment]
We might want to consider preserving some legacy information during migration by putting useful information into the revision so that we can use it for a possible future solution

**Comment by eliknebel** [comment]
We need to better handle links to activities that exist in the activity bank (previously question pools)

During ingest we can take a better approach here to extract a portion of the question stem to determine what the title should be. Alternatively, we could just use the ID here.
