### ISSUE TITLE
Instructor checklist for delivery

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2471]
Accompanying every OLI section could be an area in the Manage Course page that helps instructors keep track of all the things they might need to take care of or communicate. For example (each would be accompanied by a link where appropriate):

1. Helping students access OLI. 
2. Setting a schedule. 
3. Adding TAs.
4. Invite observers / guests.
5. Etc.

**Comment by eliknebel** [comment]
We should develop a knowledge base article first, then followup with a possible integration into the software. Before creating a a software feature, we should consult a UX designer about how to approach.

**Comment by eliknebel** [comment]
Closing for now, we can reopen when we have more info
