### ISSUE TITLE
Input question editor allows deletion of the only Input: CMU-500

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2494]
**Describe the bug**
Input questions were ingested properly from a Legacy course. However, if I delete the Dropdown input, the question loses its information and then says "Something went wrong. This item could not be displayed."

(There also doesn't appear to be a way to create new Input questions with Dropdown/Text/Number options. )

In the [author preview](https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals_lkmo5/preview/test_your_knowledge_80mlg), the question text still shows up, but the Dropdown options render strangely. In the instructor view of a course section, some questions don't show up. In the student view of a course section, the page says "Internal Service Error."

**To Reproduce**
SVN Repo:
https://svn.oli.cmu.edu/svn/content/financial_systems/finance_fundamentals/branches/v_1_2-echo/content/x-oli-inline-assessment/tutor_gl_segments.xml

Legacy:
https://echo.oli.cmu.edu/#finance_fundamentals-1.2/tutor_gl_segments?organization=finance_fundamentals-1.2_default

Torus:
https://tokamak.oli.cmu.edu/authoring/project/finance_fundamentals_lkmo5/resource/test_your_knowledge_80mlg

**Expected behavior**
It should be possible to edit Input questions without generating errors. It should be possible to create new Input questions.

**Screenshots**
This is how an unedited Input question looks like in the Torus authoring view:
![image](https://user-images.githubusercontent.com/41222927/166608291-f325fc55-9b09-4a7a-a1cb-af31ccc60e91.png)

This is how edited Input questions look like in the Torus authoring view:
![image](https://user-images.githubusercontent.com/41222927/166608246-3ef4ec33-6181-48bc-adc9-a100390b1f9c.png)

![image](https://user-images.githubusercontent.com/41222927/166608355-6f75871a-6fb4-4d32-a0a6-26a23f2fe622.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.19.1

**Comment by darrensiegel** [comment]
The creation issue I believe was due to the Multi input activity not being enabled for the course.

**Comment by darrensiegel** [comment]
In testing this, I believe the issue here is that the MultiInput editor is allowing the last Input to be deleted, thus leaving the activity in a bad state.

**Comment by LEDThereBeLight** [comment]
#2505

**Comment by LEDThereBeLight** [comment]
I wish I was able to fix this before leaving, but I'm just not sure why duplicate inputs are being created when refreshing the page. Basically, it looks like editing an input works fine and the model is persisted correctly from what I could tell, but refreshing the page somehow adds an input with the same ID at the end of the stem which leads to problems. Unfortunately I couldn't pin down what exactly was going on in time. I think this is what is causing the downstream effects of weirdness with adding/removing inputs, but I'm not 100% sure.
