### ISSUE TITLE
Youtube video heights are not scaling properly in ingested course: CMU-502

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2497]
**Describe the bug**
The Youtube video pixel width is transferring from Legacy to the ingested Torus course, but the pixel height is not scaling properly.

**To Reproduce**
SVN repo:
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/test-3ygubwm6/branches/v_1_0-echo/content/x-oli-workbook_page/f4657d9c07ca4711af394bbe3d181655.xml

Legacy - Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/f4657d9c07ca4711af394bbe3d181655?organization=test-3ygubwm6-1.0_default

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_701my/resource/including_all_students_uvx5z

**Expected behavior**
The pixel height should be the same as in Legacy, or scale properly

**Screenshots**
How it looks in Echo:
![image](https://user-images.githubusercontent.com/41222927/166613389-79ee0e23-2e7d-4ae0-9537-c86e20ae1842.png)

It looks fine in Torus authoring:
![image](https://user-images.githubusercontent.com/41222927/166613465-8fda0b5e-c465-4cfb-84cd-4af1f9417bfe.png)

But the height is not scaling properly in [author preview](https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_701my/preview/including_all_students_uvx5z), the [instructor view](https://tokamak.oli.cmu.edu/sections/gusio_spring_22_701my/preview/page/including_all_students_uvx5z), or [student view](https://tokamak.oli.cmu.edu/sections/gusio_spring_22_701my/page/including_all_students_uvx5z):

![image](https://user-images.githubusercontent.com/41222927/166613654-dd452353-c5ce-46e4-b88d-3d9f31538771.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.19.1

**Comment by LEDThereBeLight** [comment]
Should be able to fix the html content renderers
- html.ex content renderer
- html.tsx activity renderer
