### ISSUE TITLE
Input box appears twice in Multi Input activity: CMU-504

### ISSUE THREAD

**Issue by sharisiri** [Simon-Initiative/oli-torus#2505]
**Describe the bug**
When designing multi input questions the input box appears twice in preview mode and when accessing the course as a student.

**To Reproduce**
1. Create a multi input activity
2. Add one or more inputs to the question stem
3. Preview the course or publish and access as student

**Expected behavior**
The input box should only appear once in the question stem.

**Screenshots**
How the question looks in the course builder view:
<img width="1173" alt="Screenshot 2022-05-06 at 13 40 48" src="https://user-images.githubusercontent.com/37027404/167126469-16efc07e-b6e5-45ad-8422-dd5d52fb74ad.png">

What it looks like in preview mode or when accessing the course as a student:
<img width="811" alt="Screenshot 2022-05-06 at 13 40 58" src="https://user-images.githubusercontent.com/37027404/167126534-33a336be-bdb7-463f-9b50-60b5d272638f.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 0.18.4 

**Additional context**

We encountered the bug in our managed instance over at [qbl.sys.kth.se](https://qbl.sys.kth.se/). Just let me know if you need collaborator or student access to investigate further. It is hosted on AWS following the self-hosting instructions in the wiki.

**Comment by LEDThereBeLight** [comment]
See #2494
