### ISSUE TITLE
Can't match a closing curly brace in regex

### ISSUE THREAD

**Issue by zmineroff** [Simon-Initiative/oli-torus#2519]
**Describe the bug**
In the "Single Response" activity type, you can't match a closing curly brace (}) with Regex,

**To Reproduce**
1. Create a Single Response Activity within a Page.
2. Click on the Answer Key tab
3. Choose Regex in the dropdown (default is Contains)
4. In the text box next to Regex, type the following: (\\})
5. Click on Preview
6. In the activity, type the following in the text box: }
7. Press Submit
8. The activity will say your input is incorrect

**Expected behavior**
The activity should say the input is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/7597670/167946312-4c2a16f0-ddf7-4b63-ae20-c6bea6021429.png)

![image](https://user-images.githubusercontent.com/7597670/167946343-1f49305c-f4a8-4829-8b73-04850327a2d8.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 101.0.4951.54

**Additional context**
Matching an open curly brace works as expected. The Regex is: (\\{)
You actually don't even need to escape the curly brace, so the following works too: ({)

I tried a few ways of matching the closed curly brace, including:
- ([}])
- (})
- (\\})

**Comment by zmineroff** [comment]
You also can't match a closing curly brace using "Contains" in the Answer Key for a Single Response activity.

The following DOES work as expected:
1. Set the answer key to Contains and enter this: {1,2,3,4
2. Preview the activity and enter: {1,2,3,4
3. When you click submit, the activity says your input is correct.

But the following DOES NOT work as expected:
1. Set the answer key to Contains and enter this: {1,2,3,4}
2. Preview the activity and enter: {1,2,3,4}
3. When you click submit, the activity says your input is incorrect.

**Comment by darrensiegel** [comment]
Left and right braces and special characters within Torus' rule grammar. The combinator based parser needs to allow the escaping of these characters.
