### ISSUE TITLE
Check All That Apply questions have all answers checked in the ingested course Answer Key

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2525]
**Describe the bug**
When a course is ingested from Legacy to Torus, the Check All That Apply questions have all the answers checked in the answer key for the Correct Answer.

In Legacy, the author can write a global "incorrect" feedback for any selection that does not have targeted feedback. In the ingested course, this feedback becomes "targeted feedback" for all answer choices. 

Even though the answer key looks strange in authoring, the questions look normal in delivery to the student.

**To Reproduce**
SVN repo:
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/test-3ygubwm6/branches/v_1_0-echo/content/x-oli-assessment2/newefb800b8458b480a9b085baf7fcf071c.xml

Legacy - Echo authoring:
https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/newefb800b8458b480a9b085baf7fcf071c?organization=test-3ygubwm6-1.0_default&questionId=db99f6baaca04de2a311a22ad438844c

Torus authoring:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/quiz_v095d

**Expected behavior**
In the Torus authoring view, the answer key for the correct answer shouldn't have all the options checked.

Authors should also be able to see the targeted feedback for specific selections, rather than see all options checked for incorrect answers.

**Screenshots**
In Legacy authoring view, there's feedback for the correct selection (A,D) and then incorrect feedback for everything else:
![image](https://user-images.githubusercontent.com/41222927/168130569-2dc1a79a-9ff9-431c-8c9e-dbd5dd9ff269.png)

In the ingested Torus course, all the answers are checked for the correct answer in the authoring view
![image](https://user-images.githubusercontent.com/41222927/168130818-2b839cb6-5c94-48e5-a25f-917fe07d6511.png)

and all the answers are checked for incorrect targeted feedback, multiple times:
![image](https://user-images.githubusercontent.com/41222927/168131097-ab1b9df6-21b9-4d93-8e7e-50cdd1ef54d0.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.19.1

**Comment by darrensiegel** [comment]
Fixed
