### ISSUE TITLE
Linked summative assessments aren't being handled correctly in course migration tool

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2527]
**Describe the bug**
Previously, the ingested GUSIO course was showing a summative assessment as a linked Quiz.

In the two recent ingestions of GUSIO, the summative assessment is showing up as a regular practice page in both the Torus authoring and student views.

**Expected behavior**
The summative assessment should be a Quiz that links to a separate page that is not a practice page.

**Screenshots**
Previously, this is how the GUSIO course looked in the Torus [authoring view](https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/activity__quiz_q9lyo)
![image](https://user-images.githubusercontent.com/41222927/168136967-36cf41e7-f626-4c70-a997-de7656a8d6b0.png)

and Torus [student view](https://tokamak.oli.cmu.edu/sections/gusio_1ox7s/page/activity__quiz_q9lyo)
![image](https://user-images.githubusercontent.com/41222927/168137135-95fa6c59-cdb1-49ce-aff0-421de28438eb.png)

and it went to a summative assessment for the [student view](https://tokamak.oli.cmu.edu/sections/gusio_1ox7s/page/quiz_v095d), where they could only press submit at the end of the page.
![image](https://user-images.githubusercontent.com/41222927/168137406-2d141735-a05f-4f75-bfe9-4da1013fc56e.png)

However, in the last two GUSIO ingestions, it appears as a formative assessment for both the [author view](https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_701my/resource/activity__quiz_4xjka)
![image](https://user-images.githubusercontent.com/41222927/168137919-391c27b9-42f2-4f80-bd84-4953a314d17a.png)

and the [student view](https://tokamak.oli.cmu.edu/sections/gusio_spring_22_701my/page/activity__quiz_4xjka)
![image](https://user-images.githubusercontent.com/41222927/168138084-5ce8a40b-27cd-4823-8666-6367bd522150.png)

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Comment by eliknebel** [comment]
course-digest issue https://github.com/Simon-Initiative/course-digest/issues/41

**Comment by eliknebel** [comment]
Completed as part of #3020
