### ISSUE TITLE
The Quiz summative assessment needs to be more easily accessible and editable.

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2529]
**Describe the bug**
There are a few issues wrapped up in this one:

- In authoring, the Quiz summative assessment does not show up in the Curriculum. I had to access it through the Insights page.
- Clicking on the Quiz link in the authoring practice page does not take you to the editable summative assessment 
- Clicking on the Quiz link in authoring brings up a dropdown menu which cannot be easily edited, and it also persists on the page even if you click out of it.

**To Reproduce**
This is the page that has the Quiz link:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/activity__quiz_q9lyo

And this is the actual editable Quiz summative assessment:
https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_1ox7s/resource/quiz_v095d

**Expected behavior**
- The Quiz page should be accessible as an assessment page in the curriculum (if the page is in the curriculum in Legacy).

- However, if it's linked out from a practice page because it was an embedded summative assessment in Legacy, then it should be accessible through the link in Torus. 
It should also show up in something like a bucketed resources page in Torus (in case the link is deleted). 

- Regardless of how it's accessible, it also needs to have page Options available -- for example, to set the number of attempts.

**Screenshots**

Clicking on the Quiz link from the practice page doesn't take you to the editable summative assessment page, and it also brings up a dropdown menu that can't be edited easily. 
![image](https://user-images.githubusercontent.com/41222927/168143237-5503e154-bc23-4e8a-8889-234c46f8dab8.png)

________________________________________

**ONE OTHER THING TO NOTE**

In the [student view](https://dev-03.oli.cmu.edu/jcourse/lms/students/syllabus.do?last=entry&section=dce7b9a27f000001342e9a7d589055d8) in Legacy, there are direct links to summative assessments from the highest Syllabus (Sequence) view, even if they are not a page in the actual curriculum. (i.e. If you click into Module 2 to view its curriculum, you will see the practice page that has the embedded summative, not a link to the actual summative.)

![image](https://user-images.githubusercontent.com/41222927/168148304-1d62c492-18a7-4677-8831-fb3281cb0314.png)

There is no such option in Torus for students to view direct links to summatives. 

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.19.1

**Comment by eliknebel** [comment]
Completed as part of #3020
