### ISSUE TITLE
Different question types should be consistent with how they enable Submit buttons

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2534]
**Describe the bug**
In the student view of formative assessments in Torus, Multiple Choice questions do not enable the Submit button until you have selected a choice.
However other questions, such as Multi Input questions and Short Text questions, let you click Submit and receive feedback even if you haven't answered anything.

**To Reproduce**
Student view of a formative assessment:
https://tokamak.oli.cmu.edu/sections/finance_fundamentals_lkmo5/page/test_your_knowledge_06zbb

**Expected behavior**
The enabling/disabling of the Submit button should probably be consistent across questions.

**Screenshots**
![image](https://user-images.githubusercontent.com/41222927/168155194-1464350c-c5c9-47c9-a3fe-302ee9165698.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: Chrome
 - Version: v0.19.1

**Comment by darrensiegel** [comment]
closed, submit buttons removed from MCQ, multi input activities
