### ISSUE TITLE
Some controls in the UI are too low contrast for accessibility

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2542]
**Describe the bug**
Some controls in the UI have too low contrast for accessibility. Specifically the content outline expand button

**Screenshots**
<img width="668" alt="Screen Shot 2022-05-03 at 12 16 23 PM" src="https://user-images.githubusercontent.com/6248894/168333644-ab853ed3-4d43-4ee2-ab62-9c88dc9c451b.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 101

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by gitnauk** [comment]
Contrast is higher 👍 

![Image](https://user-images.githubusercontent.com/41222927/175718788-6b355dd1-4410-4826-9d57-380111c0f4a4.png)
