### ISSUE TITLE
Improve Browser Tab Labels

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2626]
**Is your feature request related to a problem? Please describe.**
The browser tab labels for any Torus page all read 'OLI Torus' making it difficult to know which Torus pages you have open when using multiple Tabs. Or even just using one tab.

**Describe the solution you'd like**
Browser Tabs should have a small snippet of the project/page title after OLI Torus.

Some examples:

OLI Torus | Overview | Ken's eLearning Demo

OLI Torus | An Introduction to the Rise Framework

OLI Torus | Preview | An Introduction to the Rise Framework

OLI Torus | Publish | DEMO - Learning Engineering Topics

**Describe alternatives you've considered**
Any more context that could be provided to in the browser tab will make it easier to navigate.

**Comment by gitnauk** [comment]
Tested 6/27/22
Browser tab labels now have title of the page. 



![Image](https://user-images.githubusercontent.com/41222927/175994847-4b80403a-49d8-4c81-a26b-d48452be8a3e.png)
