### ISSUE TITLE
Deleted pages show up in Review

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2627]
**Describe the bug**
Deleted pages are producing Review opportunities. 

**To Reproduce**
1. Create page
2. Delete page
3. Run Review
4. NOTICE: Deleted page appears with 'No Attached Activities' warning

**Expected behavior**
Deleted pages should not appear in the Review

**Screenshots**
Course only contains these 4 pages
![image](https://user-images.githubusercontent.com/18299544/172395634-d95cb444-5c53-4ac7-b812-c57745bdbcf3.png)

But Review still references these pages
![image](https://user-images.githubusercontent.com/18299544/172395727-4670511d-d0be-45a5-a68d-1aa3c330d344.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome latest

**Additional context**
Something similar happens with Activity/Questions on the Insights page, though there may be better reasons for keeping those lying around

**Comment by eliknebel** [comment]
Review query still find pages in a deleted container. For example, when you delete a container, the pages are still "around" and so they show up in review
