### ISSUE TITLE
Editing Unit names

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#2633]
Not able to find a way to rename/ edit unit names. Currently, am only able to see them as "Unit 1", "Unit 2", etc. I want to rename them to custom unit names. 

There is an edit button next to the practice page and graded assessment names but not next to unit names.

**Comment by gjbunyea** [comment]
If you click 'Options' on the Unit link you can rename the Unit (or Module, etc..)

**Comment by eliknebel** [comment]
captured in #2639
