### ISSUE TITLE
UI for editing titles in Curriculum

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2639]
**Describe the bug**
The way that Unit, Page etc titles are currently edited is confusing and harder to use.
To edit the title of a unit, page, etc, a user right now needs to click the down arrow, and select options, where they can then edit the title. This is not how other things were edited elsewhere in the interface, and not how people usually expect to edit titles. It's hard to find (eg, #2633  ), not very intuitive, and has a lot of steps. Also, for a unit title this is the only thing contained in options. 

For a page, there's an edit button *between* the title and the dropdown arrow that thus looks more like it should edit the title, but actually it's how to go to editing the page. (I in fact misclicked this later, even after I knew how it worked). For a page this way of title changing was also experienced poor workflow.

**Expected behavior**
It would be good if editing titles was more intuitive and streamlined. Further, the link that edits the page itself could be changed to something like 'edit page contents'. 

**Screenshots**
<img width="989" alt="Screen Shot 2022-06-07 at 8 38 46 PM" src="https://user-images.githubusercontent.com/23661836/172508226-70dd27b9-1579-4455-9867-5d1d7e0a7ad6.png">
<img width="993" alt="Screen Shot 2022-06-07 at 8 39 19 PM" src="https://user-images.githubusercontent.com/23661836/172508229-39d25c5d-728f-4fac-ab93-1b3001efd170.png">
<img width="802" alt="Screen Shot 2022-06-07 at 8 39 31 PM" src="https://user-images.githubusercontent.com/23661836/172508295-c43e33ab-83e9-4ec3-bc02-4bbbb460046f.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 14.1.2

**Additional context**
Cognitive accessibility relevant. 
Noticed that at the moment the text of the page title itself isn't being used for anything (unlike the unit titles, which are); it could potentially be used, which could potentially help disambiguation for a screen-reader.

**Comment by eliknebel** [comment]
We could have a UX designer investigate a better approach to how this should work.
