### ISSUE TITLE
Quiz link says "Click to begin" instead of "Quiz"

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2650]
**Describe the bug**
I'm not sure if this is an error or intentional, but the link to a Quiz in an ingested course now says "Click to Begin" instead of "Quiz"

**To Reproduce**
[The quiz workbook page in SVN repo](https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/test-3ygubwm6/branches/v_1_0-echo/content/x-oli-workbook_page/d6ed8e87b1b64901a886aa496d86b2bd.xml)
[The quiz workbook page in Echo authoring](https://echo.oli.cmu.edu/#test-3ygubwm6-1.0/d6ed8e87b1b64901a886aa496d86b2bd?organization=test-3ygubwm6-1.0_default)
[The quiz workbook page in Torus authoring](https://tokamak.oli.cmu.edu/authoring/project/gusio_spring_22_hyhwj/resource/activity__quiz_4vde3)

**Expected behavior**
The quiz link in Echo was given the name of the summative assessment, which was "Quiz" in this case. The ingested course should probably say the same thing.

**Screenshots**
This is how it looks in Legacy student delivery
![image](https://user-images.githubusercontent.com/41222927/172871192-a523e0fd-c56b-45bc-b663-9783034c4ab0.png)

but this is how it looks in Torus student delivery
![image](https://user-images.githubusercontent.com/41222927/172871329-bf22c8b1-e78b-46ad-a3ee-8df45c5c29d6.png)

**Environment (please complete the following information):**
- OS: Windows 10 Pro
- Browser: Chrome
- Version: v0.19.3

**Comment by darrensiegel** [comment]
This is by design
