### ISSUE TITLE
Summative assessment questions are not numbered in Torus.. should they be?

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2652]
**Is your feature request related to a problem? Please describe.**
Summative assessment questions were automatically numbered in Legacy. Should they also be automatically numbered in Torus?

This is how it looks in Legacy student delivery:
![image](https://user-images.githubusercontent.com/41222927/172883059-5cacfabb-e228-4358-92e1-ee4181191fa7.png)

But this is how it looks in Torus student delivery: 
![image](https://user-images.githubusercontent.com/41222927/172883199-42b1a142-5cb3-469c-aba6-e78ae0389161.png)

**Comment by eliknebel** [comment]
Closed by #3124
