### ISSUE TITLE
Always visible save status

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#2667]
In legacy the save status of a project is always visible from any screen, so you do not need to scroll to ensure that your project has been automatically saved. In torus, it appears at the top of a page. So when there is a page with a lot of content, the page save status is not always visible since it is inline at the top of any given editing page. Look in the upper right hand corner of each screenshot below. 

In Torus: 
![image](https://user-images.githubusercontent.com/32859465/173410283-183b0df6-e2ab-4688-9b18-57d73cf36486.png)

In legacy: 
![image](https://user-images.githubusercontent.com/32859465/173410449-c8f54081-d70c-409a-bf64-a5a4a421976d.png)

**Comment by cjlim1092** [comment]
save this for re-triage

**Comment by bitbldr** [comment]
fixed v25
