### ISSUE TITLE
Creating Learning objective by pressing return doesn't clear the input

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2672]
In the objectives, after typing in a new objective, both pressing the create button and hitting return creates the new objective. However, if pressing create, this also clears the input field. While if pressing return, the just-created LO text stays in the field.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 14.1.12

**Additional context**
I'd thought at first this might be on purpose, in case someone wanted to make several similar LO's, and was considering if a clear button would be good, if a user survey would be good, if a setting would be good, etc. However, having noticed the two different behaviors, I think at least one of them was not intended?

**Comment by eliknebel** [comment]
From triage: Return should also clear the input

**Comment by darrensiegel** [comment]
Closed, no longer an issue
