### ISSUE TITLE
Should new Learning objectives be created at the top of the list?

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2673]
At the moment, it looks like new LO's are added at the bottom of the LO list. Possibly it could be better to have them put at the top, so that the author can see the new LO right away, and see the success, rather than needing to scroll.

**Screenshots**
<img width="1046" alt="" src="https://user-images.githubusercontent.com/23661836/173460448-00d9c902-88d1-4ee0-a3f9-87240c446490.png">
<img width="986" alt="" src="https://user-images.githubusercontent.com/23661836/173460502-d66a4e68-995a-4b26-b31a-a6383d99a020.png">
<img width="1048" alt="" src="https://user-images.githubusercontent.com/23661836/173460558-be57a784-42ce-4596-a7a5-2ebe5dbefb3a.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 14.1.2

**Comment by eliknebel** [comment]
"There's no need to have objectives remain in the order they are created". We should simply add the objective to the top of the list.

**Comment by gitnauk** [comment]
Tested 6/27/22
New objectives are now added to the top of the list. 



![Image](https://user-images.githubusercontent.com/41222927/175982014-d48633f6-4f99-447b-9b4a-20f085c0861b.png)
