### ISSUE TITLE
Content Outline is Finicky

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2705]
**Describe the bug**
Use of the Layout manager is a bit challenging. It requires some precision and there are some problems with it

They include
* difficulty seeing where the drop points are
* Precise placement required for moving in/out of a group
* if block dropped outside drop point, block disappears

![layoutmanager](https://user-images.githubusercontent.com/18299544/174866248-8664f0c8-cf27-4921-b012-35ad183ebc61.gif)

**Comment by eliknebel** [comment]
Dropping items into the void is an issue we need to fix. We also need to double check keyboard navigation to make sure this outline is accessible. Consider breaking this issue down into separate issues.

**Comment by eliknebel** [comment]
To avoid confusion, we might want to limit dragging anywhere other than from the handle.
