### ISSUE TITLE
editing lock on activities

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2709]
In activity bank, activities have a lock icon next to them with the mouseover text 'Enable or disable editing of this activity'. It does not feel clear what this is or what its purpose is? (I could also see people in a multi-creator course being confused whether this is to prevent other people from editing your activity, or something like that).

It seems like the lock sometimes turns on by itself (if you leave the activity bank and return?), which a user may not expect, and the locked position of the lock is also not very noticeable - I several times attempted to edit, had it not work, and then realized the lock was locked.

**Screenshots**
<img width="299" alt="" src="https://user-images.githubusercontent.com/23661836/174913763-6e8fbcc2-db9d-4223-bb60-b3c841c0175a.png">
<img width="372" alt="" src="https://user-images.githubusercontent.com/23661836/174914364-56e578f3-8b93-4381-a6d2-3f9a4ab1dd1c.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.12

If the purpose is to be able to review activities without accidentally editing them, maybe an edit vs view mode might be better?

**Comment by eliknebel** [comment]
We need to rework this UX to be more clear to the purpose of locking/unlocking activities (multiple users editing bank at the same time). Possibly using an "Edit" and "View" button and a better distinction between modes.
