### ISSUE TITLE
Clarify purpose of editing activity title

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2712]
**Describe the bug**
When a new activity is made in the activity bank, it is 'titled' by the name of its activity type, and there is an 'Edit title' affordance. However, it is not clear what a title in this case does/is used for. If I remember correctly, in legacy titles are not seen by students. It's not clear if here they are student facing (and thus also if not changed students will see repeated activity type titles) or if they are used for some other purpose, or if it's just to help the user identify their activities. 

<img width="359" alt="" src="https://user-images.githubusercontent.com/23661836/174970568-36312394-f795-4279-bae6-2e0ba41591f6.png">

**Comment by eliknebel** [comment]
Title are not seen by students, they are useful for naming activities so an author can later identify in the data and analytics
