### ISSUE TITLE
extra trash can icon in activity bank?: CMU-517

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2713]
**Describe the bug**
activities in the activity bank seem to have a trash can icon to their right that doesn't do anything if I click on it? There's also already a different trash can icon on the left that works to delete the activity. (I'm guessing I'm doing something wrong but I'm not sure what, or what the purpose of two different trash can icons would be.)

**Screenshots**
<img width="1042" alt="" src="https://user-images.githubusercontent.com/23661836/174972586-493214a2-d68d-484d-8fb5-9e524be83de0.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.2

**Comment by eliknebel** [comment]
Showing two trashcan icons is a bug, there should only be a single trashcan icon displayed to users

**Comment by eliknebel** [comment]
related to #2709
