### ISSUE TITLE
Field to enter activity question is hard to see

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2715]
**Describe the bug**
In the activity bank, when creating activity, the field to input the question is, with its size, color, and placement, hard to see/notice/register, despite its importance.

**Screenshots**
<img width="447" alt="" src="https://user-images.githubusercontent.com/23661836/174976214-f57f6e52-1de7-433c-9395-b3bc16c2037d.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.2

**Additional context**
Also visual accessibility relevant.

**Comment by eliknebel** [comment]
related to #2721
