### ISSUE TITLE
possibly reorder/reformat learning objectives in dropdown menu

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2720]
Right now, LO's in the dropdown menu for attaching LO's to activities in the activity bank are presented as a flat list. It might be useful if LO's that are parents of other LO's, or vice versa, had some sort of indicator of this. Similarly, it might be useful if parent and children LO's were kept next to each other.

**Screenshots**
<img width="408" alt="" src="https://user-images.githubusercontent.com/23661836/175262038-1384b25a-202c-40e1-8725-ec9ed95ae650.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 14.1.2

**Comment by eliknebel** [comment]
fixed as of 0.20.0
