### ISSUE TITLE
issues with quotes (not working) and lists, seen in activity bank hints/feedback

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2722]
(While trying to reproduce the quote issue I also ran into the rest of these)
At the moment, when trying to use the text editing menu in activity bank hints/feedback
* Turning something into a quote does not seem to actually change the text in any way?
* Turning something into a list adds a newline after it (in feedback) and a newline before and after (in hints). These newlines persist if the text is then changed back.
* Trying to turn something into a quote has the same newline effect, even as it doesn't otherwise change the text appearance.

**Screenshots**
<img width="289" alt="Screen Shot 2022-06-23 at 5 19 14 AM" src="https://user-images.githubusercontent.com/23661836/175267366-35985101-d244-493d-b5f1-c7ab04b5da0f.png">
<img width="298" alt="Screen Shot 2022-06-23 at 5 19 23 AM" src="https://user-images.githubusercontent.com/23661836/175267374-36637f57-b743-4861-a913-648ca9526120.png">
<img width="390" alt="Screen Shot 2022-06-23 at 5 25 32 AM" src="https://user-images.githubusercontent.com/23661836/175267415-110d44b2-1878-4737-be4d-e2a3471812d6.png">
<img width="333" alt="Screen Shot 2022-06-23 at 5 25 39 AM" src="https://user-images.githubusercontent.com/23661836/175267417-84519277-df58-4a51-b013-d9b7d9bc492d.png">
<img width="314" alt="Screen Shot 2022-06-23 at 5 26 02 AM" src="https://user-images.githubusercontent.com/23661836/175267418-18fd1626-5e6f-4652-825e-00078d7a160b.png">
<img width="296" alt="Screen Shot 2022-06-23 at 5 26 09 AM" src="https://user-images.githubusercontent.com/23661836/175267420-12358e0d-5f5c-4846-bdbc-d2ee959d64d6.png">
<img width="352" alt="Screen Shot 2022-06-23 at 5 26 29 AM" src="https://user-images.githubusercontent.com/23661836/175267423-f644215a-1163-4305-a8ee-c7a8a7441b3c.png">
<img width="328" alt="Screen Shot 2022-06-23 at 5 26 38 AM" src="https://user-images.githubusercontent.com/23661836/175267425-89321dfb-e0e8-4939-ba25-549fba6a7c57.png">
<img width="331" alt="Screen Shot 2022-06-23 at 5 26 55 AM" src="https://user-images.githubusercontent.com/23661836/175267426-ef5ae8f8-5f3a-4dda-a88d-1a39c53242b1.png">
<img width="320" alt="Screen Shot 2022-06-23 at 5 27 01 AM" src="https://user-images.githubusercontent.com/23661836/175267427-7bbe792e-f3fb-4343-97d3-bb0492232b41.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: 14.1.2

**Comment by drva** [comment]
Was asked to test this again in tokamak given updates.
It looks like quotes work now, but in feedback both quotes and lists make a new line after themselves that persists if they're changed back to a paragraph, and in hints they make a new line that persists both before and after themselves.

**In feedback:**
<img width="516" alt="Screen Shot 2022-07-05 at 6 22 47 PM" src="https://user-images.githubusercontent.com/23661836/177428703-c1c09f04-9842-42cb-9902-fb0112e0981a.png">
<img width="385" alt="Screen Shot 2022-07-05 at 6 22 57 PM" src="https://user-images.githubusercontent.com/23661836/177428708-2e082629-8342-4d4d-81c0-561ef842d2bb.png">
<img width="341" alt="Screen Shot 2022-07-05 at 6 23 20 PM" src="https://user-images.githubusercontent.com/23661836/177428711-7814f97d-e189-4ca1-a47e-9dc5b23bc1fa.png">
<img width="287" alt="Screen Shot 2022-07-05 at 6 23 44 PM" src="https://user-images.githubusercontent.com/23661836/177428714-4c3e9666-112d-4c9d-a6bf-29204bbd0c10.png">
<img width="258" alt="Screen Shot 2022-07-05 at 6 23 53 PM" src="https://user-images.githubusercontent.com/23661836/177428715-785e5477-6a38-4c3b-8a07-55865746f1e4.png">

**In hints:**
<img width="320" alt="Screen Shot 2022-07-05 at 6 24 10 PM" src="https://user-images.githubusercontent.com/23661836/177428780-3345809b-ee97-4b37-890f-9517f271c568.png">
<img width="368" alt="Screen Shot 2022-07-05 at 6 24 18 PM" src="https://user-images.githubusercontent.com/23661836/177428782-40828c0b-1f46-4bef-8632-bc385d671e0b.png">
<img width="381" alt="Screen Shot 2022-07-05 at 6 24 26 PM" src="https://user-images.githubusercontent.com/23661836/177428784-ac8efda8-2798-4dc9-82fd-dda13528974f.png">
<img width="366" alt="Screen Shot 2022-07-05 at 6 25 37 PM" src="https://user-images.githubusercontent.com/23661836/177428836-37a034b5-a2a8-4999-833d-7934e35b19fc.png">
<img width="439" alt="Screen Shot 2022-07-05 at 6 25 44 PM" src="https://user-images.githubusercontent.com/23661836/177428839-23250731-964e-4283-9f60-b9e049091170.png">
<img width="429" alt="Screen Shot 2022-07-05 at 6 28 57 PM" src="https://user-images.githubusercontent.com/23661836/177428946-949d669c-7337-4639-b2c3-dc432bfbab5f.png">


Also in hints I ran into some really weird issues trying to get rid of the preceding newline with a list, or trying to change the list back into a paragraph, where I couldn't delete the newline, and the list turned into - something else, its icon was the paragraph icon with opposite colors, and I couldn't get rid of the bullet, and then when I tried more deleting it suddenly created a really large amount of whitespace that made my scrollbar behave strangely and resisted deletion?
<img width="354" alt="Screen Shot 2022-07-05 at 6 26 14 PM" src="https://user-images.githubusercontent.com/23661836/177428859-9e15c9ca-cfc7-4871-a347-4dcfca3464b5.png">
<img width="640" alt="Screen Shot 2022-07-05 at 6 26 29 PM" src="https://user-images.githubusercontent.com/23661836/177428881-1a9b2669-43e0-4cab-a40e-7c230695f694.png">
<img width="884" alt="Screen Shot 2022-07-05 at 6 26 59 PM" src="https://user-images.githubusercontent.com/23661836/177428895-fd1f9da2-5972-4dbb-a553-c1eb8c0d79cc.png">
<img width="997" alt="Screen Shot 2022-07-05 at 6 28 17 PM" src="https://user-images.githubusercontent.com/23661836/177428903-8cf5c404-7284-4aa3-a9dd-96d26b8b024a.png">

Version 0.20.0 (E19BD70) 07/05/2022

**Comment by eliknebel** [comment]
There are some usability issues with lists and block formatting, specifically in feedback. There are also some cases where errors will occur. We need to smooth out the experience here for authors so that formatting is a straightforward process that always works.

<img width="787" alt="Screen Shot 2022-09-13 at 2 28 30 PM" src="https://user-images.githubusercontent.com/6248894/189981706-1be095ac-7178-44cf-81d4-ef9f4e1f70bd.png">
