### ISSUE TITLE
title editing textbox in activity bank is small

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#2724]
When editing a title of an activity in the activity bank, the text box given to do this is very small (narrow), including smaller than the room the text being edited can take up.

**Screenshots**
<img width="798" alt="" src="https://user-images.githubusercontent.com/23661836/175270858-3f834253-eaba-4b90-970e-e13f6ebc7b3d.png">
<img width="1042" alt="" src="https://user-images.githubusercontent.com/23661836/175270861-afe08e7d-b699-499c-ab30-e6d48ee90aa4.png">
 explain your problem.

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.2

**Comment by chicken-biryani** [comment]
Hi, @drva hope you're doing well.

Are non-CMU students allowed to contribute to this project as well?
