### ISSUE TITLE
Support advanced list style rendering and authoring MER-1308

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2743]
Ordered lists must support the ability to change the numbering style.  The following is the relevant excerpt from the OLI Legacy DTD:

```
<!-- ORDERED LIST -->
<!ENTITY % olcml.list.ol.styles "none | decimal | decimal-leading-zero | lower-roman | upper-roman | lower-alpha | upper-alpha | lower-latin | upper-latin">
<!ENTITY % olcml.list.ol.style.attr
 "style		(%olcml.list.ol.styles;)	#IMPLIED"
>
```

Unordered lists support the ability to change the "bullet" style:

```
<!-- UNORDERED LIST -->
<!ENTITY % olcml.list.ul.styles "none | disc | circle | square">
<!ENTITY % olcml.list.ul.style.attr
 "style		(%olcml.list.ul.styles;)	#IMPLIED"
>

<!ELEMENT %olcml.ul.qname; (%olcml.title.qname;?, %olcml.li.qname;+)>
<!ATTLIST %olcml.ul.qname;
  %olcml.core.attrs;
  %olcml.i18n.attrs;
  %olcml.list.ul.style.attr;
>
```

For consistency of implementation, in Torus the new content model attributes and values should simply match the values from above.

**Comment by marc-hughes** [comment]
Examples of OL styles

![image](https://user-images.githubusercontent.com/333265/178547623-c42d14f4-8063-42f7-8c3c-2c1d3b530471.png)
![image](https://user-images.githubusercontent.com/333265/178547712-3c352f49-61f2-4c6d-968a-888f11c655c1.png)
