### ISSUE TITLE
"Break down objective" tool serves as a "parent objective" creator

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#2751]
**Describe the bug**
When creating and organizing objectives in PROTON, the "Break Down" tool does the opposite of what it's intention is. Breaking an objective down is creating a sub-objective.

The text reads "is this objective too broad?", which implies that "too broad" objective should have sub-objectives. This is already supported by the platform. What the tool, in it's current iteration, actually does is to place a _narrow_ objective under a parent objective. It actually nests it rather than breaking it apart.

**To Reproduce**

1. Click on "Create" on the sidebar once a project is selected (can be any project).
2. Click on "Objectives".
3. Create a sample objective if objectives don't currently exist in the Project.
4. Click any existing objective to reveal a "break down" button.
5. Click the "break down" button.
6. A pop up box titled "Break down objective" 

**Expected behavior**
Anything with a title "break down objective" should be used to define the creation of subcategories beneath that objective. This tool is extremely useful, but it could do with a rename such as "nest objective" in order to more accurately represent the function.

**Screenshots**
![Screen Shot 2022-06-28 at 7 14 06 PM](https://user-images.githubusercontent.com/100791229/176319492-1906ba56-acae-48f8-8fd8-5a43e4bc33e9.png)

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser: Chrome
 - Version: 103.0.5060.53

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by darrensiegel** [comment]
The "Break Down" feature was entirely removed by https://github.com/Simon-Initiative/oli-torus/pull/2660.

This change hasn't yet made its way to production (proton.oli.cmu.edu).  You can see it in action on our test server (tokamak.oli.cmu.edu)
