### ISSUE TITLE
Creation of sub-objectives reorganizes LO hierarchy

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#2753]
**Describe the bug**
When attempting to create a learning objective with included sub-objectives in mind, there is no mechanism to automatically create sub-objectives. In order to create a broad learning objective with sub-objectives under it, one must first create the first sub-objective as a new LO, and then use the "break down" tool in its current function to create the intended parenting objective. Once the first sub-objective is nested under the parent, a "create sub-objective" button appears beneath the thread. This makes the process for created nested sub-objectives convoluted and counter-intuitive, and can lead to complications in skill-mapping.

**To Reproduce**
1. Go to 'Create' 
2. Go to 'Objectives'
3. Create an objective if no objectives exist.
4. Click on selected objective.
5. Select 'Break Down' button.
6. Create a 'parent objective' and select 'Break down objective' button.
7. The old objective gets bumped down to under the new parent, and a 'Create Sub-Objective' button shows up.

**Expected behavior**
As a course author I would expect to put in a parent objective first and then break down parent objectives automatically. "Define story" should be the parent objective and "define conflict" should be the sub-objective (see screenshot).

**Screenshots**
![Screen Shot 2022-06-28 at 7 33 31 PM](https://user-images.githubusercontent.com/100791229/176321421-47e3c82c-e6c0-4704-98d0-db05ebfc5a17.png)

**Environment (please complete the following information):**
 - OS: iOS Monterey
 - Browser: Chrome
 - Version: 103.0.5060.53

**Additional context**

**Comment by darrensiegel** [comment]
This is fixed on `master`, currently not released to production (proton.oli.cmu.edu).  You can create an account on our test server to see this in action (tokamak.oli.cmu.edu). 

Closed by: https://github.com/Simon-Initiative/oli-torus/pull/2731
