### ISSUE TITLE
Ability to adjust iFrame height in Torus

### ISSUE THREAD

**Issue by sharisiri** [Simon-Initiative/oli-torus#2759]
**Is your feature request related to a problem? Please describe.**
it would be useful to be able to adjust iframe height in OLI Embedded to show full length / height content and prevent scrolling.

**Describe the solution you'd like**
An option in OLI Embedded to manually / or dynamically set content height. See example and options menu screenshots below.

**Additional context**

![Screenshot 2022-06-30 at 14 48 39](https://user-images.githubusercontent.com/37027404/176680764-e707a43f-22b2-4e57-9079-1d22564ae93a.png)

OLI Embedde settings page where content height could potentially be adjusted from.
![Screenshot 2022-06-30 at 14 49 20](https://user-images.githubusercontent.com/37027404/176680898-7f63cec8-eca5-4a3a-925d-1f10ed565f04.png)

**Comment by eliknebel** [comment]
This would be adding a setting to iframe element for a custom height
