### ISSUE TITLE
Restrict access to course by pre-registering email addresses in student roster before sending invitation link

### ISSUE THREAD

**Issue by sharisiri** [Simon-Initiative/oli-torus#2760]
**Is your feature request related to a problem? Please describe.**
In one of our courses at KTH we would like to restrict access by only allowing specific students access to the course. 

**Describe the solution you'd like**
There are several ways to do this but one idea would be to first add users to student roster and only allowing users with associated email addresses to register to the course. 

**Describe alternatives you've considered**
We have considered using Canvas as a main LMS but for this specific course it would make better sense to run in natively in Torus.

**Comment by eliknebel** [comment]
Torus currently defers to the LMS for more advanced roster management capabilities so this can be accomplished by using an LMS instead of direct course delivery.
