### ISSUE TITLE
Ensure that survey activities do not show up in manual graded items table

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2763]
Survey activity attempts are captured as regular attempts with a survey_id set. We need to update the manual grading feature to filter these types of attempts out for activities that require manual grading (e.g. file upload) since they aren't actually scored

**Comment by darrensiegel** [comment]
This solution should leverage the "scoreable" activity infrastructure.  Attempts that are created with "scoreable" set to false are excluded from grading.
