### ISSUE TITLE
Issues with Bibliography

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#2782]
Bibliography page - given name and family name are confusing. For articles, it may be more clear for first and middle name, last name. 
![image](https://user-images.githubusercontent.com/32859465/177391010-17abb81e-603d-41ce-ba81-f61c7d313a80.png)

For article it is unclear what container title means
![image](https://user-images.githubusercontent.com/32859465/177391319-3adff942-3a2f-4732-ab57-2e2ada521717.png)

It is unclear what classic means in types of citation menu
![image](https://user-images.githubusercontent.com/32859465/177391618-8dde7b86-3987-44f1-8e8c-3cb60d860f62.png)

Make it clear what kind of citation will appear on the page (MLA, APA, etc)

Torus Version 0.20.0

**Comment by eliknebel** [comment]
1. We should change the placeholders here to "Given Name" and "Family Name"
2. (just for article) Container Title is a bit confusing. We should change this label to "Published In"
3. It is unclear what Classic is... this should be explained in an info tooltip with a link to the official standard, or remove this option.
