### ISSUE TITLE
Sub-objectives are not showing up at the top of the page

### ISSUE THREAD

**Issue by gitnauk** [Simon-Initiative/oli-torus#2783]
**Describe the bug**
Sub-objectives are not showing up at the top of the page, but the main objectives are. 

**To Reproduce**
1. Create objectives and sub-objectives
2. Go to a page and add learning objectives and sub-objectives at the top. 
3. Click on Preview (or create a course section and look at student delivery)
4. The sub-objectives are not showing up at the top of the page. Also, the sub-objectives that do show up seem to be sorting alphabetically rather than in an order the author chooses.

**Expected behavior**
If Objectives and Sub-objectives are attached to a page in the authoring environment, they should both show up in preview and student delivery. Also, they should show up in an order the author can choose.

**Screenshots**
These are objectives and sub-objectives in Torus authoring: 
![image](https://user-images.githubusercontent.com/41222927/177411951-e1a6cb97-c9e2-4cf0-9792-ceadc2c03b79.png)

But the sub-objectives don't show up in preview or student delivery. Only the main learning objectives show up:
![image](https://user-images.githubusercontent.com/41222927/177412039-638f7bbb-fc17-4471-8f23-f3e75aae9a71.png)
 

**Environment (please complete the following information):**
- OS: Windows 10 Pro
- Browser: Chrome
Version: v0.20.0

**Comment by eliknebel** [comment]
This is part of a larger discussion around how objectives are modeled in the system currently and how they should be going forward.

If sub-objectives are in fact different entity types to be treated differently (skills) then we may need to rework the terminology and how we present them.
