### ISSUE TITLE
Sub-objectives must be able to exist under multiple different top level objectives

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2807]
Erin and Hal noted that sub-objectives must be able to exist under different top level objectives.

<img width="1200" alt="Screen Shot 2022-07-14 at 10 10 58 AM" src="https://user-images.githubusercontent.com/6248894/179002669-1df21235-8be5-43db-a63b-8f712e1095d5.png">

**Comment by eliknebel** [comment]
We need to know the exact courses that utilize this feature so we can understand how it should work.

@czerwinskie will look into finding an example (possibly A&P?)

**Comment by eliknebel** [comment]
We will need to add support in the course-digest tool for skill map spreadsheets

**Comment by darrensiegel** [comment]
Closing as this is done and present in 22 release
