### ISSUE TITLE
Allow activity content to utilize full width of page-content div 

### ISSUE THREAD

**Issue by dhbrown** [Simon-Initiative/oli-torus#2837]
**Is your feature request related to a problem? Please describe.**
I am working on adding a new Torus activity type 'VlabActivity' that includes the CMU developed Virtual Chemistry Lab.  The width of the activity is limited to 770px by the styling of .content in assets/styles/delivery/page_delivery/page.scss (line 49). The user experience would be enhanced if the Virtual Chemistry Lab was able to utilize more of the full width available to the page-content div. 

**Describe the solution you'd like**
Allow for a content element to utilize the full with of the page-content div

**Describe alternatives you've considered**
Some possible hacks/overrides exist, but a standard uniform approach to providing access to available screen real estate for this and other activities might make more sense. 

**Additional context**
The VlabActivity delivery component looks something like the following.  The request is to allow just the vlab iframe to 'escape' from the width constraint on .content.
```
return (
  <div className="activity mc-activity">
    <div className="activity-content">
      <iframe id="vlab" className="vlab-holder" src="/vlab/index.html" onLoad={onVlabLoad} />
      <StemDelivery className="form-inline" stem={model.stem} context={writerContext} />
      <GradedPointsConnected />
    ... etc

```

**Comment by eliknebel** [comment]
We intentionally limit the width of the content for a better reading experience of text/paragraphs. There are a couple of approaches that can be taken here:

1. We only restrict the width of paragraphs to the 770px, allowing activities and and other elements to utilized more of the page
2. We allow certain activities to utilize more of the width of the page, such as labs, iframes, etc...

**Comment by dhbrown** [comment]
It seems like other things (beyond paragraphs) benefit from the consistent 770 maxwidth.  Activity stems and the Submit button align nicely with the other content, and I think it would look a bit ragged if they didn't.  The extra width is more of an exception case, in my case integrating a legacy tool.  So option 2 might make more sense.  And even in this case, other text and control elements of the vlab activity should obey the default maxwidth.
