### ISSUE TITLE
Navigation is lost on activity bank when activity is deleted: CMU-519

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#2850]
**Describe the bug**
Location: In the Activity Bank
Condition: Last page of the activity bank only contains one question
Issue: When you are on the last page of the activity bank and it only contains one question, if you delete that question then the page navigation buttons disappear
![image](https://user-images.githubusercontent.com/32859465/180297516-6094804d-0edf-4813-bf46-6dee4b28fce3.png)
**Environment (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 0.21.2

**Comment by eliknebel** [comment]
This is an edge case. When deleting a activity in the activity bank, if the activity is on the last page of the activity bank and the activity is deleted, the user should be taken to the previous page so that they see their activities.
