### ISSUE TITLE
Don't show Learning Objectives on scored pages

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#2853]
**Describe the bug**
LOs should not appear atop scored assessments.

**Expected behavior**
LOs should not appear on scored pages.

There are two reasons LOs don't appear atop scored assessments:
1. They might give away answers.
2. They would overwhelm the page in a module or unit quiz.

**Comment by eliknebel** [comment]
Per Hal:

> Interactions should still contribute to the learning estimate and overall data set, but the LOs being shown in a scored-page environment isn't appropriate. In fact, having the LOs visible to the instructor in whatever “review mode” gets designed would be great.
