### ISSUE TITLE
July 2022 TORUS Community meeting feature suggestions

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#2876]
These are taken from the July 2022 TORUS Community meeting. 

1. Math course authors want the ability to create “line breaks” within the equations by using backslashes (\\) with LaTex. This would allow multiple lines of formulas in one block of math editor.

2. Math course authors want to be able to cross out equations in LaTex and MathML.

3. Math course authors want more encompassing accessibility for geometry and other graphics-based mathematics course.

4. Math course authors was a uniform consistency for mathematics screen reader.

5. Math course authors want packages such as TIKZ incorporated into TORUS in order to draw graphics within the program.

6. Math course authors want to have the ability for the numbering system to keep track of theorems (such as Theorem 1.1, Theorem 1.2) and to integrate with LaTex’s cross referencing system.

7. Math course authors want the ability to put XML Source with XSLT transformations into the source, so that they can use existing course material from the XSLTs as “plug ins”.

**Comment by eliknebel** [comment]
More discussion around these features is warranted. They have been moved to #2886
