### ISSUE TITLE
Page title editing uses a Save button instead of autosave pattern

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#2877]
**Describe the bug**
When renaming a "new page", there is no autosave for the title as there is for the rest of the page. Has to be saved manually, which is not consistent with the autosave feature of the rest of the page. 

**To Reproduce**
1. Go to 'create'
2. Click on 'currilculum'
3. Add a "Practice Page"
4. Edit page, edit title
5. Only saves with "save" button

**Expected behavior**
Create autosave title feature to match the rest of autosave page

**Comment by eliknebel** [comment]
Automatic saving here is problematic because we reload the page to update the slug (this is required for other technical reasons). If this was auto save, we wouldn't know when it is safe to reload the page.
