### ISSUE TITLE
Allow strikethrough using laTex

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2885]
Math course authors want to be able to cross out equations in LaTex and MathML.

**Comment by marc-hughes** [comment]
# For MathML

Use the menclose tag with a notation set to one of the strikethrough options.

![image](https://user-images.githubusercontent.com/333265/184178906-505744f2-4b29-421f-bff8-43c11aca2896.png)


Docs: https://developer.mozilla.org/en-US/docs/Web/MathML/Element/menclose


Example:

![image](https://user-images.githubusercontent.com/333265/184178682-310a769b-b053-4b69-8343-ed16bd7cabbb.png)


# For LaTex

This will only work after this PR is merged: https://github.com/Simon-Initiative/oli-torus/pull/2920

First, enable the cancel extension with a \require{cancel}
Then, you can use \cancel{some expression} to strike through it.

![image](https://user-images.githubusercontent.com/333265/184181217-3eec34b8-a16e-410a-9360-396687a2c03a.png)
