### ISSUE TITLE
Latex rendering not configured correctly to render all Latex commands

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2918]
1. Create a Latex Formula in a page.
2. Use the following source:

```
\require{cancel}\mathrm{mol}\;\mathrm{HCl}\;\mathrm{produced}\;=\;3\;\cancel{\mathrm{mol}\;{\mathrm H}_2}\;\times\;\frac{2\;\mathrm{mol}\;\mathrm{HCl}}{1\;\cancel{\mathrm{mol}\;{\mathrm H}_2}}\;\;=\;6\;\mathrm{mol}\;\mathrm{HCl}
```

In authoring, preview and delivery this formula incorrectly renders as:

![Screen Shot 2022-08-11 at 8 41 35 AM](https://user-images.githubusercontent.com/7431756/184135590-ee7980da-f37a-4fd4-8a37-e2550a71062a.png)

**Comment by marc-hughes** [comment]
After fix it renders as:

![image](https://user-images.githubusercontent.com/333265/184154113-060e1f35-e68c-4ca9-9216-bf08c3057527.png)
