### ISSUE TITLE
When publishing with direct delivery courses can only have one instructor

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#2957]
**Describe the bug**
When publishing with direct delivery courses can only have one instructor this is a need for elearning design principles group projects and has also been requested by folks at eberly. By allowing for multiple instructors, editing the course and viewing data will be easier.

**To reproduce bug**
Log-in as a student/instructor
Click on published section
Go to manage section
can not click on instructors box even though it says "manage the users with instructor level access" 

**Expected behavior**
Allowing for multiple instructors on the same course 

**Screenshots**
![image](https://user-images.githubusercontent.com/32859465/187277122-c61cdfc0-bad3-4ae3-abdb-a73c0c123c49.png)

**Comment by eliknebel** [comment]
Allow users who are instructors of a course to invite other users as instructors. If user doesn't exist, they should be prompted to create a user account.

Eventually, we might want to consider an "Invite Colleague" feature.

**Comment by cjlim1092** [comment]
This is fixed
