### ISSUE TITLE
"Connect to LMS" Function not necessary for most authoring

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#2997]
**Describe the bug**
In the "Publish" section in Torus's authoring platform, there is a section "Get connected" button to connect to an LMS. If only an LMS admin at an institution can link Torus and Canvas (or any other platform), this button is not necessary for the authoring environment, as authors / instructors do not have the Canvas credentials to link the LTI.

**To Reproduce**
1. Go to Publish sidebar in Proton
2. Select "Publish" tab
3. Scroll down to the bottom of the page
4. See "Deliver this course through your institution's LMS"

**Expected behavior**
We should probably just get rid of this button on the authoring platform and reserve linking for the Wiki / HelpDesk / other feature directly for LMS admins in institutions

**Screenshots**

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.
![Screen Shot 2022-09-14 at 3 54 25 PM](https://user-images.githubusercontent.com/100791229/190250766-31f7af50-8e12-4f6f-a9fb-2bb19312040b.png)

**Comment by eliknebel** [comment]
We need to determine where a better place for this would be, discussing with ETX and other partners
