### ISSUE TITLE
Insertion menu content can overflow

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#3005]
**Describe the bug**
Insertion menu contents overflows when there are more activities than it can hold.

**To Reproduce**
1. Go to Overview page for a project and enable all activity types
2. Go to a page and click the insert icon
3. See overflow issue

**Expected behavior**
 The menu should provide some way to click or scroll through items when the amount of items exceeds the size to the popup. 

**Screenshots**
<img width="661" alt="Screen Shot 2022-09-14 at 2 10 45 PM" src="https://user-images.githubusercontent.com/6248894/191332734-0b1e6c47-85b8-48e6-8b2f-10b832bd8df1.png">
  
**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.21.5

**Comment by eliknebel** [comment]
We should keep this menu similar size, but implement a paging strategy to accommodate more activity types

**Comment by marc-hughes** [comment]
@eliknebel  / @darrensiegel 

I'm seeing a different layout in the current app.

Do we want the question types back to the 3x3 grid with paging?

If so, I'd suggest letting it go to like 6x3 so you would only have to page in extreme circumstances and it still wouldn't get too tall and scroll the page. Paging in a popup like that doesn't seem very user friendly.

![image](https://user-images.githubusercontent.com/333265/205674897-b4ebfa2d-be36-40b5-8d15-86a890f9abae.png)

**Comment by marc-hughes** [comment]
Oh! Actually, it'd dependent on your browser page-zoom. When I zoomed in a bit, I got:

![image](https://user-images.githubusercontent.com/333265/205675932-b41b89e9-e3ca-414e-8eff-f4baa8f77ba3.png)
