### ISSUE TITLE
Ordering Activity does not allow multiple submissions

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3021]
**Describe the bug**
Ordering Activities allow 1 submission, but subsequent submissions do not provide feedback. 

**To Reproduce**
1. Create Ordering activity, publish
2. Put in incorrect order, submit
3. NOTICE: activity presents proper feedback
4. Reset activity
5. Put in correct order, submit
6. NOTICE: No feedback, activity does not properly submit

**Expected behavior**
Resetting ordering activity should allow resubmission

**Screenshots**
![ordering_nosubmit](https://user-images.githubusercontent.com/18299544/192312464-458b63bd-de6e-4d47-a500-3ec5af556675.gif)

**Environment (please complete the following information):**
 - OS: Windows 11, Mac
 - Browser: Chrome
 - Version: 0.21.5

**Comment by eliknebel** [comment]
We need to determine if this is broken on production or not

**Comment by gjbunyea** [comment]
This appears to be an issue on Tokamak, but not Proton in either Preview or Publish settings
