### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by shivanggupta** [Simon-Initiative/oli-torus#3036]
**Is your feature request related to a problem? Please describe.**
Videos don't currently have captions

**Describe the solution you'd like**
Enable captions so that we can upload a srt/webvtt file to ensure compliance

**Describe alternatives you've considered**
N/A

**Additional context**
Needed for when we upload videos directly to OLI instead of using Youtube

**Comment by eliknebel** [comment]
Legacy supports this, we need to investigate how to add support to torus via multiple src or tracks prop
