### ISSUE TITLE
JSON Validation of page edits has huge performance issues

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#3043]
I started poking around here because JSON validation during ingest for a course with 500 pages took close to 15 minutes to complete. 

On Tokamak, I did an experiment in the page editor, while the Network tab of the developer tools was open.  Here is what I did:

1. In the page itself (within content) I added a table. Then I waited for the deffered save request to complete.  Then I repeated that, several times.
2. Inside an Activity I then did the same thing.

Note the steadily increasing times for the page edits `exponentiation` vs the activity edit `54553?lock=35521`

![Screen Shot 2022-10-01 at 10 14 08 AM](https://user-images.githubusercontent.com/7431756/193413770-b9781582-ca78-4bf2-817b-a8d0946b4c2d.png)

The reason for this, I believe, is that JSON validation for activities is driven by a schema that is much more 'shallow' than the page schema.  The page schema fully describes the entire page content, descending into content, groups, blocks, tables, etc.  The activity schema does not validate stems, hints, choices, feedback - the places where there are far more complex and nested  constructs.  

We need to either:
1. Investigate our usage of JSON schema validation to understand if we are using it correctly - which might perhaps remove the performance problem. 
2. Remove JSON validation from page edits.  Possibly replacing it with a "JSON Validation Step" at time of publication, for only those pages that have changed. 
3. Completely just remove JSON validation from Torus.  Instead, we could focus on making the rendering more robust to "bad data", and also work to ensure that the course digest tool produces valid JSON.

**Comment by darrensiegel** [comment]
Adding a few more tables to the page, and then typing some text into a paragraph led to a situation where I was seeing network save requests taking 15 seconds.

**Comment by eliknebel** [comment]
validation has been disabled in the system, this is resolved
