### ISSUE TITLE
Add support for "notation" attribute on numeric inputs

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#3051]
Legacy DTD specifies a "notation" attribute which tells the system what input format to expect.

`oli_inline_assessment_1_3.dtd:264`
```
<!ATTLIST numeric
 %input.core.attrs;
 notation (automatic | decimal | scientific) #IMPLIED
 %size.attr;
```

XML Example
```
            <numeric id="pt1" size="small"/>
            <numeric id="pt2" size="small"/>
            <numeric id="pt3" size="small" notation="scientific"></numeric>
            <numeric id="pt4" size="small"/>
            <numeric id="pt5" size="small"/>
```

Many legacy courses including chemistry may make use of this, including chemistry, so there should be support for this in torus and the course-digest migration tool.

**Comment by darrensiegel** [comment]
Scientific notation input is already supported in Torus.  Create a "numeric" input and simply type into it: `2.34e23`, for example.
