### ISSUE TITLE
Enhance support emails

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3058]
The support emails in Torus currently don't collect the same metadata as those in legacy. The most important to include in the short term is:
* user name
* user email
* user ID
* role
* enrollment
* URL where request originated
* link to user account admin page
* link to course admin page for the user's enrollment

New request: 
* attach screenshot (file upload)
* collect browser console information, if it's possible to collect without permission
* LTI vs login account
* institution

**Comment by halturner** [comment]
Current interface. Note it doesn't automatically populate the user info, despite being signed in.
![Screen Shot 2022-10-11 at 2 06 47 PM](https://user-images.githubusercontent.com/24977416/195166985-b5d3840a-1610-4fff-8126-7354b0c24952.png)

**Comment by halturner** [comment]
Information the email currently includes:
____________________________________

> Someone created a new ticket on the Freshdesk website.
Hal @OLI Support
Course Enrollments[Hal Turner]
On 2022-10-11 18:12:14.832837+00:00 UTC UTC, Hal Turner < [hturner@cmu.edu](mailto:hturner@cmu.edu) > wrote:

Testing what information is collected. I'm currently on the Curriculum page of my course Goal Setting...


----------------------------------------------
Timestamp: 2022-10-11 18:12:14.832837+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/sections


WEB BROWSER
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Accept: */*
Language: en-US,en;q=0.9

CAPABILITIES
Cookies Enabled: true

USER ACCOUNT
Name: 
Email: 
Created:

**Comment by halturner** [comment]
Information currently collected by the legacy support tool

___________________

**Comment by eliknebel** [comment]
User account information only collected from authoring domain, it needs to include (independent) user account information as well

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1952?search_id=d00c7ab6-dac5-42dd-8e03-aea0b6cf5c15

**Comment by eliknebel** [comment]
fixed
