### ISSUE TITLE
When linking to an external video, page has weird spacing and sidebar navigation breaks

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3082]
**Describe the bug**
I embedded a video into the page and then it created numerous blank lines between content blocks. It also does not appear in the sidebar navigation. 
**To Reproduce**
1. Go to author a new page
2. Include a link to a video
3. Try to add new content under the video

**Expected behavior**
There will be 0-1 new line breaks under the content
**Screenshots**
See the right-hand scroll bar on these 
![image](https://user-images.githubusercontent.com/32859465/197863727-6b0f2619-e6f2-405c-91a4-904b0efb0528.png)
![image](https://user-images.githubusercontent.com/32859465/197863765-ee3f0e5b-ce2c-495e-a7fc-fa5287ffee7a.png)

**Environment (please complete the following information):**
 - OS: PC 
 - Browser:chrome
 - Version:Version 0.21.5 (3BEB47B) 09/01/2022

**Comment by marc-hughes** [comment]
I've seen the blank-line behavior before and looked briefly at it. What happens is for certain block elements, in certain states, the normalizer comes along, sees that there isn't a text block at the start of the document, and attempts to insert an empty paragraph. For some reason, that insert call doesn't put the paragraph at the start, but under the block element. Then another round of normalization kicks off, and it happens again, and again, and again.

I had assumed I had just gotten my document in a bad state during development, but if it's happening as easily as reported, clearly a real bug. In most cases, this normalizer works fine.

Relevant line:
https://github.com/Simon-Initiative/oli-torus/blob/master/assets/src/components/editing/editor/normalizers/root.ts#L14
