### ISSUE TITLE
The OLI-embedded activity uploaded file list is missing the project slug

### ISSUE THREAD

**Issue by rgachuhi** [Simon-Initiative/oli-torus#3111]
**Describe the bug**
The OLI-embedded activity uploaded file list is missing the project slug. i.e. a file listed as "webcontent/3268324938/oli.v2.min.js" should instead have the correct form "project_slug/webcontent/3268324938/oli.v2.min.js"

**To Reproduce**
1. Go to or add a custom OLI-embedded activity to a page
2. Click on the 'Upload File" button and upload an example file
3. Scroll down to the list of file names
4. See error that the file relative path name is missing the project slug

**Expected behavior**
Each relative file path in the uploaded file list should have a project slug prepended

**Screenshots**

![Screen Shot 2022-11-08 at 8 53 43 AM](https://user-images.githubusercontent.com/11138398/200584328-76f6f817-396c-47b0-b418-8b4ac44887c6.jpg)

**Comment by eliknebel** [comment]
Similar to #3114

**Comment by eliknebel** [comment]
The relative paths may be problematic if we are using an MD5 hash to address images, we may need to convert these paths to absolute. Oli-embedded activities use a proxy, we can leverage this to recreate an absolute path
