### ISSUE TITLE
Torus should upload media to S3 as a content addressable storage and not include slug

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#3114]
**Describe the bug**
Torus should upload media to S3 as a content addressable storage and not include slug

**To Reproduce**
1. Upload an item, see that it contains the project slug in the media url

**Comment by marc-hughes** [comment]
@eliknebel Want to make sure I understand this one.

Right now, if I upload an image, it goes to something like
https://torus-media-dev.s3.amazonaws.com/media/example_course/300.jpg

Instead, it should go to something like
https://torus-media-dev.s3.amazonaws.com/media/[FILE SHA1 HASH].jpg

You want an extra "directory" piece in there? A lot of times systems will take the first couple characters of the hash as a directory.

So if the hash was 56a7467a1f1b0edc23cb1efe8a9cd07283ecd2f8, you might get

https://torus-media-dev.s3.amazonaws.com/media/56/56a7467a1f1b0edc23cb1efe8a9cd07283ecd2f8.jpg

It makes it a bit easier to use dev-tools to browse things when the number of files gets really large.

Is it enough to only worry about new files, or do we need to migrate existing ones?

**Comment by eliknebel** [comment]
That is correct. The course-digest migration tool already handles this by creating a directory from the hash at `/media/[md5 hash]/filename.jpg`. By including the filename, we are able to keep the original filename context if the image is hovered/downloaded. This however, prevent exact duplicates with different names from being deduped in storage, but exact duplicates with the same name will point to the same file and we determined that was an acceptable tradeoff here.

I think putting an extra directory with a couple characters is an excellent idea. We should also update the course-digest to do this as well https://github.com/Simon-Initiative/course-digest/blob/4e0d3acfa8e530e206cd1153fdb01cd6dfc1cf44/src/media.ts#L123
