### ISSUE TITLE
MER-1654 Quiz preview doesn't render "quiz view"

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3170]
**Describe the bug**
When authoring a quiz, click on the preview button and the quiz will work like formative assessments where students have to submit each question. It should render like a graded assessment where students answer all questions and then hit submit. This is not an issue when rendering the page after publishing.

**Environment (please complete the following information):**

 - Version: Version 0.21.5 (3BEB47B) 09/01/2022

https://eliterate.atlassian.net/browse/MER-1654

**Comment by eliknebel** [comment]
Possible rewording of the preview message in graded assessment pages could clarify why they are rendered that way.

@czerwinskie will work to get some documentation put together so that we can add an info icon link that directs users to the docs.
