### ISSUE TITLE
Drag and Drops have fixed attempts

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3225]
**Describe the bug**
Custom Drag and Drop only allows as many tries as there are targets. So a DnD with 6 targets will become disabled after 6 total attempts. 

This is a problem because a DnD has a lot of possible combinations and should allow for more attempts. 

**To Reproduce**
1. Go to a Custom DnD
2. Drag Options around to Visit every Target once
3. NOTICE: DnD locks, Reset button shown.

**Expected behavior**
DnD should allow multiple attempts for each target area. "Submission" should be contingent upon every target area being filled.

**Screenshots**

![DnD_1](https://user-images.githubusercontent.com/18299544/212380829-5421b620-7127-47b1-93bd-8b02d1b5af43.gif)
![DnD_2](https://user-images.githubusercontent.com/18299544/212380833-feaf671e-f320-41ee-9ed2-7b0fa295c9bb.gif)
![DnD_3](https://user-images.githubusercontent.com/18299544/212380835-facc2c40-6f3c-40cf-bd3a-31c7ce95f159.gif)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 0.22.1

**Additional context**
Examples found here:
https://tokamak.oli.cmu.edu/authoring/project/general_chemistry_i_4vvnj/resource/fz8sy_matter_ck4p1
https://proton.oli.cmu.edu/authoring/project/kth_introduktion_till_python_2/resource/6wg8h_tilldelning_datatyper_och_utsk_b0f80

**Comment by eliknebel** [comment]
Greg: We need to allow students to move answers around indefinitely until they are finished with the activity and we should add a reset button to easily reset the state of the drag and drop. In a graded page, it would behave the same and be submitted with the "Submit Assessment" action

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1686

**Comment by marc-hughes** [comment]
Upon picking this up, here's what I'm seeing:

I think the first gif above appears was solved by https://eliterate.atlassian.net/browse/MER-1974 - it was a race condition from moving things too fast and is unique in that you could not move items, but there was no reset button visible.

I can't reproduce the second gif. On that dnd I can drag items around dozens of times and everything works as expected. I don't get a reset button until I've dropped all the inputs in.

The third gif I can reproduce, and I'm looking into it.

**Comment by marc-hughes** [comment]
An export/ingest from the third example does fail, the cause is the question only had 3 parts instead of 4 it should have.

Recent versions of course-digest correctly import all 4 parts and it works as expected. I believe this bug report is now fully accounted for and we're all set without any changes.

**Comment by eliknebel** [comment]
done v24
