### ISSUE TITLE
Require start and end dates for sections

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3233]
The "Active" filter view relies on dates, and if we don't require them, most courses cannot be captured by that filter.

It's also best practice to have start and end dates for every section.

**Comment by eliknebel** [comment]
Consider making open enrollment courses "opt-in" with some sort of checkbox, but otherwise require start and end date to be specified for all courses

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1717
