### ISSUE TITLE
Unable to remove option on CATA Question

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3242]
**Describe the bug**
In a migrated course, a question has an option that the instructor would like to remove. Clicking the 'X' on that option shows the 'Option Remove [Undo]' pop up, but the option remains there.

**To Reproduce**
1. Go to ['last CATA on this page'](https://proton.oli.cmu.edu/authoring/project/kth_introduktion_till_python_2/resource/6wg8h_lokala_och_globala_variabler_0spqp#:~:text=oli_check_all_that_apply)
2. Click on X to remove any option
3. See the 'Option Removed' pop up in the top-right
4. NOTICE: option still present
5. Refresh page
6. NOTICE: option still present

**Expected behavior**
Clicking 'X' on option in CATA should remove that choice. 

**Environment (please complete the following information):**
 - OS: Windows 11, Mac
 - Browser: Chrome, Safari
 - Version: 0.22.1

**Additional context**
This is a migrated course. The link provided above is to the Proton version, but the bug solution would be required for the KTH hosted version of Torus. The bug is present on both systems.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1758
