### ISSUE TITLE
Provide more constraint options for Input Activities

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3243]
**Describe the Problem**
In some cases, "Targeted Feedback" is being used to cover additional accepted responses, but is marking them as 'incorrect'. 
Particularly for fill-in the blank questions, where an author is not as skilled at regex, better constraints are required for the input and multi-input response validation. 

**Solution**
![image](https://user-images.githubusercontent.com/18299544/215862633-ccb3925c-67ef-4bf2-ab63-c0697b1a4aec.png)
On this question, found [here](https://proton.oli.cmu.edu/authoring/project/kth_introduktion_till_python_2/resource/6wg8h_tilldelning_datatyper_och_utsk_b0f80) the correct response must exclusively have the phrase _'katt'_, though using single quotes, double quotes, or no quotes is acceptable. However, any additional text must be marked incorrectly. 

To achieve this, the author has added extra 'Targeted Feedback' to capture the correct states, but each results in an error-styled feedback, suggesting incorrect. Note that _'Ratt!'_ means "Correct" (like "Right!"
![image](https://user-images.githubusercontent.com/18299544/215865308-37fd0313-d984-450f-8bcc-46d0809e55f5.png)

**Alternate Solutions**
Allowing a toggle of each 'Targeted Feedback' allow as correct or incorrect would cover this.

**Comment by eliknebel** [comment]
This sounds like 2 needs in a single ticket:
- Provide richer set of options for matching feedback on responses
- Allow targeted feedbacks to associate a score. This is already supported in the code, but we need an author mechanism to expose it
