### ISSUE TITLE
Feedback in Summative Review chopping off results (dynamic question related?)

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3244]
A summative question generated with dynamic questions is not showing properly on the Attempt Review

The correct answer, which I submitted is "39 m" shows in the Attempt review as "39"

![image](https://user-images.githubusercontent.com/18299544/215867966-1da5d131-c45e-4517-b51f-37b5b0a37e7a.png)

https://proton.oli.cmu.edu/sections/kth_test_py2/review/40872ebb-68bf-4c44-9d41-d68658f97818

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1757

**Comment by gjbunyea** [comment]
This specific case is found as the 4th question on this page:
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/kth-lvzn8qxk/adaptations/kthIntroPython2/branches/v_1_2-echo
Which leads to an Activity Bank selection: **Legacy Pool: f11eda3033084056aef7f6a30069edca**
