### ISSUE TITLE
Incorrect number of tabs

### ISSUE THREAD

**Issue by raamt1n** [Simon-Initiative/oli-torus#3260]
**Describe the bug**
The number of tabs/spaces is not converted correctly when running the [course digest](https://github.com/Simon-Initiative/course-digest) for migration.

**Screenshots**
![image](https://user-images.githubusercontent.com/76266914/218426978-f0936ead-35ca-4d04-8a28-c3a46a53029b.png)

As you can see in the screenshot only one tab has been applied after ingesting the digested course material in the new system.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1756
