### ISSUE TITLE
Wrong page marker displayed

### ISSUE THREAD

**Issue by raamt1n** [Simon-Initiative/oli-torus#3261]
**Describe the bug**
The blue page marker is always stuck on page 5, despite which page the user switches to. So for example, if I'm in the activity bank and go to page 31 it would still display "5" as seen in the photo below.

**Screenshots**
![image](https://user-images.githubusercontent.com/76266914/218428334-c2553037-6982-4dae-a644-667c9a7df9e9.png)

But everything technically works fine, this is mainly UI.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1755

**Comment by eliknebel** [comment]
https://github.com/Simon-Initiative/oli-torus/pull/3310
