### ISSUE TITLE
Dynamic variable internal server error

### ISSUE THREAD

**Issue by raamt1n** [Simon-Initiative/oli-torus#3262]
**Describe the bug**
Dynamic variable question causes internal server error on some randomly generated values.

**To Reproduce**
1. Copy the provided code below
[Dynamic variable question issue.txt](https://github.com/Simon-Initiative/oli-torus/files/10721230/Dynamic.variable.question.issue.txt)

2. Create a single response question with dynamic variables enabled
3. Preview page

**Expected behavior**
Internal server error

**Screenshots**
Works when value of answerOptions  is as shown below
![image](https://user-images.githubusercontent.com/76266914/218432344-194166bb-b88f-4ae3-add6-9ec3c424cdf6.png)

Causes internal server error when values of answerOptions are like shown below
![image](https://user-images.githubusercontent.com/76266914/218432365-f313151d-5641-4204-8fed-deed3d178ee6.png)

Certain values of
const intrestrate = OLI.random(0.9, 4.5, 2);
Gives the variable answerOptions a very large amount of decimal numbers which causes internal server error.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1754
