### ISSUE TITLE
Allow "inline math" to be a style applied, render like paragraph inline LateX

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3267]
**Describe the bug**
Writing Math notation requires adding an "inline math piece" first, then editing the content within it. However, sometimes MathML/LaTeX will automatically render. 

**To Reproduce**
LaTeX should render consistently no matter location:
1. Type LateX into a Paragraph using \\( \\)
2. Notice: Renders properly
3. Type LateX into a Question Stem using \( \)
4. Notice: Does not render properly
5. Type LateX into a Question Option using \( \)
6. Notice; Does not render properly

Applying LateX style shouldn't replace the text written
1. Type LateX using \( \)
2. Highlight and find the 'Formula' style in menu
3. Apply
4. Notice: Previously written text is replaced with '1+2=3' as LateX inline component

**Screenshots**
![image](https://user-images.githubusercontent.com/18299544/218771486-bd5ade72-7078-44af-a720-43b942ebb371.png)

These should all render the same:
![image](https://user-images.githubusercontent.com/18299544/218771558-4965d8c7-5277-4860-8267-7a25e47a0fad.png)

Applying formula formatting shouldn't replace the text written
![formula](https://user-images.githubusercontent.com/18299544/218773733-c2e1839a-e1dc-4d09-b8e3-47337a72dfa9.gif)

**Environment (please complete the following information):**
 - OS: Windows 11, MacOS
 - Browser: Chrome, Safari
 - Version: 0.22.1, 0.23.0 (tokamak current)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1752
