### ISSUE TITLE
"Cite" Citation Feature Has Won't "Deselect"

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#3288]
**Describe the bug**
When adding a citation to any text section, the citation feature doesn't allow for going back to regular text editing, or to continue adding text beyond the citation block. It only will add text within the citation block. In addition, the "edit" pencil icon does not go away when the citation block is 'deselected'.

**To Reproduce**
1. Add any block that allows for text editing (Mixed, Group, etc)
2. Select the ellipses menu in the hovering text editor toolbar and select "Cite" from the dropdown menu.
3. After selecting an appropriate citation (must have citations in the Bibliography tab), attempt to type after the citation box.
5. Extra: adding another content block that allows for text editing and trying to edit in that block will not hide the "edit" pencil icon.
6. See other error.

**Expected behavior**
A user should be able to continue typing after the citation box (so allow for clicking outside the box). The pencil icon should also go away when the citation box is "deselected".

**Screenshots**

<img width="526" alt="Screen Shot 2023-02-27 at 11 04 06 AM" src="https://user-images.githubusercontent.com/100791229/221616287-9207c10c-2897-4c71-9f54-d51cd5477424.png">
<img width="503" alt="Screen Shot 2023-02-27 at 11 04 13 AM" src="https://user-image
<img width="267" alt="Screen Shot 2023-02-27 at 11 03 44 AM" src="https://user-images.githubusercontent.com/100791229/221616419-aa935628-d96e-4c30-ba1a-4f65f31ba2d2.png">
s.githubusercontent.com/100791229/221616379-46ed2582-0c7c-4c0a-b67a-563b626fef31.png">

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.6.3
 - Browser: Chrome
 - Version: 110.0.5481.177 (Official Build) (arm64)

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1792
