### ISSUE TITLE
Automatic In-Line Citation Tool

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#3289]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but the citation feature provides a stand-in _[citation]_ text when citations are imported into a page.

**Describe the solution you'd like**
Would it be possible to create an automatic in-line citation feature according to the citation style? (Such as MLA, Chicago, APA, or any others)?

**Describe alternatives you've considered**
As of now, in-line citations would have to be manually typed when citations are implemented into the text.

**Additional context**
None really, goes along with the bug I put in with the citation tool.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1793
