### ISSUE TITLE
Citation Formatting Options That Follow Major Citation Formats

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#3290]
**Is your feature request related to a problem? Please describe.**
So far I've had luck with the citation/bibliography formatting citations according to the style they need to be in (which is in compliance with APA 7 as I'm using that as an example). But I am not sure if this is because I am using a DOI link to import the citations. I just attempted an ISBN to bibtex conversion and it also formats in APA 7. What if an instructor wanted to use MLA or Chicago formatting instead, especially if that standard is along the lines of their subjected field.

**Describe the solution you'd like**
I would like to be able to switch between the major citation styles.

**Describe alternatives you've considered**
I don't think I have any alternatives given the way Torus formats the citations.

**Additional context**
Add any other context or screenshots about the feature request here.  If you know of other platforms that offer this suggested functionality, please list them.

**Comment by eliknebel** [comment]
The rendered references should follow a specific, possibly multiple configurable formats (APA, MLA, Chicago, etc...) at a project, product and section level.

Currently, it formats "closely" to APA but we should verify this.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1791
