### ISSUE TITLE
Cool down period for summative test pages

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#3311]
**Is your feature request related to a problem? Please describe.**
Some students answer summative tests without thinking. This is of course not optimal for learning.

**Describe the solution you'd like**
In our case it would be good if we could set at cool down period between attempts on 6-24 hours to make students understand that they should take the test seriously, but also to give them time to reflect upon their answers.

**Describe alternatives you've considered**
This is possible already by doing the tests in Canvas, but that will reduce the data we can access in Torus.

**Additional context**
Canvas does this already.

**Comment by eliknebel** [comment]
Support the ability for an author/instructor to set this on summative pages so that a learner must pause for the set time between. assessment attempts (15min, 1hr, 6hr etc...)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1789
