### ISSUE TITLE
Linking into individual modules or pages

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#3312]
**Is your feature request related to a problem? Please describe.**
We have a Python course in Legacy, that is LTI-linked into Canvas. This works smoothly, but in order to structure the course for students, we have in Canvas set up pages that describes the course week-by-week (e.g. lectures, laborations, seminars) that includes links to the Legacy modules they should do the corresponding week. This works fine, as long as the student first access Legacy through the general link to the OLI course material; but if the student tries to go directly to a OLI module through the links we have in Canvas, somethings goes wrong with the login procedure, and they are denied access.

**Describe the solution you'd like**
When students follow links into any page in the OLI material, and are not logged in, they should be logged in and then taken to the corresponding page (that the link points to).

**Describe alternatives you've considered**
We have recommended our students to click on the general course link first, and then the weekly link, as this works as intended, but it seems a little limiting, as the students cannot see in advance that the session in OLI has ended, and for an outsider, this seems like a problem with a simple solution.

**Additional context**
Canvas has a half solution: if you follow a link to a course in Canvas, but have not an active session in Canvas, you are taken to the login page and can login, but you end up at the start page with all courses, not in the course your link goes to (and have to click that again).

**Comment by eliknebel** [comment]
Torus should support deep linking requests, and provide an easy way to create these deep links

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1788
