### ISSUE TITLE
Hints disappear once correct answer is selected on LBD Tokamak-Gates Design

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3321]
**Describe the bug**
When answering a question, the ability to ask for and view a hint is only available before an answer is selected, or when the incorrect answer is selected. Hints disappear if they were asked for and then the correct answer choice is selected

**To Reproduce**
1. Go to a [LBD activity](https://tokamak.oli.cmu.edu/sections/intro_stats_0308_jlnuc/page/003oi_exploratory_data_analysis_2_of_yzmlt) 
2. Click on the correct answer and the ability to ask for a hint disappears
3. Click on an incorrect answer and it reappears
4. Click on the hint and then the correct answer and it disappears again

**Expected behavior**
Hint remains visible

**Screenshots**
![image](https://user-images.githubusercontent.com/32859465/224855137-3a136f16-b8e4-453c-9417-7d16d6149904.png)
![image](https://user-images.githubusercontent.com/32859465/224855174-017d6b16-0801-41e2-b5a4-1fa2173baaf0.png)
How it appears in legacy
![image](https://user-images.githubusercontent.com/32859465/224855262-3829eff3-6396-4a32-93a1-66f5290e4b75.png)

**Environment (please complete the following information):**
 - Version: Version 0.23.0 (5D0EB47) 03/13/2023

**Additional context**

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1786
