### ISSUE TITLE
Accent Widget for Language Courses

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#3346]
Language courses require students to add accents to their open ended question responses. It has been requested that we add a widget for this.

From Natalie: Do you know if it would be possible to have a keyboard widget with accents in our French and Spanish courses once we're up on Torus? This is a common feature in other language ebooks/eworkbooks.

I'm conducting a study on the user experiences of our self-paced and instructor-led learners for French and Spanish, and every single participant that I've interviewed (n = 25) has mentioned struggling with accents and wishing that there was a keyboard widget where they could just click on the letters that they need as they type.

It appears that most folks using our courses are not accessing them from Macs, where it's the most straightforward to type accents. 

A widget or accent bar could look something like this (this is specific to Spanish). 
![image](https://user-images.githubusercontent.com/44871835/226463121-03af3d65-b08f-47f6-9f5b-fae6190bb839.png)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1851
