### ISSUE TITLE
Toolbar covers "Add input" button in multi-input question

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3355]
When attempting to add an input to a multi-input question, the ADD INPUT button is covered by the toolbar. See screenshot.
![Screenshot 2023-03-23 at 1 39 12 PM](https://user-images.githubusercontent.com/24977416/227296616-b270aeed-47b5-48c8-b1c8-f7a41faa9cef.png)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1850
