### ISSUE TITLE
Cannot add/edit formula in Safari

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3371]
**Describe the bug**
When adding an inline formula to a Torus page in Safari, I cannot select MathML and edit it unless I first refresh the page. Chrome works properly.

**To Reproduce**
1. Add inline formula to page (using safari web browser)
2. click formula to open editor
3. attempt to click MathML button and note it's non-functional

<img width="1063" alt="Screenshot 2023-03-28 at 2 19 39 PM" src="https://user-images.githubusercontent.com/6248894/228331538-54dabf31-6ce1-4484-84cb-c0a169882243.png">

**Comment by eliknebel** [comment]
Verified this is fixed/cannot reproduce in the latest release
