### ISSUE TITLE
Author Notes area

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3376]
**Is your feature request related to a problem? Please describe.**
Authors would like a place to jot notes, keep links to resources, etc within the course project. 

**Describe the solution you'd like**
A tab labelled 'Notes' to be added on the left-panel.  The panel would open up a page that only allows simple, maybe rich text. 

This way authors can add whatever they like to the area, and it won't appear in the course itself.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1845
