### ISSUE TITLE
Student Reminder system

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3377]
**Is your feature request related to a problem? Please describe.**
Instructors would like to be able to send students reminders about their progress through materials.

**Describe the solution you'd like**
A system that allows for selection of students based on criteria 
* % formative done on a given module/unit
* most recently visited page
* last active(?)
* Other criteria...

and send them a custom message, either as a batch of students, or bcc style.

**Describe alternatives you've considered**
In Legacy, an approach to this goal was to use the Email Students feature of the Learning Dashboard. Potentially tying this in with the coming dashboard Gates work would suffice.

**Additional context**
Potentially this could be connected with scheduling features

**Comment by eliknebel** [comment]
@tanvidomadia look into how this can maybe be incorporated somehow with the gates designs

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1844
