### ISSUE TITLE
Adding Ability to View Tagged Activities in the Learning Objective View on Torus

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#3380]
**Is your feature request related to a problem? Please describe.**
When going to the Learning Objective view in Torus, there is a grey box to the right of every LO that details whether or not the LO has sub-objectives, how many pages it is mapped to, and how many activities it is mapped to. Clicking on a learning objective reveals the sub-objective, as well as which pages it is mapped to. However, what is missing is a clear list or table of some sort that provides a link to the activities that the LO is mapped to as well.

![Screen Shot 2023-03-29 at 12 03 02 PM](https://user-images.githubusercontent.com/100791229/228599713-e65394fc-bc1c-481d-ba44-6d805212f453.png)

**Describe the solution you'd like**
I would like a table or matrix of sorts that resembles the existing on in Legacy which allows a comprehensive view of what activities have been tagged with that learning objective, available in the Objective tag.

![Screen Shot 2023-03-29 at 10 58 49 AM](https://user-images.githubusercontent.com/100791229/228599861-aa2b99c4-f0a3-4256-9104-36214f32bc7d.png)

**Describe alternatives you've considered**
There is a way to view activities in "insights" to get to activities, but this does not consider the need of objective mapping and to be able to search for specific assessments via LOs. This goes back to the issue Gautum had when looking for activity bank questions that weren't collecting data in some way.

**Comment by eliknebel** [comment]
<img width="1207" alt="Screenshot 2023-04-11 at 2 09 07 PM" src="https://user-images.githubusercontent.com/6248894/231252111-829efdb2-1ab7-4f06-8ccd-3567734fca5a.png">

Echo allows an author to see a matrix of objectives (skills) to the activities that they are tagged in. We need the ability to see this sort of data in torus as well.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1888
