### ISSUE TITLE
Insights LiveView filters and sorts during render: CMU-364

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#340]
Similar to how we regard the React render phase, we should not be doing work (sorting and filtering) during the LiveView render phase that we can do ahead of time (or in reaction to user events). 

Insights LiveView: `lib/oli_web/live/insights/insights.ex`

The fix here is to do that filtering and sorting upfront at the original mount, and then afterwards only in the event handlers.

**Comment by LEDThereBeLight** [comment]
Closing as done
