### ISSUE TITLE
Add additional details to Student Engagement CSV

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#3402]
**Is your feature request related to a problem? Please describe.**
In the absence of the Learning Dashboard, easy access to an exportable dataset of student engagement would be helpful.

**Describe the solution you'd like**
Currently, exporting student data provides only this data
![image](https://user-images.githubusercontent.com/18299544/231250818-8ca4f025-889d-494c-9634-82cb0b1c697a.png)

But the full set of information found in the Student Enrollment is desirable
![image](https://user-images.githubusercontent.com/18299544/231251255-b4578203-a1fc-4bf4-bded-9a63d114cd28.png)

These are found in section Enrollment tab:
https://tokamak.oli.cmu.edu/sections/gen_chem_0405_lhixj/enrollments
https://tokamak.oli.cmu.edu/sections/gen_chem_0405_lhixj/progress/167

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1889

**Comment by cjlim1092** [comment]
This is essential for GSU in the fall, can we re-triage this?

**Comment by eliknebel** [comment]
Closing this as stale. We will open a new ticket that specs out the exact need here
