### ISSUE TITLE
Quiz pages have no "missing answer" validation before submission

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3403]
**Describe the bug**
You can submit an attempt on a graded quiz page without any warning for missed questions, in legacy there was an "are you sure" popup. 

 [Tokamak version](https://tokamak.oli.cmu.edu/sections/intro_stats_0308_jlnuc/page/003oi_examining_relationships_checkp_a2c69) 
[Legacy version](https://oli.cmu.edu/jcourse/a2/rest/assessement/deliver?context=9a55f7090a0001dc0ecff40c9638a0be&attempt=1)
Legacy Alert
![image](https://user-images.githubusercontent.com/32859465/231560368-b78ea17d-0548-454d-98b4-f434e8fafbac.png)

Version .23

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2076

**Comment by eliknebel** [comment]
We need an exact specification of how this should actually work before we make changes
