### ISSUE TITLE
Dark Mode Error: Description and title text does not change color

### ISSUE THREAD

**Issue by shivanggupta** [Simon-Initiative/oli-torus#3404]
**Describe the bug**
Dark Mode Error: Description and title text does not change color

**To Reproduce**
1. Go to any course in student view with a course description
2. Turn on dark mode
5. See error

**Expected behavior**
Color should change

**Screenshots**
![image](https://user-images.githubusercontent.com/1917065/231561874-a1c42f23-ef03-4011-8649-fb531b8c2433.png)

**Environment (please complete the following information):**
 - OS: Mac
 - Browser:chrome

**Comment by eliknebel** [comment]
Fixed as of v0.23
