### ISSUE TITLE
Missing text validation on single-input questions (Migrated course v.23)

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3411]
**Describe the bug**
When there is a fill in the blank question students can press submit without entering any text in the text box. They will receive feedback on this question. In legacy there was a prompt to fill in the box before they could submit. 

**To Reproduce**
[Tokamak example](https://tokamak.oli.cmu.edu/sections/intro_stats_0308_jlnuc/page/003oi_linear_relationships_yhcr4)
[Legacy example](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9a55f7230a0001dc7ceb46a6ad9ab6ea)

**Screenshots**
Image of submitted question
![image](https://user-images.githubusercontent.com/32859465/232160875-65412efc-b548-4953-b655-ad3ef373bc3f.png)

Image of error message on legacy
![image](https://user-images.githubusercontent.com/32859465/232160707-343f014e-10d3-41bb-b537-f1a73b3a3e46.png)

**Environment (please complete the following information):**
 - Version: v23

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2076
