### ISSUE TITLE
DataShop export: need to limit size of file export

### ISSUE THREAD

**Issue by ctipperCMU** [Simon-Initiative/oli-torus#3417]
**Describe the bug**
Currently when a user exports the content of their Torus course for DataShop a single file is generated. This hasn't been a problem yet, but as courses grow, having a single, large file will break the import. Please confer with Gene as to what file size limits are working well for legacy.

If multiple files are generated, the export should be a zip file. 

**To Reproduce**
Click on the button that was, at one time, labeled "Export for DataShop" (or something like that).

**Expected behavior**
For results that would generate a single file in excess of ???MB, create multiple files below that limit and zip together.

**Additional context**
The error that is generated if a file is too large for import is based on the machine's memory; Gene has found a file size limit that has worked well for us for several years. Please use that.

**Comment by czerwinskie** [comment]
Speaking with Gene, the size limitations are:
total: 400MB archive of 8MB chunks
