### ISSUE TITLE
Internal Server Error on Migrated course checkpoint after clicking begin

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3424]
**Describe the bug**
A migrated course gives an internal server error when trying to begin a quiz. It is expected that the quiz would load. 
 
**To Reproduce**
Open quiz: 
https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_eda_examining_distributions_ch_1mfvr 
or
https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_test_1_review_mw75u

May have to do with a pool that is broken: [Probs_are_equal_pool](https://echo.oli.cmu.edu/#georgia_state_stats_support_perimeter-5.3/reviewe467fe28b0564f8abb5dcce7b1bb0a2b?organization=georgia_state_stats_support_perimeter-5.3_uuwxpzj3&nodeGuid=aa69bfe6ce0e4428b712a118926fb5e4)

[XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/x-oli-assessment2/testcee2c8be645a42e6b1d337fc196dfa7c.xml)

**Environment (please complete the following information):**
 - Version: Version 0.23.1 (0A8AD06) 04/21/2023

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1928

**Comment by cjlim1092** [comment]
As of 6/26 this happens in 3 places 
Resources: 
1. EDA Examining Distributions Checkpoint 1 (see above for links) 
3. Test 2 Review and Non-Credit Test 2 Review (these are two resources, but use the same pools)[ Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/d9df589771cd40df8aa548ef5b9e08ad?organization=georgia_state_stats_master_liu-5.10_lucqxmf9) [XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/x-oli-assessment2/d9df589771cd40df8aa548ef5b9e08ad.xml) [Legacy ](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d82b0a0001dc76767fc230bf0669)[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_noncredit_test_2_review_cq6ny)
4. Non-Credit Test 3 Review (Summer) [Echo ](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/cbbbdc88636d4f708f378a4dc603d7f2?organization=georgia_state_stats_master_liu-5.9_lucqxmf9)[XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/x-oli-assessment2/cbbbdc88636d4f708f378a4dc603d7f2.xml) [Legacy](https://oli.cmu.edu/jcourse/assessment2/activity/view.do?context=92d821af0a0001dc6950dda8f7b671d3) [Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_noncredit_test_3_review_summer_2724m)
