### ISSUE TITLE
Unlinking section from LTI sends Torus admin account to login page

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3428]
To recreate:

- sign in as Torus admin
- unlink LTI-connected section
- note page resolves to login page

![Screenshot 2023-04-25 at 11 29 12 AM](https://user-images.githubusercontent.com/24977416/234327465-cddfaa01-1007-4beb-83d3-4c645d16367a.png)

**Comment by eliknebel** [comment]
Should show an alert that the operation was successful and redirect to the section details if admin,  course setup if LTI. Should not log user out.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1926
