### ISSUE TITLE
Breadcrumb trail or other navigation from the Product Overview page to the Project

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3431]
When creating or editing products, the Product Overview page gives no indication or what project it's associated with. There is no navigation back to the project or the main product-list page from the Product Overview page.
A breadcrumb at the top of the page would help the user remember what project they're working on, and to be able to get back to it reliably. See second screenshot for an example.

![Screenshot 2023-04-25 at 12 53 21 PM](https://user-images.githubusercontent.com/24977416/234348184-a809f076-3a3f-430a-9874-3dbee4e1ed01.png)
![Screenshot 2023-04-25 at 12 55 47 PM](https://user-images.githubusercontent.com/24977416/234348762-9e764e41-5945-48da-afd1-164a72651f84.png)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1923
