### ISSUE TITLE
"Delete Section" not working

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3432]
Attempting to delete this section:
https://proton.oli.cmu.edu/sections/torus_test_a7fr2

After deleting, section is still Active. The third item in this screenshot:
https://proton.oli.cmu.edu/admin/sections?active_today=false&filter_status=&filter_type=&offset=0&sort_by=title&sort_order=asc&text_search=hal
![Screenshot 2023-04-25 at 1 07 23 PM](https://user-images.githubusercontent.com/24977416/234351252-f41b2a8a-d5df-40a9-83fa-4c783a472778.png)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1922
