### ISSUE TITLE
Checking "automatically push update" box erases info in the description field for the update

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3434]
When publishing an update, clicking the "automatically push this publication update..." checkbox results in the erasure of the Description field for the update. See attached videocap.

https://user-images.githubusercontent.com/24977416/234357432-f96c51d1-440f-45a4-844e-b10f99abf807.mov

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1918
