### ISSUE TITLE
(Migration) LBD/DIGT groups are loading multiple banners nested

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3435]
**Describe the bug**
Within a migrated course, sometimes there are group banners listed inside of larger group banners. This is an issue with LBD and DIGT groups. This is not an issue on legacy courses. 

**To Reproduce**
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_probability_rules_5_of_11_szufr)
[legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d7710a0001dc0cf89944adf482cc)
[echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.8/_u4_m01_probability_rules5?organization=georgia_state_stats_master_liu-5.8_x2z4ga6r)
[XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/_u4_probability/_m1_finding_probability/x-oli-workbook_page/_u4_m01_probability_rules5.xml)

**Screenshots**
![image](https://user-images.githubusercontent.com/32859465/234361901-814fee9b-9489-466b-8f0e-34b5c6b3e366.png)

Legacy:
<img width="983" alt="Screenshot 2023-04-25 at 2 10 21 PM" src="https://user-images.githubusercontent.com/6248894/234364868-5d91090a-cb2b-4c6f-8797-80b8a84e8d96.png">

**Environment (please complete the following information):**
 - Version: .23

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by eliknebel** [comment]
This is a composite activity, both the items are tagged with the purpose but in legacy the label only shows up once

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1920
