### ISSUE TITLE
(Migration) Datasets in Alternatives which are supposed to be downloaded do not work

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3439]
**Describe the bug**
When downloading datasets from stats activities which have alternatives, the datasets do not exist so they are not downloadable

**To Reproduce**
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_standard_deviation_admkf) example and[ legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d6790a0001dc1bf91df3f6a52b3f) and [XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/_u2_summarizing_data/x-oli-workbook_page/practice/eda_introlbd.xml)

**Screenshots**
Tokamak
![image](https://user-images.githubusercontent.com/32859465/234368525-b3ef601e-919e-498d-b25f-e18471551872.png)
Legacy
![image](https://user-images.githubusercontent.com/32859465/234368721-a34d3638-10dd-4998-a0c8-845218f744be.png)

**Environment (please complete the following information):**
 - Version: 23

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1969
