### ISSUE TITLE
Scored activities should show feedback on submit

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3445]
**Is your feature request related to a problem? Please describe.**
Current user flow has students submit the scored activity, at which point they are taken to an attempts summary page. From this summary page, they need to identify their most recent attempt and click on that link to see their feedback.

This is different from expected behavior and Legacy behavior -- students expect to be taken directly to the feedback page on submit (assuming that feedback is available).  

**Describe the solution you'd like**
A change in the user flow, such that students are taken directly current attempt feedback on submit

**Describe alternatives you've considered**
None

**Additional context**
This has been cited by several users (students, authors, instructors) as a problem -- it adds an extra click for students, it forces the students to find the most recent attempt, styling doesn't make it obvious that the attempt is a link that they are supposed to click, and it behaves differently than expected (different than the way many other educational systems behave)

We need to get this into the v24 release (made commitment to user that this would be addressed)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1999

**Comment by eliknebel** [comment]
Fixed in v24
