### ISSUE TITLE
No Way to close the hint button.

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3446]
**Describe the bug**
Can’t close hint box in Torus - you can in Legacy https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_classification_of_matter_0jwo4

![image](https://user-images.githubusercontent.com/36045601/235692343-bc87f1d8-b1f3-4730-959a-89b67bd17a87.png)

![image](https://user-images.githubusercontent.com/36045601/235692432-2906b96e-ff62-4336-9f4b-27aa68c1f0a6.png)

**Comment by darrensiegel** [comment]
Part of a larger collection of hint styling issues that will need to be addressed, but not for v24

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1998
