### ISSUE TITLE
Labels running into targets in Drag and Drops

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3447]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_application_is_it_gold_u9j3q

![image](https://user-images.githubusercontent.com/36045601/235692741-ab2c7767-1ea6-47f3-856a-841cfadb4126.png)

![image](https://user-images.githubusercontent.com/36045601/235692800-a6fc91bf-15b6-4708-b9d7-7b76212e9131.png)

**Comment by andersweinstein** [comment]
This question uses a custom layout spec which is not table based, but simply positions each element (label and target area) absolutely in its container. I assume the fixed positions were custom-chosen to work with the legacy font. This layout method is not adaptive to a change in font. But the layout does not specify any font or font size so picks up the ambient default which is now different than the one it was customized for. This will be a general issue with migrating custom-tweaked layouts like this one.

Layout could be modified to change positions for torus, or specify a font to use (but might clash visually), But best would be to use a more adaptive layout method like a tabular one.

**Comment by darrensiegel** [comment]
Task here is to emit a warning in the digest tool when encountering a DnD question with absolute positioning within the CSS

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1997
