### ISSUE TITLE
 "Complete" button for unordered pages is confusing

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3448]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_measurements_q3u21

For my response - after the survey is complete if they click the box at the bottom - the course overview opens in that tab. This is problematic because now they have the course open in two different tabs and that can be confusing.
![image](https://user-images.githubusercontent.com/36045601/235693214-9ec46d93-0bc3-4936-8cbb-01abc5a65312.png)
In legacy there is no such button. They just close it in their brower if they want. 
![image](https://user-images.githubusercontent.com/36045601/235693382-604655a2-a831-44ec-a60a-4904a5dde2e0.png)

**Comment by darrensiegel** [comment]
The "Complete" button is shown for all "unordered" pages, that is, pages that do not appear in the course hierarchy.

**Comment by darrensiegel** [comment]
Agreed this is confusing for students, but not critical to fix for Fall.  Browser back button can be used to navigate back to previously visited page.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1996
