### ISSUE TITLE
Images Not Centered

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3451]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_chemical_symbols_d6wox

![image](https://user-images.githubusercontent.com/36045601/235696287-f892a462-c5f5-43ac-bf23-bdb64a43cd00.png)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1941
