### ISSUE TITLE
Not Apparent How to Review a Quiz after its submitted

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3454]
![image](https://user-images.githubusercontent.com/36045601/235698217-ef4b96f4-731a-4d00-8fb0-5ce7aef724b0.png)

You need to click the Attempt 1 of 5 to review your quiz. This is not apparent.

**Comment by darrensiegel** [comment]
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3445
