### ISSUE TITLE
Warning Message on Quiz Submit

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3456]
In legacy, if you try to submit without filling in some of the answers you get a warning message. Not the case in Torus. 

![image](https://user-images.githubusercontent.com/36045601/235702110-b793aa6e-4224-4578-8d22-0252366e7557.png)

**Comment by darrensiegel** [comment]
Duplicate of https://github.com/Simon-Initiative/oli-torus/issues/3403
