### ISSUE TITLE
Double subscript not displaying

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3457]
Double subscript not displaying. The 2 to the right of the N should be subscripted as well as the 2 to the right of the H. [Partial Pressure of Gases (cmu.edu)](https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_partial_pressure_of_gases_yhz7j)

![image](https://user-images.githubusercontent.com/36045601/235703677-f0e794ec-53f3-4773-a50b-2f1513e1ada7.png)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1966
