### ISSUE TITLE
Add more differentiating info to "Base Project info" portion of "Manage Source Materials" tool

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3458]
The Manage Source Materials tool in Torus delivery tells you the name and version number of the source material. There is no hyperlink taking the user/admin into the authoring space, so you must rely on a search.
If the search yields multiple projects with the same name and version number, it could be impossible to discern which is the source material for the section.

Example:
Section: [Foster Active Learning](https://proton.oli.cmu.edu/sections/foster_active_learning_ybw53/manage)
Manage Source Materials info: 
![Screenshot 2023-05-02 at 4 15 07 PM](https://user-images.githubusercontent.com/24977416/235775876-d78a856d-751a-4626-b2b6-60838840c7d7.png)

Search results for "E-Learning Design Principles"

- [first result, which is version 0.15.0](https://proton.oli.cmu.edu/authoring/project/elearning_design_principles)
- [second result, which is also v0.15.0](https://proton.oli.cmu.edu/authoring/project/elearning_design_principles_yir4f)

In this specific case I was able to deduce that the correct project was the one with a team of users. But if neither had a team, or the teams were identical, or if both teams included the primary author/instructor, there would be no way of knowing which project was the source for the section.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1993
