### ISSUE TITLE
Open in full tab

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3461]
I cannot find a way to open Torus from inside the LMS without it being embedded in the LMS like an iFrame. That greatly reduces its size, and should ideally be accessible in a full browser tab of its own.

**Comment by darrensiegel** [comment]
<img width="842" alt="Screenshot 2023-05-03 at 9 46 16 AM" src="https://user-images.githubusercontent.com/7431756/235935351-5be4f83a-6986-40d1-b28d-3082ff6863e8.png">

When adding an External Tool to a module, select "open in new tab"
