### ISSUE TITLE
Payment process is unclear

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3462]
When the student is prompted for payment:

- There is no cost displayed.
- The first option/button makes no mention of credit card.
- Two boxes labeled "Pay now" and "Use a payment code" don't make it clear that the student must choose one of two options -- paying either with a credit card or with a payment code.
- Clicking "pay now" results in a form with three prefilled fields. The text is very faint gray, which communicates that the text is descriptive, not that it's been prefilled. There are no instructions or orientation of any kind.
![Screenshot 2023-05-02 at 5 23 37 PM](https://user-images.githubusercontent.com/24977416/235791270-00a868ee-a410-457b-855e-85ae69b43c62.png)

Suggestions:
![Screenshot 2023-05-02 at 5 29 08 PM](https://user-images.githubusercontent.com/24977416/235790324-36b48632-6a2b-4f80-af3c-6ed6866240a1.png)

- Replace the two gray buttons here with the prefilled fields from the screencap above.
- Format the information so it doesn't look like a series of editable fields, but instead is treated as a summary of information (Course title, student name, cost)
- Beneath the summary, include two buttons with explicit instructions that they must choose only one, pay by credit card or pay by payment code.
- Do not use a light blue-on-medium gray color scheme. It's inaccessible because it lacks sufficient contrast.
- Add a link to OLI Help. There is none on this page.
- Format the code-redemption screen so the fields aren't touching the left boundary of the frame
![Screenshot 2023-05-02 at 5 35 47 PM](https://user-images.githubusercontent.com/24977416/235791439-87abbabf-91a2-4cc9-bd9b-2ced375a1495.png)

**Comment by darrensiegel** [comment]
For fall the current process meets MVP, I think.

But ultimately it needs proper navigation and cancellation capabilities, for general usability and for screen readers. Without commenting on the UI, the UX would:

on any page/panel include a "BACK" button taking them to the previous step
offer a "CANCEL" option with confirmation step
close any newly opened payment tabs and take the user back to the page where the "Pay Now" click originated
upon successful completion of payment, with a banner notifying them of their successful payment
upon cancellation at any point
upon clicking "BACK" from the first page/panel that appears after clicking "Pay Now"

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1991
