### ISSUE TITLE
When configuring course via LTI, shortened title isn't viewable by side-scrolling

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3463]
When you're choosing the project/product to link to your LTI section, titles longer than a few characters are cut off and followed by an ellipsis. Below the title is a side-scrollbar. But using it doesn't reveal more of the title. See screenshot, which is scrolled halfway to the right.
<img width="723" alt="Screenshot 2023-05-02 at 5 44 24 PM" src="https://user-images.githubusercontent.com/24977416/235793134-af8da13d-ec1f-43cd-9dbf-26bce809a308.png">

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1990
