### ISSUE TITLE
Editing product cost or gating doesn't result in updated cost or gating for students

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3464]
To reproduce:

1. Create a product with a cost.
2. Use it to configure an LTI-connected course.
3. Access course as a student in a separate browser. Note cost.
4. Update the product with a new cost.
5. Attempt to publish updates, but note there are no updates to push.
6. Visit course as student, note price has not changed.
7. Same for gating.

**Comment by darrensiegel** [comment]
Payment settings and gating settings do not "auto update" into course sections created from Products.  Once a course section is created those settings from the product are effectively "copied" into the course section.  An admin can change those settings there in the course section.
