### ISSUE TITLE
New LTI or independent section access defaults time zone to GMT-12:00

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3466]
When a user first accesses an LTI section, the time zone is not synced with the LMS time zone, nor to the local device settings. It's automatically GMT-12:00.

Desired behavior:
To make due dates useful, the user account's time zone must be set correctly. It either needs to default to the device's time zone, or it must ask the user to set it.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1989

**Comment by Ringenberg** [comment]
Javascript Date methods might be able to help here as it is much easier to always work with UTC:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
