### ISSUE TITLE
Payment process includes no backward navigation

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3468]
When the student clicks Pay Now, there is no navigation backward through the process. 

The payment reminder banner follows you through the course, so clicking Pay Now and navigating away should result in a path that brings you back if you choose. Instead, the only way to back out of the payment process is to use the top-level Torus link, which will be located in different places in different LMS configurations. In OLI Canvas's case, it's in the lefthand menu.

This video was taken for another payment-related issue, but it illustrates the lack of navigation in the payment screens. The process needs more cancellation or back-navigation options added to the page.

https://user-images.githubusercontent.com/24977416/235945828-cd399e59-cfbd-4ef4-a4c8-196133d82387.mov

**Comment by darrensiegel** [comment]
Does the Browser "Back" button suffice here ?

**Comment by halturner** [comment]
For fall the current process meets MVP, I think.

But ultimately it needs proper navigation and cancellation capabilities, for general usability and for screen readers. Without commenting on the UI, the UX would:

- on any page/panel choose a "BACK" button taking them to the previous step
- offer a "CANCEL" option
- close any newly opened payment tabs and take the user back to the page where the "Pay Now" click originated
   - upon successful completion of payment, with a banner notifying them of their successful payment
   - upon cancellation at any point
   - upon clicking "BACK" from the first page/panel that appears after clicking "Pay Now"

**Comment by darrensiegel** [comment]
Closing, combining with other Payment issue
