### ISSUE TITLE
Add support for multipart dropdown shuffling

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3470]
Activity is set to shuffle answers and it is not shuffling. 1st and 2nd attempt (on reset), all have the answer choices in the same order and this order matches the xml. The answer choices are set to shuffle in the xml.

[International System of Units (cmu.edu)](https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_international_system_of_units_o15z7)

![image](https://user-images.githubusercontent.com/36045601/235960525-0bae0fa8-daec-45f7-9062-5b0afb81366d.png)

![image](https://user-images.githubusercontent.com/36045601/235960675-b01ad52a-1951-42e3-b0cb-41dcb391a8b6.png)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1987

**Comment by eliknebel** [comment]
fixed
