### ISSUE TITLE
Point values on quiz items confusing

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3473]
This is for all quiz questions. Points assigned in the xml come up in the 2/2, 0/2 in this example and so on. But the text above says "Points: 0.5 out of 1" I guess this is just giving the overall % for this individual question, but I think students will find this confusing. The points listed at the top says 1.83 out of 10.0. I think this should list the total points assigned like in legacy. 

https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_measurements_l1t8t/attempt/99f92f08-048d-4a85-9726-3486d1ef3761/review

![image](https://user-images.githubusercontent.com/36045601/235969442-7d625c6f-b03f-454f-9447-da8709bf8647.png)

![image](https://user-images.githubusercontent.com/36045601/235969561-2105ece6-1480-4565-9c92-fc911a1b1660.png)

![image](https://user-images.githubusercontent.com/36045601/235971149-d08afe0f-8105-4971-893f-d602892a706e.png)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1986

**Comment by eliknebel** [comment]
fixed
