### ISSUE TITLE
LTI sections cannot be given Start and End dates

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3475]
When creating a new LTI section, Start and End Dates are not automatically applied and they cannot be manually applied by the instructor or admin. This affects:

- [ability to apply gating or scheduling](https://github.com/Simon-Initiative/oli-torus/issues/3442)
- [Torus's "This project has X active course sections" feature
](https://github.com/Simon-Initiative/oli-torus/issues/3465)
- [the student's payment grace period
](https://github.com/Simon-Initiative/oli-torus/issues/3430)
- [general OLI recordkeeping
](https://github.com/Simon-Initiative/oli-torus/issues/3233)

Desired behavior:

- both dates are required
- during either LTI or independent-section setup, date-entry would be a step that precedes creation
- dates can be updated by instructor or admin after course creation
   - if students have registered, updated dates should adjust some dependent grace period duration calculations
   - if the Start Date is moved BACKWARD, all existing grace period durations should remain unchanged; shortening their grace period duration may be unfair
   - if the Start Date is moved FORWARD, all existing grace periods should be adjusted by the same amount of time that the Start Date was adjusted

**Comment by darrensiegel** [comment]
The upfront requiring of start and end dates will be handled by https://eliterate.atlassian.net/browse/MER-1728

**Comment by halturner** [comment]
[Ticket for editing date after section creation has been opened.](https://github.com/Simon-Initiative/oli-torus/issues/3483)

**Comment by eliknebel** [comment]
fixed
