### ISSUE TITLE
(Migration) HTML activities that are uploaded to echo are not visible

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3477]
**Describe the bug**
HTML activities that are directly uploaded to echo are not loading after migration. They work in legacy. 

**To Reproduce**
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.8/histogram1?organization=georgia_state_stats_master_liu-5.8_x2z4ga6r)
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_histogram_intervals_31cvg)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d5f50a0001dc3a4aeadcd58b65d7)
[XML](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/_u2_summarizing_data/_m1_examining_distributions/x-oli-workbook_page/histogram1.xml)

**Screenshots**
Tokamak
![image](https://user-images.githubusercontent.com/32859465/234369484-4f811129-7313-430a-978e-5b23afda6be8.png)
Legacy
![image](https://user-images.githubusercontent.com/32859465/234369561-277f5387-5e53-4844-bd21-af9c7b8f26e0.png)

**Environment (please complete the following information):**
 - Version: 23

**Comment by andersweinstein** [comment]
Migrating "HTML activities" is a much more substantial issue than simply handling the iframe src link (MER-1968) to an html document treated as a media item This is because the embedded html page itself may contain relative URLs into webcontent to load supporting scripts, css files and other resources such as images or data files.

**Comment by cjlim1092** [comment]
Update - the HTML Activities are now working, but some of them have additional characters
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_linear_relationships_4_of_8_3sok1)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/f22f4d44-f425-4fcb-a4f8-713d4b9069ef)

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d6da0a0001dc39638a51166c6eeb)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/80337233-55a5-4cf4-862b-20a35002000e)

**Comment by cjlim1092** [comment]
Another update, Anders likely knows about this one, but the images on the lets make a deal page are not rendering
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_introduction_to_probability_1__1mme9)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/187f7f8d-6177-4a6b-b014-0dcc4cf7a195)

**Comment by cjlim1092** [comment]
Update: This one is not clickable (the other ones so far have been clickable)
[Tokamak](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_relative_frequency_m8sgu)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/fe58382a-7185-4414-99c6-c224881fd060)

**Comment by andersweinstein** [comment]
We are in the process of changing the way we handle migrating these to a more general approach based on uploading "webcontent bundles" and preserving their directory structure. Hopefully this will avoid the issues above. But we can't evaluate until after the change.
