### ISSUE TITLE
Enable editing of Start and End dates after section creation

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3483]
Start and End dates of sections should be editable by the instructor or admin after the section has been created/configured.

For legacy parity:
- if students have registered, updated dates should adjust some dependent grace period duration calculations
     - if the Start Date is moved BACKWARD, all existing grace period durations should remain unchanged; shortening their grace period duration may be unfair. Consider a warning that appears if students have registered: "Because students have already registered in this section, their grace period durations will be unchanged by changing the section Start Date to a day/time prior to their registration."
     - if the Start Date is moved FORWARD, all existing grace periods should be adjusted by the same amount of time that the Start Date was adjusted

We have also discussed changing the restrictions that an End Date imposes in Torus. Consider access/permissions affected by a change.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1984

**Comment by eliknebel** [comment]
fixed
