### ISSUE TITLE
Cannot edit account details without changing password

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3492]
I tried to change the last name of an account that was using Google authentication. I had to enter my Google password into the password-reset / confirmation fields just to change my last name.

Then I created a fresh student account from Google authentication. To change the last name I was required to enter my Google password in the Current Password field, then was required to enter it again in the New Password and Confirm fields. That permitted me to change the Last Name value.

If a user is authenticated, presumably they should be permitted to change their details without needing to share their Google password with Torus.
It's also confusing to be required to "update" your password to change your last name, but to learn through experimentation that you can  enter your existing Google password three times instead of updating it.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1982
