### ISSUE TITLE
Keep changelog for user fields, make it admin-searchable

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3494]
@KimWahlenmayer:

> For discussion, in Legacy, students (any users) cannot change their email address. Maintaining the integrity of this key and continuity of the account is desired for many reasons.
> For example, if a student changes their name and email address, it could be impossible to find their account if they request a refund from a different email address. We could perhaps find the payment to refund but would not be able to identify the associated registration to suspend (even if the new payment process ties the course key to the payment unlike Legacy Cashnet configuration).
> For another example, if a student finishes a course, then changes the account's name and email address, it is impossible to see that the 2nd name and email address did not complete the course. Would a certificate be regenerated in the new name (it would not in Legacy unless the cached cert is deleted in the database)? This should be considered. These are academic scores and history.

Proposed behavior:
When a user changes their name or email, that change is committed but the old values are preserved and linked to the account. When a user search is conducted by an admin, results are returned based on current values first and historical values next.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1980
