### ISSUE TITLE
Duplicate feedback on points for checkpoints

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3497]
**Describe the bug**
One general issue that I have noticed in the feedback is that the points do not match where points are shown and, in the feedback, as shown below. (from Harden) 

Adding on, point values should not be shown more than once in checkpoints. The point values are sometimes consistent with one another (1 point, 1 point as seen in second screenshot below) but at other times they are not consistent with one another (as seen in first screenshot) 

**To Reproduce**
[Link to example page](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_sampling_distributions_checkpo_e08ku)

**Screenshots**
![image](https://user-images.githubusercontent.com/32859465/236544204-36926214-6dfc-4b2f-aa23-9f9ea1ae2c8b.png)
![image](https://user-images.githubusercontent.com/32859465/236544244-a88962da-2f83-4790-8eb9-e8ce583c2e61.png)

**Environment (please complete the following information):**
 - Version: 23

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1979

**Comment by eliknebel** [comment]
fixed https://github.com/Simon-Initiative/oli-torus/pull/3532
