### ISSUE TITLE
List Formatting Disappeared

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3498]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_atomic_mass_54efq
This is in a numbered list, but doesn't display like that in torus. 
![image](https://user-images.githubusercontent.com/36045601/236564482-f8bfb555-6345-47fa-8cb1-66315ae929a9.png)

Here it is in legacy
![image](https://user-images.githubusercontent.com/36045601/236564586-d1f96bce-baef-49af-8c49-5304c8450327.png)

**Comment by darrensiegel** [comment]
Fixed by https://github.com/Simon-Initiative/oli-torus/pull/3489
