### ISSUE TITLE
Objectives page enhancements

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#350]
A few things could be improved on the objective page:
- Objectives are selectable, but is this really necessary? Could we offer action buttons on hover. If not, we should all deselection by clicking outside the objective
- Adding objective/sub-objective using return key works, but the text remains requiring an author to delete this text before adding another objective. Adding multiple objective should be as frictionless as possible
- Objective target icon shows when in "add sub-objective" mode

**Comment by LEDThereBeLight** [comment]
Closing as done - other objectives page enhancements have been requested but this issue is stale.
