### ISSUE TITLE
Tokamak: "Show dates formatted as relative to today" is not honored

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3503]
After unchecking the setting, dates are still shown as "number of days ago" in the Enrolled Sections area of a user profile. I did not find the issue in other places yet.

<img width="1608" alt="Screenshot 2023-05-09 at 9 24 57 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/7648466b-a54d-4756-a1fb-4eace19f45fd">

<img width="1374" alt="Screenshot 2023-05-09 at 9 25 55 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/de4d69c2-77e9-4b27-819d-cbf8449e7b60">

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1977
