### ISSUE TITLE
Display hyperlinked instructor/student accounts when searching authoring accounts

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3505]
Display linked instructor/student accounts when searching authoring accounts. This is the converse to the "linked author" display for instructor/student profile searches. That info should also be visible and clickable from the profile page itself, not just the search results.
Ideally, the value would be a hyperlink the admin could follow to the profile page for the instructor/student account.

<img width="1496" alt="Screenshot 2023-05-09 at 9 35 39 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/dadbcf17-9923-4d51-80e2-8db13a6e35f7">

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1975
