### ISSUE TITLE
Tokamak: Drag and Drop doesn't always register feedback

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3506]
When dropping initiators into drag and drop zones, the feedback is not always triggered. See the screen recording, where an initiator was dropped into multiple zones that initially didn't result in feedback, but later did.

https://tokamak.oli.cmu.edu/sections/kth_onelearns_4_may_2023/page/74yy1_knowledge_37jhg
LBD with text "By reading the material above you should be able to infer the correct answers to these questions. Each of the statements below represent a student acquiring a piece of knowledge/a type of knowledge. Classify the knowledge described as Declarative, Procedural, or Concepts & Principles."

https://github.com/Simon-Initiative/oli-torus/assets/24977416/a7828c02-0b80-49b3-a81a-e87ea31ef47e

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1974

**Comment by eliknebel** [comment]
fixed
