### ISSUE TITLE
Tokamak: Preview course as instructor or student is not working 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3507]
**Description**
Not able to preview the course as an instructor or student for a course on Tokamak when clicking on a course as a student. 

1. Go to tokamak.oli.cmu.edu as a student 
2. Click on any of the course sections 
3. You will be taken to the main page of the course, which shows some preliminary analytics sub-tabs
4. Click on "Manage" 
5. Click on "Preview course as Instructor" or "Preview course as student"

We are taken to the same main page view with the preliminary analytics sub-tabs but not a preview of the course content. 

**Expected behavior**
Preview of the course content. 

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1973
