### ISSUE TITLE
Tracking student exposure/use across multiple products

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3508]
**Is your feature request related to a problem? Please describe.**
We have a number of internal use cases in we need to track be able to show information about students' earlier use of courses.  For example, students use one part of the collaboration suite in the Fall.  Faculty teaching chemistry and using collaboration want to see who in their class has already used the collabU, for example

This is a longer term (v25/v.26) feature request from Dietrich that still needs to be investigated and spec'ed out.  I'm just capturing here to get a place to start capturing information so that I don't lose it. 

**Describe the solution you'd like**
Ideally we can create a mechanism for identifying related groups of course products and sharing some information about sutdent use to instructors and administrators . 
**Describe alternatives you've considered**

**Additional context**
Initial requesters for this feature are Richard Scheines and Sharon Carver.  I'm imagining this is a feature that could be much more broadly used for other contexts, but this requires more information and research.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1972
