### ISSUE TITLE
Styling -- bullets not displayed in question

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3509]
**Describe the bug**
The bullets in this question are not being displayed as bullets

**To Reproduce**
Review the attached screenshot, compare The Torus and Legacy rendering -- Torus doesn't style as a list (ie w/ visible bullets). 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.
![235697770-d55b3014-9886-406a-9610-a536574625f8](https://github.com/Simon-Initiative/oli-torus/assets/4762701/ebb2a4aa-5e93-4251-9f70-cf28567759ff)

**Comment by darrensiegel** [comment]
Verify that already fixed by recent Delivery Styling bug fixes.

**Comment by darrensiegel** [comment]
Verified that this is fixed by: https://github.com/Simon-Initiative/oli-torus/pull/3489
