### ISSUE TITLE
Tokamak: after finishing drag-and-drop, items cannot be moved without full activity reset

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3516]
No adjustments are permitted after the last drag-and-drop item has been placed. This is especially inconvenient 

1. as the number of items grows
2. if the last item is incorrect, because they you must recreate the entire activity to attempt to get that last item correct.

To recreate:
https://tokamak.oli.cmu.edu/sections/kth_onelearns_4_may_2023/page/74yy1_knowledge_37jhg
In the DnD activity beginning with the text "By reading the material above you should be able to infer the correct answers to these questions," place the answers in the table. When the last one is placed, you cannot make any adjustments without beginning again.

**Comment by andersweinstein** [comment]
Note this is the same behavior as multi-input, even with part-at-a-time submission enabled: once all parts are answered, the question is completed and must be reset to change even one part. Is this a problem in the same way for multi-input?

[A drag-and-drop is effectively just a different UI for a multi-input question, behaviorally equivalent to a multi-input asking  "1. where do you want to drop draggable1? [targetA | target B | ...]; Where do you want to drop draggable2? [targetA | target B | ...]; ..."

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2074
