### ISSUE TITLE
Ability to offer either credit card or payment code availability on products, instead of both

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3517]
Many products need either/or credit cards and payment codes, but not both. For example, all GSU students purchase their OLI access via payment codes sold by the bookstore, and they are not permitted to pay by credit card. The idea solution would include checkboxes that become active when the product's "require payment" setting is selected, allowing you to use one or both of the options.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-1955

**Comment by darrensiegel** [comment]
Fixed.
