### ISSUE TITLE
Alt tags not showing for image in Example

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3519]
https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=013919ef7f0000012215b4bfc2cbb9b8
The alt tags for the images in the examples are not showing up. It does have an alt tag - I verified in legacy.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/22aa0eaa-5123-41a6-a27c-05455fe7512e)

**Comment by darrensiegel** [comment]
Alt tags are being included in the HTML produced by Torus.  

The difference between Legacy OLI and the Torus implementation is that Legacy also applied the "alt" text as the "title" attribute of the image, which results in the browser displaying a tooltip. For reasons of accessibility, Legacy should have never included that "title" attribute.
