### ISSUE TITLE
Hint Button Should be Viewable Even After Correct Input

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3520]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_nomenclature_for_ionic_compoun_pf334

After correct input the hint is no longer viewable.
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/bfe86ba9-1f5c-4b2a-ac4e-6da10f373d71)

It would be best to have the hint still viewable as in legacy. 

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/cd32349e-497b-446a-a1e9-899a31f5645f)

If students answer correctly, but maybe guessed or weren't completely sure about their answer they may still wish to view the hint for further instruction even after the correct entry.

**Comment by eliknebel** [comment]
Need to verify that all stakeholders are on board with this change, need to verify original spec

**Comment by eliknebel** [comment]
Confirmed, hints should always be available even after feedback is shown

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2158
