### ISSUE TITLE
Formula on Page not Being Centered

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3521]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_determination_of_molecular_for_v82ef

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/05ae4827-f941-431e-8597-19245dfe8638)

The (CH2O)6= C6H12O6 formula should be centered as it is in legacy.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/f1e7fbb7-63b0-4710-b4fe-b25a9d3d7026)

**Comment by darrensiegel** [comment]
This is the same issue as #3522 

Closing.
