### ISSUE TITLE
Text goes too far across the page - Need some border space

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3523]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_balancing_redox_equations_in_a_encxd

So this is the view of my full screen on the laptop. There should be some space on the side - just doesn't look right. Here is what it looks like in legacy.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/70bb271b-70d5-4533-92fb-5a24c966fda1)

**Comment by eliknebel** [comment]
Need some more margin space, ideal content width is ~800px for readability

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2151
