### ISSUE TITLE
Text Spacing Makes this Difficult to read

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3524]
https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_balancing_redox_equations_in_b_qo0wy

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/a56d0787-13e1-4699-8ee0-0af5ba924aaa)

Here's what it looks like in legacy:
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/dae8609d-f973-4c0e-ab04-4304fa6c629a)

**Comment by eliknebel** [comment]
We need some more information on what the issue is and how this should look
