### ISSUE TITLE
Trim white space in tables

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#3525]
**Is your feature request related to a problem? Please describe.**
The problem is that when adding audio clips to a table, the audio player is taking up too much space, thereby making the table much bigger than necessary.

Here is a link to a page as an example: https://proton.oli.cmu.edu/authoring/project/elementary_arabic_1_online/resource/lesson_1_greetings_vocabulary_ 

**Describe the solution you'd like**
It was reported by an author for the Arabic course to be able to manage the white space in tables better; or to be able to control the audio clip player feature to be smaller in a table.

**Comment by eliknebel** [comment]
Alternatively, users could use the "popup" element to render an audio player as a workaround
