### ISSUE TITLE
Imported superactivity out of control iframe resize

### ISSUE THREAD

**Issue by rgachuhi** [Simon-Initiative/oli-torus#3531]
**Describe the bug**
There is an issue whereby a legacy superactivity imported into Torus and delivered in a course section exhibits strange behavior when rendered on a delivery page. The iframe hosting the activity continues unbounded resizing.  

**To Reproduce**
1. Import legacy course content containing a superactivity in one of the pages
2. Create a course section and visit the page
3. Scroll down to the location of the activity
4. See if those activities' iframe continuously resizes

**Expected behavior**
The iframe hosting the activity should expand only to accommodate the height activity and no more than that. 

**Screenshots**
visit the flowing page for an example: https://tokamak.oli.cmu.edu/sections/discrete_math_primer_42923/page/n4unk_propositional_variables_and_co_cxf0d

**Comment by darrensiegel** [comment]
Fixed by https://github.com/Simon-Initiative/oli-torus/pull/3566
