### ISSUE TITLE
Some instructor-scored questions in Echo are auto-scored in Tokamak

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3537]
Essay question in Echo:
https://echo.oli.cmu.edu/#kth-s8ffaqhu-1.2/d0122cf806954b40ac9beba5c24aab13?organization=kth-s8ffaqhu-1.2_default

Same question in tokamak (KTH may have edited it; a new ingestion may be needed to confirm it's auto-scored):
https://tokamak.oli.cmu.edu/sections/kth_onelearns_4_may_2023/page/74yy1_module_test_effective_digital__n6pco

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2071
