### ISSUE TITLE
Draggable items different sizes

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3539]
very minor but draggable items should be same height. Width should adjust based on amount of text. 
https://tokamak.oli.cmu.edu/sections/gen_chem_0412_ykrj5/page/v1q9y_lattice_energy_t0144

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/4288fbd1-e2e5-4c94-9fca-7afbd070c0f6)

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2070
