### ISSUE TITLE
It would be nice to have the option to put answer choices side by side instead of just vertical

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3541]
https://tokamak.oli.cmu.edu/sections/gen_chem_0412_ykrj5/page/v1q9y_writing_lewis_structures_6xpbv

Many examples of this in the course. Even looking at this on a full screen you have to scroll up and down to see all the answer choices. 

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/8b0f4fc6-342c-4296-9c38-9c6855016c82)

If answer choices were side by side you wouldn't need to scroll or change the view of your screen. This was NOT every available in legacy as far as I know.

**Comment by eliknebel** [comment]
We would need to figure out how this would work on small form factor devices
