### ISSUE TITLE
Theorem template differs from legacy theorem structure

### ISSUE THREAD

**Issue by andersweinstein** [Simon-Initiative/oli-torus#3546]
Torus uses a "blueprint" to allow authors to insert a structured content template for a "theorem", but it differs a bit from the structure displayed for a theorem element in legacy OLI.

-It includes a heading saying "Statement".  While this is a possible design choice, Legacy does not show a heading before the Statement content. It is odd to include a "Statement" heading when there are no other optional sections to be distinguished. And it never seems necessary to label the statement content as such. Every theorem must have a statement, so this is redundant. 

- Legacy theorems also include a mandatory "type" ("axiom | corollary | hypothesis | law | lemma | principle | proposition | rule | theorem" ). If a theorem has no title, the capitalized type name is used as header in a slightly different format than a title (bold and a bit smaller). However, this could aways be handled by entering this in the theorem title field.

The statistics course apparently uses theorem tag as a way of getting certain important statements bannered in a uniform way throughout the course E.g.

**Principle**
Association **does not** imply causation!

In this example "principle" is the type, the rest is statement content, and the element has no Title, Example, or Proof.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2069
