### ISSUE TITLE
Fold the concept of "groups" into the question-creation process

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3556]
Questions in OLI courses are meant to be in a semantic container, such as Learn By Doing and Did I Get This?. Currently, Torus permits questions to be placed on the page without a semantic container. Containers are created using the "groups" feature, which is implicitly optional.

Instead, the group should be treated as a mandatory part of question creation.

This is meant as a placeholder ticket. Designs need to be developed.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2066
