### ISSUE TITLE
Author-facing descriptive field to help keep track of identically named assets 

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3561]
For consideration...

Authors need to create identically named pages (and possibly other assets) that are used in different products, or in different places in the same product (such as the way Modern Languages uses the same title for all scored assessments).

In order to differentiate them from one another, they need a human-readable unique field that would be visible in the authoring environment, and possibly could be used in analytics. That may be best served by something that serves as a guid, but having a human readable field might help also in that context. We should consult users who analyze the learning data to see if that would help.

The field would not be exposed in the delivery environment, at least not to students. It's possible that authors/researchers would find it valuable to see the unique description/label in the delivery environment, so they can have more certainty about which asset they're looking at.

I could see this being valuable in A/B testing settings, too.

**Comment by eliknebel** [comment]
Main purpose is for author facing note taking of assets

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2064
