### ISSUE TITLE
[Stats Migration]Missing values in migrated dynamic questions

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3572]
**Describe the bug**
When taking a quiz with a dynamically generated question, sometimes the values in the question and answers do not get generated correctly. 

Example 1: EDA Examining Distributions Checkpoint 2
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/675f4778-b5ea-4c20-ab0a-d68d847eba15)
Should say e.g "approximately 95%"

![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/76ebd32b-a03a-4a68-b9af-b0d408563323)

[Torus ](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_eda_examining_distributions_ch_0qxcr)
[Legacy ](https://oli.cmu.edu/jcourse/a2/rest/assessement/deliver?attempt=1&context=9b26d6950a0001dc17318d429b7f7a4b)
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.9/bcc941e4b65f40c4beea37b5bae3bd9b?organization=georgia_state_stats_master_liu-5.9_7hjyymq2)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_8-echo/content/x-oli-assessment2-pool/bcc941e4b65f40c4beea37b5bae3bd9b.xml)

This also occurs: 
EDA Examining Distributions Checkpoint 2, Question 12 
EDA Examining Distributions Checkpoint 2, Question 13
EDA Examining Relationships Checkpoint 1, Question 8
EDA Examining Relationships Checkpoint 1, EDA Examining Relationships Checkpoint 1
Introduction to Probability Checkpoint, Question 3, Third Sentence
Introduction to Probability Checkpoint, Question 4, Second Sentence
Probability Rules Checkpoint 1, Question 7:  First sentence below the table

</body>
</html>
**Environment (please complete the following information):**
 - Version: 23

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2063

**Comment by cjlim1092** [comment]
this is fixed
