### ISSUE TITLE
Allow more heading types when authoring

### ISSUE THREAD

**Issue by zmineroff** [Simon-Initiative/oli-torus#3575]
**Is your feature request related to a problem? Please describe.**
The authoring tools allow you to create H1 and H2 headings. I would also like to create H3 or H4 headings, but there is no way to do so.

**Describe the solution you'd like**
The text formatting toolbar should show H3 and H4 in addition to H1 and H2 in the heading selection dropdown.

**Describe alternatives you've considered**
I use bold formatting to simulate a "heading." this is not ideal for accessibility purposes.

**Additional context**
The H3 and H4 headings would make more sense semantically when structuring content on a page.

**Comment by eliknebel** [comment]
<img width="707" alt="Screenshot 2023-06-27 at 2 59 24 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/fbd50bc0-7b31-449b-80ce-13203fd8c6b0">
