### ISSUE TITLE
Allow updating and deleting images from the media library

### ISSUE THREAD

**Issue by zmineroff** [Simon-Initiative/oli-torus#3576]
**Is your feature request related to a problem? Please describe.**
Say I've uploaded an image and embedded it on a page and now I want to change it. There isn't a convenient way to do so, especially if the same image appears multiple times throughout the course.

**Describe the solution you'd like**
In the media library, I'd like to option to update an image by uploading a new version of it. This would replace all instances of the image in the course with the new version. I would also like to be able to delete images from the media library so that I don't have a bunch of irrelevant images around.

**Describe alternatives you've considered**
I upload a new image with something like "- 2" appended to the filename. Then I manually delete the instances of the old image on the page and re-embed the new image one-by-one. I can't delete the original image from the media library, so I have to just remember not to select the old version going forward.

**Additional context**
Add any other context or screenshots about the feature request here.  If you know of other platforms that offer this suggested functionality, please list them.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2163

**Comment by eliknebel** [comment]
Dup of https://github.com/Simon-Initiative/oli-torus/issues/3681
