### ISSUE TITLE
Organize images in media library into folders

### ISSUE THREAD

**Issue by zmineroff** [Simon-Initiative/oli-torus#3577]
**Is your feature request related to a problem? Please describe.**
The media library quickly becomes a large, unorganized mess in a course with lots of images. It takes a long time to find the right image when I want to embed something on the page.

**Describe the solution you'd like**
Add folders to the media library so I can organize them logically.

**Describe alternatives you've considered**
There isn't a great alternative.

**Additional context**
Canvas has this feature.

**Comment by eliknebel** [comment]
Perhaps media tagging & filtering as well or instead of folders
