### ISSUE TITLE
Allow more formatting options for images

### ISSUE THREAD

**Issue by zmineroff** [Simon-Initiative/oli-torus#3578]
**Is your feature request related to a problem? Please describe.**
Images are automatically centered on the page with a gray background. There is no way to change this. This causes issues with accessibility if I upload an image with a transparent background that has a similar gray on it.

**Describe the solution you'd like**
Add image formatting options that enable authors to left-align images, change the background color, and configure borders.

**Describe alternatives you've considered**
If I want to left-align something, I can add padding to the right of the image in an image editor before I upload it, but this is far from ideal.

**Additional context**
Canvas has some of these options.

**Comment by eliknebel** [comment]
We should look to canvas to see what is support there. There is likely 3 separate issues here, all related to how much we want to allow authors to style content.

Its worth noting all these options are available in the advanced/flowchart authoring
