### ISSUE TITLE
[Stats migration] Paragraph feedback loading horizontally 

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3597]
**Describe the bug**
Feedback to a question is loading horizontally, not vertically.

**Screenshots**
Tokamak
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/acb952a3-e564-438a-a6c1-af3aeea3613b)
Legacy
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/f96e9c20-d66c-41d1-bf63-b22ded86a2b7)

[Tokamak ](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_binomial_random_variables_chec_ipp3z)
[Tokamak Authoring](https://tokamak.oli.cmu.edu/authoring/project/gsu_elementary_statistics__mai_4appt/resource/589t9_binomial_random_variables_chec_ipp3z)
[Legacy](https://oli.cmu.edu/jcourse/assessment2/activity/view.do?context=9b26d8650a0001dc2e2fcc6562286bf5)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/x-oli-assessment2-pool/a115aef96a98407f8f231d49d1608b09.xml)
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/a115aef96a98407f8f231d49d1608b09?organization=georgia_state_stats_master_liu-5.10_lucqxmf9)

**Environment (please complete the following information):**
 - Version:23

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2149
