### ISSUE TITLE
[Stats Migration] LBD feedback reads "Content element is invalid"

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3600]
**Describe the bug**
LBD feedback reads "Content element is invalid." Legacy feedback doesn't seem to be working either, as it gives dropdown options for formatting but no actual feedback.

**Screenshots**
Example 1: Applications (2 of 3) | Learn by doing | Normal Random Variables

<img width="870" alt="Screen Shot 2023-06-01 at 9 50 07 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/c6e60f3f-63d5-4de4-a03c-1b87eac713bf">

<img width="868" alt="Screen Shot 2023-06-01 at 9 51 13 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/bec78427-854e-4803-ae76-e21284e8e437">

**Environment:** Version 23

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_normal_random_variables_rse59)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d8aa0a0001dc32c9633566ff4ad5)
Echo
SVN

**Other Occurrences:**
Binomial Random Variables (3 of 4) | Learn by doing | Binomial Random Variables
Hypothesis Test for a Population Mean (4 of 5) | LBD | Hypothesis Testing for the Population Mean
Hypothesis Test for a Population Mean (4 of 5) | LBD | Matched Pairs
Hypothesis Test for a Population Proportion (3 of 3) |LBD |Hypothesis Testing for the Population Proportion

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/_u4_m3_lbd10?organization=georgia_state_stats_master_liu-5.10_lucqxmf9)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m3_random_variables/x-oli-inline-assessment/u3_m3_normal8_lbd_tutor1.xml)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2148
