### ISSUE TITLE
[Stats Migration] Extra grayed-out input field above multiple choice answers.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3601]
**Describe the bug**
Extra grayed-out input field above multiple choice answers.

**Screenshots**
Example 1: Behavior of Sample Mean (1 of 3) LBD
<img width="869" alt="Screen Shot 2023-06-01 at 10 21 20 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/106618ff-6007-4086-8ec2-cd50797d55c3">

<img width="875" alt="Screen Shot 2023-06-01 at 10 21 09 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/fd3d8acd-0d14-439d-85d5-5d2e2e68d114">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_behavior_of_sample_mean_1_of_3_zfpi1)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d8e90a0001dc0d809e54cf0921be)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Behavior of Sample Mean (3 of 3)
Behavior of Sample Proportion (2 of 3)
Estimating a Population Mean (1 of 3) | Connection between Confidence Intervals and Sampling Distributions
Non-Credit Test 3 Review
Test 3 Review
Wrap-Up (Random Variables) | Normal Random Variables Checkpoint 2

Binomial Random Variables (4 of 4) | Binomial Random Variables Checkpoint (Slightly different; input boxes for n and p that should be functional are grayed out.)

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/u3_m4_mean1_tutor1ps?organization=georgia_state_stats_master_liu-5.10_7hjyymq2)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m4_sampling_distributions/x-oli-inline-assessment/u3_m4_mean1_tutor1ps.xml)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2147

**Comment by eliknebel** [comment]
Could not reproduce in latest digest

**Comment by cjlim1092** [comment]
Can someone help me identify if this is a manual fix? 
[XML ](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m3_random_variables/x-oli-assessment2-pool/dist_binary_case_pool.xml)
[Echo ](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/dist_binary_case_pool?organization=georgia_state_stats_master_liu-5.10_lucqxmf9)is unable to open the pool
[Tokamak
](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_binomial_random_variables_chec_a0kz7) (If that doesn't work use [this](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_binomial_random_variables_4_of_adpb4))
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/90c40138-e8c8-49aa-9d46-2efae480b2d1)

[Legacy](https://oli.cmu.edu/jcourse/assessment2/activity/view.do?context=92d820760a0001dc317e5b3af5de1a07)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/f9f84bf0-a206-450b-b3d6-49b466e65bff)
