### ISSUE TITLE
[Stats Migration] Links in feedback/hints aren't working.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3602]
**Describe the bug**
Links in feedback/hints aren't working. They should be linking to images, but in Torus they lead to URL about:blank#blocked

**Screenshots**
Example 1: Behavior of Sample Mean (2 of 3)
<img width="817" alt="Screen Shot 2023-06-01 at 10 44 35 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/736d2f15-fa52-4269-b574-413833e0f11f">
<img width="869" alt="Screen Shot 2023-06-01 at 10 44 46 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/d90ffaef-3ad6-4ba9-92a8-d2cc96e47928">

Image that link should lead to:
<img width="748" alt="Screen Shot 2023-06-01 at 10 44 53 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/67664e4b-a512-4386-ba6c-f28004e0fc81">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_behavior_of_sample_mean_2_of_3_vt78m)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d8ea0a0001dc2bd1e1279c26ee7c)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Behavior of Sample Mean (3 of 3)
Behavior of Sample Proportion (2 of 3)
Case C→C (2 of 2)
Hypothesis Test for a Population Mean (4 of 5) | LBD | Matched Pairs
Hypothesis Test for a Population Proportion (2 of 3)
Introduction to Normal Random Variables (2 of 3)
Probability Rules (3 of 11)
Probability Rules (4 of 11)
Probability Rules (7 of 11)
Probability Rules (8 of 11)
Probability Rules (9 of 11)

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/u3_m4_mean2_tutor1_1?organization=georgia_state_stats_master_liu-5.10_7hjyymq2&questionId=q2)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m4_sampling_distributions/x-oli-inline-assessment/u3_m4_mean2_tutor1_1.xml)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1969
