### ISSUE TITLE
[Stats Migration] Feedback reads "migrated". 

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3605]
**Describe the bug**
Feedback says "migrated," change this to better feedback.

**Screenshots**
<img width="801" alt="Screen Shot 2023-06-01 at 11 43 43 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/e90226b3-12dd-49d4-b55b-f35002832104">
<img width="852" alt="Screen Shot 2023-06-01 at 11 42 15 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/3060ad71-4073-417d-b4e5-59bc37686d56">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_estimating_a_population_mean_1_j354f)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d9240a0001dc5481750bc566efd2)
Echo
SVN

**Environment:** Version 23

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/m10_est_pop_means_1?organization=georgia_state_stats_master_liu-5.10_7hjyymq2) 
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/m10_inference_mean/topic_10_2/x-oli-workbook_page/m10_est_pop_means_1.xml)

**Comment by eliknebel** [comment]
There are 2 types of explanations in legacy, perhaps the course digest isnt handling one of them

**Comment by eliknebel** [comment]
This could be an issue in chemistry as well
