### ISSUE TITLE
[Stats Migration] Math equation parsing <p> as <mover>, this happens in part of the page but not the whole page.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3606]
**Describe the bug**
Math equation parsing < p > as < mover >, this happens in part of the page but not the whole page.

**Screenshots**
<img width="875" alt="Screen Shot 2023-06-01 at 12 08 25 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/6df55d44-9cfb-4147-8af7-c6417d0cd721">
<img width="851" alt="Screen Shot 2023-06-01 at 12 10 12 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/1c2b52d0-9bdb-4ff9-bf46-4a73c2bcbe7a">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_estimating_a_population_propor_sxlil)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d9040a0001dc3f78c5c9cce9d5df)
Echo
SVN

**Environment:** Version 23

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/m8_est_populaton_proportion_1?organization=georgia_state_stats_master_liu-5.10_7hjyymq2) 
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/m8_inference_one_proportion/topic_8_1/x-oli-workbook_page/m8_est_populaton_proportion_1.xml)

**Comment by andersweinstein** [comment]
Source for these are MathML. `<mover>` is a mathML element to put an accent over something else. Torus uses a newer version of MathJax than legacy. I believe MathJax rendering is translating the MathML to TeX; it looks like this version of MathJax is having some problem handling the mover tag in these MathML equations and it is coming into the Tex as an unrecognized macro.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2145
