### ISSUE TITLE
[Stats Migration] Questions 6 and 9 on this page migrated with extra spaces in the responses.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3607]
**Describe the bug**
Questions 6 ("Do you have a long-lasting...") and 9 ("Do you consider yourself...") have extra spaces in some of the responses.

**Screenshots**
Page: Excel Statistics Packages
<img width="797" alt="Screen Shot 2023-06-01 at 12 15 49 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/b3e388fb-2cb3-4858-b385-6484860e21bf">
<img width="801" alt="Screen Shot 2023-06-01 at 12 15 57 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/e7a66370-ca05-4118-aba0-31f55f6a323f">
<img width="858" alt="Screen Shot 2023-06-01 at 12 16 31 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/88b0df63-6c01-4e65-9d4f-8998550fa75d">
<img width="860" alt="Screen Shot 2023-06-01 at 12 16 40 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/34c40b7e-33e2-44cc-85f6-92e5cefac8e6">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_excel_statistics_packages_fwoaj)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d5b90a0001dc13042346614c8cda)
Echo
SVN

**Environment:** Version 23

**Comment by cjlim1092** [comment]
[Echo](https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/ls_demographicb6ae3aff6d3d4d0a95cbd24b6f06b746?organization=georgia_state_stats_master_liu-5.10_7hjyymq2) 
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/x-oli-inline-assessment/ls_demographicb6ae3aff6d3d4d0a95cbd24b6f06b746.xml)

**Comment by eliknebel** [comment]
Note this content was within a survey

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2144
