### ISSUE TITLE
Broken link on https://simon-initiative.github.io/oli-torus/developer.html page

### ISSUE THREAD

**Issue by Ringenberg** [Simon-Initiative/oli-torus#3611]
**Describe the bug**
The link to the LTI-1.3 configuration on https://simon-initiative.github.io/oli-torus/developer.html points to https://github.com/Simon-Initiative/oli-torus/wiki/Torus-LTI-1.3-Manual-Configuration which does not exist and it looks like it should be https://github.com/Simon-Initiative/oli-torus/wiki/Torus-LTI-1.3-Configuration

**To Reproduce**
1. Go to 'https://simon-initiative.github.io/oli-torus/developer.html'
1. Scroll down to 'bottom'
1. Click on link near bottom labeled '[Torus LTI 1.3 Manual Configuration](https://github.com/Simon-Initiative/oli-torus/wiki/Torus-LTI-1.3-Manual-Configuration).'
5. See author new page form.

**Expected behavior**
To see documentation about LTI configuration.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: current online (02-June-2023)

**Comment by eliknebel** [comment]
Fixed by #3612
