### ISSUE TITLE
UX/UI Dark Mode Readability Issues (received by oli-help)

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#3629]
On 2023-06-02 13:02:07.184445+00:00 UTC UTC, Michael Ringenberg < mringenb@andrew.cmu.edu > wrote:

I happen to have dark mode enabled and am finding that some of the content is hard to read. In particular: the "Alternatives" editing page, the list box with the alternative and its options have a light background and a light text color (colors are slightly different, but not enough contrast).

On windows 11 with Settings>Personalization>Colors>Mode = Dark, using chrome.

----------------------------------------------
Timestamp: 2023-06-02 13:02:07.184445+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/authoring/project/ringenberg_demo

WEB BROWSER
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by kwahlenmayer** [comment]
I confirmed this issue.

Without Windows Dark Mode - text visible
https://github.com/Simon-Initiative/oli-torus/assets/24357828/f516f6c9-60f1-4fdc-854d-aef6546c7867

With Windows Dark Mode - text disappears
https://github.com/Simon-Initiative/oli-torus/assets/24357828/2d79d536-1182-4c51-89b3-98a4fe1a051b

Recreate by going to this link and turning on Windows Dark Mode:
https://proton.oli.cmu.edu/authoring/project/ringenberg_demo/alternatives

**Comment by normanbier** [comment]
I don't know if this should be filed under this ticket or if it should be pulled out into a distinct ticket: one of the issues that's showing up in dark mode is around text areas and text boxes -- the form fields are white, and the text that students write into those form fields is also white, so it's not readable.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2138

**Comment by kwahlenmayer** [comment]
Adding a new report from a student:

On dark mode, the text for the drag and drop buttons is changed to white like everything else, but as the “buttons” that you are dragging are light yellow, it makes it near impossible to read the text on them.


----------------------------------------------
Timestamp: 2023-10-04 22:21:56.646846+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/sections/chem_001a_020_23f__general_che/page/vwx8a_dimensional_analysis_multistep_h5ud3


WEB BROWSER
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Accept: */*
Language: en-US,en;q=0.9
