### ISSUE TITLE
Tech Support Form Does Not Allow Additional Submissions without Page Refresh

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#3631]
[Michael Ringenberg](https://olihelp.freshdesk.com/a/contacts/32006031141) reported via the portal
4 days ago (Fri, 2 Jun 2023 at 9:08 AM)
 
On 2023-06-02 13:08:29.180744+00:00 UTC UTC, Michael Ringenberg < mringenb@andrew.cmu.edu > wrote:

Tech support form is acting oddly. After submitting my previous submission, the successful submission modal popped up with the action buttons of "Cancel" and "Send Request" with the content stating that submission was successful. However, the "Send Request" button would only pop up a new success modal with no way of entering a new issue. I had to reload the page before I was able to submit this issue.

----------------------------------------------
Timestamp: 2023-06-02 13:08:29.180744+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/authoring/project/ringenberg_demo

**Comment by eliknebel** [comment]
Fixed by #3626
