### ISSUE TITLE
UX/UI Improvements to Project Overview Page

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#3633]
[Michael Ringenberg](https://olihelp.freshdesk.com/a/contacts/32006031141) reported via the portal
4 days ago (Fri, 2 Jun 2023 at 10:09 AM)
 
On 2023-06-02 14:09:30.303706+00:00 UTC UTC, Michael Ringenberg < mringenb@andrew.cmu.edu > wrote:

On the Project Overview page, I would suggest using checkboxes or toggle switches for the activity features list as using "enable" and "disable" text can be confusing as they are actions but also represent state. The potential confusion is that "enable" means that the feature is disabled and vis versa.

Additionally, with a wide display, the feature label and the action button end up with a lot of white space between them which can disrupt the perceived connection between the label and the action link.

----------------------------------------------
Timestamp: 2023-06-02 14:09:30.303706+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/authoring/project/ringenberg_demo

**Comment by kwahlenmayer** [comment]
I confirm and agree that the enable/disable toggle as well as the vast white space between the left column and right column presents friction to the user.

Replicate by going to Project Overview and scrolling down to Advanced Activities here:
https://proton.oli.cmu.edu/authoring/project/ringenberg_demo

https://github.com/Simon-Initiative/oli-torus/assets/24357828/28d5c91c-a400-48cc-b7e2-31be614bfdf9

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2137
