### ISSUE TITLE
[Tokamak] Course Details Direct Delivery Curriculum management duplicated

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3637]
**Describe the bug**
When editing course details, the options are duplicated on curriculum management. They should only appear once. 

**To Reproduce**
1. Go to published course
2. Edit course details

**Screenshots**
Tokamak 24
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/05710101-0514-4dc4-a8bf-9e67ef8c7a57)
Proton 23 
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/0c7ebe16-07ec-4158-90c6-0885ec6f8f97)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2112

**Comment by cjlim1092** [comment]
fixed
