### ISSUE TITLE
Torus Submit and Compare uses textbox rather than textarea

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3638]
**Describe the bug**
Submit and Compare questions have a large textbox for student answer entry rather than resizable text area. Text in the textbox doesn't wrap. 

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac067f0000013121d0da37e324c7

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_matter_vxlli

**Screenshots**
Legacy on left, Torus on right

![Screenshot from 2023-06-06 15-25-30](https://github.com/Simon-Initiative/oli-torus/assets/2669407/7d143da6-f5db-4154-aac8-819fa17dec59)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2134

**Comment by marc-hughes** [comment]
@strader As far as I can tell, these should always be a textarea, and there is no way to specify them while authoring in echo, does that sound right to you?
