### ISSUE TITLE
Torus Submit and Compare "Our Answer" missing paragraph breaks between paragraphs

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3640]
**Describe the bug**
Paragraphs in Submit and Compare "Our Answer" feedback do not have any space between them - i.e. they look like a line break rather than a paragraph

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac607f00000151d59221b2de6f19

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_atomic_mass_54efq

Click "Submit" on the Submit and Compare question in the middle of the page to reveal Our Answer.

**Screenshots**
Legacy on left, Torus on right:

![Screenshot from 2023-06-06 15-41-06](https://github.com/Simon-Initiative/oli-torus/assets/2669407/184d58e2-61c2-42ea-84c1-401ec2da798f)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2132
