### ISSUE TITLE
Multi-line content presentation on legacy now presented on single line in Torus

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3642]
**Describe the bug**
Content that was presented on multiple lines on legacy is now presented on single line on Torus - i.e. paragraph/line breaks have been removed, forcing multiple lines to appear together on a single line.

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ae357f0000011f21799e9345c5f4

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_changes_in_enthalpy_8wbmp

Search the page for "Substituting" - the next two equations appear on a single line on Torus.

**Screenshots**
Legacy on left; Torus on right:

![Screenshot from 2023-06-06 15-57-49](https://github.com/Simon-Initiative/oli-torus/assets/2669407/d4978af6-7ecb-4199-b727-258893f24baf)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2130
