### ISSUE TITLE
Torus Submit and Compare questions missing "Our Answer" label

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3644]
**Describe the bug**
Submit and Compare missing the "Our Answer" label, which is helpful to indicate to students what the feedback is for this non-standard question type.

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac067f0000013121d0da37e324c7

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_matter_vxlli

On the Submit and Compare question at the bottom of the page, click to view Our Answer.

**Screenshots**
Legacy on left; Torus on right:

![Screenshot from 2023-06-06 16-03-56](https://github.com/Simon-Initiative/oli-torus/assets/2669407/8cb6ed7b-63e2-41e2-91e2-85d0063a9cf0)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2128
