### ISSUE TITLE
Torus dropdown questions missing dropdown highlight on feedback rollover

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3645]
**Describe the bug**
Torus dropdown questions are missing the dropdown highlight when the corresponding feedback is rolled over (indicates to which dropdown the feedback corresponds)

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac077f000001328f7c7e5351df23

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_classification_of_matter_0jwo4

Click on a dropdown box to get the feedback. Rollover the feedback.

**Expected behavior**
When the user rolls over the feedback box, the corresponding dropdown box is highlighted on legacy to indicate to the user to which dropdown the feedback corresponds. 

**Screenshots**
Legacy on left; Torus on right:

![Screenshot from 2023-06-06 16-12-42](https://github.com/Simon-Initiative/oli-torus/assets/2669407/20cce930-a8e3-47f2-a8a5-74f6cfa9f182)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2127
