### ISSUE TITLE
Chemistry - images in LBD on Torus much bigger than in legacy course

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3647]
**Describe the bug**
Images in LBD on Torus much bigger than in legacy course

**To Reproduce**
Legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2af697f000001232933585ff17a54

Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_molecular_polarity_and_dipole__vnuf7

First LBD on page

**Screenshots**
![Screenshot from 2023-06-06 17-14-31](https://github.com/Simon-Initiative/oli-torus/assets/2669407/9ba147ed-77d2-41a4-9c4b-e518a1eb1f7a)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2125
