### ISSUE TITLE
Torus: Definitions missing styling

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3650]
**Describe the bug**
On Torus, in a dl, the dt is no longer rendered differently than the dd, so it's not quite as clear what it is.

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac1e7f0000012e8f4764782ab61c

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_significant_figures_in_calcula_yh8q4

**Screenshots**
Legacy on left; Torus on right

![Screenshot from 2023-06-06 17-28-58](https://github.com/Simon-Initiative/oli-torus/assets/2669407/fc0d81ad-898a-4395-8308-560756bf7c06)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2122
