### ISSUE TITLE
Torus: Styling/whitespace issue with formulas

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3652]
**Describe the bug**
Torus is missing white space between formulas and paragraphs/section headers - see screenshot

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ae117f0000016ee18d62f5b101c5

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_heat_capacity_and_specific_hea_lm7xi

See formulas right before Specific Heat Capacity section

**Screenshots**
![Screenshot from 2023-06-06 17-38-41](https://github.com/Simon-Initiative/oli-torus/assets/2669407/7f2d138f-5653-4367-acbc-3a5d94095640)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2118
