### ISSUE TITLE
Chemistry course on Torus missing image

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3653]
**Describe the bug**
Missing image on the page below.

**To Reproduce**
Legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2addb7f00000112c6e4faf95665ca

Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_molecular_velocities_and_kinet_g8g7f

**Screenshots**
Legacy on left; Torus on right

![Screenshot from 2023-06-06 17-42-13](https://github.com/Simon-Initiative/oli-torus/assets/2669407/c40fa253-798e-4a34-b806-29000c043eb2)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2117

**Comment by eliknebel** [comment]
Image was being blocked by ad blocker. Loads fine on latest v24
