### ISSUE TITLE
Chemistry: Properties of Matter Quiz has "Extra Practice" prepended to it

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3655]
**Describe the bug**
Properties of Matter Quiz has "Extra Practice" prepended to it

**To Reproduce**
Legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2ac0a7f00000120914574aefaba3a

Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_module_summary_and_quiz_c5ml2

**Screenshots**
![Screenshot from 2023-06-06 17-47-17](https://github.com/Simon-Initiative/oli-torus/assets/2669407/54ff1b54-c3e4-4d72-8776-089775b211fa)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2116
