### ISSUE TITLE
QA/Review mode audits 'orphaned' activities

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#366]
Steps to reproduce:

1. Create a page and add an activity to it. 
2. Edit the activity so that it triggers one or more QA/Review warnings.
3. Delete the page. 
4. Run a QA check and you will see the warning for that resource that is now inaccessible. 

Visiting the "Publish" page at this point shows the orphaned activity as an unpublished change.

**Comment by LEDThereBeLight** [comment]
When we delete a page in the curriculum editor, mark all of the embedded activities as deleted as well.
