### ISSUE TITLE
Rename Mastery in analytics to Proficiency

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3661]
**Description of Problem:**
In instructor facing analytics, we have 'mastery' as a metric being displayed which needs to be renamed to 'proficiency'. We are currently not making any predictions or calculations about mastery and the use of the word is highly debated. 

**Solution**
Rename mastery in all screens to proficiency.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2098
