### ISSUE TITLE
[Migration Parity] Unable to navigate a course by page number

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3667]
**Describe the bug**
When a student wants to navigate to a page in Torus, they must use the contextual menu (under course content) on the side of the page or from the landing screen in home. There is no way to navigate to a page through page number. In legacy students could enter a page number where the page number was listed and it would take them to the new page in addition to the contextual sidebar menu. 

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=92d81edf0a0001dc5db18b04a083f23b)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/8124efed-b25c-4401-b68d-ce6e17749fd5)

[Tokamak (v24)
](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_measures_of_spread_2_of_5_665hh)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/fdc51cad-6c6d-439d-9bfa-1b1ed03ed230)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2160

**Comment by eliknebel** [comment]
done v24
