### ISSUE TITLE
[Stats Migration] The words "zip code" and text for the two multiple choice options are missing from the Torus version.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3670]
**Describe the bug**
The words "zip code"/"age" (depending on which pooled question is selected) and text for the two multiple choice options are missing from the Torus version of the Final Exam Review (Question 4).

**Screenshots**
<img width="1048" alt="Screen Shot 2023-06-09 at 11 03 32 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/50d69047-74a9-491f-929b-6fce26c79614">
<img width="880" alt="Screen Shot 2023-06-09 at 11 04 39 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/1b83fdf0-532c-4d4d-8aa9-7fcd8309e8ed">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_final_exam_review_bonus_point__0bgfc)
[Legacy](https://oli.cmu.edu/jcourse/assessment2/activity/view.do?context=9b26d9fd0a0001dc2b8d8fea47eed5ef)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Non-Credit Final Exam Review (Bonus Point Possible) | Non-Credit Final Exam Review (Bonus Point Possible)
Test 1 | Test 1

**Comment by eliknebel** [comment]
Dup of dynamic question issue https://eliterate.atlassian.net/browse/MER-2063
