### ISSUE TITLE
[Stats Migration] The word title appears at the beginning of the content block, but it does not appear in legacy.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3671]
**Describe the bug**
The word title appears at the beginning of the content block, but it does not appear in legacy. 

**Screenshots**
Page: Independence (1 of 2)
<img width="875" alt="Screen Shot 2023-06-09 at 11 22 43 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/6200a434-26f6-45ee-8e8c-ff9f61212c45">
<img width="861" alt="Screen Shot 2023-06-09 at 11 23 48 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/30246256-b2f5-4f97-9071-a2374cfd8b45">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_independence_1_of_2_x6zks)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d7dc0a0001dc747f3db29147604c)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Normal Approximation to the Binomial (2 of 3)
Parameters vs. Statistics
Probability Rules (11 of 11)
Probability Rules (5 of 11)
Probability Rules (8 of 11)
Probability Rules (9 of 11)

**Comment by eliknebel** [comment]
Legacy theme suppresses the title in the theme, but some previous authoring tools (echo) added a default "Title" or "Tutor". Suggested fix is in the content from echo or XML

**Comment by eliknebel** [comment]
It would be nice to add support to the course-digest tool to detect these hard coded "Title" instances and remove them
