### ISSUE TITLE
[Stats Migration] Content element type 'note' is not supported. Please contact support with issue #LOUZZFOPB4YLAWECWIDWPY

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3673]
**Describe the bug**
Content element type 'note' is not supported. Please contact support with issue #LOUZZFOPB4YLAWECWIDWPY

**Screenshots**
Page: Random Variables (1 of 2)
<img width="753" alt="Screen Shot 2023-06-09 at 11 34 40 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/b7830add-dbb7-4df4-b117-22551d74dc25">
<img width="838" alt="Screen Shot 2023-06-09 at 11 34 53 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/6da8095e-007f-4917-b669-c3cd589d83ce">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_random_variables_1_of_2_spxw2)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d7f70a0001dc6bc02863db97114f)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Sampling (1 of 2)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2161
