### ISSUE TITLE
[Stats Migration] Math objects (MathML?) have different font size/spacing than surrounding text.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3677]
**Describe the bug**
When number are coded as math objects (MathML?) they have additional spacing around them that changes the size and font, making the spacing appear off.

**Screenshots**
Page: Histogram: Shape
<img width="850" alt="Screen Shot 2023-06-12 at 12 32 28 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/a85b8b5d-3814-41e1-989b-9df463674957">
<img width="837" alt="Screen Shot 2023-06-12 at 12 33 23 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/8bf67ffc-c6ef-429a-894b-62ea255f9942">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_histogram_shape_8mkvi)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d5f80a0001dc71e8e58e884e1fd4)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Linear Relationships (3 of 8)
Linear Relationships (4 of 8)
Linear Relationships (7 of 8)
Scatterplot (1 of 5)
Scatterplot (4 of 5)
Standard Deviation (1 of 3)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2164
