### ISSUE TITLE
Can't delete images from image library

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3681]
**Describe the bug**
When uploading media to the media library, there is no way to delete old images from the image library. Currently, if I want to make a change to the existing image, I can reupload the edited image, but I must rename it from the original. I would prefer to delete the original to keep the library more neat and easily searchable. 

**To Reproduce**
1. Go to image library on page authoring
2. Try to delete or rename existing image

**Environment (please complete the following information):**
 - Version: 23

**Additional context**
From UX interviews with LEs at CMU

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2163
