### ISSUE TITLE
[Stats Migration] Link to download dataset is broken.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3682]
**Describe the bug**
Link to download dataset is broken.

**Screenshots**
Page: Hypothesis Test for a Population Mean (4 of 5) | Hypothesis Testing for the Population Mean
Clicking on link should download the associated dataset, but in Torus it leads to a separate tab that reads "Not found."
<img width="874" alt="Screen Shot 2023-06-12 at 1 10 42 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/29b35186-94f2-4602-b203-89b06cd5b360">
<img width="1280" alt="Screen Shot 2023-06-12 at 1 11 14 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/2234bf9a-77b8-4a72-8fb0-01e96acc3177">
<img width="1279" alt="Screen Shot 2023-06-12 at 1 11 38 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/bcd0cd91-04bc-4c04-8045-912646ddb9e8">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_hypothesis_testing_for_the_pop_lr9s7)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d9cb0a0001dc35f85e674b7f1883)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Exploring a Dataset
Hypothesis Test for a Population Mean (4 of 5) | Matched Pairs

**Comment by eliknebel** [comment]
fixed as of v24
