### ISSUE TITLE
[Stats Migration] Content element type 'tosumup' is not supported. Please contact support with issue #CGS9WMXWGAILSN8D9NYQHP

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3683]
**Describe the bug**
Content element type 'tosumup' is not supported. Please contact support with issue #CGS9WMXWGAILSN8D9NYQHP

**Screenshots**
Page: Introduction to Normal Random Variables (3 of 3)
<img width="870" alt="Screen Shot 2023-06-12 at 2 43 24 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/213ecdda-9b4f-4384-8c9a-6c1c3b11a73b">
<img width="854" alt="Screen Shot 2023-06-12 at 2 43 54 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/16268282-1595-4c6e-988d-fb9141ffb768">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_introduction_to_normal_random__p19rs)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d87e0a0001dc2ca006649307f88a)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:** None

**Comment by cjlim1092** [comment]
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m3_random_variables/x-oli-workbook_page/_u4_m03_normal_random_variables6.xml

**Comment by eliknebel** [comment]
Similar to https://github.com/Simon-Initiative/oli-torus/issues/3673

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2162
