### ISSUE TITLE
[Stats Migration] Feedback (reading "Thank you for your response.") missing from Torus version.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3685]
**Describe the bug**
Feedback (reading "Thank you for your response.") missing from Torus version. NOTE: Error in authoring when trying to address the issue.

**Screenshots**
Page: Learning Strategies (3 of 4)
<img width="867" alt="Screen Shot 2023-06-12 at 3 12 51 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/056a7025-bf49-43f7-9ba1-f11719a3143b">
<img width="863" alt="Screen Shot 2023-06-12 at 3 13 00 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/42197ec2-b65a-46d0-bb78-f9d80e99450b">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_learning_strategies_3_of_4_180qj)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d5a80a0001dc403e568b626f2bd4)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Learning Strategies (4 of 4)

**Comment by cjlim1092** [comment]
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u1_intro_stats_online/x-oli-workbook_page/_u01_mindset_2.xml

**Comment by eliknebel** [comment]
manual content fix
