### ISSUE TITLE
[Stats Migration] Variance equation continues off the edge of the page.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3686]
**Describe the bug**
Variance equation continues off the edge of the page. Similar to #3438.

**Screenshots**
Page: Mean and Variance of a Random Variable (4 of 6)
<img width="1069" alt="Screen Shot 2023-06-12 at 3 20 05 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/e00a0d87-560e-4b37-8671-e1e9fb2ff552">
<img width="883" alt="Screen Shot 2023-06-12 at 3 20 46 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/d8304e34-4d0a-4efa-a305-88dd4b4fc939">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_mean_and_variance_of_a_random__6wkxo)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d8250a0001dc6c85f251a89c631b)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:** None

**Comment by cjlim1092** [comment]
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m3_random_variables/x-oli-workbook_page/_u4_m03_mean_variance4.xml

**Comment by eliknebel** [comment]
Dup of https://github.com/Simon-Initiative/oli-torus/issues/3641
