### ISSUE TITLE
[Stats Migration] Original boxes greyed out. System generated new box for text entry.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3687]
**Describe the bug**
Original boxes greyed out. System generated new box for text entry.

**Screenshots**
Page: Normal Random Variables Checkpoint 2
<img width="884" alt="Screen Shot 2023-06-12 at 3 25 22 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/7f1eab39-0c5a-4d8b-a1db-6c5350ec5d2f">
<img width="874" alt="Screen Shot 2023-06-12 at 3 25 53 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/84a255e8-ea3c-4b34-9279-afdd437d4a51">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_normal_random_variables_checkp_d1t3m)
[Legacy](https://oli.cmu.edu/jcourse/a2/rest/assessement/deliver?context=9b26d8bf0a0001dc5cebfa99355b4231&attempt=1)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Test 3 Review Questions 12, 15

**Comment by cjlim1092** [comment]
SVN https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m3_random_variables/x-oli-assessment2-pool/interp_zscore_pool.xml

**Comment by eliknebel** [comment]
Dup of https://github.com/Simon-Initiative/oli-torus/issues/3601
