### ISSUE TITLE
[Stats Migration] Large spaces between each dropdown are present before answering the question.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3688]
**Describe the bug**
Large spaces between each dropdown are present before answering the question. These are there for the reset button and feedback, but are not necessary until the question has been answered. 

**Screenshots**
Page: Probability Rules (3 of 11)
<img width="871" alt="Screen Shot 2023-06-12 at 3 37 06 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/9aefffd8-ed10-448f-a123-ccd4be841f44">
<img width="871" alt="Screen Shot 2023-06-12 at 3 37 32 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/579f74e2-a8c1-409a-b1ea-a84de2293c4e">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_probability_rules_3_of_11_w9wqc)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d76e0a0001dc726813f89ab52d6f)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Probability Rules (5 of 11)

**Comment by cjlim1092** [comment]
SVN https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m1_finding_probability/x-oli-workbook_page/_u4_m01_probability_rules3.xml
