### ISSUE TITLE
[Stats Migration] Some bolded words are also italicized in Torus.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3689]
**Describe the bug**
Some bolded words are also italicized in Torus / some words that should be italicized are instead bolded.

**Screenshots**
Page: Probability Rules (8 of 11)
<img width="836" alt="Screen Shot 2023-06-12 at 4 12 02 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/b87c90b0-50cf-412c-a54a-24a7135086c7">
<img width="734" alt="Screen Shot 2023-06-12 at 4 12 15 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/7f1c85f0-158b-4ff5-808f-696444686b78">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_probability_rules_8_of_11_mkxo4)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d7750a0001dc607841151b7e5c4e)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
Standard Deviation (1 of 3)

**Comment by cjlim1092** [comment]
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u4_probability/_m1_finding_probability/x-oli-workbook_page/_u4_m01_probability_rules8.xml

**Comment by eliknebel** [comment]
SVN content issue
