### ISSUE TITLE
[Stats Migration] Question and Answer headers are missing from Torus.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3690]
**Describe the bug**
Question and Answer headers are missing from Torus.

**Screenshots**
Page: Standard Deviation (3 of 3)
<img width="884" alt="Screen Shot 2023-06-12 at 4 18 20 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/6e08c225-346b-438a-93f5-959c2ad06c4f">
<img width="867" alt="Screen Shot 2023-06-12 at 4 18 27 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/95518349-645d-4404-b2a9-170d47e1d62e">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_stats_main_campus_spring_2/page/589t9_standard_deviation_3_of_3_ncjat)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d6780a0001dc07f516b735ea4f17)
Echo
SVN

**Environment:** Version 23

**Other Occurrences:**
The Role-Type Classification (1 of 2) | Overview

**Comment by cjlim1092** [comment]
Echo: https://echo.oli.cmu.edu/#georgia_state_stats_master_liu-5.10/deviation3?organization=georgia_state_stats_master_liu-5.10_7hjyymq2
SVN: https://svn.oli.cmu.edu/svn/content/statistics/adaptations/georgia_state_stats/adaptations/georgia_state_stats_master_liu/branches/v_5_10-echo/content/_u2_summarizing_data/_m1_examining_distributions/x-oli-workbook_page/deviation3.xml

**Comment by cjlim1092** [comment]
Please make a jira ticket for this one.
