### ISSUE TITLE
[Stats Migration] Dataset link in Torus leads to legacy course.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3693]
**Describe the bug**
Dataset link leads to legacy course. However, from both Legacy and Torus I land on a Not Authorized page. 

**Screenshots**
Page: Measures of Center (1 of 2)
<img width="1280" alt="Screen Shot 2023-06-12 at 4 39 04 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/2f5f8af0-b6c3-4f1e-8810-834b39312957">
<img width="923" alt="Screen Shot 2023-06-12 at 4 39 12 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/eb740801-9dfa-4150-804b-969b0b41af3a">
<img width="1064" alt="Screen Shot 2023-06-12 at 4 39 21 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/fa802828-ba3e-455c-ae12-c9afc0aac198">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_measures_of_center_1_of_2_zpozi)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d62a0a0001dc08a07f55402e8e72)
Echo
SVN

**Environment:** Version 23

**Comment by cjlim1092** [comment]
This was a manual fix, please close this issue
