### ISSUE TITLE
[Stats Migration] Demographics survey completely missing from Torus version.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3694]
**Describe the bug**
Demographics survey completely missing from Torus version. Content Missing: Demographics survey. 10 questions . (In echo the activity type is Is_demographic).

**Screenshots**
Page: Excel Statistics Packages
<img width="917" alt="Screen Shot 2023-06-12 at 4 42 43 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/7f76d971-8ad7-4909-a921-98d651b45a6a">
<img width="1036" alt="Screen Shot 2023-06-12 at 4 42 51 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/693cc77d-29f6-4565-887a-22e2863b3acd">

[Torus](https://tokamak.oli.cmu.edu/sections/gsu_statistics_0308/page/3ch7w_excel_statistics_packages_4b2xj)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9b26d5b90a0001dc13042346614c8cda)
Echo
SVN

**Environment:** Version 23

**Comment by cjlim1092** [comment]
This has been fixed, please close this ticket
