### ISSUE TITLE
[Migration]: Page shows Internal Server Error on opening

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3698]
Page shows "Internal Server Error" on opening in Tokamak Student view (PC Software Migration). 

Page on Legacy: 
![Screenshot 2023-06-13 at 11-03-49 Metacognitive Skills](https://github.com/Simon-Initiative/oli-torus/assets/20156664/9bd7540a-4b96-47dd-b5cf-9b5f23d1f140)

Page on Tokamak: 
![metacog-skills-Torus](https://github.com/Simon-Initiative/oli-torus/assets/20156664/d6636533-dbdf-48e4-9e52-f1977b363331)

Course on Tokamak: https://tokamak.oli.cmu.edu/sections/hcc_pc_software_demo/instructor_dashboard/manage 

Course on Legacy: https://oli.cmu.edu/jcourse/lms/instructors/syllabus.do?section=029ffdf50a0001dc6ab7089379150a4b

**Comment by tanvidomadia** [comment]
Echo link: https://echo.oli.cmu.edu/#pc-software-1.3?organization=pc-software-1.3_default

**Comment by eliknebel** [comment]
Can we narrow down where the issue is occurring? This could be cause by flash elements or citations

**Comment by cjlim1092** [comment]
Related: https://github.com/Simon-Initiative/oli-torus/issues/3424

**Comment by tanvidomadia** [comment]
**Steps to Reproduce**
1. Log into tokamak.oli.cmu.edu as a student
2. Enroll into the course: https://tokamak.oli.cmu.edu/sections/join/8s493 
3. Go to the Page "Metacognitive Skills" on Unit 1 (page link can be found on homepage) 
4. See error 

![tokamak-migration-error1](https://github.com/Simon-Initiative/oli-torus/assets/20156664/9e0889d5-32d4-4a96-9ab9-0f75f765f1ba)

**Links**
1. [Tokamak Authoring Project](https://tokamak.oli.cmu.edu/authoring/project/pc_software_0t8y6/overview) 
2. [Tokamak Authoring Page](https://tokamak.oli.cmu.edu/authoring/project/pc_software_0t8y6/resource/wom3i_metacognitive_skills_uuu4g)
3. [Tokamak Instructor View](https://tokamak.oli.cmu.edu/sections/hcc_pc_software_demo/preview/page/wom3i_metacognitive_skills_uuu4g)
4. [SVN Repo](https://svn.oli.cmu.edu/svn/content/personal_computer/pc_software/branches/v_1_3-echo)
5. [Page on Echo](https://echo.oli.cmu.edu/#pc-software-1.3/_u01_m01_metacog_4?organization=pc-software-1.3_default)

**Other Details**
On talking to the instructor, he mentioned that there is no flash element on this page.
