### ISSUE TITLE
Style Edgecase: Pagename and arrow overflow from the previous page/nextpage box

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3700]
**Describe the bug**
When a page name is long, on tokamak the arrow and sometimes the words will overflow from the previous and next button containers. This gives an unfinished look.
[Example page](https://tokamak.oli.cmu.edu/sections/gsu_stats_510_review/page/86shw_introduction_to_normal_random__25hbl)

**Screenshots**
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/65c31f03-881c-4736-8f71-08c282671368)

**Environment (please complete the following information):**
 - Version:24

**Additional context**

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2185

**Comment by eliknebel** [comment]
fixed v24
