### ISSUE TITLE
Publishing Visibility's institution list needs to be differentiated

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3703]
Project > publishing visibility > restricted > institution > search

This feature permits you to add multiple institutions with identical names. There is nothing to differentiate them. This would be BEST handled at the institutional level by permitting only unique names, but if we permit identical names, we need to know which one is which. See screenshot.
![Screenshot 2023-06-15 at 11 50 24 AM](https://github.com/Simon-Initiative/oli-torus/assets/24977416/3ecfa0f5-a5ca-4d2f-8a14-0541dbf2d203)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1992

**Comment by eliknebel** [comment]
done v24
