### ISSUE TITLE
Image coding question no longer scores properly in scored pages

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3708]
KTH report.

> > Emergency: Image coding does not work anymore
> Dear Hal,
> We are in a pickle. The preparatory programming course uses these types of problems frequently:
> 
> They seem to work as formative questions, but when in a summative test, they report correct answers as faulty.
> 
> Do you have any time available today so that I can show you? I have a master’s thesis presentation at 15-16:15 (9:15-10:15 EDT), but am otherwise free.
> 
> These test have been working properly for several years, so I suspect something with some update of the Torus system has affected them.
> 

NEXT EMAIL

> Less urgent, but still an issue. Ramtin came up with the ingenious solution to make the summative pages formative instead, so we are not in a pickle any longer.
> But we need to discuss this in our next 
<img width="480" alt="PastedGraphic-1" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/f23d0fb2-8fcd-4213-9801-41e524f36e9e">
meeting.

**Comment by andersweinstein** [comment]
Reproduced on proton and tokomak. Just create a graded page with an image-coding problem on it.  For a minimal test, you can create a text-output problem to print the word "foo", set the starter code to `print('foo')` and set the answer regex to `foo`. Need to create a section to test graded page behavior.

This could have something to do with Submit-handling logic in graded page contexts for the somewhat specialized case of image coding activities.

**Comment by eliknebel** [comment]
There appears to be a workaround, can this wait to be fixed until after v24?

**Comment by eliknebel** [comment]
fixed v24
