### ISSUE TITLE
Deleted page still linked in LOs

### ISSUE THREAD

**Issue by drva** [Simon-Initiative/oli-torus#3709]
**Describe the bug**
Deleted pages still being linked from the LOs, producing a Not Found when clicked. 

**Expected behavior**
Deleted pages should not be linked from LOs as this is confusing. Potentially when deleting user should get an alert that this page was linked to LOs?

**Screenshots**
<img width="1231" alt="23-6-5DeletedActivityStillLinkedinLO1" src="https://github.com/Simon-Initiative/oli-torus/assets/23661836/178a6af5-817c-4963-acae-439a201588a2">
<img width="1331" alt="23-6-15DeletedActivityStillLinkedinLO2" src="https://github.com/Simon-Initiative/oli-torus/assets/23661836/7e301c29-2754-48cd-a024-20397c1ea4a3">
<img width="507" alt="23-6-15DeletedActivityStillLinkedinLO2(DeletePopup)" src="https://github.com/Simon-Initiative/oli-torus/assets/23661836/cde58240-9503-4064-9dc9-e7db70d870ac">

**Environment (please complete the following information):**
 - OS: macOS 11.6.7
 - Browser: Safari
 - Version: 15.5

**Comment by eliknebel** [comment]
We need some more information here, what course this is occurring in, torus version, etc.

**Comment by drva** [comment]
Course - Project ID: learn_lab_summer_school_2023_l
Torus version: Version 0.23.2 (5A13483) 05/09/2023
