### ISSUE TITLE
UX/UI of the Audio Upload Window

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#3710]
Click Add Audio to view the Audio Settings Window

Notes on Audio Settings Window (uploading or viewing or selecting uploaded audio files):

1. After choosing list view, the view resets to grid view the next time instead of remembering my selection.

3. In grid view (the default view), while 12-18 files are listed, the names are so large that only the first 10 characters are viewable despite changing my zoom settings. In the case of 100s of audio clips, if several start with the same text, it is impossible to distinguish them until you click on one after which if you cancel, the window closes so if you are guessing which is the right file, you can't click to view them one at a time without re-opening the audio window. 
(Example: Beginning Spanish 1 has 99 audio files in just a few pages of content so far and 83 of them begin with pronunciation.)

4. In list view, I cannot scroll (by mouse) and the vertical scrollbar is missing so I can only see about 8-10 files. 

https://github.com/Simon-Initiative/oli-torus/assets/24357828/2c2f9d79-bb0e-4268-a151-ce4fb9ea8ebb
https://github.com/Simon-Initiative/oli-torus/assets/24357828/7c2bd8e4-240f-4410-9735-95f5b53ece4a

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2195
