### ISSUE TITLE
Assessment Settings is missing the breadcrumb trail

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3714]
**Describe the bug**
The Assessment Settings page is missing the breadcrumb navigation -- once you get into the page, you are stuck there.

**To Reproduce**
Enter a section from the admin or instructor interface, select Assessment Options

**Expected behavior**
Page should contain the breadcrumb trail that is standard on other parts of the ui (see attached screenshots

**Screenshots**
Two screenshots, one showing bread crumbs trail in Schedule interface (desired) one showing missing trail in Assessment Settings.

<img width="741" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/e1ecd102-eeef-4221-9c3a-6e981f51218e">
<img width="963" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/634e0a08-30f4-4f7e-a20e-a4e07882b0c1">

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2171

**Comment by eliknebel** [comment]
fixed v24
