### ISSUE TITLE
Soft Schedule not always showing week #/dates in header

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3715]
**Describe the bug**
The soft scheduling interface sometimes does not show the week # / dates in the top row of the table.

**To Reproduce**
Go to https://stellarator.oli.cmu.edu/sections/bier_spain_cuisine_test_schedu/schedule

**Expected behavior**
Should see week numbers and dates to identify columns at the top of the table. Compare screenshots below

**Screenshots**
Problematic example (from https://stellarator.oli.cmu.edu/sections/bier_spain_cuisine_test_schedu/schedule)
<img width="1462" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/4ad743b5-f9c4-413b-befa-766fac41d897">

Expected behavior (from https://stellarator.oli.cmu.edu/sections/tools_for_online_learning_migr/schedule)
<img width="1402" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/fe6462f5-5af4-4c03-9a98-bb7526f36a44">

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2193
