### ISSUE TITLE
Unit #s in Soft Scheduling May be Confusing Without Label

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3716]
**Is your feature request related to a problem? Please describe.**
Soft schedule currently just uses numbers for units/modules rather than labeling as Unit 1 or Module 13.  This is not always obvious but may be ok for well titled units/modules.  However, when the titles end in numbers, you end up with a double number listing that is confusing ie Week 1 1 -- this is exacerbated by using the same font, spacing etc.

**Describe the solution you'd like**
Some way to visually distinguish the unit/module identifier from the title, even when the title ends in a number.  Combination of using the label (unit/module/chapter/etc) and styling (new font, size, bold, etc)

**Describe alternatives you've considered**

**Additional context**
This example from: https://stellarator.oli.cmu.edu/sections/tools_for_online_learning_migr/schedule  demonstrates the problem
<img width="1062" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/6ee22003-6068-47d7-8e06-03669acfcd07">

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2189
