### ISSUE TITLE
Submit late "with approval" option in assessment settings

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3717]
**Is your feature request related to a problem? Please describe.**
Currently the assessment options for late submit allow only Allow/Disallow.  

In legacy, and in some other systems, there is the ability to allow late submits with approval -- essentially, all students are allowed to submit late, but the late submission needs to be "accepted" or approved by the instructor before the grade is applied to the grade book. This allows for late submits and granting of accessions without needing to preemptively hear from every student asking for an exception and then grant one.  

We need additional discussion and user research on how to correctly implement this -- do we need additional settings for how long you can late submit w/ approval? How does the approve/disapprove interface work? Do we retain disapproved info for the research logs? etc....

**Comment by normanbier** [comment]
In reviewing again, I think this is accommodated in the FDD (https://docs.google.com/document/d/1h9uMO_OGrVj6Ec8nwSnuwhdgWd3ZTRbppia4lC02uls/edit#heading=h.hkg47830zewu) by the ability to "let instructor review late submissions and change grades"? But needs to be reviewed

**Comment by normanbier** [comment]
This feels like it should have been available after https://eliterate.atlassian.net/browse/MER-2002 in PR3, but the autosubmit and requires approval don't seem to be there. Wondering if there was an issue with this PR?

**Comment by darrensiegel** [comment]
Auto submit is implemented. I believe what is missing is the surfacing of late submissions to the instructor (e.g. highlighting late subs missions in red in the gradebook).

**Comment by normanbier** [comment]
> Auto submit is implemented. I believe what is missing is the surfacing of late submissions to the instructor (e.g. highlighting late subs missions in red in the gradebook).

I think I was misreading the PR3 text -- "requires approval" is a flag, not an option in the UI.

Further testing suggests that this does seem to be working correctly for core pages; there's still some questions about adaptive pages that we need to dig into (https://eliterate.atlassian.net/browse/MER-2178?filter=10067) 

This ticket can be closed
