### ISSUE TITLE
URL having a header called X-Frame-Options with the value "sameorigin" causes LTI failure for KTH

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3718]
We are currently working on a new "Micro" LMS along with KTH, and we previously integrated it with Torus using LTI 1.3 without any issues. However, after updating Torus to the latest version (oli-0.23.1-a3c785b), we encountered the following problem:

The issue is related to the URL having a header called X-Frame-Options with the value "sameorigin." This value indicates that the page can only be embedded in an iframe if the requesting site has the same origin (domain, protocol, and port) as the page being embedded.

I have also recreated the problem and collected the following logs for your reference, and also added the full log.txt:

Log entries:
Jun 15 11:3
[log.txt](https://github.com/Simon-Initiative/oli-torus/files/11771304/log.txt)
![image_720-1](https://github.com/Simon-Initiative/oli-torus/assets/24977416/d924d9d3-0ca1-4c53-8857-c24bf67c16e3)
![image_720](https://github.com/Simon-Initiative/oli-torus/assets/24977416/22d94258-5ddf-4491-9aa5-0b91cea8d9a2)
3:27 ip-172-31-41-33.eu-west-1.compute.internal oli[30573]: 11:33:27.678 [error] GenServer #PID<0.27722.3> terminating
Jun 15 11:33:27 ip-172-31-41-33.eu-west-1.compute.internal oli[30573]: ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{base_project_id: 155, context_id: "987988df-127f-402c-b515-562b6a580f8d", customizations: #Ecto.Changeset<action: :insert, changes: %{module: "Module", section: "Section", unit: "Unit"}, errors: [], data: #Oli.Branding.CustomLabels<>, valid?: true>, institution_id: 20, lti_1p3_deployment_id: 23}, errors: [title: {"can't be blank", [validation: :required]}], data: #Oli.Delivery.Sections.Section<>, valid?: false>}
Jun 15 11:33:27 ip-172-31-41-33.eu-west-1.compute.internal oli[30573]: (oli 0.23.1) lib/oli/delivery.ex:116: anonymous fn/6 in Oli.Delivery.create_from_publication/6
Jun 15 11:33:27 ip-172-31-41-33.eu-west-1.compute.internal oli[30573]: (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Jun 15 11:33:27 ip-172-31-41-33.eu-west-1.compute.internal oli[30573]: (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
We kindly request your assistance in resolving this issue. It would be great if you could provide any suggestions.

Thank you in advance!

Best regards,
Ramtin

**Comment by eliknebel** [comment]
Need to ensure the CORS settings in the mirco LMS are correct, since torus works correctly with other common LMSs (e.g. canvas, blackboard, etc...)
