### ISSUE TITLE
PartyScience and SPARC 2.0 Objectives page repeatedly reloading

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#3720]
**Describe the bug**
PartyScience and SPARC 2.0 Objectives page is repeatedly reloading, making it impossible to read sub-objectives and other info. I can click on the objective to expand it, but because of the reload it closes almost immediately. This occurs in Chrome, Chrome incognito, and Safari. It doesn't seem to be happening in other courses.

**Screenshots** 
<img width="1280" alt="Screen Shot 2023-06-16 at 1 23 07 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/b6b64c21-d28a-4630-855a-4b9e0bdfc96b">

https://proton.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/objectives

**Environment (please complete the following information):**
MacOS, Chrome and Safari

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2192

**Comment by cjlim1092** [comment]
This is[ the copy ](https://stellarator.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/overview)from the proton database on stellarator. Does this need a fresh ingestion?

**Comment by eliknebel** [comment]
We believe this issue was already fixed by https://github.com/Simon-Initiative/oli-torus/pull/3571 in torus but has not yet been deployed to proton. Fixed. Stellarator should have the fix so if we upload it there we can verify it is fixed.
