### ISSUE TITLE
Admin Tool - View Projects for a Given Author

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#3721]
While I can see the number of projects for a given authoring account, I cannot click on the projects to see what they are, nor can I search an email address under projects to find the projects for a given author. Unless an author self-identifies a project they are inquiring about or sends from the Technical Support link while signed in to their project so metadata is attached, we have to ask which project they are inquiring about. More often than you might think, support inquiries come in without specifying a project/package/course.

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2191
