### ISSUE TITLE
Submit partially completed Advanced page exercises at due date

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3723]
Activities on ASU's advanced pages only ship their scores upon full completion and intentional submission by the student. If they begin the work but don't finish by the due date, the only way to be granted partial credit is for the system to submit their unfinished work on their behalf.

I'm not sure how to treat this when Late Submissions are allowed; I supposed they should be left unsubmitted, and be listed/flagged just like any other late submission.

**Comment by eliknebel** [comment]
We have to investigate how to handle this, the solution may be short term - simply scoring as a zero (current approach) until we can come up with a better solution

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2190
