### ISSUE TITLE
In-progress scored pages can be accessed after Due Date depending on Graded Resource Policy

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3724]
Not sure if this applies only to Advanced pages, which is what ASU uses. I will test OLI's native scored page and update with my findings.

ASU reports that students can bypass the due date and submit late if they begin their attempt before the due date, and if Graded Resource Policy is set to "Allow the review of previously completed attempts."

Desired behavior:
* when reviewing previously completed attempts, Advanced and Basic scored pages should not permit work and/or submission past the due date

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2178
