### ISSUE TITLE
Command/Messaging to YouTube video not migrating correctly

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3725]
**Describe the bug**
Legacy supports command messaging to the YouTube player indicating start and end times.  Here is an example of the format:
<section>
            <title>
                Introduction to Chemistry
            </title>
            
            <body> <youtube src="FSyAehMdpyI" id="intro_chem" controls="false">
                
                
            </youtube>
                <p><command target="intro_chem" style="button" type="message">
                    <title>Introduction to Chemistry</title>
                    <message>startcuepoint=0.0;endcuepoint=84.0</message>       
                </command></p></body>
        </section>

When ingested, the tool is capturing th message correctly, but is not associating it with a target.  This leaves us with a button in Torus that doesn't do anything.

**To Reproduce**
You can see the author view of the above ingested code here: https://stellarator.oli.cmu.edu/authoring/project/general_chemistry_i_6vvab/resource/vuswd_introduction_to_chemistry_7x6w6

Screenshot below shows the button with message but no target

**Additional context**
My suspicion is that Torus doesn't yet support YouTube as a possible command target, so there's nothing for the ingestion tool to connect to. Fixing this likely requires better support for the YouTube player to pass on the start/end parameters AND being able to specify the YouTube object as a target.

We have already seen a few requests/points of confusion from Torus users who were used to providing start/end times in YouTube (I think via URL) so that capability might also be thought through as part of this issue.

**Screenshots**
<img width="1037" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/969a34ee-4e12-4d1c-9831-1f1e344f6c37">

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2188
