### ISSUE TITLE
Layout issue in question feedback - it appears that paragraphs are being laid out horizontally instead of vertically

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3733]
In question feedback with multiple paragraphs, there's something amiss with the way the feedback is formatted - see screenshots for examples. The paragraphs appear side by side horizontally rather than vertically.

Example page: https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_atomic_mass_fdt5o

![Screenshot from 2023-06-19 16-15-50](https://github.com/Simon-Initiative/oli-torus/assets/2669407/6dc1bfc1-8580-4876-ba73-c7a5c2ef5a8a)

![Screenshot from 2023-06-19 16-16-26](https://github.com/Simon-Initiative/oli-torus/assets/2669407/a19ce3bd-3fbf-412e-a9f2-375e177c6113)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2149

**Comment by eliknebel** [comment]
fixed v24
