### ISSUE TITLE
Chemistry: Two Phet simulations not loading

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3734]
The two Phet simulations on this page do not load.

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_covalent_bond_formation_pnirj

![Screenshot from 2023-06-20 10-52-05](https://github.com/Simon-Initiative/oli-torus/assets/2669407/bb3220c6-8246-4f82-a1e8-579fa28b15cc)

![Screenshot from 2023-06-20 10-51-54](https://github.com/Simon-Initiative/oli-torus/assets/2669407/3342a8f5-bffc-4ab1-a825-3431bb7706f3)

**Comment by normanbier** [comment]
Can't replicate. 
These are currently loading and able to run ok for me in Firefox right now -- wondering if this was an issue on the PhET servers?

**Comment by strader** [comment]
Checked on a different machine and they load for me there, so this may just be a browser issue on my end.
