### ISSUE TITLE
Quiz timer sometimes appears on regular non-quiz pages

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3742]
Quiz timer sometimes appears on regular non-quiz pages - see screenshots.

I'm not completely sure how to replicate this, or even whether an actual student would be likely to see it. I'm wondering if I'm triggering it by review behavior - i.e. moving quickly through the course and through multiple quizzes.

![Screenshot from 2023-06-20 22-55-17](https://github.com/Simon-Initiative/oli-torus/assets/2669407/cca0c2da-b1cd-48a8-ad99-11e586f0b827)

![Screenshot from 2023-06-20 22-55-31](https://github.com/Simon-Initiative/oli-torus/assets/2669407/72d6d846-a91c-400a-a516-b14f07828d08)

**Comment by normanbier** [comment]
Adding that I'm seeing this too, even w/ a fairly fresh (< 10 minutes) log-in/enrollment and no previous quiz access. 
<img width="1409" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/71cb8221-28ba-4e0f-96fb-02b0dfc758fe">
