### ISSUE TITLE
Chemistry: Broken formula H2O

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3745]
See screenshot

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_introduction_to_chemistry_7x6w6

![Screenshot from 2023-06-21 12-15-05](https://github.com/Simon-Initiative/oli-torus/assets/2669407/d28dfdc6-0976-42a7-b797-1226e8da0d76)

**Comment by eliknebel** [comment]
Fixed v24
