### ISSUE TITLE
Quiz question points reported to 16 decimal places

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3746]
Consider rounding to one or two decimal places.

![Screenshot from 2023-06-19 13-27-58](https://github.com/Simon-Initiative/oli-torus/assets/2669407/88a04e92-bd7a-4042-ba0f-95d2b6e95c8c)

![Screenshot from 2023-06-19 13-29-10](https://github.com/Simon-Initiative/oli-torus/assets/2669407/461d7884-3fe1-4ea4-aaa5-cb5c0133ada0)

**Comment by eliknebel** [comment]
We should round decimal places to 2 digits
