### ISSUE TITLE
Chemistry: update "separate tab" statements

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3751]
There are many places in the course where the page states that a link will open in a separate tab, but it instead opens in the same tab. If the behavior has changed with the new platform, consider updating content correspondingly.

An example is the PhET simulations on this page: https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_exploring_electron_and_molecul_xbvg0

![Screenshot from 2023-06-21 12-45-52](https://github.com/Simon-Initiative/oli-torus/assets/2669407/3e02b051-0a99-4892-9f07-cbd7e8e1a623)

**Comment by halturner** [comment]
GUIDANCE NEEDED.
Two solutions are available:

1. Change the functionality so links can open in new tabs, if that's how they're coded in legacy.
2. Change the words on the page, using an XML find-and-replace before the final migration.

**Comment by eliknebel** [comment]
It appears the `target` property is being captured as part of the course digest, which means we can use to add support in the future in torus for links to specify how they should open, new tab or not.
```
              {
                "type": "p",
                "children": [
                  {
                    "text": "If you would like to open the simulation in a separate tab, click this link: "
                  },
                  {
                    "type": "a",
                    "children": [
                      {
                        "text": "Balancing Chemical Equations",
                        "strong": true
                      }
                    ],
                    "idref": "balance_eq_phet_sim",
                    "target": "new"
                  }
                ]
              },
```

**Comment by darrensiegel** [comment]
Despite the fact that legacy worked this way, adding support for links that open in new tabs automatically is not a great idea for reasons of usu ability and accessibility. Especially on small form factors and touch devices, a link that opens a new tab can be confusing and difficult to use. 

We need to let the browser work the way it was designed to work, and allow the user to simply right click and open in new tab or window at their discretion.

**Comment by eliknebel** [comment]
The content should be rephrased as to not state that the link will open in a new tab.

**Comment by normanbier** [comment]
grep -rli 'separate tab' --include='*.xml' shows 16 pages:

./u1_foundations_chem/m4_elements/x-oli-workbook_page/p2_atomic_mass_gates.xml
./u1_foundations_chem/m4_elements/x-oli-workbook_page/p4_intro_periodic_table.xml
./u1_foundations_chem/m4_elements/x-oli-workbook_page/p4_intro_periodic_table_gates.xml
./u1_foundations_chem/m4_elements/x-oli-workbook_page/p2_atomic_mass.xml
./u1_foundations_chem/m4_elements/x-oli-workbook_page/p3_ions.xml
./u3_rxn_stoich/m1_chemical_equations/x-oli-workbook_page/p2_balancing_eq.xml
./u3_rxn_stoich/m2_reaction_stoichiometry/CL_rxn_stoich_scaffold/x-oli-workbook_page/p3_CL_scaffold_limit_reactions.xml
./u3_rxn_stoich/m2_reaction_stoichiometry/CL_rxn_stoich_PreCoReq/x-oli-workbook_page/p3_CL_PreCoReq_limit_reactions.xml
./u3_rxn_stoich/m2_reaction_stoichiometry/x-oli-workbook_page/p3_limit_reactions.xml
./u3_rxn_stoich/m2_reaction_stoichiometry/x-oli-workbook_page/p3a_limit_reactions_ctat.xml
./u3_rxn_stoich/m2_reaction_stoichiometry/skills/x-oli-workbook_page/SK_p3_limit_reactions.xml
./u7_MolecularGeo/m3_molec_structure/x-oli-workbook_page/preview_pages/prev_p2_lone_pairs.xml
./u7_MolecularGeo/m3_molec_structure/x-oli-workbook_page/preview_pages/prev_p1_electron_molec_geo.xml
./u7_MolecularGeo/m3_molec_structure/x-oli-workbook_page/p2_lone_pairs.xml
./u7_MolecularGeo/m3_molec_structure/x-oli-workbook_page/p1_electron_molec_geo.xml
./u7_MolecularGeo/m1_ionicCovalent/x-oli-workbook_page/p4_covalent_formation.xml
