### ISSUE TITLE
Chemistry: Degree symbol after text entry box wrapping to new line

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3752]
Degree symbol after text entry box wraps to a new line when browser window is not wide enough. 

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_18/page/vuswd_lone_pairs_of_electrons_and_bo_tzmzq

![Screenshot from 2023-06-21 12-47-37](https://github.com/Simon-Initiative/oli-torus/assets/2669407/feca7450-d765-4c13-b724-eeb305564045)

**Comment by eliknebel** [comment]
Fixe v24
