### ISSUE TITLE
Unscored page attempt doesn't seem to reset on publish

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#3759]
**Describe the bug**
On an unscored practice page, I had a multi input question with a text input which I changed to a math input, then published but the activity didn't update. Once I clicked "Reset Answers" and a new page attempt  was created, then the math input was displayed.

Q: Are unscored pages supposed to update their content automatically, regardless of existing attempts, when a new publication is released? Or is this normal behavior?

**Comment by darrensiegel** [comment]
This is working as designed.  In this scenario you only edited the activity resource, not the page.
