### ISSUE TITLE
Sections in Pools Not Working

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3768]
Module Assessment referenced in video:
https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_compounds_and_chemical_formula_je2lk

Unit Assessment referenced in video: https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_atoms_molecules_and_ions_z21h1

See video here: https://drive.google.com/drive/u/0/folders/1s_SUGnKNRkqehwuAMkNTwzq89acUOX17

**Comment by andersweinstein** [comment]
Some notes: in legacy, one can have a pool of *sections*, each of which contains multiple questions, and a selection with scope = "section", which selects one multi-question section from such a pool for inclusion in an assessment.

Section selection also behaves specially in legacy's targeted retake mode: for retake purposes, a section is only treated as correct if all questions within it are correct. In that way it behaves like single compound question for retake purposes.

**Comment by eliknebel** [comment]
We might add support for activity bank groups in the future, but for chemistry this is a content related issue that should be fixed in the XML
