### ISSUE TITLE
Random Ordering of Assignments from Assignment Tab

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3786]
https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/my_assignments

When you click the assignment tab, the quizzes show up in random order. They should show up in the order that they are in in the course.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/8c3de3f2-34bd-4568-9229-083a54966bb9)

**Comment by eliknebel** [comment]
The issue here is that these assignments are from page links but are not actually part of the course hierarchy. We need to add the ability to look for page links in a page's content and include those linked assignments in the ordering of assignments
