### ISSUE TITLE
Centering Equations

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3790]
I thought equations were being centered in previous versions I looked at, but I could be mistaken. I think they definitely should be centered. 

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/0b30ecca-e923-4dc4-86fb-bb1d1397d657)

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_waves_tofnr

**Comment by eliknebel** [comment]
It is likely that this is already fixed but we should retest this.
