### ISSUE TITLE
Can't read text from drop down once it is chosen

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3792]
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/9a70d2e0-3ceb-40a6-9b18-766584aa00ed)

https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_the_spin_quantum_number_jgedy

Text boxes should be legible once chosen. Here is what it looks like in legacy.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/2ec1ab89-9ad1-43e9-930e-798bec31d598)

**Comment by eliknebel** [comment]
fixed v24
