### ISSUE TITLE
Unusual Text Wrapping

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3793]
https://stellarator.oli.cmu.edu/sections/real_chemistry_review_june_24/page/5s48r_variation_in_ionic_radii_s7sdk
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/21d6d528-5e31-4eb9-b7c5-d538c17b1f76)

The 2+ should be superscripted next to the Ca. Looks like this in legacy.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/8abe9f19-fad5-42af-a7e0-29bfad7cd04b)

https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=fddfc52f7f0000013278ae73ab744e80

**Comment by eliknebel** [comment]
Fixed in v24
