### ISSUE TITLE
[Migration] Text field is small but it should be large

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3797]
**Describe the bug**
In legacy there is a large textbox, but in tokamak the text field is small. 

[Legacy ](https://oli.cmu.edu/jcourse/workbook/activity/page?context=6db0164f0a0001dc56ba1670a7d70267)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/ed8816d9-a36b-45d0-b8d7-c1083925dd04)

[Tokamak](https://tokamak.oli.cmu.edu/sections/conflictu_s9pev/page/gxmeb_more_practice_di4ds)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/248af963-91d8-402f-ae52-bac2e1a57a25)

[SVN](https://svn.oli.cmu.edu/svn/content/conflict_resolution/conflict_u/branches/v_1_5-echo/content/x-oli-inline-assessment/DIGT_prof_email.xml)

**Environment (please complete the following information):**
 - Version: 24

**Comment by eliknebel** [comment]
May be a duplicate, but this is likely fixed in latest digest tool. We should retest with the latest course-digest tool

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2165
