### ISSUE TITLE
[Migration] Questions in pool are shuffled, but should not be

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3798]
**Describe the bug**

[Legacy](https://oli.cmu.edu/jcourse/assessment2/activity/view.do?context=6db016420a0001dc3b2afb43547c6776)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/0475b085-92fd-4985-8701-baf53845f72a)

[Tokamak](https://tokamak.oli.cmu.edu/sections/conflictu_s9pev/container/pretest_z49uy)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/305f1147-6568-4964-af89-86d0f2c2c422)

[Echo](https://echo.oli.cmu.edu/#conflictu1-1.5/pretestd1d783459f1f40349e17fdc62f899ea7?organization=conflictu1-1.5_default&nodeGuid=db6e592fca1a491d9f6812da03ee4298)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/4eef32b4-37ff-40b9-94b6-ddb93b9aee9a)

[SVN](https://svn.oli.cmu.edu/svn/content/conflict_resolution/conflict_u/branches/v_1_5-echo/content/x-oli-assessment2-pool/d115213470af4062b6bf8cac05f8908c.xml)

**Environment (please complete the following information):**
 - Version: 24

**Comment by eliknebel** [comment]
Can we verify with re-digest this is still an issue

**Comment by cjlim1092** [comment]
it is

**Comment by andersweinstein** [comment]
Migration issue was fixed, but requires new conversion/ingestion to get change. Looks OK in

https://tokamak.oli.cmu.edu/sections/conflictu_anders_test_9723/page/hzny6_pretest_30wkn

**Comment by andersweinstein** [comment]
Is the problem that the *questions* are not pulled from the pool in successive order, as they are in legacy when selection strategy = in order, as shown here? Torus does not support in-order selection from pools, so questions will always be selected in random order.
