### ISSUE TITLE
Popup Content in question stem is breaking preview

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#3810]
**Describe the bug**
I was attempting to test popup (rollover) functionality on stellarator.  When hitting preview, the system throws a 500 error.

**To Reproduce**
Go to https://stellarator.oli.cmu.edu/authoring/project/_a_bier_test_course/resource/popup_text_in_a_question_that_
Press "Preview)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
Stellarator, using Safari on Mac

**Additional context**
Additional information available via AppSignal
[Incidents] 1 error incident for oli-stellarator (staging) [#100] 
https://appsignal.com/open-learning-initiative/sites/64822a7083eb671d87807a11/exceptions/incidents/100/samples/timestamp/2023-06-30T14:56:00Z

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2234
