### ISSUE TITLE
As a student, revisit completed work that's been obscured by an author update

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3812]
THIS IS A PLACEHOLDER. CAREFUL DESIGN NEEDED, AS THIS IS CONNECTED TO PARTICIPATION, LEARNING ESTIMATE, VERSIONING, ETC.

When content updates go out, the completed work on those pages is no longer visible to the student. According to Darren, their completed work still contributes to their participation percentage, but they cannot see their past work.

Some kind of visualization should be considered, such as
- a modal that shows past work on updated questions
- a message that notifies the student that "this question has been updated. If you want to answer it again, you can review your answer(s) that you made before the update."

**Comment by eliknebel** [comment]
Consider taking an approach when activities have not changed (e.g. typo update to page content) leaving the activities and current attempts in place, only updating page material
