### ISSUE TITLE
[Stellarator] Instructor dashboard: Learning objective sub-tab for individual student view not opening

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3817]
**Description of the bug**
On Stellarator, when an instructor clicks on individual student view for a section, they can view individual student progress, on clicking on the learning objectives sub-tab, the content sub-tab is loaded again. Learning objective sub-tab does not show up. 

**To Reproduce**
Need to add

**Expected behavior**
The learning objectives view with completion and proficiency should show up. 

**Environment:**
 - OS: Windows
 - Browser: Safari

**Comment by tanvidomadia** [comment]
**To Reproduce**
1. Go to a course section as an instructor on stellarator.oli.cmu.edu
2. Click on Reports tab 
3. Click on Students 
4. Click on any individual student
5. Within the individual student view, click on learning objectives

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2266
