### ISSUE TITLE
[Migration Parity] List items not appearing in tokamak

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#3840]
**Describe the bug**
In legacy there is a list coded with <li> and it is not appearing in tokamak, note also that there is a missing line break

[Tokamak](https://tokamak.oli.cmu.edu/sections/conflictu_s9pev/page/gxmeb_idea_generation_5e73w)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/5d08278a-9284-45d4-be4e-cb40eef78c3b)

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=6db016500a0001dc6cee095e10f43325)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/bc9e54e3-44c0-4dcc-ab4d-485aa1086706)

[SVN](https://svn.oli.cmu.edu/svn/content/conflict_resolution/conflict_u/branches/v_1_5-echo/content/x-oli-workbook_page/CU_segment8_workbook.xml)
[Echo](https://echo.oli.cmu.edu/#conflictu1-1.5/CU_segment8_workbook?organization=conflictu1-1.5_default)

**Environment (please complete the following information):**
 - Version: 24

**Comment by eliknebel** [comment]
Can we retest the ingestion of this with the latest course-digest to verify the issue still exists?
