### ISSUE TITLE
Activity bank selection in authoring tool results in broken button in delivery

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3894]
[This page in Authoring 
](https://stellarator.oli.cmu.edu/authoring/project/learning_engineering_topics_co/resource/an_introduction_to_the_rise_fr)
![Screenshot 2023-07-11 at 2 54 31 PM](https://github.com/Simon-Initiative/oli-torus/assets/24977416/10551471-8fb4-4448-a477-221043e73494)

[results in this page in the delivery environment](https://stellarator.oli.cmu.edu/sections/demo__rise_analysis/page/an_introduction_to_the_rise_fr) (this is a full section, not a preview page)
<img width="982" alt="Screenshot 2023-07-11 at 2 55 21 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/d4de10f1-993d-45d5-a753-584c4367a288">

The button has no label. It leads to a 404 when you click it. And the first question doesn't generate feedback for the student.

**Comment by normanbier** [comment]
There is a major issue with activities that use Activity Banks.  Attempting to launch an activity as a student also produces the image below.  Reproduce here:  https://stellarator.oli.cmu.edu/sections/real_chemistry_i_7132023_merge/page/a43ug_electromagnetic_energy_and_the_9h7ko

![image](https://github.com/Simon-Initiative/oli-torus/assets/4762701/0785789b-2afd-4438-ad88-8060e00c0dd8)
