### ISSUE TITLE
Group render error

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3897]
Group render error. Please try again or contact support with issue #IXNLPVO6MXRPF3HP4DMIMS.

[Stellarator page](https://stellarator.oli.cmu.edu/sections/rise_framework_dashboard_demo_jai7u/page/qss63_automation_of_the_rise_framewo_ob2ks)
<img width="1608" alt="Screenshot 2023-07-11 at 3 11 12 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/ca2be2f6-0925-4965-93df-cea76ed4bbf2">

Group render error. Please try again or contact support with issue #GLJVYAK5UHXM25XCVDWGPN.
Group render error. Please try again or contact support with issue #UDBEJ4MTFZK2DZBKIGZQJ4.

And several others on that page

**Comment by eliknebel** [comment]
Used to work, seems to be broken now. Ingested from a different torus instance.
