### ISSUE TITLE
Datashop export failure

### ISSUE THREAD

**Issue by LEDThereBeLight** [Simon-Initiative/oli-torus#394]
Jul 10 13:24:44 proton oli: 13:24:44.596 request_id=FiBm-EW0hjGzdFQAAAwB [info] POST /project/raff_psychology/datashop
Jul 10 13:24:44 proton oli: 13:24:44.725 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #34807EC2 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.728 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #20E113E5 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.738 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #46F15E3D Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.738 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #E3521E94 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.739 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #7CB2DA49 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.739 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #EDFF50A4 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.740 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #1D3E7AB0 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.741 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #8512DFA3 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.743 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #34419B0C Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.743 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #08ABD90E Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.744 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #7FF913C9 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.745 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #3A713299 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.749 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #FDEB18C4 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.749 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #D2EDACD2 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.750 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #F3EA291C Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.751 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #91DABC1D Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.752 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #2BDE69ED Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.752 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #2EC7F9DE Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.754 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #B3A581EE Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.755 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #89C0EAD5 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.755 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #AAA0302E Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.756 request_id=FiBm-EW0hjGzdFQAAAwB [error] Render Error #101291A2 Content element is invalid: nil
Jul 10 13:24:44 proton oli: 13:24:44.810 request_id=FiBm-EW0hjGzdFQAAAwB [info] Sent 500 in 213ms

**Comment by darrensiegel** [comment]
I ran into this error as well
