### ISSUE TITLE
Dark mode might cause issues with images that contain text

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#3940]
Looks like when you are in dark mode it cuts off the bottom of an image? Isn't the blue line in regular mode.
I checked this in authoring preview, student, and instructor all gets cut off. 
indicative o
![image dark mode](https://github.com/Simon-Initiative/course-digest/assets/139511643/f193a3de-3c28-4c83-b217-c056e3b2fb1b)
![image in light mode](https://github.com/Simon-Initiative/course-digest/assets/139511643/c9a06206-5687-4871-99d4-cea48b8b1f28)
f the image space?

**Comment by eliknebel** [comment]
Is suspect the image here might actually have a combination of transparent background with text overlayed on top of another screenshot that has a white background causing it to appear this way. Would it be possible to track down this image and verify this?

**Comment by kllarson** [comment]
Yes, since this is a screenshot of legacy it will not be used, but it
sounds like this could happen where any image that is put in pptx say, and
then arrows, text etc. added could cause this to happen?

**Comment by eliknebel** [comment]
Good point, any image that has text on transparent background or low contrast on dark backgrounds.

Short term, authors can avoid this by including a high contrast background (e.g. white) for images with text. But this isn't very accessible for users who wish to use dark mode.
Longer term, we have this issue with the torus logo and the way it is handled is to render a different image with white text when in dark mode. I could imagine a feature in torus where authors can specify a "dark variant" of an image in cases where they can't provide an image that works well in both light and dark themes.
