### ISSUE TITLE
[Stellarator Instructor Dashboard]: Course progress not recorded correctly, shows 0% for the student view 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3949]
**Describe the bug**
In the Reports view as an instructor, when clicking on the Students sub-tab, the course progress is 0% for all students whereas when clicking on the Content sub-tab the student completion is showing non-zero numbers (33%, 22%, 22%, 22%, etc). So even though students have gone through some of the course, the course progress seems to be resetting to zero. 

**To Reproduce**
1. Go to course [recursion data test Torus](https://stellarator.oli.cmu.edu/sections/recursion_data_test_torus/instructor_dashboard/overview) on stellarator as an instructor. 
2. Click on 'Reports' tab 
3. Scroll down to click on 'Content' sub-tab, see non-zero student completion rates. 
4. Click on 'Students' sub-tab, see zero course progress rates 

**Expected behavior**
Non-zero course progress rates 

**Screenshots**
Non-zero student completion view in Content sub-tab: 
![image](https://github.com/Simon-Initiative/oli-torus/assets/20156664/70318177-02e2-4220-81f3-87234285f97b)

Zero course progress view in Students sub-tab: 
![image](https://github.com/Simon-Initiative/oli-torus/assets/20156664/e18ada99-26c0-46b5-aefb-5940611f1f11)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by tanvidomadia** [comment]
Same applies for [individual student view](https://stellarator.oli.cmu.edu/sections/recursion_data_test_torus/student_dashboard/5090/content) as well: 

![image](https://github.com/Simon-Initiative/oli-torus/assets/20156664/d89971b5-4c25-4a06-b2b6-400403ba9633)

**Comment by eliknebel** [comment]
We need to again try remixing to kick off a section resource rebuild, and if that fixes the issue the may be an issue with the migration fix previously put in place

**Comment by tanvidomadia** [comment]
The course progress is reflected after remixing the section (resource rebuild).

**Comment by tanvidomadia** [comment]
Works on new course as well.
