### ISSUE TITLE
[Stellarator Student Analytics]: Course progress is incorrect on homepage for a course section 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3952]
**Description of the bug**
As a student, enter a course section. The home page shows Overall course progress which is always at 1% even after working through all the pages within the course. 

**To Reproduce**
1. Go to course on Stellarator as a student. For example, [Jemstedt LearnLab 2022: Creating practice questions and answers that promote long-term learning](https://stellarator.oli.cmu.edu/sections/jemstedt_learnlab_2022_creatin/overview)
2. See course progress is 1% 
3. Work through the course
4. Click on home in the left hand side panel to view the home page again. 
5. Course progress is still at 1%

**Expected behavior**
The course progress has to be updated in real time and should show 100% for having worked through the entire course and not 1%. 

**Screenshots**
![image](https://github.com/Simon-Initiative/oli-torus/assets/20156664/98b0155e-84dc-4e62-a3ae-f271e107aff2)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by eliknebel** [comment]
Can we try making a remix change to this course to verify if this is related to a recent migration fix that has landed.

**Comment by tanvidomadia** [comment]
after course remix, updated course progress for the student is seen, still need to test in a new section

**Comment by tanvidomadia** [comment]
Works fine after testing with a new section (just that the progress starts with 1% but that's a minor issue); overall functionality works.
