### ISSUE TITLE
As instructor in dark mode it is hard to tell if you checked a box or not

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#3958]
When you are on manage it is kind of hard to tell for sure if you have checked a box or not.
For example you are thinking that because the box below is black it means it is checked. When I switched to light mode it was not checked. I had to check it for the mark to show up. 

![dark mode instructor check boxes 2](https://github.com/Simon-Initiative/oli-torus/assets/139511643/a73df406-c911-439c-8e8a-38d8bfcaa51e)
![dark mode instructor check boxes](https://github.com/Simon-Initiative/oli-torus/assets/139511643/990bfea7-af86-4a02-b829-c2a497e16b06)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.  If you know of other platforms that offer this suggested functionality, please list them.

**Comment by eliknebel** [comment]
Fixed
