### ISSUE TITLE
Ability to see who created a section in the publish area that shows you the sections that were created off of a project

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#3959]
**Is your feature request related to a problem? Please describe.**
Ability to see who created a section in the publish area that shows you the sections that were created off of a project

![see who created a section](https://github.com/Simon-Initiative/oli-torus/assets/139511643/7237aff2-8d4a-456f-956a-5c34862bc1ce)

**Describe the solution you'd like**
We need another column in the publish table that lists the section creator and instructors.

**Comment by eliknebel** [comment]
Knowing who created the section is helpful, but it could also be more helpful to know who the instructors are
