### ISSUE TITLE
Media Library does not give specific message when duplicate file is uploaded

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#3966]
Can't get this one to upload - 
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/c4339084-8cef-43de-aa91-7ad882e9c38f)

This one uploaded fine - 
![43-430748_erlenmeyer-flask-fluid-chemistry-orange-media-chemistry-clip-art](https://github.com/Simon-Initiative/oli-torus/assets/36045601/1893d158-e696-4536-842a-5b17c676f75b)

**Comment by darrensiegel** [comment]
Both files upload fine for me, I believe the issue here is that the first file (which fails for you) is already present in that course's media library.  The system is not giving a specific enough failure message

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2373

**Comment by eliknebel** [comment]
Fixed
