### ISSUE TITLE
In Reports when I click on a unit, then click on a student, I get internal server error

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#3972]
**Describe the bug**
In Reports when I click on a unit, then click on a student I get internal server error

I am here:
![report error 1](https://github.com/Simon-Initiative/oli-torus/assets/139511643/ddd877f4-510d-4c00-9b41-0d1f91e64379)

Then I click on the student, and I get this:
![image](https://github.com/Simon-Initiative/oli-torus/assets/139511643/871f424d-20c6-4d6e-a22f-5d10ba431b80)

I am in as an instructor and I'm on Chrome, windows

If you need any other info let me know. Thanks!

**Comment by darrensiegel** [comment]
Code to summarize the "Required Student Survey" is breaking when it encounters an MCQ with "shuffle options" disabled. 

https://eliterate.atlassian.net/browse/MER-2372

**Comment by darrensiegel** [comment]
Fixed

**Comment by kllarson** [comment]
Thanks!On Jul 19, 2023, at 7:09 PM, Darren Siegel ***@***.***> wrote:﻿
Fixed
