### ISSUE TITLE
Survey doesn't show up correctly in dark mode, can't ready text in alternating rows

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#4000]
**Describe the bug**
Survey doesn't show up correctly in dark mode, can't ready text in alternating rows

Here is a link if you want to see it in a course
https://proton.oli.cmu.edu/sections/join/zmdsp 

![image (6)](https://github.com/Simon-Initiative/oli-torus/assets/139511643/5ea5f13f-5d86-4cb5-ae11-279d3d362e9d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2386
