### ISSUE TITLE
In instructor view of discussion activity, when you click on any link "curriculum you get "500 internal server error"

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#4001]
**Describe the bug**
When I go to instructor view of discussion activity and I see discussion then when you click on any link "curriculum you get "500 internal server error"
![discussion_activity](https://github.com/Simon-Initiative/oli-torus/assets/139511643/571a59c4-586b-4209-ade3-c3970cf79657)
![clickOnDiscussionLinkInstructorErroPage](https://github.com/Simon-Initiative/oli-torus/assets/139511643/2f5ddb5c-d4e1-4846-a455-5e233e92a93e)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2388
