### ISSUE TITLE
url in table header cell can't be removed- not sure how it got there, it is a proton publish url

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#4002]
**Describe the bug**
A few of us were editing tonight on this page:https://proton.oli.cmu.edu/authoring/project/real_chemistry_i_taylors_versi/resource/vwx8a_mole_conversions_single_step_l1swi

Something happened because at some point I noticed the table looked odd. I went into authoring and saw this url in the header. I couldn't edit it out. I can place my cursor anywhere else in this table and others, but not in the one with the weird publish url in it. 

![weirdURLinTableHeader](https://github.com/Simon-Initiative/oli-torus/assets/139511643/ac953d90-4146-4d3d-8584-c12627dc1b77)

FYI, this section is for "instructors only" if that helps at all. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by normanbier** [comment]
I was able to go in and edit this cell without a problem. Not sure what state it was in, but it opened and I was able to correct the text without any problem.
