### ISSUE TITLE
Dialogue Feature Readability Issues - colors and shading/filtering

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4021]
**Describe the bug**
On 2023-07-24 19:03:55.152935+00:00 UTC UTC, Keziah Olsen < keziaho@andrew.cmu.edu > wrote:
I was trying to implement the dialogue feature on this page (which we will use on multiple pages in every unit of the course), but the preview shows these crazy colors that make the dialogue hard to read and it seems like there's a filter over the dialogue. 
----------------------------------------------
Timestamp: 2023-07-24 19:03:55.152935+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/authoring/project/spanish_for_beginners_level_a1/resource/leccin_2_el_beso_t9ab0

![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/b796d678-da92-4671-b07d-324adf736f69)

Note: Color-blind considerations here too.

**Comment by darrensiegel** [comment]
https://eliterate.atlassian.net/browse/MER-2398

**Comment by eliknebel** [comment]
Fixed
