### ISSUE TITLE
Block callouts are not formatted properly

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#4032]
**Describe the bug**
From LL23: Callouts are intended to allow content to standout from other content in a way that grabs the students attention. There is currently no formatting happening for callouts but they should be formatted in a way that better accomplishes this goal.

For example: (design from Aleks)

![Callout](https://github.com/Simon-Initiative/oli-torus/assets/6248894/0420dc32-bebb-4494-a98d-4090ac8479c6)

**Comment by andersweinstein** [comment]
We have a similar complaint about "pullouts", https://github.com/Simon-Initiative/oli-torus/issues/3659.
