### ISSUE TITLE
Using parent learning objective in activity selection crashes preview

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#4034]
**Describe the bug**
Attaching and using parent learning objective in activity selection crashes preview and possibly delivery.

**To Reproduce**
1. Create a learning objective with sub-objectives
2. Attach to activity and preview course
4. See 500 error

**Comment by eliknebel** [comment]
This issue is simply a bug but does raise the larger question around what learning objectives can be used where

**Comment by bitbldr** [comment]
Step 1: We need to determine if this also affects pages in delivery (not in preview)
