### ISSUE TITLE
Wrong feedback displayed

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4043]
[On mobile, the user made three attempts.
](https://proton.oli.cmu.edu/sections/pd_k12_empathy/progress/5096/70278)
The first attempt was incorrect, and the user received the appropriate feedback:
<img width="1608" alt="Screenshot 2023-07-27 at 4 55 23 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/2e144bb8-cde6-4629-98a6-0156d5cc3d81">

Then the user answered a different incorrect order, but received feedback that it was correct (it was not correct). Correct is local > state > federal.
<img width="1608" alt="Screenshot 2023-07-27 at 4 56 23 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/093df695-1ded-43c2-afd3-6e46fe23e4db">

Then they answered a third time and it was incorrect, resulting in the appropriate incorrect feedback:
<img width="1608" alt="Screenshot 2023-07-27 at 4 57 02 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/aba57a98-fea8-4fb4-ab93-2fefadbb7bb1">

**Comment by halturner** [comment]
@normanbier https://proton.oli.cmu.edu/authoring/project/pd_k12_empathy/resource/k12_funding

The question is an activity bank selection at the bottom.

**Comment by normanbier** [comment]
@halturner Can you replicate this? I'm trying and I can't get the same result (I'm always getting it appropriately correct/incorrect)...

**Comment by halturner** [comment]
@normanbier I was unable to replicate it myself. That's why I relied on the history, hoping it would provide some kind of breadcrumb trail. My understanding is that it was encountered while on mobile, though. I tested on mobile and desktop, but Sasha was the student and definitely was using her phone when it occurred. Another report that we couldn't corroborate was also on mobile.

**Comment by bitbldr** [comment]
Using the guids, timestamps and other information available, we should dedicate some engineering time to investigate this further
