### ISSUE TITLE
Learner account verification email categorized as Promotion by gmail

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4047]
Signing up for a new Learner account using a gmail address resulted in the email being categorized as Promotional in gmail.

**Comment by halturner** [comment]
`Delivered-To: othergames1+oli@gmail.com
Received: by 2002:a05:6a10:2011:b0:4be:652a:b5b6 with SMTP id h17csp758606pxc;
        Fri, 28 Jul 2023 07:29:06 -0700 (PDT)
X-Google-Smtp-Source: APBJJlE/P005Q7ddV+gU07wUG8dWAjo/buNSXM8hUdlXgygSzVS7U1tzbiNcHD5I20zGzL8whK5X
X-Received: by 2002:ac8:5a15:0:b0:401:e2b1:d28d with SMTP id n21-20020ac85a15000000b00401e2b1d28dmr3261679qta.20.1690554546297;
        Fri, 28 Jul 2023 07:29:06 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1690554546; cv=none;
        d=google.com; s=arc-20160816;
        b=kiy+orUwAtUdw+gMDXHFKwDqTASzJyUOsz8+8l+8enC0m5iMDte4XKASos3vkZxeZ6
         fDL4Rp8bjGWr9Q0+52sXAsK0F4CjYAWJVDcBQqwk+24sIblbH+kgn2pZGmw7Kc3yfjGm
         tJOCqi0lKJ6m+tqwAXBSzwvSBIHdCdOGMKumRrvBNKsyytEnLC4QsConAbdkJO+fC0fI
         6Nv7jsjAgx60IBxZvV4dLyvPOCq3RfmZYWmJoWtfZNQnyS/WAdkx8vgoPSNyba4mbABt
         a+gPc3pjsyvrYEmKB96jtLoa5iGJCtUpiPfw4sqsUfhKfrwqaer8GthEZh8ilmGW4ART
         zjig==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=feedback-id:date:message-id:mime-version:subject:to:reply-to:from
         :dkim-signature;
        bh=J+qsUyMsh6cmlteKvh7emJrgWWWq9wUP2t+OyYVo18I=;
        fh=7n5NyOR6Ab242Pzn4F08Gw+Xe7IgHm/MB1y+69kS1pg=;
        b=TS8AjCRUcPpVg5inMFlxo+NlzZL4oNMWCBT3qT751v+MygRe4kw6vf2d4e2PbBPCha
         Vc8kL2eHZMWBQcSOvbEwvEFDaAUEWJleESdWefE+qHQSc6XGpMw3SoqIO6OEK19C7HIQ
         jOos3JU2Haey7UoXznam/5rGwkjwytj0ZkVFKgHdjTZ83/reyINYrBEOkuqHLWDQNUBG
         8sYkorUFH15yCSGHhDqQ5BnopfMrWQjiXsYqmr4fkiieudluHvfDM52Kce8PbRAWrmFf
         CV1Q6l3MLt2udM5EzEcD9/+XTCK8ogQp3KwSnMw//jh2mWxUzVdw43CqDfs+DwdOHAht
         RMiw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@amazonses.com header.s=224i4yxa5dv7c2xz3womw6peuasteono header.b=WUhkyWyB;
       spf=pass (google.com: domain of 010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com designates 54.240.48.33 as permitted sender) smtp.mailfrom=010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com;
       dmarc=fail (p=NONE sp=NONE dis=NONE) header.from=cmu.edu
Return-Path: <010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com>
Received: from a48-33.smtp-out.amazonses.com (a48-33.smtp-out.amazonses.com. [54.240.48.33])
        by mx.google.com with ESMTPS id z20-20020ac87f94000000b0040551396393si2287277qtj.797.2023.07.28.07.29.05
        for <othergames1+oli@gmail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 28 Jul 2023 07:29:06 -0700 (PDT)
Received-SPF: pass (google.com: domain of 010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com designates 54.240.48.33 as permitted sender) client-ip=54.240.48.33;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@amazonses.com header.s=224i4yxa5dv7c2xz3womw6peuasteono header.b=WUhkyWyB;
       spf=pass (google.com: domain of 010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com designates 54.240.48.33 as permitted sender) smtp.mailfrom=010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@amazonses.com;
       dmarc=fail (p=NONE sp=NONE dis=NONE) header.from=cmu.edu
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple; s=224i4yxa5dv7c2xz3womw6peuasteono; d=amazonses.com; t=1690554545; h=From:Reply-To:To:Subject:MIME-Version:Content-Type:Message-ID:Date:Feedback-ID; bh=TgZGLQ/70ydZQQGISgKv/w2r3kLEA+U30Zh6mk3Fv8A=; b=WUhkyWyB75rQHPCpax3eD6JGcLFJ3641JMWun20lOhXDoZEw6d9EGibOJOrYK/kI O6wIW6e6zb6jYPup+rSRvZGtT/dDsLPeacDSlAdjd19jBljcgzTLlYw4sjO68/hGDMw 9u9g/E3ls1zVzPCT0Uj+VCSqsApdMKfXLKUKpYdM=
From: Open Learning Initiative <torus-admin@oli.cmu.edu>
Reply-To: oli-help@cmu.edu
To: othergames1+oli@gmail.com
Subject: Confirm your email address
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="----=_Part_808004_2060672440.1690554545522"
Message-ID: <010001899ce7356f-2aa3a422-fc40-4155-86bf-0ed79f282db7-000000@email.amazonses.com>
Date: Fri, 28 Jul 2023 14:29:05 +0000
Feedback-ID: 1.us-east-1.Z/QZgZbVvoe8s9YrMMvSeYIez8YUYgq287ic2NIxv3Q=:AmazonSES
X-SES-Outgoing: 2023.07.28-54.240.48.33

------=_Part_808004_2060672440.1690554545522
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

torus-logo (https://proton.oli.cmu.edu/)

*********************
Confirm Email Address
*********************

Please confirm your email address using the button below.

Confirm Email
(https://proton.oli.cmu.edu/confirm-email/SFMyNTY.Nzc4MDAyMzUtYmJhMi00YjA0LWI4ZDAtOWUzZmM3YmNlZjVj.AufthuQJ7mSdtoiVOyLu7wzRojTq8en_NDzZHlL1ugM?section=spanish_for_beginners_level_a1)

Open Learning Initiative

Carnegie Mellon University
5000 Forbes Ave, Pittsburgh, PA 15213 US

The Open Learning Initiative enables research and experimentation
with all aspects of the learning experience.
As a leader in higher education's innovation of online learning,
we're a growing research and production project exploring
effective approaches since the early 2000s.

To learn more about our platform visit
https://oli.cmu.edu
------=_Part_808004_2060672440.1690554545522
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html lang=3D"en" xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:sch=
emas-microsoft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:office"=
><head><meta charset=3D"utf-8"/> <meta name=3D"viewport" content=3D"width=
=3Ddevice-width"/> <meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedg=
e"/> <meta name=3D"x-apple-disable-message-reformatting"/> <meta name=3D"fo=
rmat-detection" content=3D"telephone=3Dno,address=3Dno,email=3Dno,date=3Dno=
,url=3Dno"/> <meta name=3D"color-scheme" content=3D"light"/><meta name=3D"s=
upported-color-schemes" content=3D"light"/><title></title> <style>

        /* What it does: Tells the email client that only light styles are =
provided but the client can transform them to dark. A duplicate of meta col=
or-scheme meta tag above. */
        :root {
          color-scheme: light;
          supported-color-schemes: light;
        }

        /* What it does: Remove spaces around the email design added by som=
e email clients. */
        /* Beware: It can remove the padding / margin and add a background =
color to the compose a reply window. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        /* What it does: Centers email on Android 4.4 */
        div[style*=3D"margin: 16px 0"] {
            margin: 0 !important;
        }

        /* What it does: forces Samsung Android mail clients to use the ent=
ire viewport */
        #MessageViewBody, #MessageWebViewDiv{
            width: 100% !important;
        }

        /* What it does: Stops Outlook from adding extra spacing to tables.=
 */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        /* What it does: Fixes webkit padding issue. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }

        /* What it does: Uses a better rendering method when resizing image=
s in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }

        /* What it does: Prevents Windows 10 Mail from underlining links de=
spite inline CSS. Styles for underlined links should be inline. */
        a {
            text-decoration: none;
        }

        /* What it does: A work-around for email clients meddling in trigge=
red links. */
        a[x-apple-data-detectors],  /* iOS */
        .unstyle-auto-detected-links a,
        .aBn {
            border-bottom: 0 !important;
            cursor: default !important;
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        /* What it does: Prevents Gmail from displaying a download button o=
n large, non-linked images. */
        .a6S {
            display: none !important;
            opacity: 0.01 !important;
        }

        /* What it does: Prevents Gmail from changing the text color in con=
versation threads. */
        .im {
            color: inherit !important;
        }

        /* If the above doesn't work, add a .g-img class to any image in qu=
estion. */
        img.g-img + div {
            display: none !important;
        }

        .email-container {
            padding: 20px 10px;
        }

        /* What it does: Removes right gutter in Gmail iOS app: https://git=
hub.com/TedGoas/Cerberus/issues/89  */
        /* Create one of these media queries for each additional viewport s=
ize you'd like to fix */

        /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
        @media only screen and (min-device-width: 320px) and (max-device-wi=
dth: 374px) {
            u ~ div .email-container {
                min-width: 320px !important;
            }
        }
        /* iPhone 6, 6S, 7, 8, and X */
        @media only screen and (min-device-width: 375px) and (max-device-wi=
dth: 413px) {
            u ~ div .email-container {
                min-width: 375px !important;
            }
        }
        /* iPhone 6+, 7+, and 8+ */
        @media only screen and (min-device-width: 414px) {
            u ~ div .email-container {
                min-width: 414px !important;
            }
        }

        .more-link {
            color: #2c66c4;
        }

    </style><style>

=09    /* What it does: Hover styles for buttons */
=09    .button-td,
=09    .button-a {
=09        transition: all 100ms ease-in;
=09    }
=09    .button-td-primary:hover,
=09    .button-a-primary:hover {
=09        background: #2557a5 !important;
=09        border-color: #23519a !important;
=09    }

=09    /* Media Queries */
=09    @media screen and (max-width: 600px) {

=09        /* What it does: Adjust typography on small screens to improve r=
eadability */
=09        .email-container p {
=09            font-size: 17px !important;
=09        }

=09    }

    </style></head><body width=3D"100%" style=3D"-ms-text-size-adjust:100%;=
-webkit-text-size-adjust:100%;background-color:#ffffff;height:100% !importa=
nt;margin:0 auto !important;mso-line-height-rule:exactly;padding:0 !importa=
nt;width:100% !important;"><center role=3D"article" aria-roledescription=3D=
"email" lang=3D"en" style=3D"-ms-text-size-adjust:100%;-webkit-text-size-ad=
just:100%;background-color:#ffffff;width:100%;"><div aria-hidden=3D"true" style=3D"-ms-text-size-adjust:100=
%;-webkit-text-size-adjust:100%;max-height:0;mso-hide:all;overflow:hidden;"=
></div><div class=3D"email-container" style=3D"-ms-text-size-adjust:100%;-w=
ebkit-text-size-adjust:100%;margin:0 auto;max-width:600px;padding:20px 10px=
;"><tr style=3D"-ms-text-size-adjust:100%;-webkit-text-size-=
adjust:100%;"><a class=3D"navbar-brand torus-logo" href=3D"https://proton.o=
li.cmu.edu/" style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:10=
0%;text-decoration:none;"><td style=3D"-ms-text-size-adjust:100%;-webkit-te=
xt-size-adjust:100%;mso-table-lspace:0pt !important;mso-table-rspace:0pt !i=
mportant;padding:20px 0;text-align:center;"><img src=3D"https://d2xvti2irp4=
c7t.cloudfront.net/logos/prod/oli_torus_logo.png" width=3D"277" height=3D"1=
00" alt=3D"torus-logo" border=3D"0" style=3D"-ms-interpolation-mode:bicubic=
;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;height:auto;"/></t=
d></a></tr><table align=3D"center" role=3D"presentation" cellspacing=3D"0" =
cellpadding=3D"0" border=3D"0" width=3D"100%" style=3D"-ms-text-size-adjust=
:100%;-webkit-text-size-adjust:100%;border-collapse:collapse !important;bor=
der-spacing:0 !important;margin:0 auto !important;mso-table-lspace:0pt !imp=
ortant;mso-table-rspace:0pt !important;table-layout:fixed !important;"><tr =
style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;"><td styl=
e=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;background-col=
or:#ffffff;mso-table-lspace:0pt !important;mso-table-rspace:0pt !important;=
padding:20px 10px;"><table role=3D"presentation" cellspacing=3D"0" cellpadd=
ing=3D"0" border=3D"0" width=3D"100%" style=3D"-ms-text-size-adjust:100%;-w=
ebkit-text-size-adjust:100%;border-collapse:collapse !important;border-spac=
ing:0 !important;margin:0 auto !important;mso-table-lspace:0pt !important;m=
so-table-rspace:0pt !important;table-layout:fixed !important;"><tr style=3D=
"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;"><td style=3D"-ms=
-text-size-adjust:100%;-webkit-text-size-adjust:100%;color:#555555;font-fam=
ily:sans-serif;font-size:15px;line-height:20px;mso-table-lspace:0pt !import=
ant;mso-table-rspace:0pt !important;padding:20px;"><h1 style=3D"-ms-text-si=
ze-adjust:100%;-webkit-text-size-adjust:100%;color:#333333;font-family:sans=
-serif;font-size:25px;font-weight:normal;line-height:30px;margin:0 0 10px 0=
;">Confirm Email Address</h1><p style=3D"-ms-text-size-adjust:100%;-webkit-=
text-size-adjust:100%;margin:0;">Please confirm your email address using th=
e button below.</p></td></tr><tr style=3D"-ms-text-size-adjust:100%;-webkit=
-text-size-adjust:100%;"><td style=3D"-ms-text-size-adjust:100%;-webkit-tex=
t-size-adjust:100%;mso-table-lspace:0pt !important;mso-table-rspace:0pt !im=
portant;padding:0 20px;"><table align=3D"center" role=3D"presentation" cell=
spacing=3D"0" cellpadding=3D"0" border=3D"0" style=3D"-ms-text-size-adjust:=
100%;-webkit-text-size-adjust:100%;border-collapse:collapse !important;bord=
er-spacing:0 !important;margin:0 auto !important;mso-table-lspace:0pt !impo=
rtant;mso-table-rspace:0pt !important;table-layout:fixed !important;"><tr s=
tyle=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;"><td class=
=3D"button-td button-td-primary" style=3D"-ms-text-size-adjust:100%;-webkit=
-text-size-adjust:100%;background:#2C67C4;border-radius:4px;mso-table-lspac=
e:0pt !important;mso-table-rspace:0pt !important;transition:all 100ms ease-=
in;"><a class=3D"button-a button-a-primary" href=3D"https://proton.oli.cmu.=
edu/confirm-email/SFMyNTY.Nzc4MDAyMzUtYmJhMi00YjA0LWI4ZDAtOWUzZmM3YmNlZjVj.=
AufthuQJ7mSdtoiVOyLu7wzRojTq8en_NDzZHlL1ugM?section=3Dspanish_for_beginners=
_level_a1" style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%=
;background:#2C67C4;border:1px solid #2C67C4;border-radius:4px;color:#fffff=
f;display:block;font-family:sans-serif;font-size:15px;line-height:15px;padd=
ing:13px 17px;text-decoration:none;transition:all 100ms ease-in;">Confirm E=
mail</a></td></tr></table></td></tr></table></td></tr></table><table align=
=3D"center" role=3D"presentation" cellspacing=3D"0" cellpadding=3D"0" borde=
r=3D"0" width=3D"100%" style=3D"-ms-text-size-adjust:100%;-webkit-text-size=
-adjust:100%;border-collapse:collapse !important;border-spacing:0 !importan=
t;margin:0 auto !important;mso-table-lspace:0pt !important;mso-table-rspace=
:0pt !important;table-layout:fixed !important;"><tr style=3D"-ms-text-size-=
adjust:100%;-webkit-text-size-adjust:100%;"><td style=3D"-ms-text-size-adju=
st:100%;-webkit-text-size-adjust:100%;color:#212529;font-family:sans-serif;=
font-size:12px;line-height:15px;mso-table-lspace:0pt !important;mso-table-r=
space:0pt !important;padding:20px;text-align:center;"><br style=3D"-ms-text=
-size-adjust:100%;-webkit-text-size-adjust:100%;"/><br style=3D"-ms-text-si=
ze-adjust:100%;-webkit-text-size-adjust:100%;"/>
Open Learning Initiative<br style=3D"-ms-text-size-adjust:100%;-webkit-text=
-size-adjust:100%;"/>
Carnegie Mellon University<br style=3D"-ms-text-size-adjust:100%;-webkit-te=
xt-size-adjust:100%;"/><span class=3D"unstyle-auto-detected-links" style=3D=
"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;">5000 Forbes Ave,=
 Pittsburgh, PA 15213 US</span><br style=3D"-ms-text-size-adjust:100%;-webk=
it-text-size-adjust:100%;"/><br style=3D"-ms-text-size-adjust:100%;-webkit-=
text-size-adjust:100%;"/></td></tr></table></div><table role=3D"presentation" cellspacing=3D"0" ce=
llpadding=3D"0" border=3D"0" width=3D"100%" style=3D"-ms-text-size-adjust:1=
00%;-webkit-text-size-adjust:100%;background-color:#f8f9fa;border-collapse:=
collapse !important;border-spacing:0 !important;margin:0 auto !important;ms=
o-table-lspace:0pt !important;mso-table-rspace:0pt !important;table-layout:=
fixed !important;"><tr style=3D"-ms-text-size-adjust:100%;-webkit-text-size=
-adjust:100%;"><td style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adj=
ust:100%;mso-table-lspace:0pt !important;mso-table-rspace:0pt !important;">=
<div align=3D"center" class=3D"email-container" style=3D"-ms-text-size-adju=
st:100%;-webkit-text-size-adjust:100%;margin:auto;max-width:600px;padding:2=
0px 10px;"><table role=3D"presentation" cellspacing=3D"0" =
cellpadding=3D"0" border=3D"0" width=3D"100%" style=3D"-ms-text-size-adjust=
:100%;-webkit-text-size-adjust:100%;border-collapse:collapse !important;bor=
der-spacing:0 !important;margin:0 auto !important;mso-table-lspace:0pt !imp=
ortant;mso-table-rspace:0pt !important;table-layout:fixed !important;"><tr =
style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;"><td styl=
e=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;color:#2d3436;=
font-family:sans-serif;font-size:12px;line-height:20px;mso-table-lspace:0pt=
 !important;mso-table-rspace:0pt !important;padding:20px;text-align:left;">=
<p style=3D"-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;margin:=
0;">
The Open Learning Initiative enables research and experimentation with all =
aspects of the learning experience.
As a leader in higher education&#39;s innovation of online learning, we&#39=
;re a growing research and production project exploring effective approache=
s since the early 2000s.

                            <br style=3D"-ms-text-size-adjust:100%;-webkit-=
text-size-adjust:100%;"/><br style=3D"-ms-text-size-adjust:100%;-webkit-tex=
t-size-adjust:100%;"/>
                            To learn more about our platform visit
                            <a href=3D"https://oli.cmu.edu" style=3D"-ms-te=
xt-size-adjust:100%;-webkit-text-size-adjust:100%;color:#2c66c4;text-decora=
tion:none;">
https://oli.cmu.edu
                            </a></p></td></tr></table></div></td></tr></table></center></body></html>
------=_Part_808004_2060672440.1690554545522--`

**Comment by halturner** [comment]
Github wouldn't let me attach the .eml file I downloaded from Gmail. [Here it is hosted in Box.](https://cmu.box.com/s/zh3a5pbqmwe4me7qh1r9w4m3ly5vel9t)

**Comment by eliknebel** [comment]
This might be a good issue for @efhastings to take a look into

**Comment by efhastings** [comment]
I have no access to  https://eliterate.atlassian.net/browse/MER-2436.
What significance does "promotional" have? Is that a new word for spam?
I'm not gaining any insight from the email message that Hal posted, either.
Can someone please tell me what the steps are for what's supposed to happen, and where it failed?

**Comment by eliknebel** [comment]
Sorry for the non-context here Gene, we just discussed this one in triage and thought you might be able to provide some expertise here. Perhaps @halturner can provide some more information, but the gist is that he's identified some emails coming from torus being bucketed in gmail as "Promotional" and we wanted to look into see if there is anything on our end (SES, email format, etc...) that can be tweaked so that doesn't occur, since they are not promotional emails, they are account management emails.

**Comment by efhastings** [comment]
I did some digging. It appears to be a feature of GMAIL having done us all the favor of introducing tabs with incoming mail identified according to some opaque algorithm for filing.

I don’t know if we can do anything on the sending end to permanently get by Google’s classification bot. Perhaps by making the messages look more conversational? I’m guessing that anything that looks like boilerplate (and Google will see a lot of samples even of ours) is classed as promotional. It doesn’t matter if it’s administrative - the code can’t tell that yet, or may become skeptical. It’s the fact that the body resembles a LOT of other messages passing through Google with the same basic structure with minor variations - AND with something to click!

While I can think of specific things for Hal, I can’t think of something to advise an ordinary user to do, except when they initiate the request button, provide a message to tell them to double check their tabs and spam folder. I’ve seen multiple merchants and sites with accounts include the caution that it might get filed as spam. Which tells me that this happens to everybody’s form letters.

One other thing occurs to me, which may not help - and I’ll see what I can find - does SES provide settabiltiy for the weak email authentication like spf, dkim or dmarc? That might help attribution, but there will be legitimate companies sending promotion mail, so it may not make a difference.

Does this make any sense to you?

Gene
