### ISSUE TITLE
If creating new account during registration, return to registration process after confirming email address

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4050]
When a student is following a registration link, the registration process should not be interrupted by email verification. 

The current order of the process is this:

1. student follows invitation/registration link
2. student creates new account, and Torus lands on a login page with "You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you." notification message at the top.
3. student navigates to email and finds verification email to click "CONFIRM EMAIL" button.
4. a new tab opens with a notification message at the top about the confirmation succeeding, but the new tab is just a login page.
5. the student must figure out that they need to log in and continue the process.

The preferred process would be different starting with Step 4:
1. student follows invitation/registration link
2. student creates new account, and Torus lands on a login page with "You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you." notification message at the top.
3. student navigates to email and finds verification email to click "CONFIRM EMAIL" button.
4. preferred (if the student is still in the same browser window): the same registration tab gets focus, and instead of asking them to sign in they're simply presented with the "you're registering for this course" step of the process.
5. not preferred: a new tab opens and instead of asking them to sign in they're simply presented with the "you're registering for this course" step of the process. This isn't optimal, because it results in an orphan tab being leftover from the original registration-process click.

**Comment by eliknebel** [comment]
Likely need to add a unit test for this case, considering this issue keeps popping back up
