### ISSUE TITLE
"Up Next" link to container does not render correctly

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#4053]
**Describe the bug**
Normally containers are rendered with a light table of contents -- Units show the modules, Modules show the pages. This is how the system works when these containers are accessed via the arrowed navigation or from the lower pane of the portal.  However when the module has a read-by date, it will be recommended in Up Next.  The Open link from Up Next opens a page that renders like a blank, normal page (a page number and nothing else) instead of the table of contents view.  

In addition, note in the screenshot below that the mis-rendering also claims to be page 5.  This should not be page anything (these container pages aren't numbered); the 5 is actually the module number.

**To Reproduce**
Head to https://proton.oli.cmu.edu/sections/real_chemistry_i__07212023/overview as a student before Aug 4th and click on the open link

**Expected behavior**
I expect the container page to look like this no matter my originating link:
<img width="1460" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/77619f16-c450-43f8-bf8c-da950431e417">

**Screenshots**
But when I click on Open in from this view: 
<img width="669" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/3207f26b-db91-4e74-87ee-7fa537916860">  
Opens to: 
<img width="1443" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/4159081f-019a-43c7-87c6-01f9df08eca8">

**Comment by bitbldr** [comment]
merged v25
