### ISSUE TITLE
Hints for dropdown questions multiply instead of being deleted.

### ISSUE THREAD

**Issue by meturner1122** [Simon-Initiative/oli-torus#4057]
**Describe the bug**
After clicking the X button next to a hint input box on a dropdown question, multiple additional hints are added instead of the selected hint being deleted. 

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-31 at 10 06 35 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/135067656/ddb12e9e-2bf4-4ae8-a93a-a5f676859b98">
[Link to Torus](https://proton.oli.cmu.edu/authoring/project/wellstart_original_migration_c/resource/xdacr_saying_goodbye_while_saying_he_g941x)

**Environment:**
MacOS, Chrome

**Comment by meturner1122** [comment]
Original version of the buggy question had been deleted since the course is going to be published soon, but here's the link to a duplicate version of the course: https://proton.oli.cmu.edu/authoring/project/wellstart_20_copy/overview

**Comment by bitbldr** [comment]
fixed v0.24.3
