### ISSUE TITLE
UX/UI - My courses view for Instructors

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4084]
**Is your feature request related to a problem? Please describe.**
My courses view needs to differentiate between courses enrolled and courses published for instructors. Also, it would be nice to have a search function. Note this is with direct delivery, but it is likely this will also be a problem for LTI connected instructors as well. 

current:
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/b4940c3a-d642-4bcd-8c4f-f09f7263dd58)

**Describe the solution you'd like**
1. Expose which courses are enrolled and which courses are published for instructors
2. Add search function for my courses view 

Version
.24

**Comment by darrensiegel** [comment]
I'm not sure I understand what you mean by "published for".  Can you elaborate on that?  This view intends to show an user the course sections that they are enrolled in (whether as an instructor or as a student).

**Comment by cjlim1092** [comment]
This view shows courses which an instructor is administering as well as courses an instructor may be enrolled in. In legacy, this view was also condensed, but an instructor who is also enrolled in classes could tell the difference because there were more options such as the learning dashboard and system check in classes which they were the instructor. In the screenshot below you can see a class I am an instructor in in red and one I am a student in in yellow. This is not a good solution, but I do feel like one should eventually be added. 

Legacy
![Screenshot 2023-08-07 at 9 11 04 AM](https://github.com/Simon-Initiative/oli-torus/assets/32859465/a08d2d90-7423-4f42-953a-5fbc32397356)
