### ISSUE TITLE
[Migration bug] Copy and paste adding additional tag

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4086]
**Describe the bug**
Right now I have two windows open. One in the Page Editing so I can see the questions I want to copy, and another window with the activity bank. Often after I have copied content from the page (when I’m in question tab on both screens) and go paste into the activity bank, it triggers adding a random tag in the activity bank question. It’s weird. I’m trying to figure out what’s unique about the times when that doesn’t happen.

**To Reproduce**

Copying from (where I am currently): https://proton.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/resource/wkhhy_turning_down_a_drink_s6pp4

Copying to: https://proton.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/bank#

1. In activity bank>create new> multiple choice
2. I add an LO and add a new tag
3. I go to the curriculum page window, copy a question
4. When I click back on the activity bank window and hover over the question field, I see the cursor insert, but as soon as I click the mouse
5. *Boom* new tag

**Expected behavior**
No new tag should be added

**Environment (please complete the following information):**
 - Version: 24

**Additional context**
Working with migrated course, further development

**Comment by eliknebel** [comment]
Can we get some more details here, perhaps a screenshot or recording of the issue?
