### ISSUE TITLE
[Migration bug] Error when deleting question on migrated page

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4087]
**Describe the bug**
In the questions that imported from Echo, that do have an extra targeted feedback with the checkbox checked for the correct answer, if I delete that the question suddenly has an issue and is replaced with an error box that indicates wait and do a screen refresh. Waiting and refreshing doesn’t seem to do anything.  The good thing is I’m copying from the content pages so I’m not losing any work or much time.

Note: Questions are being copied from content pages into an activity bank. 
Copying from (where I am currently): https://proton.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/resource/wkhhy_turning_down_a_drink_s6pp4
Copying to: https://proton.oli.cmu.edu/authoring/project/partyscience_and_sparc_copy/bank#

**Environment (please complete the following information):**
 - Version: 24

**Additional context**
Bug from migrated course

**Comment by eliknebel** [comment]
Can we capture a screen recording of the issue?
