### ISSUE TITLE
Change "Preview Course as Instructor" to "Preview Course in Student View"

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#4089]
**Describe the bug**
A suggestion from both myself and Mark Blaser - in the Instructor view, under "Manage", there is an option to "Preview the Course as Instructor". Clicking on this takes you to a student preview of the course. We think the "Preview Course as Instructor" wording does not reflect the function / the intended use.

**Expected behavior**
We suggest renaming it to something like "Preview Course in Student View/Mode/Etc", something that indicates the actual function. "Preview Course as Instructor" implies an instructor view of the course.

**Screenshots**
<img width="735" alt="Screenshot 2023-08-08 at 8 17 06 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/100791229/ad727979-bc16-4f0c-ac52-6a7f1502e914">

**Comment by eliknebel** [comment]
Previewing is, in-fact, an instructor view so the button text is correct here but this ticket may indicate a UX issue around how exactly this feature works and what it is intended to be
