### ISSUE TITLE
Activity bank question causes "Could not find correct response" error in authoring

### ISSUE THREAD

**Issue by andersweinstein** [Simon-Initiative/oli-torus#4092]
Attempting to edit this chemistry question causes an error with message "Could not find correct response". Same error occurs on merely viewing answer key for certain parts of question.

Course Activity Bank:
https://proton.oli.cmu.edu/authoring/project/real_chemistry_i_taylors_versi/bank

Search for tag `po1_atomic_radius_pool`

Question title is `po1_atomic_radius_pool-describe_atomic_radius_pool_v2`

Question appears to have correct answers defined in XML source used for migration:
https://svn.oli.cmu.edu/svn/content/chemistry_general/chemisty_general1/trunk/content/u6_elect_structure/m3_periodic_properties/x-oli-assessment2-pool/po1_atomic_radius_pool.xml

One note is that an input id in this question differs from the partId (partId "twp" corresponds to input id "two"); possibly some torus code assumes they will be the same.

**Comment by eliknebel** [comment]
To debug, we need an easier way to access the JSON/revision history for activities in the activity bank
