### ISSUE TITLE
Bullet points not working beside default one

### ISSUE THREAD

**Issue by gautamyadavs** [Simon-Initiative/oli-torus#4123]
**Describe the bug**
a minor bug in torus which wasn't there before but after trying in multiple pages, I cannot seem to make it work so thought I will report, font in bullet works if it's default one but if I change it to numbered fonts than I cannot do any related action like create sub-bullets, indentation, remove bullets, etc.

**Expected behavior**
Bullet options for editing shouldn't go away.

**Screenshots**
https://github.com/Simon-Initiative/oli-torus/assets/25340998/979ba2aa-c4cc-4a8b-b40e-9cc0ca5a9f42

**Environment (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by bitbldr** [comment]
Maybe related to https://github.com/Simon-Initiative/oli-torus/issues/4090
