### ISSUE TITLE
Requiring enrollment renders existing guest invitation URL moot

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4131]
**Describe the bug**
If an instructor sets up a course and shared the guest invitation link, it will no longer work when the "require enrollment" setting is later checked by the instructor.

**To Reproduce**
1. Build a new Torus course and confirm it's NOT set to require enrollment.
2. Create an invitation link
3. Change the setting to "require enrollment."
4. Follow the existing invitation link.
5. Note there is an endless loop that doesn't result in an error message.

**Expected behavior**
Once this URL is no longer useful, either 

- PREFERRED: default to an interface that requires enrollment (login or account creation) OR
- display an error message stating the URL is no longer valid and they should check with the instructor for a new link.

**Screenshots**
N/A

**Environment (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by darrensiegel** [comment]
Is another PREFERRED solution here to simply allow the original invitation link to work, but it requires the student to create an account ?

**Comment by halturner** [comment]
Yes, that's what I tried to describe with the first preferred option, that the link would now require enrollment (which is either logging in, or creating an account and logging in).

**Comment by bitbldr** [comment]
We need to test this further to identify gaps in the system, specifically around toggling "Requires Enrollment".

We also want to make the "Requires Enrollment" checkbox an admin-only feature.
In legacy, once a student enrolls, the section can no longer be changed from open and free.
