### ISSUE TITLE
Apply same times to all Start Dates and to all Due Dates

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4133]
**Is your feature request related to a problem? Please describe.**
Manually entering a time for each Start Date and each Due Date is tedious and largely unnecessary. Instructors almost exclusively use the same times for all their Starts and  Dues

**Describe the solution you'd like**
A bulk-application field that lets you apply the same time to all Start Dates and another time to all Due Dates. For example, all assessments are available at 12:01am EST and are due by 11:59pm EST. Individual times could be overridden for the entire roster, or in individual exceptions. With the times automatically applied, only the dates need to be manually set.

**Describe alternatives you've considered**
Inheriting the Start Date time from the last one you set, and likewise for the Due Date time. So if you set Assessment 1 to start at 12:01am EST, Assessment 2 defaults to 12:01am EST with the option of changing it.

**Comment by bitbldr** [comment]
Perhaps during course section creation, this would be an option to set a default date.

Currently these dates are set in the "Assessment Settings" page
<img width="1169" alt="Screenshot 2023-08-29 at 2 57 13 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/ab2ad583-aae8-41ee-b149-6f59eb25e794">

**Comment by bitbldr** [comment]
Alternatively, we could add the ability to set "default start/end times" or "preferred time to schedule things".

@halturner would this meet the need? What exact wording do we want here.

**Comment by bitbldr** [comment]
We would also need this default to be changeable after initial section creation
