### ISSUE TITLE
Preview with activity bank questions shows error

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#4141]
**Describe the bug**
When page or course preview is selected to view a page with activity bank selections, you get 500 error.

**To Reproduce**
1. In authoring, Go to any page with an activity bank selection
2. Click on page preview (or this happens even for the course preview also)
4. New tab opens up with the error

**Expected behavior**
would like to see a preview

**Screenshots**
<img width="714" alt="Screenshot 2023-08-28 at 11 28 59 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/44871835/ee21d2b3-7f3a-4182-94f3-8b54fde65084">

**Environment (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 115.0.5790.170 (Official Build) (x86_64)

**Comment by halturner** [comment]
https://proton.oli.cmu.edu/authoring/project/erins_test_course/resource/new_page_whww0

**Comment by normanbier** [comment]
The example above contains a bunch of different activities, including three activity banks.  All of the activity banks are lacking any selection rule, which I think is what's causing the error.

If you need a simple page that has only one activity bank AND has a rule for selecting, you can see it here:
https://proton.oli.cmu.edu/authoring/project/erins_test_course/resource/test_graded_page_with_activity
-->Note that this does not trigger an error, it previews just fine.

However, creating a single activity bank with no criteria also previews gracefully:
https://proton.oli.cmu.edu/authoring/project/_a_bier_test_course/resource/new_assessment_activity_bank_w

**Comment by bitbldr** [comment]
Likely related to https://github.com/Simon-Initiative/oli-torus/issues/2769

**Comment by bitbldr** [comment]
We need to ensure the system is doing something sensible in delivery when this condition occurs. We might need to add some features to indicate to an author, perhaps a QA check, that their selection will never actually be fulfilled

**Comment by normanbier** [comment]
I just dug in a little more.  It's not enough to have a selection w/ no criteria of an activity bank (that will still preview) -- you also need a criteria that is impossible, like this: https://proton.oli.cmu.edu/authoring/project/_a_bier_test_course/resource/new_assessment_activity_bank_w

<img width="1163" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/4762701/ab3f02ca-e7db-4822-8213-6274c445c4ad">

Adding one impossible criterion ("limit selection to drop downs" when there is no drop down in the pool) triggers the 500 error on preview.
