### ISSUE TITLE
Specific page changes format on iPad / not responsive

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#4142]
**Describe the bug**
When doing a click-through of REAL Chemistry on an iPad (https://proton.oli.cmu.edu/sections/erins_real_chemistry/overview) I discovered that one page in the sequence was not displaying with the same responsive affordances as others in the sequence. Instead, the page displays with the same format as the "normal" web browser

**To Reproduce**
On an iPad, log into the course above as a student. 
 Go to page 35, then click through to page 36 (using the 'next' option at the bottom of the page).  Note the layout change on 36.  
Now click through to page 37.  Note the return to expected layout

**Expected behavior**
Page 36 should have the same layout as other pages (responsive design

**Screenshots**
Screenshots capture navigating through the three pages:
![IMG_A21E37691DCC-1](https://github.com/Simon-Initiative/oli-torus/assets/4762701/44ab16f9-ea05-4811-923a-f6ded8d68667)

![IMG_98388BD635B4-1](https://github.com/Simon-Initiative/oli-torus/assets/4762701/045d0351-7ac3-4659-9c7c-c59a2224bad9)

![IMG_54AFF8BCF188-1](https://github.com/Simon-Initiative/oli-torus/assets/4762701/7c0b04b7-33f0-4880-8ad4-008acbe0a1ca)

**Environment (please complete the following information):**
 - OS: iOS 15.6.1 (iPad Pro 11 inch 2nd generation)
 - Browser: Safari
 - Version: [e.g. 22]

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

**Comment by bitbldr** [comment]
Assuming the discussion element is what is breaking the layout here, we should be able to make a target fix to the mobile layout so that the discussion panel renders below the content
