### ISSUE TITLE
Admin "Not Authorized" to view student pages

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#4145]
**Describe the bug**
An admin should have access to all views in the system, specifically related to student overview and pages to help in regards to support requests.

Currently, instructors and admins have access to a "preview" view but cannot access student views without standing up proper student context etc. for the admin. There are other considerations here such as ensuing the admin doesn't contribute to section data and analytics.

**To Reproduce**
1. Go to student URL from a support email
2. See "Not Authorized" message

**Expected behavior**
Admin should be able to access the same view that students can. In the short term, this means redirecting an admin to the corresponding `/preview` route, but in the future it could include standing up a mock student context in order for an admin to exercise materials as a student would and see the same *exact* view a student is seeing.

**Comment by bitbldr** [comment]
This is a support need that was brought up by Kim & Hal in devteam channel and a blocker issue for support, and probably requires a hotfix

**Comment by bitbldr** [comment]
We could take a 2 step iterative approach to fix:
1. Render in preview mode, which is better than "Not Authorized"
2. Render an actual student view, with access to instructor information. Possibly mocking a student account or masquerading as the student from an admin account

**Comment by normanbier** [comment]
#2 relates to: https://github.com/Simon-Initiative/oli-torus/issues/4165 and https://github.com/Simon-Initiative/oli-torus/issues/4201
