### ISSUE TITLE
Learning objectives absent at Unit/ Module level view 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#4149]
**Description**
Learning objectives absent at the unit/module level view as opposed to how they are seen in legacy. See images below: 

Unit/ Module level page in Tokamak: 
<img width="1254" alt="Screenshot 2023-08-28 at 7 34 43 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/20156664/b461a10e-3c3b-4ced-b85f-1835daeda9c3">

Unit/ Module level page in OLI Legacy: 
<img width="947" alt="Screenshot 2023-08-28 at 7 34 29 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/20156664/59612597-8c70-4d5c-8fa3-b670ef3e8e8a">

**To Reproduce**
1. Go to tokamak.oli.cmu.edu as a student
2. Go to PC [Hardware course invite link](https://tokamak.oli.cmu.edu/sections/join/46e51) and enroll as student. 
3. Go to the [Hardware Basics page](https://tokamak.oli.cmu.edu/sections/pc_hardware_test_0818/container/the_basics_btgp7).  
4. Compare with PC Hardware in [legacy](https://oli.cmu.edu/jcourse/webui/syllabus/module.do?context=783b69340a0001dc02b4ceff14ea01ce)

**Expected behavior**
Learning objectives for Module/ Unit level would be great to have as instructors/ students can see all learning objectives for that unit. 

**Environment (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: 16.4

**Comment by bitbldr** [comment]
Legacy "rolls-up" page level attachments and displays them in the module view. We want to do the same in torus
