### ISSUE TITLE
Invite Instructors to Course Section

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4154]
**Is your feature request related to a problem? Please describe.**
Instructors need to invite other instructors to a course section.

**Describe the solution you'd like**
Instructors can send an invite to another instructor
Consider asking for confirmation that this is for an instructor not student

**Describe alternatives you've considered**
Current process
Instructor enrolled as student by invite link but wants to be an instructor, doesn't understand that they are a student since they have an instructor account
They email for help
admin searches instructor at https://proton.oli.cmu.edu/admin/users
click title of enrolled section
click actions, change student to instructor, click enroll

**Additional context**
N/A

**Comment by bitbldr** [comment]
Admins should have the ability to add anyone to any section as any role

**Comment by bitbldr** [comment]
Fixed v25
