### ISSUE TITLE
Need to Re-enroll Unenrolled Students and to Suspend Students

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4158]
Need to re-enroll a previously un-enrolled student, allowing them to continue with their previous progress.
(What happens now if we unenroll a student and then re-invite them to the same section and they sign in with the same account? Is their previous work there or not?)

There are several situations where we re-enroll previously unenrolled students and expect progress to be restored (accident, changed mind, schedule change, payment dispute, a school can ask us for student's progress from forever ago, and more). 

Further, there are several situations where it is best to preserve the UI of a previously enrolled student (i.e. Suspended enrollment status) (payments, history, accident, changed mind, grade disputes at their institution, preserving payment / enrollment history (how many paid), invoicing, and more). This requires a new enrollment status of Suspended.

**Comment by bitbldr** [comment]
The underlying functionality exists, we just need a UX to expose this ability to an admin or instructor
