### ISSUE TITLE
Invitation link should prioritize students/instructors

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#4174]
As currently structured, when student follows in invitation link, the structure of the page prioritizes the large "ARE YOU AN AUTHOR" element, pushing the student sign in / registration to the bottom -- the ability to create an account is not obvious, and is often pushed out off the screen.

The vast majority of individuals using the invitation link will be students and then educators. We should see a much smaller proportion being an author.  The page should emphasize and lead the Learner/Educator Sign in and demo the Authoring warning to the bottom of the page. 

As an intermediate fix, the two elements should be swapped. Longer term, the sign in processes need meaningful design attention.

To reproduce, use an invitation link: https://proton.oli.cmu.edu/sections/join/y4wb6

If I am a student who is following an invitation link, this page is very confusing.
![image](https://github.com/Simon-Initiative/oli-torus/assets/4762701/10ed1a90-f03b-4399-bbaa-6f7d12bbe165)

**Comment by bitbldr** [comment]
Logging in/creating an account via invitation link is a *very* common path and asking every student if they are "Looking for authoring" is confusing
