### ISSUE TITLE
Admin view: add list of projects to author account details page

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4185]
**Is your feature request related to a problem? Please describe.**
Admins need to know which projects an authoring account is associated with.

**Describe the solution you'd like**
When and admin visits an author's details page, they should be able to see and navigate to the projects that author is a team member of. Ideally the list would be sortable by title, date of project creation, date the author was added to the project, and the name of the person who added/invited them to the project (unless the author created it).

**Describe alternatives you've considered**
None. The only solution is checking projects individually or asking the author.

**Additional context**
N/A

**Comment by darrensiegel** [comment]
This exists in V25
