### ISSUE TITLE
[Migration bug] Text-entry fields inactive

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4187]
**Describe the bug**
Text-entry fields are migrating as empty boxes that are not clickable. Students should be able to type in the boxes and submit. 

**To Reproduce**
[Tokamak](https://tokamak.oli.cmu.edu/sections/conflictu_83123/page/xnxrx_inteam_activity_for_conflictu_s6hf3)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/2999c353-3361-4399-bc7d-1246c9fcc464)

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=6db016860a0001dc61b5dc911d01bed4)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/53fe2c28-6d27-4dc9-a562-070d06faecdf)
https://svn.oli.cmu.edu/svn/content/conflict_resolution/conflict_u/branches/v_1_5-echo

**Environment (please complete the following information):**
 - Version: 25

**Additional context**
ConflictU

**Comment by bitbldr** [comment]
This is a special case where content needs rework. But we need the migration utility to flag these as warnings.
