### ISSUE TITLE
[Migration parity] Description field on "my response" item types doesn't show

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4189]
**Describe the bug**
Description field at the top of the page is missing: Please answer the questions below. Your response will not be graded, but will be available for your instructor to read. Answering these questions may also shape the discussions in class.

[ECHO](https://echo.oli.cmu.edu/#intro_stats-5.2/stemplot_feedback?organization=intro_stats-5.2_prob_stat_r_openfree)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/statistics/branches/v_5_2-echo/content/_u2_summarizing_data/_m1_examining_distributions/x-oli-feedback/stemplot_feedback.xml)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/b50a6d71-e5e4-42aa-8bbd-027268645898)

[Tokamak](https://tokamak.oli.cmu.edu/sections/52_review_9123/page/fo843_about_stemplots_vgk3u)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/84703f07-f5a2-486f-9150-546ab3360d48)

[Legacy](https://oli.cmu.edu/jcourse/feedback/activity.do?context=9a55f60b0a0001dc2d581e3438ea4e88)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/41f3ac32-49b2-4b20-a549-be1c3f5f7ed5)

**Environment (please complete the following information):**
 - Version: 25

**Comment by bitbldr** [comment]
Migration tool needs to have support for description tag
