### ISSUE TITLE
[Migration bug] Alternatives that do not appear in legacy appear empty in migrated course

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4190]
**Describe the bug**
In stats choices Excel 2003 and statcrunch (no capital) are empty alternatives; these choices don't appear in legacy

[Echo](https://echo.oli.cmu.edu/#intro_stats-5.2/boxplot1lbd?organization=intro_stats-5.2_prob_stat_r_openfree)
[SVN](https://svn.oli.cmu.edu/svn/content/statistics/statistics/branches/v_5_2-echo/content/_u2_summarizing_data/_m1_examining_distributions/x-oli-workbook_page/practice/boxplot1lbd.xml)

[Tokamak](https://tokamak.oli.cmu.edu/sections/52_review_9123/page/fo843_boxplot_zt05p)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/76fb481a-4791-4c4c-904a-a39f66d4bbe8)

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=9a55f6590a0001dc09afc63f1ea49482)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/fd93fa5c-638d-4cbf-b102-655a4c1106ec)

**Environment (please complete the following information):**
 - Version: 25

**Comment by bitbldr** [comment]
Followup with @cjlim1092 to see if this is still an issue

**Comment by andersweinstein** [comment]
`alternative value="statcrunch"` occurs in the following files. These should be removed if it is not being used. 
```
content/_u5_inference/_m2_inference_for_relationships/x-oli-workbook_page/_u5_m02_two_independent_samples7_openfree.xml
content/_u5_inference/_m2_inference_for_relationships/x-oli-workbook_page/_u5_m02_two_independent_samples7.xml
content/_u5_inference/_m2_inference_for_relationships/x-oli-workbook_page/practice/_u5_m2_lbd3.xml
```

**Comment by bitbldr** [comment]
Per @cjlim1092 this will be a content fix
