### ISSUE TITLE
List unenrolled students, and permit reversal of unenrollment

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4204]
**Is your feature request related to a problem? Please describe.**
Unenrolled students are removed from a roster and barred from re-entry. There is no system-generated message, no list of unenrolled students, and no value associated with their account that indicates this action was taken. For students, instructors, and Torus admins it's impossible to track who is in this state.

**Describe the solution you'd like**
A record of the unenrollment.
A list of unenrolled students, per section roster.
The ability to reverse the unenrollment.
A notification email that's sent to the student and the instructor when the student is either unenrolled or reenrolled.

**Describe alternatives you've considered**
Legacy uses the notion of "suspension" to designate students who've been removed from the section, but who could be reinstated. Perhaps this middle ground is a better solution, and unenrollment can remain psuedo-permanent (permanent from the student/instructor end, reversible by Torus admin).
This middle ground would go toward feature parity with legacy, but unenrollment still needs to be tracked and knowable long-term.

**Additional context**
N/A

**Comment by bitbldr** [comment]
Duplicate https://github.com/Simon-Initiative/oli-torus/issues/4158
