### ISSUE TITLE
Student Attempt history lists "(yesterday)" even if it's two days ago

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4210]
**Describe the bug**
"(yesterday)" is appended to the Submitted timestamp for attempts not submitted yesterday

**To Reproduce**
Review Attempt History of a student whose attempts took place over multiple days.
https://proton.oli.cmu.edu/sections/elearning_design_principles_an/progress/10067/42948

**Expected behavior**

**Screenshots**
![Screenshot 2023-09-14 at 1 58 34 PM](https://github.com/Simon-Initiative/oli-torus/assets/24977416/dae7313b-18e5-4a36-b5a8-7caec653b024)

**Environment (please complete the following information):**
MacOS 13.5.1
Chrome 117

**Additional context**
NA

**Comment by bitbldr** [comment]
There is also duplicate #3 attempt here
