### ISSUE TITLE
Quiz Answers and Submissions when Offline

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4215]
Students should not be able to enter answers or submit quizzes when offline without an error or browser message as it leads to reports of "lost" answers and attempts.

Answers Offline
Start quiz, enter answers or not, go offline, enter more answers (this should not be possible), go online, enter more answers or not, submit quiz - answers entered offline are blank and reported by the student as "lost"

Submit Offline
Start quiz, enter answers or not, go offline, enter answers or not, submit, the button grays and says submitting (there should be an error or browser message here), go online, navigate to quiz, the quiz is in the same state as before went offline, quiz submit is reported as "lost" along with any associated answers entered offline

**Comment by bitbldr** [comment]
We need to test this condition out to see if it is an issue
