### ISSUE TITLE
Content reports: click Unit title to see its modules

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4224]
**Is your feature request related to a problem? Please describe.**
The Unit/Module selector isn't obvious, and the default should probably be Module.

**Describe the solution you'd like**
Because it's not very obvious how to see module-level content reports, clicking the title of a unit should take you to them.

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by bitbldr** [comment]
Add capability to click on a unit to see reports
