### ISSUE TITLE
Pages on Content report appear as links, but aren't clickable

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4225]
**Describe the bug**
In the Content report, pages appear as links, but nothing happens when you click them.

**To Reproduce**
1. Visit https://proton.oli.cmu.edu/sections/testing_collab_space_enablemen/instructor_dashboard/reports/content?page_id=454
2. Click one of the pages in the report

**Expected behavior**
Not sure; either the page itself, or a visualization of the data that contributes to the percentage that's being displayed. It depends on what useful information is available to share.
 
**Screenshots**
<img width="1608" alt="Screenshot 2023-09-19 at 2 08 34 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/cef0c261-1f3f-4694-944d-d95ceec0c9c8">

**Comment by bitbldr** [comment]
Links should take the user to the page
