### ISSUE TITLE
Student emails never exposed

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4226]
**Describe the bug**
There is no (obvious) way to see the email associated with a student in the roster.

**To Reproduce**
1. View the roster
2. View the student reports
3. Download reports.
4. Note there are no email addresses

**Expected behavior**
Email address as a column, next to the students' names
Email address visible on the student profile page

**Screenshots**
<img width="1608" alt="Screenshot 2023-09-19 at 2 12 33 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/3b6bc7b0-12de-480b-8a3d-a5367b524c5b">
<img width="1608" alt="Screenshot 2023-09-19 at 2 12 43 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/5075245e-eeb0-4e43-b4e9-dd057d51c854">

**Comment by bitbldr** [comment]
More than one student may have the same name, this would be crucial to being able to differentiate or uniquely identify students
