### ISSUE TITLE
Activity Bank Selection Equals vs Contains

### ISSUE THREAD

**Issue by gautamyadavs** [Simon-Initiative/oli-torus#4231]
**Describe the bug**
we just noticed that by default when we do equals (which is the default) instead of contains like in the screenshot it was not pulling any multi-input questions which led to students only getting 3 instead of 10 questions.

**Expected behavior**
Equals should select all question types that are labeled with that learning objective

**Screenshots**
<img width="748" alt="Screenshot 2023-09-19 at 1 20 03 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/25340998/73369da7-ec04-46d2-b61f-5857c5929299">

**Comment by bitbldr** [comment]
Equals should select iif the list of objectives matches exactly. We need to test this to make sure it is working as expected.
