### ISSUE TITLE
Duplicate Quiz #X (results in a stuck attempt so student cannot start another attempt)

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4250]
**Describe the bug**
Here is an example of a student with more than 1 attempt #X. Since 1 attempt is not submitted, the student cannot start another attempt. To resolve the issue, the duplicate attempt has been accepted so the student can start another attempt. We have not yet been able to replicate the multiple attempt #X issue though there have been other reports including from KTH.

On 2023-09-20 13:44:14.578099+00:00 UTC UTC, [name redacted](https://proton.oli.cmu.edu/admin/users/10080) > wrote:
When I do the quiz in module 7, I cannot start it once again, but it's said that I can do this an unlimited number of times.
----------------------------------------------
Timestamp: 2023-09-20 13:44:14.578099+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/sections/elearning_design_principles_an/page/gltl7_quiz_cckwq

**To Reproduce**
Unable to reproduce

**Expected behavior**
each attempt should have a unique number
student should be able to submit their attempt or start a new attempt without manual acceptance of the stuck duplicate attempt

**Screenshots**
![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/e5dcf0c5-54f2-42fd-a63e-cdf78acbe725)

**Environment (please complete the following information):**
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Accept: */*
Language: zh-CN,zh;q=0.9

**Additional context**
This has been reported from multiple courses and instances including KTH.

Current protocol is to report and document the issue, resolve the issue by accepting the duplicate attempt, and ask for more information as follows:
In an effort to research this to avoid the issue happening again, did you notice anything unusual that happened while you were starting the attempts?
Did you ever have to start it again?
Switch browsers or computers? 
Leave an attempt open in the browser for a few hours?
Start and attempt and open another tab in the course?
See an error message?
Experience any Internet disconnection or switch from wifi to network?

**Comment by bitbldr** [comment]
Next steps, we need to analyze database records at the page attempt level since we have not been able to reproduce the issue in a developer environment.

The issue seems to be isolate to certain courses

**Comment by kwahlenmayer** [comment]
Here is another example with 2 #1 attempts. The 2nd had to be manually accepted so the student could start another attempt.

https://proton.oli.cmu.edu/sections/chem_001a_020_23f__general_che/progress/13430/62360
This is Real Chem making it 3 course packages where this has happened.
I wonder if anyone can see the start times of the attempts to see if two are spawning at the same start time.

**Comment by kwahlenmayer** [comment]
Here is another example with 2 #5 attempts:
https://proton.oli.cmu.edu/sections/elearning_design_principles_an/progress/10067/43022

We received this report:
I talked with a student for which it happened 2nd time and she said both times the glitch happens after she tried going back to the previous page on the browser after starting the attempt. In this instance, she was trying to go to the page where it shows all of her previous attempts after starting 5th attempt but somehow that just started a new 5th attempt automatically and she lost access to the page so I need to manually submit for her before she can start 6th attempt.|

In testing this:
When I have an open attempt, I cannot get back to the page with the list of attempts by either the back button in the browser or by opening the quiz attempt in a new tab. Instead, my open attempt appears. In conclusion, still not able to replicate the duplicate #X quiz attempt.
