### ISSUE TITLE
Group paging policy dropdown disappears on mouse over

### ISSUE THREAD

**Issue by andersweinstein** [Simon-Initiative/oli-torus#4252]
**Describe the bug**
In a group with content breaks, the page policy dropdown (left of audience dropdown) disappears on mouse over. This makes it hard for author to discover how to edit the setting.  

**To Reproduce**
Open a page with a multi-page group in authoring. 
See page policy setting in blue left of audience dropdown, e.g. "Allow user to paginate through items'
Hover mouse over it.
See area becomes blank.

However, clicking in the now-blank area does show a dropdown menu (see screenshot). 

**Expected behavior**
Expect it to remain visible. 
Might also be helpful to have some visual indicator that this is an affordance for obtaining a dropdown. But at minimum should not disappear.

**Screenshots**
<img width="580" alt="Screenshot 2023-09-27 at 1 45 57 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/7094628/0b6ca6cb-ef9d-4486-bed7-0ecb4550d81c">

<img width="375" alt="Screenshot 2023-09-27 at 1 46 49 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/7094628/47b05710-b0d6-4636-b979-8527609f26be">

**Comment by bitbldr** [comment]
Likely a CSS issue
