### ISSUE TITLE
In-page toggle for changing between instructor view and student view

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4254]
**Is your feature request related to a problem? Please describe.**
Instructors express confusion about the difference between previewing the course as a student and the "instructor view."

**Describe the solution you'd like**
Instead of two distinct paths that must be entered and exited, instructors could see every page and change between the instructor and the student views. Ideally, instructors could even enter a student's name / email / ID, and see their work on the page. "View as a specific student."

The toggle could be a dropdown list located in whatever part of the page is anchored when you scroll. It would retain your current state until it's manually change. The states would be View As:

- Instructor, to view answers to all activities and the Learning Objectives linked to them
- generic student who can interact with activities
- specific student to view their work on this page

**Describe alternatives you've considered**
Just the existing approach.

**Comment by bitbldr** [comment]
We likely can get most of what we need here just by adding a student rendered view/tab to the current instructor preview for activities

**Comment by halturner** [comment]
Existing related ticket: https://github.com/Simon-Initiative/oli-torus/issues/4201
