### ISSUE TITLE
z-index issue between the page title and the create menu modal 

### ISSUE THREAD

**Issue by rgachuhi** [Simon-Initiative/oli-torus#4267]
**Describe the bug**
The page title covers the "create" menu modal in authoring mode. Looks like a z-index issue.

**To Reproduce**
1. Edit any practise page
2. Click on 'create' menu on the left column
3. Notice that the 'page title' covers a portion of the create modal.

**Expected behavior**
The menu should render on top of the page title

**Screenshots**
![Screenshot 2023-10-02 at 3 45 33 PM](https://github.com/Simon-Initiative/oli-torus/assets/11138398/5c5254d7-d2ea-40ea-83e2-5176384359f0)

**Comment by bitbldr** [comment]
fixed v25
