### ISSUE TITLE
ADMIN: Payment tracking and visibility

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4270]
**Is your feature request related to a problem? Please describe.**
There is no easy way to see which students have paid, and what method they used.

**Describe the solution you'd like**
User-level solution: On the user profile page, include information about if/when grace period was elected, when payment was submitted, and what method they used. If credit card, link to the credit card transaction in Cashnet. If they used a payment code, make it known which one.

Roster-level solution: on roster page, display for instructor and admin a column with paid date. For admin, add a column for payment method; if it's a code, display it; if it's a credit card payment, link the label "credit card" to the payment record in cashnet. Ask Norm if the instructor should know the payment method, or if that should be admin only. Columns should be sortable and values should be searchable.

Admin-level solution: an interface that lets you view all payment codes and make them exportable, searchable and sortable. Search results should be available in browser, not just via export. Default view should be either Date Created (recent) or Date Redeemed (recent).
Search by:
- redeemer name, email, institution
- instructor of section where redeemed
- institution 
- product
- value
- date created (on date, not on date, before date inclusive, after date inclusive, date range inclusive)
- date redeemed (on date, not on date, before date inclusive, after date inclusive, date range inclusive)
- creator
- refund granted (date stamp in local time and by what user; consider adding NOTES field to refunds, and making it searchable and revealable via click)

Sort by:
- same values as Search

Other queries:
- We should have visibility into all aspects of payment, and be able to view in the aggregate across many dimensions:
    - Institution (one or more)
    - Product(s) (one or more)
    - Numbers of paid enrollments and unpaid enrollments (roster, product, institution, date, can combinations of these)
    - Dates
    - Refunds granted
    - Total values of revenue collected, revenue refunded, and ability to break out by method (credit card, payment code, institutional arrangement, grant-funded)

**Describe alternatives you've considered**
None. I don't know how to find Torus payment code redemption information at all.

**Additional context**
If an institutional discount has been put in place for a percentage off, add a searchable/sortable column.

**Comment by bitbldr** [comment]
Some of this does exist under products.
<img width="1296" alt="Screenshot 2023-10-03 at 2 24 21 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/6248894/1624bf83-f290-41e9-965b-89acb142e0e0">

There are also some tools for instructors in the instructor dashboard.

**Comment by bitbldr** [comment]
@halturner will determine what aspects of this are still relevant given the existing functionality
