### ISSUE TITLE
Add knowledgebase link to Tech Support modal

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4279]
**Is your feature request related to a problem? Please describe.**
The platform includes no link to the knowledgebase.

**Describe the solution you'd like**
Add this language, which links to this URL:

Find answers quickly in the Torus knowledge base and FAQ.
https://olihelp.zohodesk.com/portal/en/kb

![support modal](https://github.com/Simon-Initiative/oli-torus/assets/24977416/68110af8-9c20-43c0-ada5-5ef5b4fc5ee4)

**Comment by bitbldr** [comment]
Should be configurable on a per-torus instance basis. Even better would be configurable at the institution and community level.
