### ISSUE TITLE
Emoji Functionality in Discussions

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4294]
**Is your feature request related to a problem? Please describe.**
An author suggested: Requesting emoji feature for discussion posts so you can react instead of writing a response

**Comment by bitbldr** [comment]
Adding a feature to tag a post with an emoji (e.g. thumbs up/down, etc). Could be consider as part of the larger social annotation.

Current workaround is pasting an emoji into  a discussion post
