### ISSUE TITLE
Dark Mode: Readability of Yellow Buttons with Yellow Text in DnD

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4297]
**Describe the bug**
 This was originally added as a comment in an existing Dark Mode ticket. Based on discussion in OLI Torus Support slack, this report is broken out into a separate issue.

New report from student.

On dark mode, the text for the drag and drop buttons is changed to white like everything else, but as the “buttons” that you are dragging are light yellow, it makes it near impossible to read the text on them.

----------------------------------------------
Timestamp: 2023-10-04 22:21:56.646846+00:00 UTC UTC
Ip Address: 0.0.0.0.0.65535.32512.1
Location: https://proton.oli.cmu.edu/sections/chem_001a_020_23f__general_che/page/vwx8a_dimensional_analysis_multistep_h5ud3

WEB BROWSER
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Accept: */*
Language: en-US,en;q=0.9

**Comment by kwahlenmayer** [comment]
![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/31ff84e7-0fb7-4923-82a8-ce7c7e4e8671)
This is another page in the same course showing the issue.

**Comment by bitbldr** [comment]
Styles are embedded within the drag and drop activities themselves, we need to:

1. Update the stylesheet in the authoring interface to support dark mode (add a higher class selector of `.dark`)
2. Fix the drag and drop implementation to not have embedded/user-configurable styles
3. Possibly choose a default color that works in both light and dark mode (works with white and dark text)

**Comment by andersweinstein** [comment]
I would add 

4. add "color: black" to .initiator styles on CSS tab to ensure black text in all modes. 

The default dnd stylesheet pasted in by migration tool when source dnd has no custom styles includes this style (though it does not use a pure black). This stylesheet renders draggables in a light blue box with dotted grab handles, as seen in Echo-generated tabular DnDs.

However, the default style sheet used for newly created DNDs in torus uses a different style like the chem yellow boxes.
