### ISSUE TITLE
Soft Schedule can't be removed

### ISSUE THREAD

**Issue by normanbier** [Simon-Initiative/oli-torus#4308]
Once a soft schedule has been set, it is impossible to "blank out" or "clear" the schedule. You are able to change to a different schedule, but there is no mechanism for simply removing the schedule. 

We need some kind of mechanism for clearing a schedule completely.

**Comment by bitbldr** [comment]
"Reset Timelines" will only reset back to suggested schedule. We need a "Clear" function to remove schedule
