### ISSUE TITLE
Significant Figures not Correct

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4310]
https://proton.oli.cmu.edu/sections/real_chemistry_1/page/measurements_module_checkpoint/attempt/80aff7de-79eb-4a79-bf11-2a5fe4835cb7/review

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/940b1e27-0c98-4026-b124-86160f523a56)

**Comment by sandyraysor** [comment]
This has the correct sig figs based on how legacy handled precision, but apparently Torus is handling precision differently. 
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/85dd125a-a5bc-4d20-a941-e6716e51ba2f)

**Comment by andersweinstein** [comment]
This was already  captured as https://eliterate.atlassian.net/browse/MER-2557 which remains open.

Until torus implements support for significant figures (or legacy parity on this), a workaround where answer requires proper significant figures could be to use string-valued answers, using multiple correct answers to match different acceptable forms (0.36, .36, 3.6e-1, 3.6E-1) and some targeted incorrect forms for likely forms that are numerically correct but wrong on significant figures (e.g. 0.360, 3.60e-1)

**Comment by sandyraysor** [comment]
I don't have access to jira. Is there someone who is going to walk the
course and do this for affected questions?

Sandy

**Comment by bitbldr** [comment]
We need a solution that meets the criteria:
1. A solution that behaves as expected/properly in torus, that aligns with the actual definition of significant figures
2. Also meets the need to how legacy handled significant figures so that courses are backwards compatible
