### ISSUE TITLE
Marking incorrect when its correct 

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4311]
https://proton.oli.cmu.edu/sections/real_chemistry_1/page/measurements_module_checkpoint/attempt/5e051672-552b-430c-9ed2-74030dc6a743/review

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/8b8d2cc9-0e13-4cb4-80c3-08a117fd781e)

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/7ad7249c-f198-48c3-b900-d1d87fcb138a)

Answer is set to 0.006, but when a student answers this as the answer it says its wrong.

**Comment by bitbldr** [comment]
This was caused by a hotfix v0.24.5 missing in the release v0.25.0
