### ISSUE TITLE
Update D2L Brightspace registration form's auto-population values

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4316]
**Is your feature request related to a problem? Please describe.**
The values that OLI auto-populates for D2L registrations are not all correct.

**Describe the solution you'd like**
Auth server value: https://api.brightspace.com/auth/token
Auth token URL value: https://auth.brightspace.com/core/connect/token

**Describe alternatives you've considered**
manual changes

**Additional context**
These changes enable grade passback, and possibly other things.

**Comment by bitbldr** [comment]
Fixed
