### ISSUE TITLE
Improve student progress download file

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4320]
**Is your feature request related to a problem? Please describe.**
The excel file generated via Reports > Students > Download differs from the on-screen presentation in a few ways. The following changes are suggested to make the file more useable. A sample file is attached.

**Describe the solution you'd like**

1. Split the single student name field into First Name and Last Name. On Torus, students are sorted by last name first. In the file, students are sorted by first name first, making it difficult to use the field in an LMS. 
2. The Last Interacted field includes unnecessary extraneous digits. 2023-09-28 15:22:51.000000Z is an example. Instead, it should be presented in the same format as Torus, Oct. 12, 2023 - 5:54 PM.
3. Progress in Excel should be a regular percentage. On Torus, Course Progress is a two-digit percentage. In Excel it's a expressed as a fraction of 1 with extraneous digits. An example: 0.9985714285714287. 
4. Align the last column and its purpose. On Torus it's Type and they're listed as Student. In Excel the column is "requres_payment". Payment status would be the better of the two choices.

**Describe alternatives you've considered**
N/A

**Additional context**
[partyscience_and_sparc__fall_2_students.csv](https://github.com/Simon-Initiative/oli-torus/files/12918509/partyscience_and_sparc__fall_2_students.csv)

N/A

**Comment by bitbldr** [comment]
We want to strike a balance between access to raw data from the system and also usability. This feature was likely geared towards the former.

Raw data should include full fidelity data and allow the user to choose how to format. But for more user focused features, we likely want to design the data towards the use case (i.e. human formatted dates for direct analysis)
