### ISSUE TITLE
(tokamak) course creation is timing out/ not leading to new course project when completing course building process

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4323]
**Describe the bug**
On tokamak direct delivery I get stuck in a ~publishing~ course builder loop (for this course [authoring](https://tokamak.oli.cmu.edu/authoring/project/gsu_elementary_statistics__per_t5hov/overview), [published](https://tokamak.oli.cmu.edu/sections/gsu_perimeter_stats_101623_57_/instructor_dashboard/manage)). After entering all the course details it takes a long time to publish without any feedback then leads directly to course selection again. This was not an issue before.

**To Reproduce**
1. Go to course section creation (direct delivery)
2. Create a new section
3. You will see the page return to course selection after clicking publish, before it would go to the published section. In my experience it has still created the course, but I get stuck in this publishing loop

**Expected behavior**
When publishing, it should lead to published section

**Environment (please complete the following information):**
 - Version: 26

**Comment by bitbldr** [comment]
Typically this is a course digest issue, where a resource is missing
