### ISSUE TITLE
Feedback Field Freezes / Does Not Save in Windows Chrome

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4339]
**Describe the bug**
Editing / adding feedback with backspace or punctuation or delete in an activity on a page results in freezing. So far this has happened in feedback fields in multiple projects, multiple user accounts, multiple browser, multiple networks. There is a video in the devteam channel.
This is resolved by refreshing the page where sometimes (always?) what has been typed after the freeze is not there. I can cause a freeze in one field and then wait a moment and type in another field but what is typed after a initial freeze all seems to be lost.
This is a complete blocker to creating activities. It can be avoided by using Windows Firefox or Mac.

**To Reproduce**
Open this test page in Windows Chrome, navigate to an activity, click answer key, click in a feedback field and type including a lot of punctuation and backspace and delete until typing no longer works and the page is frozen. Any subsequent typing if the freeze resolves will not be saved.
Test page:
https://proton.oli.cmu.edu/authoring/project/oli_sample_course/resource/new_page_7vu3y

**Comment by bitbldr** [comment]
Duplicate, in progress MER-2682
