### ISSUE TITLE
Remove "Manage Enrollments" view

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4346]
**Describe the bug**
It is impossible to sort or export progress for all students.

**To Reproduce**
Go to view all enrollments. For example: https://proton.oli.cmu.edu/sections/introduction_to_learning_engin_nu6db/enrollments
Click the progress column header, nothing happens
Export the csv, open in a sheet, view no progress column, column D is blank

**Expected behavior**
When viewing all enrollments, clicking the progress column header should sort by progress 0 - 100%, then clicking again should resort 100% - 0.
When exporting all enrollments, the progress % should be present in column D

**Screenshots**
![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/25d28eb9-6fa5-4339-b6b1-2fe2b8f81951)
![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/d0d4cf4d-0fc8-4d1b-9067-42a67719e5b0)

**Comment by darrensiegel** [comment]
Repurposed this issue to target the root cause.
