### ISSUE TITLE
Progress Calculation

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4347]
**Describe the bug**
Progress does not seem to calculate as expected. When I complete a module with activities on the page and a quiz, I cannot get 100% progress for the module.

It is expected to be:
For practice pages:  Progress is calculated based on the percentage of the activities that the student attempts on the page.  A page with 10 activities, where the student has attempted 3 of them would be 3/10 or 30% progress.  For practice pages that contain 0 activities the act of visiting the page set that page progress to 100%.
For graded pages: Progress is calculated again based off of percent of completed activities, but since the activities on a graded page are all submitted at the same time when the user clicks "Submit Assessment", graded pages typically only ever have either 0% or 100% completion.
Activities within surveys do not count towards progress. (though maybe each survey page needs to be visited?)
Discussions do not contribute.

**To Reproduce**
Invite yourself to this course and go through module 1 (3 pages), try to get 100% by answering all the questions and submitting a quiz. My OLI Support & Admin student account cannot get over 86% but other students have so it is possible.
https://proton.oli.cmu.edu/sections/partyscience_oli_support_admin/

Another project course section with students with 100% progress:
https://proton.oli.cmu.edu/sections/partyscience_and_sparc__fall_2/enrollments

**Expected behavior**
I expect to be able to achieve 100%. I have only been able to do this in modules with no questions and no quizzes, pages with text only.

**Screenshots**
![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/f680e5e5-c128-4df8-bbc4-572a91d55235)

**Comment by bitbldr** [comment]
Courses that contain adaptive pages, it will be very difficult (maybe impossible) to attain 100% - likely not applicable here. Another issue could be, course progress calculation also takes into account pages that are not present in the hierarchy but are linked from within a page (linked pages), and therefore students may not be actually navigating to these pages.

We need to investigate if any of these are applicable here, and ensure this is working as expected.

**Comment by bitbldr** [comment]
To test this, we should use a simple course with 1 practice page and 1 assessment. Put 3 activities on each. Work through and answer all questions.

This should result in 100% progress.

**Comment by kwahlenmayer** [comment]
Here's an image showing my progress through  module 1 which is 3 pages, 2 practice plus 1 quiz. I cannot share this page link which is only viewable by my student account.


![image](https://github.com/Simon-Initiative/oli-torus/assets/24357828/e2465acc-a479-406d-af93-404acdf711bd)
