### ISSUE TITLE
Formatting with Chemical Formulas

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4351]
https://proton.oli.cmu.edu/sections/real_chemistry_1/preview/page/vwx8a_precipitation_reactions_and_so_gty9v

See Solubility Guidelines

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/2265e19f-47ec-4bb7-bb99-36b2d8256196)

**Comment by andersweinstein** [comment]
subscripts/superscripts within list items got placed in distinct paragraphs. 

Current migration tool output looks correct for these (does not introduce paragraphs). 

A recent ingestion of Chem content followed by edit of the page does not reproduce this issue. It may have been an issue at time of this particular course migration/ingestion only.

**Comment by bitbldr** [comment]
Will be resolved in the source, no longer an issue in the course-digest
