### ISSUE TITLE
(Migration) Missing rollover text

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4353]
**Describe the bug**
Text missing from the rollover image description reading "Alternative version".

[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test_/page/x340o_adding_and_subtracting_like_fr_tg601)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/4d3cddc5-d535-49b5-b2d1-a0728e2957f2)

[XML](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m1a_Arithmetic_part2/x-oli-workbook_page/add_subtract_fractions_unlike.xml)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/5008a023-9bea-46bf-bfcb-9259c8bd7e3c)

[Echo](https://echo.oli.cmu.edu/#stem_readiness-1.2/add_subtract_fractions_unlike?organization=stem_readiness-1.2_open_free)

**Expected behavior**
Roll over shows the following text: Two fractions appear on the left, one on top of the other. On the top is “1/3”. On the bottom is “1/6”. On the right, the text reads, “Least Common Denominator = 6”.

**Environment (please complete the following information):**
 - Version:26

**Comment by bitbldr** [comment]
Fixed in latest course digest tool
