### ISSUE TITLE
Enhance summative reports: CSV export with lateness info

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4375]
**Is your feature request related to a problem? Please describe.**
The lateness data is not captured in CSV exports

**Describe the solution you'd like**
A format that indicates which cells contain scores that were submitted late.

**Describe alternatives you've considered**
None. Consulting the Torus gradebook is the only known solution.

**Additional context**
I'm not sure what kind of formatting CSV files permit. Color is the most obvious first choice.

**Comment by bitbldr** [comment]
For accessibility, we likely do not want to **only* use color to indicate lateness
