### ISSUE TITLE
(Migration) Spacing is inconsistent throughout paragraphs

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4384]
**Describe the bug**
On STEM foundations paragraphs are too close together. This happens on every page of the course. 

[SVN](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_workplace_comm/m1_app_read_strat/x-oli-workbook_page/Identifythemainideaandsupportingdetailsofatext_1.xml)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e028f0a0001dc302e7babefbe7c27) [Echo](https://echo.oli.cmu.edu/#fast_track-1.1/Identifythemainideaandsupportingdetailsofatext_1?organization=fast_track-1.1_default)
<img width="877" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/129827b8-cc3d-434d-9ea9-5fd5fd606520">

[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_apply_reading_strategies_to_im_tznpt)
<img width="700" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/64d7086a-df4e-4e09-8780-2555dc56e9b8">

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by andersweinstein** [comment]
Error introduced into torus development version. Fixed version now on tokamak.

**Comment by bitbldr** [comment]
Formatting was broken on tokamak, but this has been fixed
