### ISSUE TITLE
(Migration parity) Text that is highlighted on legacy is not highlighted on tokamak

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4388]
**Describe the bug**
Text that is highlighted on legacy is not highlighted on tokamak. This happens 10+ times in this course.

[SVN](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_mathematics/m5_signed_values/x-oli-workbook_page/signed_values_3.xml)
[Echo](https://echo.oli.cmu.edu/#fast_track-1.1/signed_values_3?organization=fast_track-1.1_default)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e045d0a0001dc411577ad0ff729f5)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/fe44419b-77d3-43f7-8f14-2d4460c6501e">
[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_order_of_operations_q1dwn)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/e5942522-ba3a-4d26-a346-7e19eacd5571">

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by andersweinstein** [comment]
Note this occurs in MathML rendered by MathJax.

**Comment by cjlim1092** [comment]
the name of the mark is mark
