### ISSUE TITLE
(Migration bug) Fraction being rendered inline is being treated as block

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4389]
**Describe the bug**
MathML should be inline, but it is rendering as a block. 

[SVN](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_mathematics/m2_mult_divide_int/x-oli-workbook_page/mult_div_int_2.xml)
[Echo](https://echo.oli.cmu.edu/#fast_track-1.1/mult_div_int_2?organization=fast_track-1.1_default)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e03da0a0001dc61c0fd4c8a9a487b)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/933ba57c-f92e-43c9-8739-ffaeae30bae3">
[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_division_9hvfa)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/568d5bf6-c4d2-40f2-87fb-6dd2f2e082d0">

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by andersweinstein** [comment]
One possibility is to rewrite as inline formula using MathML or LaTex. LaTex form would be `\dfrac{3}{1}`
Believe can be embedded inline via `$\dfrac{3}{1}$`
