### ISSUE TITLE
No license present

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4398]
**Describe the bug**
The content license is not present.

**To Reproduce**
1. Visit any course page in Torus and note the lack of a content license.

**Expected behavior**
A footer that includes the license, the year, and a link to the Open Learning Initiative homepage, like you see on legacy.

**Comment by bitbldr** [comment]
License is not being rendered in student page delivery, also missing from being set on package overview page.

**Comment by cjlim1092** [comment]
This is still an issue on new migration projects, should be present in ng24
