### ISSUE TITLE
Be able to format left-to-right and right-to-left text within the same paragraph block.

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#4401]
**Is your feature request related to a problem? Please describe.**
Modern Languages (Arabic) has run a Tokamak review of the right-to-left feature to be deployed in v26 December release, current work around between Arabic and English content is to create new text blocks between arabic and english to change alignment. Wants a feature that allows alignment formatting changes within the same block of text.

**Describe the solution you'd like**
Arabic course developers within Modern Languages want the ability to switch justifications within the same paragraph block.

**Additional context**
As mentioned, can just create two blocks, but if you have direct sentence - to - sentence translation between Arabic and English, you'll have to create a new block for every sentence, it puts a lot of blocks on the page that can make it a hassle for the block sidebar in case content needed to be reordered on a page.

**Comment by cjlim1092** [comment]
Possible enhancement: keystroke for adding new text block
