### ISSUE TITLE
(Migration) Code for non-breaking space is displayed, instead of actual non-breaking space

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4404]
**Describe the bug**
The string &nbsp; is on the page.

**To Reproduce**
Tokamak: https://tokamak.oli.cmu.edu/sections/systematic_reviews_and_metaana/page/i43sj_systematic_review_methods_an_o_uwlzy
Legacy equivalent: https://oli.cmu.edu/jcourse/workbook/activity/page?context=941e007c0a0001dc046c8cec84f3b677

**Expected behavior**
Code would be translated into a space.

**Screenshots**
<img width="372" alt="Screenshot 2023-11-07 at 1 52 08 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/b243f07a-436e-403d-870a-b13b2450d49d">

**Comment by andersweinstein** [comment]
Simplest to delete this in source or, if don't want new ingestion, in torus authoring. This involves custom HTML for the layout which is passed through migration without change. 

In theory migration tool might be changed to better handle entity references like `&nbsp;` with the custom html. But looks like there is no general need for it and this is only one case, easily fixed.
