### ISSUE TITLE
Table extends off the right margin

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4407]
**Describe the bug**
This wide table extends off the page instead of being scrollable or being fit to the page.

**To Reproduce**
View table: https://tokamak.oli.cmu.edu/sections/systematic_reviews_and_metaana/page/i43sj_screener_agreement_upqp2

**Expected behavior**
table would scroll, or bit

**Screenshots**
<img width="1608" alt="Screenshot 2023-11-07 at 2 14 53 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/1eaef50e-fd7a-4573-8120-b0bb2ee4cac2">

**Comment by bitbldr** [comment]
Need to define what tables **should** do here
