### ISSUE TITLE
(Migration) Popup definition values are missing

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4408]
**Describe the bug**
The definition popups are empty

**To Reproduce**
See the definitions here and note they're empty: https://tokamak.oli.cmu.edu/sections/systematic_reviews_and_metaana/page/i43sj_structured_formats_t70wz

Legacy: https://oli.cmu.edu/jcourse/workbook/activity/page?context=941e01e90a0001dc177e8a75a85076f1

<img width="201" alt="Screenshot 2023-11-07 at 2 17 53 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/f5a9dfe2-a6d8-4e55-84bc-690ad439bb71">
<img width="291" alt="Screenshot 2023-11-07 at 2 18 06 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/40e16327-d682-49e9-9d3c-626a5f9f4472">

**Comment by andersweinstein** [comment]
Possible more recent migration tool has fixed this

**Comment by bitbldr** [comment]
@halturner can you verify and we can close if this is already fixed?

**Comment by andersweinstein** [comment]
Put more recent migration at https://tokamak.oli.cmu.edu/authoring/project/systematic_reviews_and_metaana_rcwxo/overview

Verified popup content shows in preview on referenced page and elsewhere. Think this was fixed by
https://eliterate.atlassian.net/browse/MER-2696
so we can close.
