### ISSUE TITLE
(Migration) Reference link was split in two pieces

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4410]
**Describe the bug**
note the extra "click out" icon in the middle of the reference link

**To Reproduce**
https://tokamak.oli.cmu.edu/sections/systematic_reviews_and_metaana/page/i43sj_advanced_quantitative_synthesi_o01oe
See: For more information, see [Chaimani](https://training.cochrane.org/handbook/current/chapter-11) [et al.](https://training.cochrane.org/handbook/current/chapter-11) [(2022)](https://training.cochrane.org/handbook/current/chapter-11) , [Grant and Calderbank-Batista (2013)](https://doi.org/10.5243/jsswr.2013.25) , and [Salanti (2012)](https://doi.org/10.1002/jrsm.1037) .

**Screenshots**
<img width="952" alt="Screenshot 2023-11-07 at 2 32 04 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/c5f5663c-d92a-491a-93fb-39e2c5b85dd6">

**Comment by andersweinstein** [comment]
Source XML has three successive links, one on `Chaimani`, one on `et. al`., and one on `2022.` Best to fix in source.

**Comment by halturner** [comment]
Thanks @andersweinstein , closing
