### ISSUE TITLE
Cannot apply update

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4411]
**Describe the bug**
Clicking APPLY UPDATE results in failure.

**To Reproduce**
Visit as an instructor and apply the update:
https://proton.oli.cmu.edu/sections/real_chem_i_gates_demo_course_7xp5j/instructor_dashboard/manage
Note it will not be applied

**Expected behavior**
Application of update

**Comment by bitbldr** [comment]
Fixed in hotfix v0.25.4
