### ISSUE TITLE
(Migration) MathML, reads "mundermundermunder" with a yellow highlight.

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4415]
**Describe the bug**
The text next to "isolating C" has errored, and reads "mundermundermunder" with a yellow highlight. It should be a space

[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p5_angle_sum?organization=readiness_ccss-1.2_default)
[SVN](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m5_triangles/x-oli-workbook_page/p5_angle_sum.xml)

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e57a0a0001dc3f71baee81a8020c)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/9b069f72-6c58-46c7-a2dd-c9efc8da4480)

[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test_/page/x340o_triangle_angle_sum_theorem_whzml)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/90ce875e-938a-457c-9c8e-bb7cd4deed7e)

**Environment (please complete the following information):**
 - Version:25

**Additional context**
STEM Readiness for india

**Comment by andersweinstein** [comment]
I am not sure the munder is doing anything in the legacy formula. I would be expect it to show something under the enclosed content, but I don't see anything. Suggest experiment with taking out all `<munder> `and `</munder>` tags from the mathml , leaving whatever is between them, and seeing if result is OK.

**Comment by bitbldr** [comment]
Fix in the XML, take out the munder. If the problem persists we can reopen this

**Comment by cjlim1092** [comment]
After editing the xml the munder has disappeared, but the spacing was not maintained. This is now usable, but not ideal still.

**Comment by andersweinstein** [comment]
The spacing is effected by all the `<m:mi>&nbsp;</m:mi>`s in the formula. Spacing should not be affected if they are left there.  Here is a version of the formula with munder wrappers removed while leaving their contents:

```
<m:math xmlns:m="http://www.w3.org/1998/Math/MathML" display="inline" overflow="scroll">
    <m:mrow>
            <m:mo lspace="2px" rspace="2px">
                &minus;
            </m:mo>
            <m:mn>
                146
            </m:mn>
            <m:mi>
                &deg;
            </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
        <m:mi>
            &nbsp;
        </m:mi>
          <m:mo lspace="2px" rspace="2px">
                &minus;
            </m:mo>
            <m:mn>
                146
            </m:mn>
            <m:mi>
                &deg;
            </m:mi>
    </m:mrow>
</m:math>
```

**Comment by andersweinstein** [comment]
It looks like there is a bug passing `&nbsp;` through the migration tool. That is an encoding of a non-breaking space character in the MathML. But this character is not showing up in the resulting formula on ingestion (either before or after the munder was removed).  It might be getting converted to a regular space that is normalized away. But that is what explains why the spacing is being lost.
