### ISSUE TITLE
Arabic font in Drag & Drops is smaller than surrounding text on the page

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4420]
**Describe the bug**
The styling of Drag & Drop exercises presents the Arabic font smaller than the text on the page.

**To Reproduce**
Note the D&D on this page (Chrome): https://proton.oli.cmu.edu/authoring/project/elementary_arabic_1_online/preview/_reading
<img width="1016" alt="Screenshot 2023-11-09 at 1 12 36 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/82a3785e-46fc-44a0-a91f-893ab33cb3a6">

**Expected behavior**
For all fonts to be identically sized unless there is a reason for them to be different.

**Screenshots**
Safari: 
![Screenshot 2023-11-09 at 1 16 20 PM](https://github.com/Simon-Initiative/oli-torus/assets/24977416/27cf09ac-ac16-45d0-bafb-c5692a2a6409)

**Environment (please complete the following information):**
 - OS: [MacOS 13.5.2]
 - Browser: [Chrome]; Safari
 - Version: [119.0.6045.105]; Safari 16.1

**Comment by bitbldr** [comment]
We should investigate whether this is affecting all courses, arabic or not. Likely caused by the embedded custom drag and drop CSS

**Comment by bitbldr** [comment]
These instances were hand created in torus. The authors will need to go in a adjust the custom stylesheets to fix the font size

**Comment by andersweinstein** [comment]
Text in the body was given H1 header styling, making it larger than normal and bold. Text within the drag-and-drop picks up default text styling only so does not match this customized text style. 

Text within the layout and initiator elements would have to be styled to make them match. This might be done by setting a default fontsize within the activity's custom style sheet. 

ALSO, the absolute y-coordinates of the target elements need to be increased a bit (all  to the same value) to move them to the right and avoid text pieces in the layout overlapping them.
