### ISSUE TITLE
Videos with size parameters not centered

### ISSUE THREAD

**Issue by andersweinstein** [Simon-Initiative/oli-torus#4426]
Logic and Proofs migration results in videos that are not centered with respect to surrounding text. Experiment suggests this is because video size parameters were included and carried through in migration. In all cases the size parameters appear to specify the intrinsic resolution of the video with no scaling. For example, a video with resolution 500 x 400 includes size parameters of 500 and 400. 

If the size parameters are removed in authoring the video displays centered though scaled up in size (to 814 x 648 in preview, 720x 576 in authoring, both of which preserve the 5:4 aspect ratio). With the size parameters it shows at the 500x400 size but is no longer centered; rather slightly indented on the left.

Can be seen on this authoring project page. This project has been superseded by a more recent migration so can be played with. 
https://tokamak.oli.cmu.edu/authoring/project/logic_and_proofs_lt6tq/resource/yyb4k_overview_cicxl

**Comment by bitbldr** [comment]
The fix here is to remove the sizing of videos in the migration
