### ISSUE TITLE
Curriculum link in discussion post from instructor to student gives 500 error when clicked on

### ISSUE THREAD

**Issue by kllarson** [Simon-Initiative/oli-torus#4431]
**Describe the bug**

**To Reproduce**
Create and instructor post
Go in as student and click on link to post
See error

**Expected behavior**
I'm not sure where this link would even take you. The others go to the page the discussion is on

**Screenshots**
video clip attached
Student link to course
https://proton.oli.cmu.edu/sections/join/q9mwp 

https://github.com/Simon-Initiative/oli-torus/assets/139511643/c0759260-1879-4a1a-80e1-00eb990d404e

**Comment by bitbldr** [comment]
Top level discussion links are not resolvable.

One solution here is to recognize this and make these links not navigable.
