### ISSUE TITLE
(migration bug)Paragraph breaks in mathML text are lost

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4432]
**Describe the bug**
Paragraph breaks in mathML text are lost. While this does not impede learning, this did happen multiple times in the course and could be a problem in future migrations. 

[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p9_cartesian_linear_equation?organization=readiness_ccss-1.2_default)
[XML](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m6_cartesian_plane/x-oli-workbook_page/p9_cartesian_linear_equation.xml)
<img width="749" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/e7cada32-48b2-43fa-9f8e-4c4216cd9813">
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e5f60a0001dc082b9d73729a1379)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/24116e85-7890-42f0-bb91-a7f17b89a0d0)
[Torus](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test__ia9ay/page/3d6so_the_linear_equation_ng9on)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/d67c9c89-f33d-4c6d-94ba-bb3f970457c3)

**Environment (please complete the following information):**
 - Version: 25

**Comment by andersweinstein** [comment]
The migration tool deliberately migrates a formula inside a paragraph into an inline (as opposed to block) formula. It is surprising these are coming out as block formulas in legacy. If that is normal behavior in legacy then the migration tool should be corrected to avoid turning these into inline formulas.

**Comment by darrensiegel** [comment]
The Torus intepretation of the Legacy content model is correct here.  These `<formula>` elements are inline elements and are rendering correctly.  I would argue that Legacy is broken here.

**Comment by andersweinstein** [comment]
An odd resolution since the desired appearance is what the legacy rendering gives. The migration tool does not have to turn these into inline formulas if that is not how legacy renders them.

**Comment by andersweinstein** [comment]
Note Echo editor renders these as inline formulas

<img width="936" alt="Screenshot 2023-11-17 at 7 34 30 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/7094628/8beeecc4-36da-4212-9a86-b477be640625">
