### ISSUE TITLE
(migration bug) List items in an ordered list are missing bullet points (in this case, numbers)

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4433]
**Describe the bug**
 List items in an ordered list are missing bullet points (in this case, numbers). They should have numbers. 
[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p10_cartesian_graph_line?organization=readiness_ccss-1.2_default)
[XML](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m6_cartesian_plane/x-oli-workbook_page/p10_cartesian_graph_line.xml)
<img width="884" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/80d4cf3d-6443-4913-b7f6-a001c298ce51">

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e5f70a0001dc16b9a1ad0f710e13)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/7f2070d8-4d46-4184-9b69-f35cbf85c4c7)

[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test__ia9ay/page/3d6so_graphing_a_line_using_the_yint_3fl9n)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/cf0b18bc-80c6-4add-962d-8c0d78165b20)

**Environment (please complete the following information):**
v25

**Comment by darrensiegel** [comment]
The problem here is that this is an ordered list **inside** of a paragraph.  Torus does not support nested block level elements.

**Comment by darrensiegel** [comment]
The XML here should be rewritten so that there is a paragraph, followed by an ordered list, followed by a paragraph

**Comment by andersweinstein** [comment]
Migration tool carefully collects warning messages on these, but never prints the collected warnings anywhere.

Might be more convenient if migration tool could restructure the content into torus-acceptable form.

**Comment by bitbldr** [comment]
Content fix required, XML should be fixed here
