### ISSUE TITLE
(migration parity) Math equation is left-justified, it should be center-justified

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4434]
**Describe the bug**
Math equation is left-justified, it should be center-justified. Looks like this was done in echo, at a glance I can't find the parameter that tells it to center-align in the xml. 

[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p13_cartesian_distance?organization=readiness_ccss-1.2_default)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/81bf4959-6633-4f05-8e07-a218cb2150e1)

[SVN](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m6_cartesian_plane/x-oli-workbook_page/p13_cartesian_distance.xml)

[Legacy
](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e5fa0a0001dc167c670ccac7828f)![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/8b04b64e-e2bb-431e-973c-ad6a850dd80d)

[Torus](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test__ia9ay/page/3d6so_determining_the_distance_betwe_kxzkp)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/76ad2237-cb97-4dad-a82f-505129fd95e0)

**Environment (please complete the following information):**
v25

**Comment by andersweinstein** [comment]
The square root formula is wrapped in a paragraph tag as the paragraph's sole content. This is causing the migration tool to infer that the formula should be inline in that paragraph. Because there is no text before it in the paragraph, it comes out on the left.

This can be avoided by removing the opening and closing paragraph tags around the formula in the xml source.

**Comment by andersweinstein** [comment]
Note also the example on this page contains an ordered list `<ol>` within a `<p>`. The migration tool currently strips these as illegal so the example structure does not migrate. This is an unrelated issue affecting migration of this page. Our usual advice is to correct this in the XML source.
