### ISSUE TITLE
(style migration parity)Content tagged with <em> in legacy looks like a drop shadow(?) but comes across as bolded on torus. 

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4435]
**Describe the bug**
Content tagged with <em> in legacy looks like a drop shadow(?) but comes across as bolded on torus. This is arguably better than legacy, just pointing out that it is different.

[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p13_cartesian_distance?organization=readiness_ccss-1.2_default)
[SVN](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Math/m6_cartesian_plane/x-oli-workbook_page/p13_cartesian_distance.xml)
<img width="854" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/c32edaeb-d79d-44ba-8ad0-e5c820ee2881">
[Legacy
](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e5fa0a0001dc167c670ccac7828f)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/9ba62d83-f2c5-448a-b1f1-257c6428834a)

[Torus](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test__ia9ay/page/3d6so_determining_the_distance_betwe_kxzkp)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/9f9c78f9-7b78-48a9-9c64-b0e74a0eb180)

**Environment (please complete the following information):**
v25

**Comment by darrensiegel** [comment]
`<em>` translates to a `<strong>` (i.e. "bold") markup.  Closing as I don't see any issue here.
