### ISSUE TITLE
(migration) Title parameter missing for list items

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4436]
**Describe the bug**
Lists with a title parameter are missing titles. This appears somewhat frequently in STEM Readiness and does impede learning, but could be reauthored. 

[Echo](https://echo.oli.cmu.edu/#readiness_ccss-1.2/p3_info_from_text2?organization=readiness_ccss-1.2_default)
[XML](https://svn.oli.cmu.edu/svn/community/stem/stem_readiness/adaptations/readiness_ccss/branches/v_1_2-echo/content/Unit_Communications/m1_intro_communications/x-oli-workbook_page/p3_info_from_text2.xml)
<img width="854" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/6269dc3f-73c7-4d3a-a22e-26f9f43ceda5">

[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=48f6e6380a0001dc72ff190f44d76708)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/bfd1381f-520f-441d-a4d5-7d5cc07e86c4)
[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_readiness_migration_test__ia9ay/page/3d6so_key_information_from_text_2_5ukic)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/14fd9f73-1798-4b52-a78d-5495c247833c)

**Environment (please complete the following information):**
 v25

**Comment by andersweinstein** [comment]
This should be fixed in recent digest tool.
