### ISSUE TITLE
A collaborator on a course is not visible on the collaborator list

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4441]
**Describe the bug**
A collaborator on a course is not visible on the collaborator list but she has been making changes. On Tokamak.

[Collaborator: 
](https://tokamak.oli.cmu.edu/admin/authors/240)
[Course: 
](https://tokamak.oli.cmu.edu/authoring/project/elementary_french_1_vo1f3/overview)
![image](https://github.com/Simon-Initiative/oli-torus/assets/32859465/3b8e4edc-49f8-45e9-9ba9-51946afc63b7)

**Environment (please complete the following information):**
 - Version: 25

**Comment by bitbldr** [comment]
We should try to ensure that all account have a full name entered, but we need to make sure this works in all cultures/name formats
