### ISSUE TITLE
[French I] formatting for silent letters is not formatted properly

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#4444]
**Describe the bug**
The original formatting for "silent letters" in French is not formatted properly according to how it was in Legacy. The "silent" letter should be unformatted (unbolded, grey, un-italicized, not-underlined). See screenshots.

**Expected behavior**
Might be an easy manual fix but may be an issue for future modern languages migrations. 

**Screenshots**
Should migrate to follow the following formatting

<img width="876" alt="Screenshot 2023-11-15 at 11 37 36 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/100791229/efc94ce2-42d6-4e7a-ae34-82dc95e18cf1">

The following is the current display

<img width="952" alt="Screenshot 2023-11-15 at 11 40 00 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/100791229/e7ac496f-657f-4217-96f5-3ce7583c3691">

**Links to Errors**
https://tokamak.oli.cmu.edu/sections/french_1_migration_qa_0216/page/bwhpc_spelling__pronounciation_r90ar
https://oli.cmu.edu/jcourse/workbook/activity/page?context=79c7db170a0001dc56a12dbc54015d80

Does have a Jira ticket but has not been fixed.

**Comment by andersweinstein** [comment]
This issue was addressed. The linked course shows a title including 02/16 indicating it is from February. You should be looking at more recent migration version that incorporates fixes made since then.

**Comment by cjlim1092** [comment]
This has been fixed and can be closed https://tokamak.oli.cmu.edu/sections/elementary_french_1_101323/page/5iytc_spelling__pronounciation_2ckc4
