### ISSUE TITLE
Dialogue is not color-coded

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#4445]
**Describe the bug**
In the Legacy version, the dialogue is color-coded to represent which speaker is speaking which line. 

**Expected behavior**
Torus should have a themed or user-set color-coded system, or an alternative labeling system for ingested.

**Screenshots**

<img width="933" alt="Screenshot 2023-11-15 at 11 45 43 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/100791229/47b30c7d-47da-4469-9ea1-c00c18f7445a">

<img width="969" alt="Screenshot 2023-11-15 at 11 48 31 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/100791229/5cfcce97-6070-441e-8ed3-f8bdb783f79a">

**Additional context**
Add any other context about the problem here, for instance a full link to the page or resource if this problem is specific to a course or a resource in a course.

https://tokamak.oli.cmu.edu/sections/french_1_migration_qa_0216/page/bwhpc_reconstruisez_la_conversation_kwm5y

https://oli.cmu.edu/jcourse/workbook/activity/page?context=79c7db560a0001dc612ac8b4d9d9776d

**Comment by cjlim1092** [comment]
This has been fixed, can close ticket https://tokamak.oli.cmu.edu/sections/elementary_french_1_101323/page/5iytc_reconstruisez_la_conversation_1f3et
