### ISSUE TITLE
Removed formatting for discussion board

### ISSUE THREAD

**Issue by qqmmm** [Simon-Initiative/oli-torus#4453]
**Is your feature request related to a problem? Please describe.**
When I was posting or replying to others to the discussion board, it will remove all the formatting we made to the post. For example, it will remove new line or additional space we made. 

**Describe the solution you'd like**
I am thinking of allowing users to return for a new line, as well as allowing bold, and italic for specific content since sometimes when we write a big chunk of information it will increase the cognitive load and slow the reading speed down for others. 

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.  If you know of other platforms that offer this suggested functionality, please list them.

**Comment by bitbldr** [comment]
This is expected behavior, discussions currently only support plaintext. It would be nice for these discussions to support a more rich set of formatting, reactions, attachments, etc..
