### ISSUE TITLE
A Pre Course Survey Not Available to Students Counts against Progress

### ISSUE THREAD

**Issue by kwahlenmayer** [Simon-Initiative/oli-torus#4466]
**Describe the bug**
If a pre-course survey is not available to students, the student progress cannot be 100% because the pre-course survey is not done.

**To Reproduce**
See this course with a pre-course survey that is turned off in the section. One student has 94% though they have completed everything except the pre-course survey.
https://proton.oli.cmu.edu/sections/foster_active_learning_cmuafri_szumg/instructor_dashboard/reports/students?sort_by=progress
To reproduce, invite your student account to the course, enroll, then see that you are not able to access the survey.
From your admin account, see that your student account has not completed the survey.

**Expected behavior**
A pre-course survey that is not available should not be in the progress calculation.

**Comment by bitbldr** [comment]
It could be that when a precourse survey is not enabled for a section, then students cannot access and progress cannot be completed to 100%
