### ISSUE TITLE
[migration] Citations/references are missing

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4468]
**Describe the bug**
Citations/references do not migrate with the content.

**To Reproduce**
Compare these two pages in Systematic Reviews and Meta Analysis
Legacy: https://oli.cmu.edu/jcourse/workbook/activity/page?context=941e00750a0001dc5459f9dd1ce88eea
Tokamak November migration: 
https://tokamak.oli.cmu.edu/authoring/project/systematic_reviews_and_metaana_rcwxo/preview/ui7gz_types_of_systematic_reviews_vghlq

**Expected behavior**
Citations would follow the content through migration and appear at the bottom of the page in the same format as on legacy

**Screenshots**
<img width="1257" alt="Screenshot 2023-11-27 at 5 53 34 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/1c9850bc-01c4-4ff3-9995-4be9956611f7">
<img width="1073" alt="Screenshot 2023-11-27 at 5 53 55 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/1e78184f-4535-4913-b323-6cc599bff536">

**Comment by andersweinstein** [comment]
The reference on the example page is not coming out in the migration tool output for the page.  
SVN source: 
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/systematic-lkgnjr6l/branches/v_1_6-echo/content/x-oli-workbook_page/a81b4872f5034fb49f68e2d62adf98ff.xml
