### ISSUE TITLE
Learning objectives tagged to the page, but not listed at the top when previewing

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4470]
**Describe the bug**
This page has learning objectives attached, but they're not displayed when previewing.

**To Reproduce**
Authoring page: https://tokamak.oli.cmu.edu/authoring/project/systematic_reviews_and_metaana_rcwxo/resource/ui7gz_time_effort_and_resources_need_r2j6w
Preview: 
https://tokamak.oli.cmu.edu/authoring/project/systematic_reviews_and_metaana_rcwxo/preview/ui7gz_time_effort_and_resources_need_r2j6w

**Expected behavior**
for LOs to be shown

**Screenshots**
<img width="894" alt="Screenshot 2023-11-27 at 6 05 06 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/20128430-554b-4ac5-98e2-c60dab278c63">

<img width="1066" alt="Screenshot 2023-11-27 at 6 05 19 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/99d897c9-5abb-421e-ad39-f0c51f8ee962">

**Comment by halturner** [comment]
I just realized this is the Preview behavior only. The LOs are still visible when published.

**Comment by bitbldr** [comment]
This likely could leverage any new infrastructure used for admin section page access in authoring preview, ensuring that an author in preview is seeing exactly what will be delivered to a student
