### ISSUE TITLE
Table titles need style, to differentiate them page text

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4478]
**Is your feature request related to a problem? Please describe.**
The SRMA development team noted that table titles just look like regular text, and don't look like titles on the page.

**Describe the solution you'd like**
A style to be applied that sets off the table title, so it's evident it applies to the table and isn't page content. Torus vs Legacy:

<img width="1387" alt="Screenshot 2023-11-29 at 11 05 01 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/371f5b11-6037-46f1-ad88-a3a11eafbe21">

<img width="1045" alt="Screenshot 2023-11-29 at 11 05 16 AM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/56f8ebab-120f-4fbd-a0d4-464b6f94c4b6">

**Comment by andersweinstein** [comment]
Migration tool converts title to an h5 header, which apparently renders this way. The same procedure is used for any titles included on images, iframes, audio, video, or youtube clips. 

Torus styling of h5 could be changed. Or it could be migrated to a more visually distinctive header level, or include bold tags around the text in these headers.

**Comment by bitbldr** [comment]
We need to decide whether torus should support more header types in authoring, h4, h5, h6 and then add proper styles for them in delivery.

We also need to determine how supporting headers affect accessibility

**Comment by andersweinstein** [comment]
Legacy theme renders table title as follows. 
```
<thead>
  <tr>
    <th lang> My Table Title </th>
  </tr>
</thead>
```
Appears no custom styling applied to get bold.
