### ISSUE TITLE
Size of input box doesn't change when you change the size

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4485]
This page in authoring https://proton.oli.cmu.edu/authoring/project/latest_real_chemistry_i_taylor_4mv9k/resource/personalized_practice_limiting
See activity "Limiting Reactant: Number of Molecules" Input boxes are set to small
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/9ed4d3bd-7be4-4062-aa17-74d35e2406bb)

They change size in authoring, but in the student view they don't change size.
![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/293d4e79-6e76-4f5b-8e9a-a6f47804376e)

https://proton.oli.cmu.edu/sections/real_chem_i_gates_demo_course_7xp5j/page/personalized_practice_limiting

**Comment by bitbldr** [comment]
It would be good to get a sense for how many instances of this exist
