### ISSUE TITLE
Ability to create Module containers outside of Unit containers.

### ISSUE THREAD

**Issue by aambrozi** [Simon-Initiative/oli-torus#4498]
**Is your feature request related to a problem? Please describe.**
Would it be wise to add the ability to create modules in the overall page without creating Units? I know there is a way to *rename* the containers in project overview, but could we add a "module" button on the main landing page in Curriculum? Currently I am making Module containers in a Unit container and moving them out manually.

**Describe the solution you'd like**
A module container option outside of a Unit.

**Describe alternatives you've considered**

![Screenshot 2023-12-05 at 12 05 34 PM](https://github.com/Simon-Initiative/oli-torus/assets/100791229/47ad462c-d2eb-48d4-9ad0-009587200312)

**Comment by bitbldr** [comment]
It would be good to get some more user research on this to see how many authors are facing a similar issue
