### ISSUE TITLE
Dynamic Variables Range Bug

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4503]
Hard to explain - I took a video. On this page of the course https://proton.oli.cmu.edu/authoring/project/latest_real_chemistry_i_taylor_4mv9k/resource/personalized_practice_limiting

https://github.com/Simon-Initiative/oli-torus/assets/36045601/1420ef26-2e07-41e1-a593-3e4cd7bbba81

**Comment by andersweinstein** [comment]
From experiment, it looks like it always sorts the variables in alphabetical order from top to bottom, so attempts to change the order get reset. Maybe a sorting step somewhere designed to ensure lower bound first is not handling possibility of dynamic variables? Until fixed, workaround could be to rename variables, e.g. change corHigh to corUpper.
