### ISSUE TITLE
Prototype email support using AWS SES

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#534]
We need to investigate AWS Simple Email Service in order to understand if it provides a better solution than relying on the CMU relayed email service.   

The criteria that we should be using to evaluate it for:

1. Does SES provide a high level of reliability for delivering emails so that they do not end up in a receipients spam folder?
2. How well does the SES provided ways to track sent emails work?  Can we do this interactively via a web UI?  Or only via an API or notifications (e.g. like when an email fails to be delivered)
3. Can we customize the sender email address so that it is something OLI specific, such as "admin@oli.cmu.edu"
4. How easy is `https://github.com/thoughtbot/bamboo` and the `https://github.com/kalys/bamboo_ses` AWS SES adapter to use in setting up an email integration in a Phoenix app?

**Comment by bitbldr** [comment]
done
