### ISSUE TITLE
Page/Assessment options scroll out of view in large course: CMU-425

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#562]
<img width="1186" alt="Screen Shot 2020-07-30 at 9 57 34 PM" src="https://user-images.githubusercontent.com/6248894/88992471-845db700-d2b1-11ea-9f4f-97671ad36b69.png">

**Comment by LEDThereBeLight** [comment]
Verify this still happens

**Comment by LEDThereBeLight** [comment]
Closing as done. Reworked.
