### ISSUE TITLE
Add support for quote sources

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#565]
Bootstrap supports sources for block quotes out of the box. We should support this feature as well

<img width="980" alt="Screen Shot 2020-07-30 at 10 19 14 PM" src="https://user-images.githubusercontent.com/6248894/88993034-da7f2a00-d2b2-11ea-9ad3-268d8779652f.png">

**Comment by LEDThereBeLight** [comment]
I'm in favor of not doing this because it adds another option to a quote menu that can be handled by text formatting.
