### ISSUE TITLE
Republishing a course does not reset student activity attempts

### ISSUE THREAD

**Issue by LEDThereBeLight** [Simon-Initiative/oli-torus#570]
If a student has a submitted activity attempt for an activity that has been changed in a new publication, the submission prevents the activity from showing the updates (including any new objectives that have been added and which roll up to the page)

**Comment by darrensiegel** [comment]
This should only be true for graded pages.  It is by design that a graded page that has an activity attempt in progress - but then a new publication of that activity is created - keeps displaying the old attempt and old activity content until that attempt is completed.
