### ISSUE TITLE
YouTube video instructions are confusing

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#583]
We should only provide one set of clear instructions here for the common use case (which is most likely the entire URL) instead of specifying two different ways (video ID or URL). I don't think many users will understand the concept of a video ID and it's really a relic of the legacy DTD. E.g. "Paste the YouTube video URL"

<img width="827" alt="Screen Shot 2020-09-08 at 2 03 27 PM" src="https://user-images.githubusercontent.com/6248894/92512003-23909b00-f1dc-11ea-8aaa-fc06bcea3547.png">

**Comment by LEDThereBeLight** [comment]
Also need to make sure we handle youtu.be urls, not sure if we do or not but I know that was a problem in Echo.
There may be other youtube shorteners we want to support

**Comment by LEDThereBeLight** [comment]
Closing as done.
