### ISSUE TITLE
Clicking outside of insert menu flashes it in top left corner

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#586]
Clicking outside of insert menu flashes it in top left corner

<img width="260" alt="Screen Shot 2020-09-15 at 9 23 05 AM" src="https://user-images.githubusercontent.com/6248894/93215939-12dca980-f735-11ea-86c0-6a49855a34c0.png">

**Comment by LEDThereBeLight** [comment]
Closing as done.
