### ISSUE TITLE
Gating/scheduling: CMU-180

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#729]
The ability to gate access to material in a course via constraints. 

1. The ability for an author to specify progress constraints in a course (e.g. students cannot access “Unit 2” until they have completed “Unit 1”)
2. The ability for an instructor to override progress constraints and define new ones for their course sections.
3. The ability for an instructor to define time-based scheduling constraints (e.g. students cannot access “Quiz 4” until June 1st and 15:30) for the resources in their course sections. 
4. The ability for an instructor to configure graded assessments to have a time limit. 
5. Support individual student exceptions for all of the above.

**Comment by LEDThereBeLight** [comment]
Closing as done.
