### ISSUE TITLE
Consent to use notices

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#811]
New authors, instructors and students should see:
-Notification that cookies are in use

New students should see:
-Research opt-in / opt-out

The research opt-in / opt-out decision needs to be persisted with this user.

**Comment by normanbier** [comment]
The immediate need is for simple (one study, one consent form) research opt-in/opt-out but longer term we need to think about and plan for supporting multiple studies, sometimes with multiple consent forms.  The overall OLI form needs to be forced on first access, with later opportunity to change; later we may have additional course or intervention specific forms.  Also note that anyone (not just students) should get the overall form -- we do research on faculty and author behaviors too...
