### ISSUE TITLE
Head container names not vertically aligned correctly in breadcrumb trail: CMU-264

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#830]
**Describe the bug**
The breadcrumb UI does not properly align, vertically, the names of containers when the container is the head (aka "active") item. 

**To Reproduce**
1. Visit a curriculum as an author
2. Create a container
3. Click on the container to navigate into the container

**Expected behavior**
The container name should be aligned with the rest of the items in the breadcrumb trail. 

**Screenshots**
![Screen Shot 2021-03-11 at 12 17 17 PM](https://user-images.githubusercontent.com/7431756/110827521-268c4700-8264-11eb-830e-a759ef84a57e.png)

**Comment by LEDThereBeLight** [comment]
Closing as fixed.
