### ISSUE TITLE
Incorrect user name is displayed when a page is locked: CMU-256

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#847]
**Describe the bug**
When editing a page as another user, it shows "Jane Doe is editing this", but the user editing the page name should be my name.

**To Reproduce**
1. Go to a page as user A to acquire a lock
2. Go to the page's container as user B in another browser

**Expected behavior**
User lock message should have the correct user's name

**Screenshots**
<img width="1482" alt="Screen Shot 2021-03-22 at 11 40 59 AM" src="https://user-images.githubusercontent.com/6248894/112017743-45ac9380-8b04-11eb-8799-b42a7e7ca5b1.png">

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser Chrome
 - Version 89

**Comment by eliknebel** [comment]
This may be related to the developer seed data, an not actually a production issue

**Comment by LEDThereBeLight** [comment]
Closing as fixed.
