### ISSUE TITLE
Trying to access an activity after page title change fails

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#848]
**Describe the bug**
After creating an activity on a page and clicking "Edit ...", an error is thrown.

**To Reproduce**
1. Go to a page
2. Change the title
2.  Create an activity (Multiple Choice, for example)
2. Immediately click "Edit Multiple Choice"
3. An error will be thrown

**Expected behavior**
A user should be able to edit an activity after changing the page title

**Screenshots**
<img width="1526" alt="Screen Shot 2021-03-22 at 12 57 03 PM" src="https://user-images.githubusercontent.com/6248894/112028328-6ed22180-8b0e-11eb-96e7-239b42d9c4fc.png">

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser Chrome
 - Version 89

**Additional context**
I've seen this a couple times, usually when creating the first activity in a project.

**Comment by eliknebel** [comment]
This appears to be related to changing the resource title, resulting in an invalid URL. The routing logic either needs to be adjusted to handle old title slugs or the url must be updated to the new slug when a title is changed.

For example, when the title is changed from "New Assessment" to "Quiz 1", the url generated for the activity Edit button still has the old slug, e.g. `https://localhost/project/my_course/resource/new_assessment/activity/multiple_choice`

Exiting the page, then returning shows that the new, correct slug is used and Edit works again, e.g.`https://localhost/project/my_course/resource/quiz_1/activity/multiple_choice`

**Comment by kwahlenmayer** [comment]
User Report Example:
Whenever I try to edit an activity on a new practice page, I will always receive an error "Internal Server Error." This error will only pop up for the first new activity on a new practice page. I will have to go back a few pages for the website to return to normal again.

Support Resolution Example:
This known error occurs when attempting to add an activity after editing the name of the page. Until the engineers resolve the issue, the workaround is to go to a different page and then return and continue editing.
