### ISSUE TITLE
Instructor and student level assessment configuration: CMU-158

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#897]
The ability for an instructor to change the parameters for assessments in this course section. The parameters that can be changed without requiring the instructor to "become an author" and duplicate the course are:

1. Number of attempts for graded pages
2. Time limit for timed assessments

Instructors also need the ability to specify exceptions for the above on a per student basis.

**Comment by eliknebel** [comment]
<img width="1195" alt="Screenshot 2023-03-28 at 2 55 38 PM" src="https://user-images.githubusercontent.com/6248894/228339419-57ff97f7-a1c0-4bdc-861c-1744e595be93.png">

**Comment by eliknebel** [comment]
It is actually more important that instructors are able to set these parameters for assessments than authors

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-1855
