### ISSUE TITLE
Activity SDK: CMU-153

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#902]
While Legacy OLI has support for APIs to enable third-party created activities, it did little in the way of pairing this facility with documentation, examples, reference implementations and peripheral tooling to provide an "Activity SDK".  Torus should implement the documentation for this as a public-facing web site, similar to docs.oli.cmu.edu (the documentation for OLI dynamic questions).

**Comment by eliknebel** [comment]
https://simon-initiative.github.io/oli-torus/overview.html
