### ISSUE TITLE
Creating objective with Enter key should clear the text field: CMU-321

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#939]
**Describe the bug**
When created an objective, if the enter key is pressed the objective gets created however, the text remains in the textfield. This operation should reset the field to empty like it does when using the button.

**To Reproduce**
1. Go to objectives page
2. Create objective using the Enter key

**Expected behavior**
This operation should reset the field to empty like it does when using the button.

**Screenshots**
<img width="1176" alt="Screen Shot 2021-04-13 at 10 09 26 AM" src="https://user-images.githubusercontent.com/6248894/114566751-92d1e000-9c40-11eb-8c5d-2a216e81b32a.png">

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89

**Comment by LEDThereBeLight** [comment]
Still an issue as of 3/1/22.
