### ISSUE TITLE
Don't display delivery footer in page preview mode: CMU-319

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#945]
**Describe the bug**
In page preview mode, the footer is rendered resulting in duplicate footers. Page preview should not render the delivery footer.

**To Reproduce**
1. Go to Page Preview
2. See the double footer displayed

**Expected behavior**
Page preview should not render the delivery footer.

**Screenshots**
<img width="1236" alt="Screen Shot 2021-04-13 at 12 33 29 PM" src="https://user-images.githubusercontent.com/6248894/114588413-a9823200-9c54-11eb-964d-e43105fec91f.png">

**Comment by LEDThereBeLight** [comment]
Closing as fixed.
