### ISSUE TITLE
Activities need a better way to say when they have been completed and are ready for submission: CMU-317

### ISSUE THREAD

**Issue by LEDThereBeLight** [Simon-Initiative/oli-torus#950]
**Describe the bug**
The server decides an activity is completed and ready to be submitted when all activity parts have a response. However, for questions like Ordering, choosing a single option (without all options selected) will allow the activity to be submitted in a graded assessment. For short answer, typing something and deleting it (causing a response to be saved) also allows the activity to be submitted.

**Comment by eliknebel** [comment]
I think for short answer specifically, we want to leave the ability to submit an empty response. We've gotten feedback that an empty response may, in fact, be the correct answer choice for certain types of single response questions

**Comment by eliknebel** [comment]
Closing as stale
