### ISSUE TITLE
Dark mode needs to be tested and fixed

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#967]
**Describe the bug**
Dark mode should be tested for consistency and readability. Some known issues:
- Image captions text is dark on dark, not readable
- Add a delivery toggle for dark mode override
- Styling in page preview is inconsistent when system is dark mode, but authoring theme is set to light. For example, caption wrappers should respect light/dark mode
- There could be other issues that may need fixed

There should also be an option in delivery to toggle dark mode for user preferences.

**Comment by halturner** [comment]
It can be difficult to see images that were created with transparent backgrounds and dark text before Dark Mode became commonplace. I wonder if a user setting for "add white background to all images" would help individuals who benefit from Dark Mode and don't want to have to switch just for their Torus interactions.

![Screen Shot 2021-07-28 at 10 32 49 AM](https://user-images.githubusercontent.com/24977416/127366655-d28019a9-ea20-48df-a3c8-af1f4b655b4c.png)

**Comment by eliknebel** [comment]
This will also be an issue for students who have dark mode enabled in delivery as well for any images that contain dark text with a transparent background.

I wonder if an alternative solution could be to allow the author to set an image background color (or just a white background option) to force the image background to display as white for those images that have text. I don't think we want this setting to affect all images in a course as that can be jarring for dark mode users and providing both options seems like overkill.
