### ISSUE TITLE
LTI access nags about cookie preferences: CMU-454

### ISSUE THREAD

**Issue by bitbldr** [Simon-Initiative/oli-torus#990]
**Describe the bug**
Because cookies cant be set from an iframe anymore, a user will continually be prompted about cookie preferences in LTI frame which is annoying. We have a few options here:

1. Disable cookie preferences prompt in LTI pipeline
2. Make cookie preferences prompt less intrusive
3. Find a workaround for iframe cookies or only allow torus to be launched in a new tab

**To Reproduce**
1. Open torus from LTI launch
2. Constantly get nagged about cookie preferences

**Screenshots**
<img width="967" alt="Screen Shot 2021-04-20 at 2 44 10 PM" src="https://user-images.githubusercontent.com/6248894/115448146-5cb7d180-a1e7-11eb-9304-229dc7900ff3.png">

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89

**Comment by czerwinskie** [comment]
Change where they accept cookies so that the message will go away.
